### ISSUE TITLE
認可機能のドキュメントバグ

### ISSUE THREAD

**Issue by btkodakak** [terasolunaorg/guideline#1003]
## Description

6.5. 認可
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/Security/Authorization.html

> 以下に、<sec:authorize>タグの使用例を示す。
> spring-security.xml
> 
> &lt;div&gt;
>   &lt;sec:authorize access=&quot;ROLE_USER&quot;&gt;  &lt;!-- (1) --&gt;
>       &lt;p&gt;This screen is for ROLE_USER&lt;/p&gt;
>   &lt;/sec:authorize&gt;

上記の箇所、対象は .jsp であり、access 属性の記述をそのまま利用するとエラーが発生します。

## Possible Solutions

以下のような記述が適切かと思います。

> 以下に、<sec:authorize>タグの使用例を示す。
> JSP
> 
> &lt;div&gt;
>   &lt;sec:authorize access=&quot;hasRole('ROLE_USER')&quot;&gt;  &lt;!-- (1) --&gt;
>       &lt;p&gt;This screen is for ROLE_USER&lt;/p&gt;
>   &lt;/sec:authorize&gt;

## Affects Version/s
* 5.0.0.RELEASE
* 1.0.2.RELEASE

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.1

**Comment by btshimizukza** [comment]
ガイドラインに記載している内容は、Expression Language(EL式)を使用しない場合に指定する書式です。
EL式を使わない場合は、`<sec:http>`要素の`use-expressions`属性を書略するか`false`にする必要がありますが、ガイドラインとしては全体的にはEL式を使う前提で記載されているので、EL式を使う例に修正すべきですね。
