### ISSUE TITLE
[TutorialTodo] Document bug in section 3

### ISSUE THREAD

**Issue by btsatoukzn** [terasolunaorg/guideline#1013]
## Description
In section 3, there is a mistake in the below sentence.

https://github.com/terasolunaorg/guideline/blob/master/source/TutorialTodo/index.rst

■3.3. 環境構築
* Spring Data JPAの使用してデータベースにアクセスするRepositoryImpl

■3.4.1.2. Repositoryの作成
* Note 「完了済み件数の取得する」メソッド

■3.4.2.4.1. Formの修正
  todoIdを追加した際、セッターゲッター行の白色強調がされていない。

■3.5.1. データベースのセットアップ
  プロパティファイルの設定をすることになっているが、3.5.2と順番が逆のほうが良い。

## Possible Solutions
■3.3. 環境構築
* Spring Data JPAを使用してデータベースにアクセスするRepositoryImpl

■3.4.1.2. Repositoryの作成
* Note 「完了済み件数を取得する」メソッド

## Affects Version/s
* 5.0.0.RELEASE
* 1.0.2.RELEASE

## Fix Version/s
- [x] 5.0.1.RELEASE
- [x] 5.1.0.RELEASE

## Issue Links
*

**Comment by shimakuray** [comment]
最終レビューをお願いいたします。
