### ISSUE TITLE
[REST] Joda Time or JSR-310用のObjectMapperの作り方

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1022]
## Description
日付項目にJoda TimeやJSR-310のAPIを使う場合のObjectMapperの作り方をガイドラインで紹介する。
デフォルトの状態の`ObjectMapper`を使うとJSONに変換する際に日時形式も文字列にフォーマットに変換されない。

## Possible Solutions
`Jackson2ObjectMapperFactoryBean`を使って`Module` を登録することで解決する方法を紹介する。

https://github.com/terasolunaorg/guideline/issues/1022#issuecomment-132703938

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
 - [x] 5.1.0.RELEASE
 - [x] 5.0.2.RELEASE

## Issue Links
English Translation at #1510

**Comment by making** [comment]
適切なフォーマットとは？

` objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);`で対応できる話とは別でしょうか？

**Comment by making** [comment]
http://stackoverflow.com/questions/14026081/jackson-automatic-formatting-of-joda-datetime-to-iso-8601-format

**Comment by making** [comment]
一応、これでも設定できます・・
汎用的ですが、分かりづらい・・

``` xml
<bean id="objectMapper" class="org.springframework.beans.factory.config.MethodInvokingFactoryBean">
    <property name="targetObject">
        <bean class="com.fasterxml.jackson.databind.ObjectMapper">
            <property name="dateFormat">
                <bean class="com.fasterxml.jackson.databind.util.StdDateFormat"/>
            </property>
        </bean>
    </property>
    <property name="targetMethod" value="registerModule"/>
    <property name="arguments">
        <array>
            <bean class="com.fasterxml.jackson.datatype.joda.JodaModule" />
        </array>
    </property>
</bean>
```

**Comment by kazuki43zoo** [comment]
`Jackson2ObjectMapperFactoryBean`を使うとシンプルな定義で`ObjectMapper`を柔軟にカスタマイズできそう。

```xml
<bean id="objectMapper" class="org.springframework.http.converter.json.Jackson2ObjectMapperFactoryBean">
    <property name="modules">
        <bean class="com.fasterxml.jackson.datatype.joda.JodaModule"/>
    </property>
</bean>
```
とか
```xml
<bean id="objectMapper" class="org.springframework.http.converter.json.Jackson2ObjectMapperFactoryBean">
    <property name="modules">
        <array>
            <bean class="com.fasterxml.jackson.datatype.joda.JodaModule"/>
            <bean class="......"/>
        </array>
    </property>
</bean>
```
でよさそう。

JavaConfigの場合は `org.springframework.http.converter.json.Jackson2ObjectMapperBuilder` を使うとよさげ。

**Comment by iwanagah** [comment]
`Jackson2ObjectMapperFactoryBean`　を使うのがよいと思います。
ただ、`com.fasterxml.jackson.databind.ObjectMapper`　を`org.springframework.http.converter.json.Jackson2ObjectMapperFactoryBean`に単純に置き換えると一部挙動が変わります。
JavaDocにも書いてありますが、以下です。

* MapperFeature.DEFAULT_VIEW_INCLUSION is disabled
* DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES is disabled

※JavaDoc：http://docs.spring.io/autorepo/docs/spring/4.2.3.RELEASE/javadoc-api/org/springframework/http/converter/json/Jackson2ObjectMapperFactoryBean.html

`DEFAULT_VIEW_INCLUSION` は`@JsonView` を使用した場合にアノテーションを付けなかった項目を出力するかどうか、
`FAIL_ON_UNKNOWN_PROPERTIES` はJSONに存在する項目がマッピング先のJavaBeanにない場合の挙動の違いでした。

追記の時にフォローしておいたほうがよいと思います。

**Comment by btshimizukza** [comment]
`JodaMapper` を使うのではなく、`Jackson2ObjectMapperFactoryBean`を使って`JodaModule` を登録するスタイルの方がよい。加えて、Joda-TimeのAPIではなくJSR-310(Data and Time API)を使う場合も意識した構成で記載する。

**Comment by kazuki43zoo** [comment]
`Jackson2ObjectMapperFactoryBean` を使用すると、自動で`JodaModule` or `JSR310Module` が登録される仕組みになっていた。
