### ISSUE TITLE
データソース切り替え機能についてのガイドライン追加

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#1071]
## Description
[複数データソースを使用するための設定](http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/DataAccessCommon.html#id14)の1つとして、データソース切り替え機能に関するガイドを追加する。

データソース切り替え機能は、何らかのコンテキスト情報（認証ユーザー情報、時間、ロケール等）によって使用する`DataSource`を切り替える機能である。

具体的には、[org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource](http://docs.spring.io/autorepo/docs/spring/4.1.4.RELEASE/javadoc-api/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.html)を実装することで実現可能である。使用例は参考URLを参照。

## Possible Solutions
[ArchitectureInDetail/DataAccessCommon.rst](https://github.com/terasolunaorg/guideline/blob/master/source/ArchitectureInDetail/DataAccessCommon.rst)へ記述追加。

## Affects Version/s
* 5.0.0.RELEASE
* 1.0.2.RELEASE

## Fix Version/s
- [x] 5.0.1.RELEASE (ja)
- [x] 5.1.0.RELEASE (ja)
- [x] 5.0.1.RELEASE (en)
- [x] 5.1.0.RELEASE (en)

## Issue Links
* http://docs.spring.io/autorepo/docs/spring/4.1.4.RELEASE/javadoc-api/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.html
* https://spring.io/blog/2007/01/23/dynamic-datasource-routing/
* http://howtodoinjava.com/2013/12/28/spring-3-2-5-abstractroutingdatasource-example/

**Comment by kazuki43zoo** [comment]
Hi @btamurutab, please translate to the English version.
