### ISSUE TITLE
VirtualWebappLoaderの代替について追記する

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#1081]
## Description

[7.5.3.1. Tomcatへのデプロイ](http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/Appendix/EnvironmentIndependency.html#tomcat
)で[VirtualWebappLoader](http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/loader/VirtualWebappLoader.html)が紹介されているが、Tomcat8では存在しない。

## Possible Solutions
Tomcat8における代替機能を追記する。

## Affects Version/s

* 5.0.0.RELEASE
* 1.0.2.RELEASE

## Fix Version/s
- [x] 5.0.1.RELEASE (ja)
- [x] 5.1.0.RELEASE (ja)
- [x] 5.0.1.RELEASE (en)
- [x] 5.1.0.RELEASE (en)

## Issue Links

* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/124
* Tomcat7 https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml
* Tomcat8 https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml
* terasolunaorg/terasoluna-tourreservation#214

**Comment by btshimizukza** [comment]
設定例として https://github.com/terasolunaorg/terasoluna-tourreservation を参照するリンクがガイドラインにあるが、ツアーサンプルはまだTomcat 8をサポートしていない。

**Comment by btshimizukza** [comment]
関連issueとして terasolunaorg/terasoluna-tourreservation#214 を発行した。

**Comment by btshimizukza** [comment]
tomcat7とTomcat8の記載はわけた方がよいと思うので、リファクタリングします。
