### ISSUE TITLE
Typo mis in DataAccessMyBatis3.rst

### ISSUE THREAD

**Issue by attarudes** [terasolunaorg/guideline#1091]
## Description
There is difference in function name used in Service class and Repository class.
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/DataAccessMyBatis3.html#entity-sql

In Repository class
　long countByCriteria(@Param("criteria") TodoCriteria criteria);
In Server 
　　long total = todoRepository.countByCriteriaForPageable(criteria);

## Possible Solutions
"countByCriteriaForPageable" needs to be replaced by "countByCriteria"

## Affects Version/s
(**Required**: Please select affected versions)
* 5.0.0.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE
- [x] 5.0.1.RELEASE

## Issue Links
Non

**Comment by btshimizukza** [comment]
There is a same mistake in the English version.
