### ISSUE TITLE
codelist クラス図の typo

### ISSUE THREAD

**Issue by btkodakak** [terasolunaorg/guideline#1095]
## Description
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/Codelist.html の「Picture - Image of codelist class diagram」に typo がある。

pkg org.teras**p**luna.gfw

## Possible Solutions
pkg org.terasoluna.gfw

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.1

**Comment by btshimizukza** [comment]
There is a same mistake in the English version.
