### ISSUE TITLE
[TutorialREST] Document bug in section 7.1.3

### ISSUE THREAD

**Issue by btkitsunedukam** [terasolunaorg/guideline#1102]
## Description
In section 7.1.3, there is a mistake in the below sentence.

https://github.com/terasolunaorg/guideline/blob/master/source/TutorialREST/index.rst

■7.1.3.6.4. PUT Todoの実装
* 項番(1)
　メソッドがGETのリクエストを処理するために、method属性にRequestMethod.GETを設定する。

## Possible Solutions
* 項番(1)
　メソッドがPUTのリクエストを処理するために、method属性にRequestMethod.PUTを設定する。

## Affects Version/s
* 5.0.0.RELEASE
* 1.0.2.RELEASE

## Fix Version/s
- [x] 5.0.1.RELEASE
- [x] 5.1.0.RELEASE

## Issue Links
*

**Comment by btshimizukza** [comment]
There is a same mistake in the English version.
