### ISSUE TITLE
Add how to use encryption (symmetric/asymmetric)

### ISSUE THREAD

**Issue by btkodakak** [terasolunaorg/guideline#1106]
## Description
「6. セキュリティ対策」に、暗号化に関するガイドラインを追加する

* 共通鍵暗号方式
* 公開鍵暗号方式
* 暗号論的擬似乱数生成器

に関して概要とAPIの使い方を追加する。

## Possible Solutions
6.8 として [Security/Encryption.rst](https://github.com/terasolunaorg/guideline/blob/master/source/Security/Encryption.rst) を追加。

## Fix Version/s

- [x]  5.1.0.RELEASE

## Issue Links

* http://www.cryptrec.go.jp/list.html
* http://www.cryptrec.go.jp/images/cryptrec_ciphers_list_2013.pdf
* http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#crypto

**Comment by making** [comment]
Consider supporting https://github.com/spring-projects/spring-security/commit/a48cc18858b1df22821462df785693647d222df9

**Comment by making** [comment]
https://github.com/dsyer/spring-security-rsa has `RsaSecretEncryptor`.
This would be convenient than native JCA.
But i'm not sure this is an official and stable library...
