### ISSUE TITLE
[CreateWebApplicationProject] Add how to build a war file

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1146]
## Description
Currently, how to build a war file does not described.

## Possible Solutions
Add how to create a war file in the "4.1. Create Web application development project"

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE(ja)
- [x] 5.0.1.RELEASE(ja)
- [x] 5.1.0.RELEASE(en)
- [x] 5.0.1.RELEASE(en)

## Issue Links
None

**Comment by kazuki43zoo** [comment]
Hi @btamurutab, please translate to the English version.

**Comment by btshimizukza** [comment]
@btamurutab @attarudes , thanks for translating!!

**Comment by btshimizukza** [comment]
Small polishing is need in the English version.
