### ISSUE TITLE
Add how to implement E-mail sending (SMTP)

### ISSUE THREAD

**Issue by btkitsunedukam** [terasolunaorg/guideline#1165]
## Description
Springのメール送信機能についてのガイドを追加する。

## Possible Solutions
ArchitectureInDetail/Email.rst を追加する。

## Fix Version/s
- [x] 5.1.0

## Note

翻訳は #1329 で対応。

**Comment by btshimizukza** [comment]
翻訳は#1329で対応する。 追加で記載することがなければ本issueはcloseする。

**Comment by kazuki43zoo** [comment]
一旦クローズ。何かあればreopenして対応する。
