### ISSUE TITLE
チュートリアルをオフラインで実施するためのmvnコマンドに関するメモの追記

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#1197]
## Description

オフラインでチュートリアルを実施したいことがある模様

## Possible Solutions

ネットワークがつながる環境で、

```
$ mvn dependency:go-offline -Dmaven.repo.local=フォルダ名
```

を実行し、オフライン環境にフォルダをコピーする。

オフライン環境側で、

```
$ mvn package -Dmaven.repo.local=フォルダ名
```

を実行。

↓のあたりに書く。
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ImplementationAtEachLayer/CreateWebApplicationProject.html#id2

## Affects Version/s
* 5.0.0-5.0.1

## Fix Version/s
- [x] 5.1.0 (ja)

## Issue Links
* http://takezoe.hatenablog.com/entry/20120302/p1
* #1343 (英語化issue)

**Comment by akimotokn** [comment]
オフライン環境下におけるMavenの使用方法（シングルプロジェクト）

(0) 動作環境
```bash
Maven 3.3.3
```
(1) プロジェクト作成（オンライン環境）
```bash
$ mvn archetype:generate -B^
 -DarchetypeCatalog=http://repo.terasoluna.org/nexus/content/repositories/terasoluna-gfw-releases^
 -DarchetypeGroupId=org.terasoluna.gfw.blank^
 -DarchetypeArtifactId=terasoluna-gfw-web-blank-archetype^
 -DarchetypeVersion=5.0.1.RELEASE^
 -DgroupId=todo^
 -DartifactId=todo^
 -Dversion=1.0.0-SNAPSHOT
```
(2) (1)で作成したプロジェクトのpom.xmlが存在するディレクトリへ移動
```bash
$ cd todo
```
(3) repository複製（オンライン環境）
　　-> この時、repositoryは(2)で指定したフォルダ直下に生成される。
```bash
$ mvn dependency:go-offline -Dmaven.repo.local=repository
```
(4) .warファイル生成（オンライン環境下）
```bash
$ mvn package -Dmaven.repo.local=repository
```
(注意) 作業(4)をオンライン環境下で行わないとrepositoryの中に以下のフォルダが生成されない。
　　　　　-> 以後のオフライン環境下でpackageやcompileが不可能になる。
　　　　　・ ../repository/xmlpull
　　　　　・ ../repository/xpp3

(5) オフライン環境下にフォルダをコピー

(6) Mavenの各種コマンドを実行（今回はpackageとcompileを確認）
```bash
$ mvn package -Dmaven.repo.local=repository
$ mvn compile -Dmaven.repo.local=repository
(*)この時、-Dmaven.repo.local=repositoryによってrepositoryを指定しているため"-o"は不要
```

**Comment by akimotokn** [comment]
STSへインポート（Existing Maven Projects）

(0) 動作環境
```bash
STS 3.6.3
```
(1) repositoryのパスを指定
　　 ->  設定ファイル（.../conf/settings.xml）の以下を編集
```bash
<!-- localRepository
  | The path to the local repository maven will use to store artifacts.
  |
  | Default: ${user.home}/.m2/repository
<localRepository>/path/to/local/repo</localRepository>
  -->
```
(2) (1)で指定したパスにrepositoryをコピー

(3) STSにMaven Projectをインポート

**Comment by akimotokn** [comment]
STSへインポート（.warファイル）

オフライン環境下におけるMavenの使用方法に示した作業を行って得た.warファイルをインポートする場合、
repositoryの設定を行う事なく、.warファイルをSTSへインポートするだけでOK。

**Comment by making** [comment]
@akimotokn thx. rstファイルに書いてpull requestお願いします。

CreateWebApplicationProject.rstのAppendixに追加かな？

**Comment by btshimizukza** [comment]
英語化issue(#1343)を発行済みなので、このissueはcloseする。
