### ISSUE TITLE
Introduce the DelegatingAuthenticationFailureHandler

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1223]
## Description
Spring Security 4.0 から `DelegatingAuthenticationFailureHandler` が追加された。
このクラスを使用すると、`ExceptionMappingAuthenticationFailureHandler` に比べて柔軟な設定が可能になる。

## Possible Solutions
認証の章にて、`DelegatingAuthenticationFailureHandler` の紹介を追加する。

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
- [ ] 5.1.0

## Issue Links
* #812
* https://jira.spring.io/browse/SEC-2835
*  #1325

**Comment by iwanagah** [comment]
#1325 にて対応済みか確認してください。

**Comment by ikeyat** [comment]
#1325で当該クラスの紹介のみ追加している（実装例などは無しだが本Issueの目的は達成）。
#1325に統合し、本Issueはクローズ。
