### ISSUE TITLE
Servlet3.0ファイルアップロードAPIのJBossEAP6影響

### ISSUE THREAD

**Issue by n-agetsu** [terasolunaorg/guideline#1253]
## Description
5.17.1 Overviewの冒頭でNoteで指摘している、Servlet3.0のファイルアップロードAPI不具合について、現状は代表例としてWebLogicが記述されているが、JBossEAP6.x系の最新6.4でも全く同じ問題を踏む事例があった。もし、JBossがガイドラインのスコープ外でなければ、注意すべきAPサーバの1つとして追記するのはいかがでしょうか。

http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/FileUpload.html?#overview

## Possible Solutions
『WebLogicなど一部のアプリケーションサーバー上』の部分にJBossも追記。

## Affects Version/s
* 5.0.0.RELEASE
* 1.0.2.RELEASE

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.1

## Issue Links
いずれもOpenで、具体的な修正予定はなし。

Bug 1213790 - Multipart/form-data charset detection
https://bugzilla.redhat.com/show_bug.cgi?id=1213790
ガイドラインで指摘されている内容と同じく、ファイルとテキストフォームを同時送信すると、
リクエストパラメータが文字化けする不具合。

Bug 1246939 - Multiple file uploading issue
https://bugzilla.redhat.com/show_bug.cgi?id=1246939
複数のファイルをアップロードすると、最後の1ファイルしかAPIで取得できない不具合。

**Comment by kazuki43zoo** [comment]
レポートありがとうございます。
5.0.1.RELEASE(8月上旬リリース予定) では、JBoss EAP 6.4も検証対象APサーバにしており、同様の事象を検出しています。
我々が把握している範囲でのJBoss EAP 6.4利用時の注意事項については、[こちら](https://github.com/terasolunaorg/terasoluna-gfw/wiki/JBoss_ja) を参照していただければと思います。

また、APサーバ毎の注意事項は [こちら] (https://github.com/terasolunaorg/terasoluna-gfw/wiki#notes-for-each-application-server) で管理しています。現時点では、Tomcat7/8, WebLogic12c, JBoss EAP 6.4 が検証済みのAPサーバになります。

ガイドラインへの反映については、5.0.1.RELEASEのガイドラインに反映したいと思いますが、ひょっとしたら5.1.0(5.0.2)になってしまうかもしれません。
