### ISSUE TITLE
[Authentication]エラー発生時にセッションクリア（ログアウト）する実装方法の紹介

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1285]
## Description

システムエラーが発生した場合は、業務継続させたくないケースが多いと思うので、
エラー画面を返す前（例外ハンドリングの中）でログアウト相当のセッションクリアを行うような要件もありうる。
セッションクリアする場合の実装方法をガイドラインで紹介する。

＃さもないと、ブラウザバックでシステムエラーから業務継続できてしまったり、
＃不要なセッションが残ってしまったりと問題が起きるため

## Possible Solutions

 * 実装ポイント
   SystemExceptionResolverの拡張でしょうか？
   http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/ExceptionHandling.html#exception-handling-basic-flow-resolver-label
 * セッションクリア方法
    * SecurityContextをclearContext()する
      http://docs.spring.io/spring-security/site/docs/3.2.0.RELEASE/apidocs/org/springframework/security/core/context/SecurityContextHolder.html#clearContext()
    * Servlet3のHttpServletRequest.logout()を呼び出す
      https://spring.io/blog/2012/12/17/spring-security-3-2-m1-highlights-servlet-3-api-support
    * HttpSession#invalidate()
        * invalidateした後にSecurityContextが新たにセッションに保存されてしまい、認証情報がセッションに残ってしまう模様

## Affects Version/s
* 5.0.x.RELEASE
* 1.0.x.RELEASE

## Fix Version/s
- 5.1.0.RELEASE (at #1325 )

## Issue Links
#1325

**Comment by ikeyat** [comment]
@btsatoutkzy 
#1325にてガイドラインに記載済みか否かの確認だけ、お願いいたします。
記載済みでない場合は、マイルストーンを延長し、5.1.0より後での対応とします。

**Comment by btsatoutkzy** [comment]
@ikeyat 
「SecurityContextをclearContext」
上記でガイドライン記載済みです。

**Comment by ikeyat** [comment]
#1325 側で管理するので、クローズ。
