### ISSUE TITLE
SqlSessionTemplateをbean定義した際のwarnログについて

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1292]
## Description

SqlSessionTemplateをbean定義するとアプリケーション停止時にwarnログが出力されるためガイドラインに[暫定的な回避方法](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/DataAccessMyBatis3.html#dataaccessmybatis3howtoextendexecutortypebatchindividualsetting)を紹介しているが、この事象は mybatis/spring#77 で解決された。

## Possible Solutions
MyBatis-Spring 1.2.4 でリリースされたので、フレームワークスタックに反映したタイミングでガイドラインに紹介している回避策も削除する。

## Affects Version/s
* 5.0.0.RELEASE - 5.1.0.RELEASE

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1

## Issue Links
* mybatis/spring#77
* mybatis/spring#78

**Comment by sasakitsy** [comment]
リリース対象のMyBatisのバージョンを確認する。

**Comment by sasakitsy** [comment]
5.1.1、5.2.0ともにMyBatis-Spring1.2.5とするため、ガイドラインの[暫定的な回避方法](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/DataAccessMyBatis3.html#dataaccessmybatis3howtoextendexecutortypebatchindividualsetting)を削除する。

**Comment by sasakitsy** [comment]
ガイドラインの[暫定的な回避方法](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/DataAccessMyBatis3.html#dataaccessmybatis3howtoextendexecutortypebatchindividualsetting)の削除によるテストケースの変更等、影響がないか確認する。

**Comment by btijnb** [comment]
@sasakitsy 

影響確認結果です。（”SqlSessionTemplate”でGrepした結果です。）

* **SqlSessionTemplateをBean定義しているソースはありましたが、destroy-method属性は設定してないので影響はないと思います。**

 * **source path :** spring-functionaltest\spring-functionaltest-domain\src\main\resources\META-INF\spring\spring-functionaltest-infra.xml

* **影響はないと思われますが、DataSourceのBean定義しているソースファイルでdestroy-method="close"の属性を設定しています。**
 * spring-functionaltest\spring-functionaltest-env\src\main\resources\META-INF\spring\spring-functionaltest-env.xml　など

**Comment by btyoshikawaa** [comment]
@btijnb 
Do not write the internal information to external Github. Please remove https://github.com/terasolunaorg/guideline/issues/1292#issuecomment-234186298.
