### ISSUE TITLE
@SessionAttributesで管理している読み取り専用オブジェクトの取得方法について

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1293]
## Description

ガイドラインではメソッドの引数にセッションに格納しているEntityを宣言して取得するようにガイドされているが、メソッドの引数に宣言するとリクエストパラメータがバインドされる可能性がある。

http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/SessionManagement.html#id18
## Possible Solutions

読み取り専用のオブジェクトは`ModelMap.get(key)`又は`Model.asMap().get(key)`で取得することで、リクエストパラメータのバインドを抑止した方がよい。

メソッドの引数を使って読み取り専用のオブジェクトを安全に取得する方法は、https://jira.spring.io/browse/SPR-13402 (Spring 4.3)で対応される。
## Affects Version/s
- 5.0.0.RELEASE - 5.0.1.RELEASE
- 1.0.0.RELEASE - 1.0.3.RELEASE
## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1
## Issue Links

Nothing

**Comment by kazuki43zoo** [comment]
4.3.0 RC1で対応され、`@ModelAttribute(binding=false)` を指定すると、リクエストパラメータがバインドされなくなる。
https://jira.spring.io/browse/SPR-13402

**Comment by kazuki43zoo** [comment]
ちなみに・・・「`@SessionAttributesで管理している`」と表現していますが、正確には「`Modelとして管理している`」ですね。
たとえば・・・、`@ModelAttribute`メソッド使って`Model`に格納した読み取り専用のオブジェクトをHandlerメソッドの引数として受け取りたい場合も同じことが言えるので。

**Comment by btyoshikawaa** [comment]
see https://github.com/terasolunaorg/guideline/pull/2404#issuecomment-273679849

**Comment by btyoshikawaa** [comment]
@bturamatuyu 
Please write for 5.2.1 .

**Comment by btyoshikawaa** [comment]
Japanese ver. fix Complated.

**Comment by sasakitsy** [comment]
Translating #2641 
And close this.
