### ISSUE TITLE
[PublicReview]6.7. CSRF対策

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#13]
内容の対するコメント
----
（１）
6.7.1. Overviewにて、
冒頭に「Webサイトにスクリプトや自動転送(HTTPリダイレクト)を実装することにより、」と「自動転送(HTTPリダイレクト)」も攻撃の手法の１つとしているが、Spring Securityから提供している機能のデフォルト動作ではGETはチェックされないため、「自動転送(HTTPリダイレクト)」による攻撃は防げない。
ドキュメント内での矛盾が発生していそう・・。

（２）
6.7.2.1.1. spring-security.xmlの設定にて、
CsrfAuthenticationStrategyが何者か簡単に説明がよいと思います。

（３）
6.7.2.1.1. spring-security.xmlの設定にて、
「AccessDeniedHandlerImplのerrorPageプロパティを省略した場合の、エラーハンドリングについて」の補足として、
403はCSRFエラー以外にも発生する可能性がある事を記載しておいた方がいいかも？Spring Securityの設定次第かもしれないが・・。認証・認可にSpring Securityを使わない場合もあるかもしれないので・・・。
＋
その場合、「csrf-error.jsp」ではなく「forbidden-error.jsp」とかの方が妥当かな・・。
＋
CSRFエラーとしてハンドリングしたい場合はAccessDeniedHandlerImplのerror-page、まるっとforbiddenエラーならweb.xmlのerror-pageを推奨パターンにすればよいのでは？

（４）
6.7.2.2.1. CSRFトークンを自動で埋め込む方法にて、
「CSRFトークンはログインのタイミングで生成される。」の意味がよくわからなかった・・。
どういう意味なのでしょうか？

記述に対するコメント
----
（５）
6.7.2.2.2. CSRFトークンを明示的に埋め込む方法にて、
「CSRFトークンチェック対象のリクエスト(デフォルトでは、HTTPメソッドが、GET, HEAD, TRACE, OPTIONS以外の場合)で、・・」のnoteはここで必要？
いらない気がしますが・・。

**Comment by btshimizukza** [comment]
5.1.0で全面的にセキュリティ編の記載内容を見直したので、本Issueはクローズします。
