### ISSUE TITLE
Spring Security チュートリアルでログアウトできない

### ISSUE THREAD

**Issue by tabatakz** [terasolunaorg/guideline#1300]
## Description

「6.2.4.2.4. ログアウトボタンの追加」で述べられている方法（以下JSPの抜粋）でログアウトボタンを追加してもSubmitされないためログアウトできない。

``` jsp
            <!-- (1) -->
            <form:form action="${pageContext.request.contextPath}/logout">
                <button>Logout</button>
            </form:form>
```

## Possible Solutions

これでうまくいきました。

``` jsp
            <!-- (1) -->
            <form:form action="${pageContext.request.contextPath}/logout">
                <button type="submit">Logout</button>
            </form:form>
```

## Affects Version/s
* 5.0.1.RELEASE

### typeをsubmitへ変更
- [x] 5.1.0
- [x] 5.0.2

### SPR-13426
- [ ] 5.1.0

## Issue Links
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/Security/Tutorial.html#id40

**Comment by making** [comment]
元のコードでもうまくいくみたい(Chrome, IE11)ですが、
ブラウザは何でしょうか？

**Comment by kazuki43zoo** [comment]
HTML5の仕様上は`<button>` タグの`type`属性のデフォルト値は `submit` と読み取れます。
http://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-type

ブラウザの種類と正確なバージョンを教えて頂きたいです。
よろしくおねがいします。

**Comment by kazuki43zoo** [comment]
ちなみに・・
HTML4もXHTMLのデフォルトも`submit`そうです・・。

http://www.w3.org/TR/html401/interact/forms.html#adef-type-BUTTON
http://xhtml.com/en/xhtml/reference/button/

**Comment by tabatakz** [comment]
>ブラウザの種類と正確なバージョンを教えて頂きたいです。
IE 10.0.9200.17457 です。

**Comment by btshimizukza** [comment]
Microsoftの[API Reference](https://msdn.microsoft.com/en-us/library/ms535211(v=vs.85).aspx)をみると、最後の方のRemarksに[ドキュメント互換モード](https://msdn.microsoft.com/en-us/library/cc288325(v=vs.85).aspx)によってtypeのデフォルト値が違うと記載されてますね。

おそらくこの辺りが影響しているのではないかと思います。

**Comment by making** [comment]
とりあえず`<form:button>`にしておくのが無難ですかね

**Comment by btshimizukza** [comment]
`<form:button>`だと、なんらかのオブジェクト(通常はフォームオブジェクト)が`<form:form>` に割り当てられていないとエラーになってしまいます・・・。
`<form:input path="プロパティ名">` などプロパティにアクセスするタグならエラーにした方がいいけど、プロパティにアクセスしない`<form:button>` ではエラーにしないでほしい・・。

直し方正しいかは怪しいですが、[JIRA](https://jira.spring.io/browse/SPR-13426) を起票してPRしてみました。
↑が対応されなければ、`<button type="submit">` が確実な方法そうです。

**Comment by making** [comment]
なるほど。
SPR-13426の対応を見守りますか。

**Comment by making** [comment]
いったん`<button type="submit"> `で対応。
リリース付近で、[SPR-13426](https://jira.spring.io/browse/SPR-13426)の状況を見て(5.1.0で?)`<form:button>`にするかどうか検討。

**Comment by iwanagah** [comment]
直接の対応は完了しているので、クローズとする

**Comment by kazuki43zoo** [comment]
[SPR-13426](https://jira.spring.io/browse/SPR-13426) は「Works as Designed」でクローズされました。PRで修正した場所が `<bind>` タグでも使われていて、そちらの動きを変えずに対応するには少し大変そうで、頑張っても大きな効果がなさそうなのでPR取り下げました。
