### ISSUE TITLE
セッションスコープのBeanの参照方法について

### ISSUE THREAD

**Issue by ishiharatmy** [terasolunaorg/guideline#1306]
## Description

ガイドラインでは、セッションスコープのBeanをjspから参照するにはModelオブジェクトにBeanを追加するという記載がある。しかし、これではBeanを参照するviewに関連するすべてのControllerにModelオブジェクトにBeanを追加する処理を記述する必要がある。

http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/SessionManagement.html#id21

SpEL式を用いれば、直接セッションスコープのBeanを参照できる。そのため、ModelオブジェクトにBeanを追加する処理を削除して、SpEL式を用いてjspから参照する方法を記載する。

## Possible Solutions

http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/SessionManagement.html#id21
(2)に対応するソースコード、説明を削除する。
代わりに、Noteにspel式を用いた参照方法を記載する。

http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/SessionManagement.html#sessionbeancontroller
ModelオブジェクトにBeanを追加する処理を削除する。
jspでセッションスコープのBeanを参照している箇所は、すべてSpEL式を用いた参照に置き換える。

``` jsp
<spring:eval expression="@sessionCart.cart.total" />

<spring:eval var="cart" experssion="@sessionCart.cart" />
```

## Affects Version/s
- 5.0.0.RELEASE
- 1.0.2.RELEASE

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2

## Issue Links
Nothing

**Comment by ikeyat** [comment]
@attarudes 
Please translate these changes

**Comment by btshimizukza** [comment]
English translation will resolve via #1455.
