### ISSUE TITLE
Add the REST Client(HTTP Client) section

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1307]
## Description
`RestTemplate`を使用したRESTクライアント(HTTPクライアント)処理の実装方法をガイドラインに追加する。

## Possible Solutions
\-

## Affects Version/s
\-

## Fix Version/s
- [x] 5.1.0

## Issue Links
Nothing

**Comment by kazuki43zoo** [comment]
4.2.1まではデフォルトで登録される`HttpMessageConverter`を使うと、大きなファイルをダウンロードすると`OutOfMemoryError`が発生する可能性があった。(無条件にbyte配列に変換するため)
4.2.2より([SPR-13443](https://jira.spring.io/browse/SPR-13443)の対応により)レスポンスボディを`InputStream`のまま(`InputStreamResource`として)扱うことが可能になったため、`OutOfMemoryError` が発生するリスクを抑えることができるようになる。5.1.0対応(Spring IO Platform 2.0対応)でとりこむSpring Frameworkのバージョンが4.2.2以上なら、↑の内容をガイドラインに反映する。

`responseType` に `InputStreamResource` を指定すると レスポンスBODYを `InputStream` のまま扱うことができるようになる。

```java
RestTemplate restTemplate = new RestTemplate();
Resource resource = restTemplate.getForObject("http://localhost:8080/myApp/foo.zip", InputStreamResource.class);
```

**Comment by making** [comment]
GJ :+1:

**Comment by btshimizukza** [comment]
resolved via 4e42d15529bf397d72d72c3cb259840bc2187782.

**Comment by btshimizukza** [comment]
英訳は #1440 で対応。

**Comment by btshimizukza** [comment]
- [ ] How to useに「`spring-web`」を依存ライブラリに追加するための設定方法を記載する
