### ISSUE TITLE
ページ情報等の画面表示に関わる情報の保持方法

### ISSUE THREAD

**Issue by ishiharatmy** [terasolunaorg/guideline#1308]
## Description

ある画面から別の画面に遷移して再度元の画面に戻ってきたときに、元の状態(検索条件等)で画面を表示したいという要求がある。この要求を満たすために、画面表示に関わる情報の保持方法について、推奨する方法をガイドラインに記載する。

画面表示に関わる情報の例として以下が考えられる。
* ページ情報
* 検索条件
* プルダウンリストの項目

## Possible Solutions
@SessionAttributeを利用して、画面表示情報を保持する方法が考えられる。
具体的な実装は要検討。

## Affects Version/s
* 5.0.0.RELEASE - 5.0.1.RELEASE
* 1.0.0.RELEASE - 1.0.3.RELEASE

## Fix Version/s
- [ ] 5.1.0.RELEASE
- [ ] 5.0.2.RELEASE

## Issue Links
#1240

**Comment by iwanagah** [comment]
ページネーションタグの制約事項の為、ページネーションのガイドラインに注意事項と回避策を記載する。

**Comment by ikeyat** [comment]
https://github.com/terasolunaorg/guideline/issues/1240
と重複Issueのためクローズ。
