### ISSUE TITLE
Servlet 3.0ファイルアップロード機能の文字化け解消状況（WebLogic 12c）

### ISSUE THREAD

**Issue by ymkn** [terasolunaorg/guideline#1309]
※My Oracle Supportの利用規約に抵触していそうだったので、確認がとれるまでいったん取り下げます。

**Comment by btshimizukza** [comment]
貴重な情報ありがとうございます！

**Comment by ymkn** [comment]
Oracle社問い合わせの結果、My Oracle Support内への記事リンク、および情報の共有は不可との回答でしたので、本IssueはCloseとさせてください。

ドキュメントをアップデートいただくには、将来公開されるバージョンをテストして確認するか、Oracle社が能動的にパッチ情報を公開するのを待つかする必要があるようですね。。。

**Comment by making** [comment]
@ymkn 情報ありがとうございます。WLSの次のバージョンがでたら`StandardServletMultipartResolver`で再度検証します。
