### ISSUE TITLE
処理メソッドの引数で基本的に使用しないものの中でHttpSessionが漏れている

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/guideline#1313]
## Description
[処理メソッド引数で使用しないものにHttpSessionが漏れている。]
(http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#controller-method-argument-label)にて、Noteの中にHttpSessionがあるが、一覧に存在しない。一覧にあった方が良い。記載漏れと思われる。
## Possible Solutions
~~HttpSessionを一覧に追加する。~~
直後のNoteに、``HttpSession`` の利用は同様の理由のため、他で代替できる場合は極力使用しないこと、を追記する。

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.0.RELEASE - 5.0.2.RELEASE
* 1.0.0.RELEASE - 1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [x] 5.2.0_en
- [x] 5.1.1_ja
- [x] 5.1.1_en

## Issue Links
\-

**Comment by making** [comment]
これはわざと残していたはず。(`HttpSession`じゃないとできないこともあるので)

**Comment by making** [comment]
とはいえ、むやみに使わないような注意書きが必要か・・・？

**Comment by btyoshikawaa** [comment]
@btyamadasun 
Please backport to 5.1.x.

**Comment by btyamadasun** [comment]
@btyoshikawaa 
 I have completed the backport and created the pull request. Please confirm.
