### ISSUE TITLE
Translate #708(Method Validation)

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#1322]
## Description
Reflect #708(a29cf3fe019d6e0c4961cef7a2a690c1e66a4d7e) into English version .

## Fix Version/s
- [x] 5.1.0

## Issue Links
* #708(a29cf3fe019d6e0c4961cef7a2a690c1e66a4d7e)

**Comment by kazuki43zoo** [comment]
Hi @attarudes,

I've assigned this issue to you. Please dispatch to a translator.
