### ISSUE TITLE
Compile error at example code [5.3.3.1.2. Adding the custom methods to all Repository interfaces in batch]

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1326]
## Description
5.3.3.1.2. すべてのRepositoryインタフェースに一括で追加する
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/DataAccessJpa.html#custommethod-all-label

における、「共通Repositoryインタフェースの実装クラスのインスタンスを生成するためのFactoryクラス」
の実装例が、Spring Data JPA 1.6.0.RELEASEからの変更に対応していない。
 * 名前が変更された``LockModeRepositoryPostProcessor`` が使用されているためコンパイルエラーとなる。
 * ``protected JpaRepository<T, ID> getTargetRepository(
            RepositoryMetadata metadata, EntityManager entityManager)`` のシグネチャ（戻り値）が変更になっているためコンパイルエラーとなる。
 * 名前が変更された``SimpleJpaRepository.setLockMetadataProvider()`` が使用されているためコンパイルエラーとなる。

なおTERASOLUNA FW ver 5.0.1スタックにおけるSpring Data JPAは1.7.3.RELEASEである。
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/Overview/FrameworkStack.html

## Possible Solutions
 * ``LockModeRepositoryPostProcessor`` を ``CrudMethodMetadataPostProcessor`` にリネームし、さらに ``MyProjectRepositoryFactory`` を ``org.springframework.data.jpa.repository.support`` 配下に作成する（``CrudMethodMetadataPostProcessor`` がパッケージスコープなことへの対応）。
 * ``protected SimpleJpaRepository<T, ID> getTargetRepository(
            RepositoryMetadata metadata, EntityManager entityManager)`` に変更する。
 * ``SimpleJpaRepository.setRepositoryMethodMetadata()`` に変更する。

ただし、これらの破壊的な仕様変更を考えると、本クラスの拡張は可能な限り控えるべきであり、非推奨な実装例とすべきと考える。

## Affects Version/s
* 5.0.1.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE_ja(with new feature since spring data commons 1.11.0)
- [x] 5.0.2.RELEASE_ja(gray out  to deprecate because it needs workaround for locking)
- [x] 5.1.0.RELEASE_en
- [x] 5.0.2.RELEASE_en

## Issue Links
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/DataAccessJpa.html#custommethod-all-label
https://github.com/spring-projects/spring-data-jpa/commit/5438c44c8f922cfb07f30ff7f5902631e1266224

**Comment by ikeyat** [comment]
Translated into English for  foreigner.

## Description
5.3.3.1.2. Adding the custom methods to all Repository interfaces in batch
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/ArchitectureInDetail/DataAccessJpa.html#adding-the-custom-methods-to-all-repository-interfaces-in-batch

Example code for "Factory class for creating instances of common Repository interface implementation class" does not catch up the changes since Spring Data JPA 1.6.0.RELEASE.
I got compile errors from following reasons.

* ``LockModeRepositoryPostProcessor`` is used but it was renamed and changed to package scope.
* Type of the return value for ``protected JpaRepository<T, ID> getTargetRepository( RepositoryMetadata metadata, EntityManager entityManager)``  was changed.
* ``SimpleJpaRepository.setLockMetadataProvider()`` was renamed.

On TERASOLUNA FW ver 5.0.1 stack, Spring Data JPA 1.7.3.RELEASE is adopted.
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/Overview/FrameworkStack.html#oss-versions

## Possible Solutions
* Rename ``LockModeRepositoryPostProcessor`` to ``CrudMethodMetadataPostProcessor`` and move ``MyProjectRepositoryFactory`` to ``org.springframework.data.jpa.repository.support`` package.
* Fix type of the return value to ``protected SimpleJpaRepository<T, ID> getTargetRepository( RepositoryMetadata metadata, EntityManager entityManager)``
* Fix the method name to ``SimpleJpaRepository.setRepositoryMethodMetadata()``

Anyway we should deprecate this example when we take into account that Spring Data team made these breaking changes without alarm.

## Affects Version/s
* 5.0.1.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
#1326 
https://github.com/spring-projects/spring-data-commons/commit/51b128fac1c17c8327d6fdd8c7ef87b039ac6c60

**Comment by iwanagah** [comment]
spring-data-commonsの1.11.0.RELEASEにて、Repositoryインタフェースに一括で追加する方法が簡単になる変更が入った。詳細は以下を参照のこと

https://jira.spring.io/browse/DATACMNS-542

上記の修正をするときに合わせて取り込む必要がある。

**Comment by attarudes** [comment]
Above PR #1511 implementation is compatible with 5.1.0 milestone means compatible with Spring-data-commons 1.11.0.RELEASE version but not sure about 5.0.2 milestone.

**Comment by ikeyat** [comment]
@attarudes 
I found spring data commons 1.9.4 that is used in 5.0.x line does not support it.
http://docs.spring.io/spring-data/commons/docs/1.9.4.RELEASE/reference/html/#repositories.custom-behaviour-for-all-repositories

I added a fixing direction at fix versions. Please find it.
