### ISSUE TITLE
Translate #1165(Email Sending) 

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#1329]
## Description
Reflect #1165(592c0c32884e9ca09d6d9571fc142f02dbf55e28) into English version .

## Fix Version/s
- [x] 5.1.0

## Issue Links
* #1165(592c0c32884e9ca09d6d9571fc142f02dbf55e28)

**Comment by kazuki43zoo** [comment]
Hi @attarudes,

I've assigned this issue to you. Please dispatch to a translator.
