### ISSUE TITLE
Translate #1197(how to develop an application in offline environment)

### ISSUE THREAD

**Issue by akimotokn** [terasolunaorg/guideline#1343]
## Description
Please translate [#1197: How to develop an application in offline environment](https://github.com/terasolunaorg/guideline/issues/1197) into English.

## Fix Version/s
- [x]  5.1.0 (en)

## Issue Link
* [#1197: How to develop an application in offline environment](https://github.com/terasolunaorg/guideline/issues/1197)
* [Merged commit](https://github.com/terasolunaorg/guideline/commit/c703d8d91bcb4448d67134734b8b1224b9e07e5b)

**Comment by making** [comment]
@attarudes,
Please dispatch this.
