### ISSUE TITLE
Add assertion for detect build error and warning on travis-ci

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#1361]
## Description

Currently, build is succeed when build warning occurs.
However we should be modified build warning as possible.
Hence; we add assertion for detect build warning.
## Possible Solutions

Add assertion script for detect build warning in `.travis.yml`.
All warnings will be rejected on Travis-ci.
## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2
- [x] 5.1.0 for support ERROR
- [x] 5.0.2 for support ERROR
- [x] 5.3.0 reopend
- [x] 5.2.1 reopend
- [x] 5.1.2 reopend
- [x] 5.0.3 reopend
- [x] 1.0.6 reopend
- [ ] 5.3.0  PDF compile check
- [ ] 5.2.1  PDF compile check
- [ ] 5.1.2  PDF compile check
- [ ] 5.0.3  PDF compile check
- [ ] 1.0.6  PDF compile check
## Issue Links

N/A

**Comment by btshimizukza** [comment]
Add 'ERROR` at assertion script.

**Comment by ikeyat** [comment]
Need to improvement for #1879

**Comment by btmikamihdt** [comment]
@ikeyat 
Please review #2149

**Comment by ikeyat** [comment]
@btmikamihdt 
PDFビルド時のerror/warningの検知も追加できないか調査お願いできますでしょうか。latexなどをtravisのコンテナインストールしてあげるようtravis.ymlに定義すれば実行できそうな気がします。
参考：http://qiita.com/yyu/items/e3451caa86779b94abe1

**Comment by kazuki43zoo** [comment]
@ikeyat 

できると思うけど、時間かかりそうなｗ
もし時間がかかるようなら、PDFのビルドの実行契機は考慮した方がよい気がする。

**Comment by btmikamihdt** [comment]
@ikeyat  @kazuki43zoo 
承知致しました。確認致します。

**Comment by ikeyat** [comment]
@btmikamihdt 
PDFのビルドチェックは時間短縮や条件絞って実行する手段がなければ、travis ci対応せずクローズする。

**Comment by btmikamihdt** [comment]
@ikeyat @kazuki43zoo 
latexインストールを毎回行うことにより、ci実行に時間がかかるため、
latexインストールのキャッシュ化の方法について検討していた件について報告いたします。

申し訳ありませんが、latexのインストールをキャッシュすることができませんでした。


・ruby gem をインストールするbundleインストールする方法
・ディレクトリをキャッシュする方法

等の情報はネット上で見つかりましたが、gemのインストール資材はなく、

http://qiita.com/yyu/items/e3451caa86779b94abe1　の「キャッシュの設定」を参考に、
インストール先のディレクトリをキャッシュに設定する等、試しましたが上手く実行されませんでした。

以下travis-ciを試行した際のPRになります。
#2150 


申し訳ありませんが、クローズをお願い致します。

**Comment by ikeyat** [comment]
@btmikamihdt 
サイズの小さいBasicTeXでの実現は難しそうですか？
https://travis-ci.org/y-yu/travis-tex
では8分ほどで走り切っています。

**Comment by ikeyat** [comment]
basictexはosxのため、
https://github.com/travis-ci/travis-ci/issues/2312
の制約を受ける(phythonのインストールができない)。

そのため、basictex相当のtexl iveをインストールするため、
https://texwiki.texjp.org/?TeX%20Live#p06f63c2
の``-scheme``オプションを試してみる。
scheme-smallがbasictexに相当し、scheme-basicはさらにそれよりも小さい構成らしい。
https://texwiki.texjp.org/?TeX%20Live#p06f63c2

**Comment by btmikamihdt** [comment]
@ikeyat  @kazuki43zoo 
9874301febbba8d96bdb74f9b3c3d35ac6a45db7
上記のコミットでビルドするとdviファイルからpdfファイルへの変換時、（dvipdfmx実行時）に下記エラーが出力されます。


** WARNING ** Failed to load ToUnicode mapping: UTF8-UCS2
** WARNING ** Interpreting special command tounicode (pdf:) failed.
** WARNING ** >> at page="1" position="(72, 769.89)" (in PDF)
** WARNING ** >> xxx "pdf:tounicode UTF8-UCS2"
** ERROR ** Unable to find TFM file "phvb8t".


UTF8-UCS2は下記に存在するのですがdvipdfmx実行時に読み込まれません。

$ sudo find / -name "UTF8-UCS2"
/usr/local/texlive/2016/texmf-dist/fonts/cmap/dvipdfmx/UTF8-UCS2


/etc/texmf/dvipdfmx
/usr/share/texmf-texlive/fonts/cmap/dvipdfmx
配下等他に読み込んでいそうなディレクトリにUTF8-UCS2をコピーしましたが読み込まれませんでした。

dvipdfmxではなく、dvipdf（dvipdfmxはdvipdfの日本語機能等を拡張したものです。）
を使用するとビルドは成功するのですが、jenkins実行時には検出されない下記エラーが出ます。


cat $ERROR_LOG_FILE
dvips: Font phvb8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvb8t
dvips: Font upjisg-h not found,  using cmr10 instead.
dvips: ! invalid char 12522 from font upjisg-h
dvips: Font phvb8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvb8t
dvips: Font phvbo8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvbo8t
dvips: Font phvb8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvb8t
dvips: Font phvb8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvb8t
dvips: Font ptmb8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font ptmb8t
dvips: Font phvr8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvr8t
dvips: Font phvb8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvb8t
dvips: Font ptmr8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font ptmr8t
dvips: Font phvr8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvr8t
dvips: Font phvb8t not found,  using cmr10 instead.
dvips: Checksum mismatch in font phvb8t
dvips: Font upjisr-h not found,  using cmr10 instead.
dvips: ! invalid char 8220 from font upjisr-h

後ほどご相談させてください。

**Comment by itouyun** [comment]
各コミットで止まっているため、要現状確認。

**Comment by kazuki43zoo** [comment]
pdfのチェックはtravisではなく内部ビルド(Jenkinsのdailyビルドとか)で検証すればよい気がします。

**Comment by itouyun** [comment]
pdfのチェックは内部課題へ移行し、本issueはcloseとする。
