### ISSUE TITLE
Add description how to prevent overwriting Cache-Control header by Spring MVC

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1373]
## Description
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/Security/SpringSecurity.html#http
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/Security/SpringSecurity.html#settings-to-assign-a-secure-http-header
6.1.3.1. Settings to assign a secure HTTP header

When a Controller class has ``@SessionAttribute`` or using its attribute model in request handler, Spring MVC automatically overwrites ``Cache-Control`` header by default.
The header directives are quite different from that added by Spring Security and it's difficult to configure before Spring 4.2. After Spring 4.2, it become easier because of ``CacheControl`` enhancement. But need to customize ``CacheControl`` directives manually.

Before Spring 4.2, it has option to disable adding ``Cache-Control`` header. After Spring 4.2, the option was deprecated. See detail JIRA issue in links.

## Possible Solutions
* JIRA先のWorkaroundは保留（妥当性が不明）。
* Spring Securityの ``<headers>`` の説明にNoteとして以下の事実を記載する
    * アプリケーションがHTTP Headerを上書きされる可能性がある。
    * Spring MVCがDescriptionに書いた条件下において、 ``Cache-Control`` headerを上書きする。

## Affects Version/s
* 5.0.0.RELEASE-5.0.1.RELEASE
* 1.0.0.RELEASE-1.0.3.RELEASE

## Fix Version/s
- [ ]  5.1.0.RELEASE

## Issue Links
* [SPR-13598](https://jira.spring.io/browse/SPR-13598)
* [Reference for cache control on Spring MVC](http://docs.spring.io/spring/docs/4.2.2.RELEASE/spring-framework-reference/htmlsingle/#mvc-caching-cachecontrol)
* [JavaDoc of ResourceHandlerRegistration](https://docs.spring.io/spring/docs/4.2.2.RELEASE/javadoc-api/org/springframework/web/servlet/config/annotation/ResourceHandlerRegistration.html#setCachePeriod-java.lang.Integer-)
* [JavaDoc of WebContentGenerator](https://docs.spring.io/spring/docs/4.2.2.RELEASE/javadoc-api/org/springframework/web/servlet/support/WebContentGenerator.html#setUseCacheControlHeader-boolean-)

**Comment by ikeyat** [comment]
@btsatoutkzy 
現在#1325で執筆している中に、本Issueの内容が組み込まれているか確認をお願いします。組み込まれていなければ、追記をお願いいたします。

**Comment by iwanagah** [comment]
#1325 に統合するのでクローズ。
