### ISSUE TITLE
6.2.4.1.3. AccountSharedServiceの作成でtypo 「呼び出し事」→「呼び出す事」

### ISSUE THREAD

**Issue by btakiyamayuk** [terasolunaorg/guideline#1374]
## Description
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/Security/Tutorial.html#accountsharedservice

Note

本ガイドラインでは、Serviceから別のServiceを呼び出し事を推奨していない。

とありますが、「呼び出す事」の誤字だと思われます。

## Possible Solutions
「呼び出し事」→「呼び出す事」に修正。

## Affects Version/s
* 5.0.0.RELEASE
* 1.0.2.RELEASE

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2

**Comment by btshimizukza** [comment]
@btakiyamayuk

報告ありがとうございます。リンク先をpublicなサイトに変更しました。

**Comment by btakiyamayuk** [comment]
@btshimizukza
ありがとうございます。publicなサイトというのがあったのですね。
次からはこちらを貼るようにします。
