### ISSUE TITLE
Add new constraints of Bean Validation

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/guideline#1389]
## Description

Add new constrains which are not provided by JSR-341 nor Hibernate Validator.

Like
* `@Before`
* `@After`
* `@ByteMin`
* `@ByteMax`

...

## Affects Version/s
* N/A

## Fix Version/s
- [x] 5.1.0.RELEASE

## Issue Links

* https://github.com/terasolunaorg/terasoluna-gfw/issues/372

**Comment by making** [comment]
closed by https://github.com/terasolunaorg/guideline/commit/0fc8b5bd36eb1ee0d05e1f148945a5336009eefb

**Comment by btshimizukza** [comment]
We need to introduce the `@ConsistOf` annotation on `Validation.rst` .

**Comment by ikeyat** [comment]
@btshimizukza 
Nice follow!
We need to add an overview and link of ``@ConsistOf`` described in ``StringProccessing.rst``.
