### ISSUE TITLE
5.0.1 ガイドラインの4.4.1.5.1. HTMLを応答する　(5)の説明の誤記

### ISSUE THREAD

**Issue by kudoueiji** [terasolunaorg/guideline#1390]
## Description
「prefix属性には、デフォルト値として".jsp"が適用されているため、明示的に指定する必要はない。」
ですが、prefixではなくsuffixの誤りかと思います。

## Possible Solutions

prefix -> suffixに修正

## Affects Version/s

* 1.0.0 - 1.0.3
* 5.0.0 - 5.0.1

## Fix Version/s

- [x] 5.0.2
- [x] 5.1.0

## Issue Links
* http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#html

**Comment by btshimizukza** [comment]
@kudoueiji 

報告ありがとうございます。次回から（できれば）ガイドラインの該当箇所へのリンクを張っておいてくれると助かります !!
