### ISSUE TITLE
Add CodePoint and CodePoint-based Validation Instructions

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1406]
## Description
Write how to use on guideline.
See https://github.com/terasolunaorg/terasoluna-gfw/issues/390

## Possible Solutions
TBD

## Affects Version/s
* N/A

## Fix Version/s
- [ ] 5.1.0

## Issue Links
https://github.com/terasolunaorg/terasoluna-gfw/issues/390

**Comment by making** [comment]
https://github.com/terasolunaorg/guideline/issues/1451 にまとめます
