### ISSUE TITLE
Add JMS section

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1407]
## Description
Introduce how to implement JMS integration with Spring JMS libraries.

## Possible Solutions
Add
* Overview of JMS with Spring
* Configuration
* Basic sending 
* Basic receiving
* Input validation
* Transaction
* etc...

This will be improved at #2085.

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0_ja
- 5.2.0_en (at #2127)

## Issue Links
N/A

**Comment by ikeyat** [comment]
@kashimakz 
Please fill issue templates.

@sasakitsy 
To be translated

**Comment by ikeyat** [comment]
I've  filled them.
Will be translated at #2127
