### ISSUE TITLE
typos in Codelist.rst

### ISSUE THREAD

**Issue by garbagetown** [terasolunaorg/guideline#1437]
## Description
In section 5.14. コードリスト, I found some typos listed below.

- コードリストを用いて入力チェックするを行う機能
- <task:scheduler> の要素を定義する、pool-size属性にスレッドの...

## Possible Solutions
Modify them as follows.
- コードリストを用いて入力チェックする機能
- <task:scheduler> の要素を定義する。pool-size属性にスレッドの...

## Affects Version/s
- 5.0.1.RELEASE
- 1.0.3.RELEASE

## Fix Version/s
- [x]  5.1.0.RELEASE
- [x]  5.0.2.RELEASE

## Issue Links
- N/A

**Comment by ikeyat** [comment]
merged at #1438.
TODO: backport to 5.0.x branch
