### ISSUE TITLE
UIで切り替えたロケールを<spring:message>に反映させるためにはSpring MVC経由でJSPを呼び出す必要がある

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1439]
## Description
`LocaleChangeIntercepter` + 任意の `LocaleResolver` を使ってロケールを切り替えるようにした場合、Springの`DispatcherServlet`経由[1]でJSPを呼び出さないと`<spring:message>` を使って出力するメッセージにロケールの変更が反映されない。
ブランクプロジェクトでは、認可系のエラー画面などいくつかのJSPをSpring MVC経由で呼び出していないため、ユーザが指定した言語でエラーメッセージが表示されない可能性がある。

[1] 
正確には、`DispatcherServlet`でリクエストを受けた後のJSP呼び出しであれば、ロケールの変更が反映される。例えば、Spring MVC配下の処理で`HttpServletResponse#sendError`し、サーブレットコンテナのエラーページ機能で任意のJSPに遷移した場合は、ロケールの変更は反映される。

## Possible Solutions
ガイドラインではエラーページの国際化については特に触れられていないが、「エラーページも国際化の必要がある場合は、必ずSpring MVC経由でJSPを呼び出すこと」という感じのNoteを追加した方がよさそう。
くわえて、ブランクプロジェクトから提供しているJSPについては、すべてSpring MVC経由で表示する(直接JSPを呼び出すのではなくView Controller経由でJSPを呼び出す)ように修正することを検討する。

## Affects Version/s
* 5.0.0.RELEASE - 5.0.1.RELEASE
* 1.0.0.RELEASE - 1.0.3.RELESAE

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2

## Issue Links
* http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/Internationalization.html

**Comment by btshimizukza** [comment]
Descriptionが正確な記載ではなかった（View経由というのは正しい表現ではなかった）ので、Descriptionを修正しました。
