### ISSUE TITLE
Translate #1307 (RestClient) 

### ISSUE THREAD

**Issue by attarudes** [terasolunaorg/guideline#1440]
## Description
Translate RestClient portion into English version .
   source/ArchitectureInDetail/RestClient.rst

## Fix Version/s
- [x] 5.1.0

## Issue Links
* #1307
* #1477 (added at 12/11)

**Comment by btshimizukza** [comment]
@attarudes and @neetapimpalnerkar ,
Please translate #1477.

**Comment by attarudes** [comment]
#1477 (added at 12/11) has been done
