### ISSUE TITLE
Add String operations

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1451]
## Description
Add general example code.

ja
- [x] Substring
- [x] Split / Join
- [x] Trimming
- [x] Padding / suppress
- [x] Japanese half/wide-characters (Kana) conversion
    https://github.com/terasolunaorg/terasoluna-gfw/issues/367
- [x] Code Points(#1406)

en
- Moved to #1559

## Possible Solutions
TBD

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.1.0.RELEASE

## Issue Links
-  http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/ArchitectureInDetail/Utilities/index.html
-  #1406

**Comment by kazuki43zoo** [comment]
We need to introduce the `@ConsistOf` annotation on `Validation.rst` .
