### ISSUE TITLE
半角全角のガイドラインの修正 #1451

### ISSUE THREAD

**Issue by btishinoyu** [terasolunaorg/guideline#1461]
## Description
テスト結果を受けて、ガイドラインの以下の不備を修正する。
 ・ ‐と"と'と\の変換を二重にFullHalfPairsBuilderに登録するサンプルになっている。
 ・ CustomFullHalf を MyProjectFullHalfと記載している。

## Fix Version/s
 - [x] 5.1.0.RELEASE
 - [ ] 5.1.0.RELEASE_en

## Issue Links
https://github.com/terasolunaorg/guideline/issues/1451

**Comment by btshimizukza** [comment]
翻訳は#1451 でまとめて対応するためクローズする。
