### ISSUE TITLE
JPA Implementaion : Search Page of entities : Wrong Annotation Used for Pagination

### ISSUE THREAD

**Issue by btundes** [terasolunaorg/guideline#1463]
## Description
A wrong(Earlier deprecated and later omitted at Spring Data Commons 1.8.0.RELEASE) annotation ``@PageableDefaults``
is being used to search the page of entities.
Guideline Location-
Controller class of the following link-
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/ArchitectureInDetail/DataAccessJpa.html#searching-page-of-entities-matching-the-conditions

## Possible Solutions
The ``@PageableDefaults`` annotation must be replaced by ``@PageableDefault`` annotation.
More ever, the attributes of the annotation also needs to be modified as per the ``@PageableDefault`` annotation.
The correct usage of annotation is as below-

```java
@PageableDefault(
            	page = 0,
            	value = 5,
            	sort = { "createdDate" },
            	direction = Direction.DESC)
				Pageable pageable
```

## Affects Version/s
- 5.0.1.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE
- [x] 5.1.0.RELEASE_en
- [x] 5.0.2.RELEASE
- [x] 5.0.2.RELEASE_en

## Issue Links
http://docs.spring.io/spring-data/commons/docs/1.8.0.RELEASE/api/org/springframework/data/web/PageableDefault.html

TODO: URL of changes in Spring Data Commons for ``@PageableDefaults``'s deprecation.

**Comment by ikeyat** [comment]
@btundes 
Please attach the URL that mentions omitting of ``@PageableDefaults`` in Spring Data Commons (Spring-JIRA/Spring github issue)

**Comment by ikeyat** [comment]
@attarudes 
Please fix the guideline.
