### ISSUE TITLE
JPA: Search All Entities matching Dynamic conditions : Wrong Class referred for query parameter binding in LIKE condition 

### ISSUE THREAD

**Issue by btundes** [terasolunaorg/guideline#1464]
## Description
A wrong class ``SqlUtils`` is used to bid the parameter to the like condition

Guideline Location-
Custom Repository  class of the following link-
http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/ArchitectureInDetail/DataAccessJpa.html#searching-all-entities-matching-the-dynamic-conditions 

Invalid Usage:

```java
bindParameters.put("itemName", SqlUtils
                    .toLikeCondition(criteria.getItemName()));
```

## Possible Solutions
Correct Usage:

```java
bindParameters.put("itemName", QueryEscapeUtils
                    .toLikeCondition(criteria.getItemName()));
```

## Affects Version/s
- 5.0.1.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE
- [x] 5.1.0.RELEASE_en
- [x] 5.0.2.RELEASE
- [x] 5.0.2.RELEASE_en

## Issue Links
https://github.com/terasolunaorg/terasoluna-gfw/blob/release/5.0.1.RELEASE/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/QueryEscapeUtils.java

**Comment by ikeyat** [comment]
@attarudes 
Please fix the guideline.
