### ISSUE TITLE
RestClientのガイドラインにApache HTTP Clientについて記載する

### ISSUE THREAD

**Issue by btishinoyu** [terasolunaorg/guideline#1477]
## Description
FactoryBeanの実装例にimport文とpom.xmlの書き方を記載する。

## Fix Version/s
 - [x] 5.1.0.RELEASE
 - [ ] 5.1.0.RELEASE_en

# Issue Links
* https://github.com/terasolunaorg/guideline/issues/1307

**Comment by btshimizukza** [comment]
English translation resolve via #1440 .
