### ISSUE TITLE
#1076 modification is not correct

### ISSUE THREAD

**Issue by btfurukawatkr** [terasolunaorg/guideline#1482]
## Description
in issue #1076, it was mentioned that the path for RedirectAuthenticationHandler is wrong and shoud be corrected as
　`org.terasoluna.gfw.security.web.redirect.RedirectAuthenticationHandler`

but was modified as:
`org.terasoluna.gfw.security.web.RedirectAuthenticationHandler`

## Possible Solutions
Needs to modify as follows
class="org.terasoluna.gfw.security.web.redirect.RedirectAuthenticationHandler">
Refer for "RedirectAuthenticationHandler" class implementation
https://github.com/terasolunaorg/terasoluna-gfw/tree/master/terasoluna-gfw-security-web/src/main/java/org/terasoluna/gfw/security/web/redirect

## Affects Version/s
* 5.0.1.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE
- [x] 5.1.0.RELEASE_en
- [x] 5.0.2.RELEASE
- [x] 5.0.2.RELEASE_en

## Issue Links
* #1076

**Comment by kazuki43zoo** [comment]
@btfurukawatkr Please fix this
