### ISSUE TITLE
@JsonView(and ResponseBodyAdvice,RequestBodyAdvice) 対応。

### ISSUE THREAD

**Issue by iwanagah** [terasolunaorg/guideline#1490]
## Description
`@JsonView`(and `ResponseBodyAdvice`,`RequestBodyAdvice`) が追加された。
それに伴い、RESTのガイドラインに説明を追記する。

## Possible Solutions
Appendixに追記がよいと思われるが調査後に検討する。

## Fix Version/s
- [x] 5.1.0.RELEASE_ja
- 5.1.0.RELEASE_en (by #1648)

## Issue Links
* #1305

**Comment by ikeyat** [comment]
@iwanagah
please push your code.
