### ISSUE TITLE
English Translation of #1332 ( inject JdbcTemplate into JdbcCodelist)

### ISSUE THREAD

**Issue by attarudes** [terasolunaorg/guideline#1494]
## Description
Please confirm #1332. 

 Under above PR, Japanese contents are modified as well partially reflected into English version also. Need to verify the English contents as well translate remaining part.

Related PRs
* #1332 
* #1496 (added at 12/17)

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2

Updated on 3rd March
 - [x] translation/5.1.0
 - [x] translation/5.0.2
 - [x] 5.0.x
 - [x] 5.1.x
 - [x] master

## Related Issues
- #501

**Comment by btshimizukza** [comment]
@attarudes 

I added #1496 as related PRs. Please check changes.
