### ISSUE TITLE
MayBe the text has a problem about "mvn archetype:generate"

### ISSUE THREAD

**Issue by PengbingChu** [terasolunaorg/guideline#1498]
3. チュートリアル(Todoアプリケーション)　の
3.3.1. プロジェクトの作成　の
》Bash上でmvn archetype:generateを実行する場合は、以下のように^を\に置き換えて実行すればよい。
⇒
Bash上でmvn archetype:generateを実行する場合は、以下のように\を^に置き換えて実行すればよい。

**Comment by btshimizukza** [comment]
@PengbingChu Thanks for reporting.

I think this description is correct.
Where is a mistake ?

**Comment by PengbingChu** [comment]
Thank you for your reply.
I made a mistake.
I ran it in CMD(windows). Overlooked the text "Bash上で".
