### ISSUE TITLE
PDF error in StringProcessing.rst

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#1504]
## Description

LaTeXに変換できない文字を使っているため、PDFビルド時にエラーが発生する。

```
...
LaTeX Warning: Hyper reference `ArchitectureInDetail/Utilities/StringProcessing
:stringoperationshowtousecustomfullhalfconverter' on page 1556 undefined on inp
ut line 103350.

[1556]
Overfull \hbox (25.19997pt too wide) in paragraph at lines 103379--103380
[][] 

! Package inputenc Error: Unicode char 鐔� (U+3BB371)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
...
```

## Possible Solutions
(Optional: Please write solutions of this issue you think)

## Affects Version/s
* master

## Fix Version/s
- [x] 5.1.0_ja
- [x] 5.1.0_en

## Issue Links
* https://github.com/kmuto/review/issues/182 (参考になるかも)

**Comment by ikeyat** [comment]
過去に行った対応。最悪画像で対応しましょう。
https://github.com/terasolunaorg/guideline/issues/1353

**Comment by btkobayashitkzp** [comment]
@ikeyat 

文字の処理方法をuplatexにてunicode変換にすることで、当issueが解消されました。
変更前のbuild-pdf.shは、.rstファイルをpdfへ一括返還するものでした。
sphinx-build では pulatex コマンドは使えず、「.rst→.tex変換」までの処理としました。
後続の処理として、uplatexコマンド(tex→dvi 変換) とdvipdfmx コマンド(dvi→pdf 変換)の変換をそれぞれ個別のコマンドで実行することにしました。
また、uplatexコマンドを2回実行することにより、PDFの目次が生成されます。

**Comment by btishiwatasns** [comment]
change only makefile
