### ISSUE TITLE
For corresponding to the 'Spring Security 4' , modify existing guideline

### ISSUE THREAD

**Issue by btsatoutkzy** [terasolunaorg/guideline#1519]
## Description
For corresponding to the 'Spring Security 4' , modify existing guideline.
However,"Spring Security" section will be excluded.

Target

- ArchitectureInDetail\Logging.rst
- ArchitectureInDetail\REST.rst
- Overview/FirstApplication.rst
- TutorialREST\index.rst
- TutorialTodo\index.rst

## Possible Solutions
- remove ``use-expressions="true"``
- remove ``<sec:headers>``
- remove  ``<sec:csrf>`` or add ``<sec:csrf disabled="true"/>``
- modify ``org.springframework.security.web.bind.support.AuthenticationPrincipalArgumentResolver`` to ``org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver``
- modify ``org.springframework.security.web.bind.annotation.AuthenticationPrincipal`` to ``org.springframework.security.core.annotation.AuthenticationPrincipal``
- modify ``j_username``, ``j_password`` to ``username``,``password``
- use SpringSecurity default values as possible

## Fix Version/s
- [x] 5.1.0

## Issue Links
#1035

**Comment by kazuki43zoo** [comment]
translation will resolve via #1570 .
