### ISSUE TITLE
Translate #1340 (Add SOAP) 

### ISSUE THREAD

**Issue by iwanagah** [terasolunaorg/guideline#1540]
## Description
Please translate #1340 . 
For changes to see https://github.com/terasolunaorg/guideline/pull/1507/files .

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.1.0_en

Updated on 3rd March
 - [x] translation/5.1.0
 - [x] 5.1.x
 - [x] master

## Issue Links
N/A

**Comment by neetapimpalnerkar** [comment]
I am facing a hyperlink issue in #1540 wherein hyperlink is visible in Japanese version but cannot be seen in English version (Integration system connector hyperlink in wsimport section). Request you to look into it.
