### ISSUE TITLE
[Encryption] Class of jdk8 is used

### ISSUE THREAD

**Issue by btsatoukzn** [terasolunaorg/guideline#1562]
## Description
 - In section 6.8.2.2.1, Base64 is used in sample source. Base64 is a class of jdk8.
 - AES/GCM is supported since JDK8.

## Possible Solutions
 - [x] Change to the class of spring security.
 - [x] Add warning on AES/GCM that it is available only JDK8.

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.1.0.RELEASE_ja
-  5.1.0.RELEASE_en (by #1641)

## Issue Links
* #1106

**Comment by kazuki43zoo** [comment]
@ikeyat @btsatoukzn 

[REST Client](https://github.com/terasolunaorg/guideline/blob/master/source/ArchitectureInDetail/RestClient.rst) でも類似の箇所があり、Java 8より前のバージョンの場合はSpring Securityのクラスを使うようにガイドししてるので、記載レベルはあわせるべき。
個人的には、未来志向でREST Clientにあわせるのがいいと思っています。
どうでしょうか？

**Comment by ikeyat** [comment]
- [ ] Please add warning on ``AES/GCM`` that it is available only JDK8.
