### ISSUE TITLE
RESTful Web Serviceのエラーハンドリングのサンプル修正

### ISSUE THREAD

**Issue by btishinoyu** [terasolunaorg/guideline#1590]
## Description
RESTful Web Serviceのエラーハンドリングのサンプルにて、`web.xml` に定義している `<error-page>` の `<location>` に、別のAPIのURL（例： `/api/v1/error?errorCode=e.sf.cmn.0503` ）を指定しているが、Servletの仕様では `<location>` にクエリ文字列(`?errorCode=e.sf.cmn.0503`)を指定した場合の振る舞いは未定義である。

## Possible Solutions
Servletの仕様に沿うように、クエリ文字列を指定しないよう修正する。

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2

**Comment by btshimizukza** [comment]
@btishinoyu 
Please create new issue for translation.
