### ISSUE TITLE
Translate #1590 (RESTful Web Serviceのエラーハンドリングのサンプル修正)

### ISSUE THREAD

**Issue by btishinoyu** [terasolunaorg/guideline#1594]
## Description
Please translate #1590.
Modifications refer to https://github.com/terasolunaorg/guideline/pull/1591/files

## Fix Version/s
- [ ] 5.1.0
- [ ] 5.0.2

Updated on 10th March
 - [ ] translation/5.1.0
 - [ ] translation/5.0.2
 - [ ] 5.0.x
 - [ ] 5.1.x
 - [ ] master

**Comment by btshimizukza** [comment]
@attarudes 

Please dispatch.
