### ISSUE TITLE
[spring security] remove 'auto-config' and correspond to spring security 4

### ISSUE THREAD

**Issue by btsatoutkzy** [terasolunaorg/guideline#1622]
## Description
#1519 の見直し

auto-config
- ``<sec:http>`` から``auto-config="true"`` を削除し、``<sec:form-login>``、``<sec:logout>`` を追加する

spring security 4
- ``use-expressions="true"`` を削除する
- ``<sec:headers>``を削除する
- ``<sec:csrf>`` を削除するか、 ``<sec:csrf disabled="true"/>`` を追加する
- ``org.springframework.security.web.bind.support.AuthenticationPrincipalArgumentResolver`` から ``org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver`` に変更する
- ``org.springframework.security.web.bind.annotation.AuthenticationPrincipal`` から ``org.springframework.security.core.annotation.AuthenticationPrincipal`` に変更する
- ``j_username``, ``j_password`` を ``username``,``password`` に変更する
- SpringSecurity のデフォルトを使用するよう変更する。

※Spring Security章は除く

## Possible Solutions
N/A

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.1.0_ja
- 5.1.0_en (by #1645)

## Issue Links
#1519

**Comment by ikeyat** [comment]
@btsatoutkzy 
Some changes at #1623 seem to cause errors. Please consider how to fix them.
