### ISSUE TITLE
Translate #1574 (Add exclusions tag to dependency tag)

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1632]
## Description
Please translate #1574 
Modifications refer to https://github.com/terasolunaorg/guideline/pull/1579/files

## Fix Version/s
- [x] 5.1.0_en

Updated on 23rd March
 - [x] translation/5.1.0
 - [x] 5.1.x
 - [x] master

**Comment by attarudes** [comment]
@neetapimpalnerkar 
Since other issues have been merged, you can proceed further this issue.
