### ISSUE TITLE
リリース前最終確認により上がった軽微な修正

### ISSUE THREAD

**Issue by iwanagah** [terasolunaorg/guideline#1676]
## Description
誤字など最終確認を修正する

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.4.RELEASE

## Issue Links

**Comment by iwanagah** [comment]
changelog.rstの移行ガイドのリンクが英語版へのリンクになっているので日本語版へのリンクにする

**Comment by ikeyat** [comment]
changelogにOnjectMappperという誤字を発見しました

**Comment by ikeyat** [comment]
共通Repositoryインタフェースの実装クラスのインスタンスを生成するためのFactoryクラス

が全部インライン化されてる
