### ISSUE TITLE
5.1.0.RELEASEガイドラインPDF目次が表示されない。

### ISSUE THREAD

**Issue by btsatoukzn** [terasolunaorg/guideline#1680]
## Description
5.1.0.RELEASE版ガイドラインPDFファイルで、目次の内容が表示されていない。

## Possible Solutions
REST.rstの表において、カラム数設定誤りがあり、それを修正することで目次が表示されるようになる。

## Affects Version/s
- 5.1.0

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.0

**Comment by ikeyat** [comment]
Please backport to ``release/5.1.0.RELEASE``
