### ISSUE TITLE
Optimize the order of chapters and sections

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1683]
## Description
主にチュートリアル#54やAppendixなどが散在、肥大化しているので、章構成を体系立てる。

## Possible Solutions
TBD

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0_ja
- 5.2.0_en (via #1896)

## Issue Links
* #54

**Comment by btokadanob** [comment]
### 目次案( 章名は思案中)

1. はじめに
  1. 利用規約
  1. このドキュメントが示すこと
  1. このドキュメントの対象読者
  1. このドキュメントの構成
  1. このドキュメントの読み方
  1. このドキュメントの動作検証環境
  1. ガイドラインの観点別マッピング
  1. 更新履歴
1. TERASOLUNA Server Framework for Java (5.x)のアーキテクチャ概要
  1. TERASOLUNA Server Framework for Java (5.x)のスタック
  1. Spring MVCアーキテクチャ概要
  1. はじめてのSpring MVCアプリケーション
  1. アプリケーションのレイヤ化
1. TERASOLUNA Server Framework for Java (5.x)によるアプリケーション開発
  1. Webアプリケーション向け開発プロジェクトの作成
  1. ドメイン層の実装
  1. インフラストラクチャ層の実装
  1. アプリケーション層の実装
  1. ブランクプロジェクトから新規プロジェクトの作成
  1. 開発プロジェクトのビルド
1. TERASOLUNA Server Framework for Java (5.X)によるWeb系
  1. 入力チェック
  1. ロギング
  1. 例外ハンドリング
  1. ページネーション
  1. セッション管理
  1. 二重送信防止
  1. ファイルアップロード
  1. ファイルダウンロード
  1. Beanマッピング(Dozer)
1. TERASOLUNA Server Framework for Java (5.X)によるWeb画面系
  1. Tilesによる画面レイアウト
  1. 共通ライブラリが提供する JSP Tag Libraryと EL Functions
  1. Ajax
1. TERASOLUNA Server Framework for Java (5.X)によるWeb Service系
  1. RESTful Web Service
  1. RESTクライアント（HTTPクライアント）
  1. SOAP Web Service（サーバ/クライアント）
  1. JMS Web Service（サーバ/クライアント）
1. TERASOLUNA Server Framework for Java (5.X)によるデータアクセス系
  1. 共通編
  1. MyBatis3編
  1. JPA編
  1. 排他制御編
1. TERASOLUNA Server Framework for Java (5.X)によるプロパティ管理系
  1. メッセージ管理
  1. プロパティ管理
  1. 国際化
  1. コードリスト
1. TERASOLUNA Server Framework for Java (5.X)による日時操作系
  1. 日付操作(JSR-310 Date and Time API)
  1. 日付操作(Joda Time)
  1. システム時刻
1. TERASOLUNA Server Framework for Java (5.X)による文字操作系
  1. 文字列処理
1. TERASOLUNA Server Framework for Java(5.X)による外部連携系
  1. E-mail送信(SMTP)
1.  TERASOLUNA Server Framework for Java (5.x)によるセキュリティ対策
  1. Spring Security概要
  1. 認証
  1. 認可
  1. セッション管理
  1. CSRF対策
  1. ブラウザのセキュリティ対策機能との連携
  1. XSS対策
  1. 暗号化
  1. 代表的なセキュリティ要件の実装例
1. TERASOLUNA Server Framework for Java (5.x)によるチュートリアル
  1. チュートリアル(Todoアプリケーション)
  1. チュートリアル(Todoアプリケーション REST編)
  1. セッションチュートリアル
  1. Spring Securityチュートリアル
1. Appendix (Know How)
  1. NEXUSによるMavenリポジトリの管理
  1. ボイラープレートコードの排除(Lombok)
  1. 参考書籍
  1. Spring Framework理解度チェックテスト

**Comment by kazuki43zoo** [comment]
ぱっと見で気になった点をコメントしておきます。

> 4.TERASOLUNA Server Framework for Java (5.X)によるWeb系 

* 「ii.ロギング」は、Web関係ない・・

> 6.TERASOLUNA Server Framework for Java (5.X)によるWeb Service系 

* 「iv.JMS Web Service（サーバ/クライアント）」は、JMSはそもそもWeb Serviceではない。どちらかというと外部連携かな！？

> 9.TERASOLUNA Server Framework for Java (5.X)による日時操作系
> 10.TERASOLUNA Server Framework for Java (5.X)による文字操作系

* このあたりは、「（アプリの形態に依存しない）汎用的な機能」というくくりでまとめた方がよい気がした・・ ※ロギングとBeanマッピングも

**Comment by btokadanob** [comment]
* Rest, SOAP, JMSはjavaee 系カテゴリとしてまとめると違和感なさそうな気もしますね。※章名としては悩みますが
　ただそれだとJPAは入らないの？という話にもなり若干悩ましい。。
　JMSはできしだい再考しましょうか
* ロギングは利用者の目につきやすいWebアプリ系の機能の一員として置くのがよいのかなという話でここに配置、Dozerもスタックとして内包されているので同様に、という考えです
* 汎用的な機能でまとると、今後その場所が雑多なものになりかねないので、カテゴリ分けをする、という考えです

**Comment by kazuki43zoo** [comment]
追加で、

> 4.TERASOLUNA Server Framework for Java (5.X)によるWeb系 

* 「v.セッション管理」と「vi.二重送信防止」は画面系の方な気がします。

> 8.TERASOLUNA Server Framework for Java (5.X)によるプロパティ管理系 

* 「iii.国際化」も画面系でいい気が。

**Comment by btokadanob** [comment]
@kazuki43zoo san
ありがとうございます目次を更新しました。

**Comment by btakahoshin** [comment]
> 6.TERASOLUNA Server Framework for Java (5.X)によるWeb Service
> 11.TERASOLUNA Server Framework for Java(5.X)による外部連携 
ですが、まとめて「TERASOLUNA Server Framework for Java (5.X)による外部連携」としてはいかがでしょうか。

また、
> 9.TERASOLUNA Server Framework for Java (5.X)による日時操作
> 10.TERASOLUNA Server Framework for Java (5.X)による文字操作
も今後中身がそんなに増えるような気がしないので、「TERASOLUNA Server Framework for Java (5.X)による文字列・日付操作」としてまとめるというのはいかがでしょうか。

**Comment by btokadanob** [comment]
Thranks for your comment!

* 汎用機能 ->日付、文字列、Dozer
* Web Browser - > ページネーションを移動
* 外部連携はそのままに、今後JMSがここに入る想定

please check (comment) [https://github.com/terasolunaorg/guideline/issues/1683#issuecomment-218091806]

※ 4,5章は纏めていいかも・・

**Comment by btkomodan** [comment]
「TERASOLUNA Server Framework for Java (5.X)による」が何度もでてくるので、最初だけ書いてしまって後は省いてしまってもよい気がします（グルーピング関連の話じゃなくてすみません）。
※階層が1つ深くなってしまうので厳しいですか？

* TERASOLUNA Server Framework for Java (5.X)の機能説明
  * Webアプリケーションの開発に必要な機能
    * 入力チェック etc...
  * 画面の開発に必要な機能
    * ページネーション etc...
  * 他システム連携に必要な機能
  * セキュリティ対策に必要な機能
etc...

**Comment by kuramotoki** [comment]
なんとなく目についたので少しだけ…かつ、抽象的ですみません。

機能をカテゴライズしようとすると、どちらに入れようか迷ったり、切り離せなかったりするのと、違和感がぬぐえない部分がどうしてもでてきてしまうのだと思います。
さっと見ただけで「うーん…この…」と思ってしましました。たとえば…
* WebアプリとWebServiceでロギングは両社共通だけど、別れて見える
* webブラウザの話の中で二重送信と国際化は系統が異なるけどすぐ近くにいる
* 外部プロパティファイル機能ってなんだ？

機能をカテゴライズするより、目的をカテゴライズして機能をはめ込むような考え方だとどうでしょうか？
* 様々なプロトコル/入出力に対応したい
* ソースのメンテナンス性を高めたい
* 複数の環境に対応したい
* etc...

共通的な部分はまるっとまとめてしまうしかないと思いますが…
参考になれば幸いです。

**Comment by ikeyat** [comment]
コメント受けたUpdate版目次が見たいですね。

* 「TERASOLUNA Server Framework for Java (5.X)の」なのは自明なので、この際全部取ってしまってよいと思います。
* 「Web Browser関連機能 」はjavascriptとかと誤解招きそう＋画面系以外でも使用できるものが含まれている（セッションとかコードリストとか）＋「Webアプリケーション関連機能 」との境界が今一わからない。合体してしまってもよいのでは。
* 「ブランクプロジェクトから新規プロジェクトの作成」はシングルPJの作成方法の手順で、現在非推奨化されているので、この章は削除で良いと思います。ただし、冒頭の「ブランクプロジェクトの種類」などの一部は、「i.Webアプリケーション向け開発プロジェクトの作成」にマージしたほうが良いかも。

**Comment by btokadanob** [comment]
Updateしました。
皆様コメントありがとうございます。
１頁で全項目見えるようにしたいので、階層は2階層までとしています。

**Comment by kazuki43zoo** [comment]
> プロパティファイル関連機能

この見出し必要かな？

* メッセージ管理は、「Webアプリ開発機能」 ※ログメッセージの追加とかあるけど、「Webアプリ開発機能」 かな。
* プロパティ管理は、「アプリケーション形態に依存しない汎用機能」

だと思う。

**Comment by kazuki43zoo** [comment]
節の順番は見直した方がよさそうなところはありそうだけど、いったん無視ｗ。

**Comment by btokadanob** [comment]
I updated.
当初の想定より細かいカテゴリ分けには限界を感じmath

**Comment by btakahoshin** [comment]
一旦カテゴリ分けに関してはこのあたりでFIXとして、気になる箇所があれば別途対応するということにしたいと思います。

**Comment by ikeyat** [comment]
I additionally commented here.
https://github.com/terasolunaorg/guideline/pull/1892#issuecomment-220909825

**Comment by ikeyat** [comment]
@sasakitsy 
Please create a new issue for English translation as seen in other past issues.
After create the issue, close this issue.

**Comment by attarudes** [comment]
本Issue対応前の状況：
　（CreateWebApplicationProject.rst内に設定されているタイトル下記通りです。）

 .. _CreateWebApplicationProjectBuild:
 開発プロジェクトのビルド

 .. _CreateWebApplicationProjectCustomize:
 開発プロジェクトのカスタマイズ

本Issue対応後（現在）：
　（「開発プロジェクトのビルド」が新しいCreateProject.rstへ移動され、CreateWebApplicationProject.rst内容下記通り)

 .. _CreateWebApplicationProjectBuild:
 開発プロジェクトのカスタマイズ
　
実際に下記通りで修正する必要
　（CreateWebApplicationProject.rst内容)
 .. _CreateWebApplicationProjectCustomize:
 開発プロジェクトのカスタマイズ

   (CreateProject.rst内容)
 .. _CreateWebApplicationProjectBuild:
 開発プロジェクトのビルド

**Comment by ikeyat** [comment]
@attarudes 
Thanks for the report. Please fix and create PR separately from the translation PR.

**Comment by ikeyat** [comment]
- [x] fix https://github.com/terasolunaorg/guideline/issues/1683#issuecomment-222908445
