### ISSUE TITLE
Used Deprecated Method for adding warning message and improper handling of the same to be displayed on the view

### ISSUE THREAD

**Issue by btundes** [terasolunaorg/guideline#1694]
## Description
[Refer Code Snippet block explaining ExceptionHandler for Optimistic Locking Failure Exception](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/ArchitectureInDetail/ExclusionControl.html#error-handling-in-case-of-optimistic-locking-failure)

1. Deprecated method ```warn()``` of ```org.terasoluna.gfw.common.message.ResultMessages``` is used to construct the ```ResultMessages``` object to add the warning message.

2.1  In addition to this, after adding the warning message to the ```ResultMessages``` object, this object is not added to the ```org.springframework.ui.ExtendedModelMap```. As a result of this, the added warning message would not be displayed on the view.

:point_right: 2.2 The same issue is present in the exception handler code snippet explanation for [Pessimistic Locking Failure Exception](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/en/ArchitectureInDetail/ExclusionControl.html#error-handling-in-case-of-pessimistic-locking-failure)

## Possible Solutions
The code snippet explained in guidelines needs to be modified as below

**Old Snippet**
```java
@ExceptionHandler(OptimisticLockingFailureException.class) // (1)
public String handleOptimisticLockingFailureException(
        OptimisticLockingFailureException e) {
    // (2)
    ExtendedModelMap modelMap = new ExtendedModelMap();
    ResultMessages resultMessages = ResultMessages.warn();
    resultMessages.add(ResultMessage.fromText("Other user updated!!"));
    modelMap.addAttribute(setUpForm());
    String viewName = top(modelMap);
    return new ModelAndView(viewName, modelMap);
}
```
**Modified Snippet**
```java
@ExceptionHandler(OptimisticLockingFailureException.class) // (1)
public ModelAndView handleOptimisticLockingFailureException(
        OptimisticLockingFailureException e) {
    // (2)
    ExtendedModelMap modelMap = new ExtendedModelMap();
    ResultMessages resultMessages = ResultMessages.warning();
    resultMessages.add(ResultMessage.fromText("Other user updated!!"));
    modelMap.addAttribute(setUpForm());
    modelMap.addAttribute(resultMessages);
    String viewName = top(modelMap);
    return new ModelAndView(viewName, modelMap);
}
```

:point_right: For 2.2 of above, just replace the ```warn()``` with ```warning()``` , return type of the method handlePessimisticLockingFailureException to ```ModelAndView``` and add the line ```modelMap.addAttribute(resultMessages);``` before the return statement of the existing code snippet mentioned in the guideline

## Affects Version/s
- 5.1.x
- 5.0.x
- 1.0.x

## Fix Version/s
- [x] 5.2.0_ja
- [x] 5.2.0_en
- [ ] 5.1.1_ja
- [ ] 5.1.1_en

## Issue Links
#1312

**Comment by btshimizukza** [comment]
Hi @btundes , Thanks for reporting.

Should change return type from `String` to `ModelAndView` .
This code occur compile error...

**Comment by btundes** [comment]
@btshimizukza 
I have modified the contents of the possible solutions.Please confirm if they are fine.

**Comment by btshimizukza** [comment]
@btundes :+1:

**Comment by ikeyat** [comment]
The existing error of ``String`` or ``ModelAndView`` has been corrected at #1312

**Comment by btyoshikawaa** [comment]
@btijnb 
Please backport to 5.1.x .

**Comment by sasakitsy** [comment]
Checked English translation.
