### ISSUE TITLE
Add issue and PR template

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1696]
## Description
See https://github.com/blog/2111-issue-and-pull-request-templates

## Possible Solutions
Add ``ISSUE_TEMPLATE.md`` and ``PULL_REQUEST_TEMPLATE.md `` in the root directory.
The templates are written on existing [CONTRIBUTE.md](https://github.com/terasolunaorg/guideline/blob/master/CONTRIBUTING.md).
## Affects Version/s
N/A

## Fix Version/s
- [x] master (5.2.0)  
I think backport is not necessary because GitHub may see only default branch for this feature.

- [x] master (5.2.0) index.html 

## Issue Links

**Comment by ikeyat** [comment]
See https://github.com/terasolunaorg/terasoluna-gfw/issues/509 as an example.

**Comment by ikeyat** [comment]
Please add the following template at the end and a link in CONTRIBUTE.md on master branch.

```
## ChangeLog
(To be written later by project member)

```

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please assign to change issue link in [Index](https://github.com/terasolunaorg/guideline/blob/master/source/index.rst) as well as CONTRIBUTE.md.
