### ISSUE TITLE
Add health check

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1698]
## Description
Add a description of health check that supports 
 * replies ``200`` status code and simple ``OK`` response body if it is normal status.
 * replies ``50x`` status code if it is error status.
 * checks DB access with simple validating query.

A candidate for inserting location is here.
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Utilities/index.html

## Possible Solutions
Guide how to scratch a simple health check Controller with an example.

~~Need to consider if existing OSS libraries e.g. ``spring-boot-actuator`` can be used.~~
~~http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready~~

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0_ja
- 5.2.0_en (at #2122)

## Issue Links

**Comment by making** [comment]
Spring Boot ActuatorをBoot以外で使おうとせず、
Spring Bootを素で使うべきかと。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create issue for translate, after that close this..
@ikeyat @iwanagah 
I confirmed this finally.
If you have additional comments, please re-open this or create issue for improvement.

**Comment by ikeyat** [comment]
Will be translated at #2122
