### ISSUE TITLE
Add description to add a dependency of terasoluna-gfw-string

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1699]
## Description
``terasoluna-gfw-string`` など、一部の共通ライブラリはブランクプロジェクトに定義せず、必要に応じて ``<dependency>`` を追加するスタンスをとっているが、``terasoluna-gfw-string`` に対しその旨がガイドラインに明記されていない。

http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Utilities/StringProcessing.html#id9

なお、同様スタンスの ``terasoluna-gfw-validator`` や ``terasoluna-gfw-codepoints`` などはガイドラインにその旨が記載されている。
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Validation.html#validation-terasoluna-gfw-how-to-use
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Utilities/StringProcessing.html#stringprocessinghowtousecodepointsclasses

## Possible Solutions
該当箇所に、``pom.xml`` に追加すべき ``<dependency>`` の設定例を示す。

## Affects Version/s
* 5.1.0.RELEASE

## Fix Version/s
- [x] 5.2.0_ja (#1855 and #1906)
- [ ] 5.2.0_en
- [x] 5.1.1_ja (#1910)
- [ ] 5.1.1_en

## Issue Links
#1474

**Comment by ikeyat** [comment]
See https://github.com/terasolunaorg/guideline/pull/1855#discussion_r59487152

**Comment by sasakitsy** [comment]
Leave a comment
