### ISSUE TITLE
[RESTful Web Service] Spring 4.3よりOPTIONSとHEADがデフォルトでサポートされる

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1704]
## Description

Spring 4.3より、Spring MVCのフレームワーク機能としてOPTIONSとHEADが暗黙的にサポートされるため、Controllerで個々で明示的に実装する必要がなくなる。
## Possible Solutions

暗黙的にOPTIONSとHEADがサポートされる旨を記載し、現在記載している実装例を削除する。
## Affects Version/s
- 5.1.0.RELEASE
- 5.0.0.RELEASE - 5.0.2.RELEASE
- 1.0.1.RELEASE - 1.0.4.RELEASE
## Fix Version/s
- [x] 5.3.0
## Issue Links
- https://jira.spring.io/browse/SPR-13130

## ChangeLog

- [x] Yes

**Comment by kazuki43zoo** [comment]
もう少し詳細な情報は[こちら](http://qiita.com/kazuki43zoo/items/53d2ca25c174ff618331#head%E3%81%A8options%E3%81%AB%E5%AF%BE%E3%81%99%E3%82%8B%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E3%83%8F%E3%83%B3%E3%83%89%E3%83%A9%E3%83%BC%E3%81%8C%E6%9A%97%E9%BB%99%E7%9A%84%E3%81%AB%E7%94%A8%E6%84%8F%E3%81%95%E3%82%8C%E3%82%8B-1)を参照。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create issue for translation, and close this.

**Comment by sasakitsy** [comment]
Translating #2640 
And close this.
