### ISSUE TITLE
[REST Client] Spring 4.3よりAsyncRestTemplateでCleint Interceptorの仕組みが追加される

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1705]
## Description

Spring 4.3よりRestTemplateでサポートされているClient Interceptorと同等の仕組みがサポートされる。
## Possible Solutions

ガイドラインにAsyncRestTemplateにはInterceptorの仕組みがない旨を記載しているため、同等の仕組みがある旨を記載する。
使い方の説明やサンプルコードを記載するかは、要検討。
## Affects Version/s
- 5.1.0.RELEASE
## Fix Version/s
\-

## Issue Links
- https://jira.spring.io/browse/SPR-12538
- #2369

**Comment by kazuki43zoo** [comment]
使い方は[こちら](http://qiita.com/kazuki43zoo/items/53d2ca25c174ff618331#asyncresttemplate%E3%81%AB%E3%82%A4%E3%83%B3%E3%82%BF%E3%82%BB%E3%83%97%E3%82%BF%E3%83%BC%E3%82%92%E7%B5%84%E3%81%BF%E8%BE%BC%E3%82%81%E3%82%8B-1)を参照。

**Comment by kazuki43zoo** [comment]
fixed already via #2369.
please close this.

**Comment by itouyun** [comment]
@kazuki43zoo 
Thank you your check. I close this issue.
