### ISSUE TITLE
Typo ExceptionHandling sample code

### ISSUE THREAD

**Issue by btarakists** [terasolunaorg/guideline#1747]
Description
-----
例外ハンドリングのサンプルのメソッド名がTypoしている。

http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/ExceptionHandling.html#exception-handling-how-to-use-codingpoint-controller-usecase-label

```java
@ExceptionHandler(BusinessException.class) // (1)
@ResponseStatus(HttpStatus.CONFLICT) // (2)
public ModelAndView handdleBusinessException(BusinessException e) {
    ExtendedModelMap modelMap = new ExtendedModelMap();                 // (3)
    modelMap.addAttribute(e.getResultMessages());                       // (4)
    String viewName = top(modelMap);                                    // (5)
    return new ModelAndView(viewName, modelMap);                        // (6)
}
```

Possible Solutions
-----

handdleBusinessException　→ handleBusinessException　

Affects Version/s
----
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.4.RELEASE

Fix Version/s
---
- [x] 5.2.0.RELEASE
- [x] 5.1.1.RELEASE

Issue Links
---

**Comment by iwanagah** [comment]
Please backport 5.1.x
