### ISSUE TITLE
MyBatis 3.4よりJDBC4.0実装のBLOB/CLOB用のTypeHandlerが追加される

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1775]
## Description

MyBatis 3.4より、ガイドラインで紹介していた実装例が標準でサポートされます。
そのため、JDBC 4.0をフルサポートしているJDBCドライバであれば特に追加でTypeHandlerを実装する必要はなくなります。
## Possible Solutions

現在ガイドラインで紹介している実装例は削除し、JDBC 4.0対応のJDBCドライバであれば標準機能でサポートされている旨を補足する。
JDBC 4.0未対応のフォローは要検討。
## Affects Version/s
- 5.1.0.RELEASE
- 5.0.2.RELEASE
- 1.0.4.RELEASE
## Fix Version/s
- [x] 5.3.0
- [ ] 5.3.0 en
## Issue Links
- http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/DataAccessMyBatis3.html#dataaccessmybatis3howtoextendtypehandler
- https://github.com/mybatis/mybatis-3/pull/598

**Comment by kazuki43zoo** [comment]
公式アナウンスはまだないけど、MyBatis 3.4 + MyBatis-Spring 1.3がMaven Centralにリリースされました。
JDBC 4.0サポートのJDBCドライバーであれば、BLOB⇔InputStream、CLOB⇔Reader変換用のタイプハンドラーがデフォルトで有効になります。

**Comment by sasakitsy** [comment]
MyBatisのバージョンを上げるかどうかで判断します
バージョンを上げる場合、対応します。

**Comment by kazuki43zoo** [comment]
@sasakitsy, please create issue for translation.

**Comment by sasakitsy** [comment]
I will close this issues, Because I've created issue for translate #2429
