### ISSUE TITLE
@Transactionalのtimeoutの扱いに関する説明の追加

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#1776]
## Description
現在のガイドラインでは、`@Transactinal` の `timeout` 属性 に指定した値がどのように扱われるか説明がない。
Springのリファレンスページでもほとんど説明されていないが、ここで指定した値は、使用するトランザクションマネージャへのヒントであり、トランザクション境界内の処理が指定した時間を超えた時にタイムアウトを保障するものではない。（https://jira.spring.io/browse/SPR-14038 でSpring FrameworkのリーダーであるJuergenのコメントより）
たとえば、JDBCの`DataSource`用のトランザクションマネージャである`DataSourceTransactionManager`を使う場合は、JDBCの`Statement#setQueryTimeout` に残り時間を設定することで、JDBCレベルでタイムアウトを検知する仕組みになっている。これは、DBアクセス以外の処理で時間がかかった場合は、タイムアウトにならないケースがある事を意味している。
JTA(OSSのJTA実装であるAtomikosで確認した範囲)では、コミット時にタイムアウトを超えている場合は、タイムアウトが検知されロークバックされた。

## Possible Solutions
TBD

## Affects Version/s
- 5.1.0.RELEASE
- 5.0.2.RELEASE
- 1.0.4.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- 5.4.0_en (master) another issue
- 5.3.1_en (5.3.x) another issue

## Final Solution
@Transactionalアノテーションのtimeoutを使用する際のタイムアウトチェックが行われるタイミングと挙動の注意点についてを`Note`に記載。
詳細はhttps://github.com/terasolunaorg/guideline/issues/1776#comment を参照。

対応箇所
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ImplementationAtEachLayer/DomainLayer.html#transaction-management-declare-transaction-info-label
`3.2.6.1.2. 「宣言型トランザクション管理」で必要となる情報`　の属性名の説明順に準拠し、
 Note「主要DBのisolationのデフォルトについて」と、Note「「読み取り専用のトランザクション」が有効にならないケースについて」の間に追加。

#2008 と同時対応
## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- http://qiita.com/yoshidan/items/7ce240ead835d48ce2a1
- #1777
- #2008

**Comment by making** [comment]
see also
http://qiita.com/yoshidan/items/7ce240ead835d48ce2a1

@NaozumiTaromaru 先生はよく知っている件な気がしますが。

**Comment by btshimizukza** [comment]
@making 

まさに↑の件です。
ちなみに・・MyBatis側に反映されない件は、MyBatis 3.4 + MyBatis 1.3から対応されます。

**Comment by btshimizukza** [comment]
MyBatis側での対応は、
https://github.com/mybatis/spring/issues/115

**Comment by making** [comment]
iBatis時代からあった気がするけど、対応されるのか・・・
GJ!

**Comment by kazuki43zoo** [comment]
公式アナウンスはまだないけど、MyBatis 3.4 + MyBatis-Spring 1.3がMaven Centralにリリースされました。
クエリを実行する際に、トランザクションの生存時間チェック＋生存時間を `Statement#setQueryTimeout` する処理が実行され、Springの`JdbcTemplate`使用時と同じ動作になります。

**Comment by itouyun** [comment]
上にも書いてありますが、MybatisにおけるTimeout値が連携されない（反映されない）バグ（？）は既に修正されています。
http://qiita.com/kazuki43zoo/items/1ac208a49c1d6ceeb0b8

また、

> DBアクセス以外の処理で時間がかかった場合は、タイムアウトにならないケース

とありますが、一般的のことだと思うため、特に言及不要な気がしましたがいかがでしょうか。本件、対応不要な気がします。

**Comment by itouyun** [comment]
検討会議の結果、TransactionのTimeoutについて、BeginからCommitまでの時間と勘違いしやすいため、その点はガイドしたほうが良い。
実際は、1回のDBへのアクセス時から応答が返ってくるまでの処理時間の経過時間で、Timeoutするかどうかの判定がなされる。
その場合は、NoteやWarning等への記載が無難と想定。

**Comment by NaozumiTaromaru** [comment]
> 実際は、1回のDBへのアクセス時から応答が返ってくるまでの処理時間の経過時間で、Timeoutするかどうかの判定がなされる。

この表現だと誤解しそうです。
Descriptionにも書いてある通り、
実際にタイムアウト動作(例外スロー)が行えるのはDBアクセス時ですが、
Springで設定するトランザクションタイムアウトは、トランザクション開始時点からの経過時間で判断されます。

Spring - MyBatis3連携のところ(MyBatis3からはMyBatis側が用意している)で、
Spring - iBATIS2連携(Spring側が用意していた)と同じ仕組みになっているのであれば、ですが、
・SQL実行前に既にタイムアウトしていないかチェック
・(タイムアウトしていなければ)タイムアウトまでの残り時間をクエリタイムアウトとして設定してSQL実行
のようになっているかと。

コミット時にタイムアウト検査が行われているかどうかは確認したことがありません。
Oracleで考えれば、
コミットするところまで来たのであれば、コミットした方がロールバックするよりも高速で、
タイムアウト検査をする必要性すら感じなかったので。

**Comment by itouyun** [comment]
すみません、認識誤認してました。
コメントありがとうございます。

＜正しい認識＞
- TransactionのTimeout値について、TransactionのBeginからCommitまでの時間のタイムアウト時間を計測して、超えたらタイムアウト例外を出す、というポリシーそのものは正しい。
- しかし、リアルタイムで正確にTimeout時間を超えたかどうかをチェックしているわけではなく、チェックのタイミングは限定的である。
- もしも最後のチェックタイミング以降に処理時間が掛かってしまい、Commitを迎えた場合、たとえタイムアウト時間を超えていたとしても、例外が発生せずに正常終了する。
- もしも最初の途中のチェックタイミング以前に処理時間が掛かってしまい、チェックを迎えた場合、例えば10秒設定なのに20秒経過していたら、確かにタイムアウト例外は発生するが、20秒経過後に例外が発生することになる。

＜チェックタイミング＞
上のコメント（ https://github.com/terasolunaorg/guideline/issues/1776#issuecomment-319843190 ）参照。

**Comment by yoshikawaa** [comment]
＜正しい認識＞がいまいち分かりづらかったので自分なりにまとめてみましたが、認識あってますか？

* トランザクション開始から`@Transaction#timeout`で指定した時間が経過するとタイムアウトであり、クエリ発行時とコミット時にタイムアウトしていないことをチェックする

* クエリ発行時は、クエリ発行するAPI（JdbcTemplateや`@Repository`メソッド実行時）でチェックする
  - クエリ発行前にチェックが行なわれ、**既にタイムアウトしている**場合`TransactionTimedOutException`がスローされる
  - タイムアウトまでの残り時間が`Statement#setQueryTimeout`されクエリが発行されるが、これ以降の挙動はJDBCの実装に従う（少なくとも、JdbcTemplateとMyBatis3はそう）

* コミット時は、トランザクションマネージャでチェックする
  - `DataSourceTransactionManager`では、チェックされない
  - `JtaTransactionManager`では、コミット前にタイムアウトチェックが行なわれ、**既にタイムアウトしている**場合`TransactionTimedOutException`がスローされる

* 勘違いしやすい点
  - いずれもタイムアウトチェックは既にタイムアウトしていることを確認するため、`timeout`に指定した時間が経過したタイミングで例外が返却されるわけではない
  - DataSourceTransactionManager`では、クエリ発行後の関係ない業務処理にいくら時間がかかってもタイムアウトにはならない

※コミット時のチェックは[こちら](http://qiita.com/yoshidan/items/7ce240ead835d48ce2a1)を参考にしてます

**Comment by itouyun** [comment]
@yoshikawaa 
追記ありがとうございます。
私のまとめだと`DataSourceTransactionManager`と`JtaTransactionManager`をひとまとめにして記載しているのが、よくないところですね。
**勘違いしやすい点** についても、私の書いた日本語と意図は同じでも、 @yoshikawaa さんの記載のほうが明快かつ端的でわかりやすいので、ガイドに記載するならこっちの方が良いですね。

**Comment by kazuki43zoo** [comment]
@yoshikawaa @itouyun 

> JtaTransactionManagerでは、コミット前にタイムアウトチェックが行なわれ、既にタイムアウトしている場合TransactionTimedOutExceptionがスローされる

念のため・・・
Spring提供の`JtaTransactionManager`の処理としてチェックを行っているわけではなく、JTAのAPIである`UserTransaction`の`setTransactionTimeout`を呼ぶ事でJTAの仕様？（JTAプロバイダの実装？）にもとづきトランザクションが制御される（＝トランザクションがロールバックされる？）というのが正確かな〜と思いました。（→ガイドでどう表現するかは別の話）

ちなみに・・・JTA 1.2の仕様書(PDF)をtimeoutで検索してみましたが、timeout時の仕様が明記されている箇所が見つけられなかった。＋ [JavaDoc](http://docs.oracle.com/javaee/7/api/javax/transaction/UserTransaction.html#setTransactionTimeout-int-)の説明も「Modify the timeout value that is associated with transactions started by the current thread with the begin method. If an application has not called this method, the transaction service uses some default value for the transaction timeout.」と記載があるだけで、タイムアウトを超えた時の振る舞いが明記されてない気がする・・・。

ま〜タイムアウト超えたらエラーでロールバックでしょう！というのは明白？なので仕様に明記してないのかもしれませんが、Spring提供の`DataSourceTransactionManager`使うとエラーにならずコミットされるので、明記してないことを仕様と言い切っていいのか微妙だな〜と思ってしまったりする・・・。
↓
単に見落としているだけかもしれないので、JTAおよび`JTATransactionManager`の仕様を確認した上でFinal Solutionを検討頂ければと思います。

**Comment by itouyun** [comment]
細かいことを書きすぎても、個々の仕様の説明特化のNote（Noteにしても細かすぎ）になってしまうと思うし、逆に書かなすぎても必要な情報がユーザに伝わりません。

結局ガイドに記載すべき点は以下ぐらいの情報に絞るのが良いと思います。

- 基本線
  - トランザクション開始から@Transaction#timeoutで指定した時間が経過するとタイムアウトであり、クエリ発行時とコミット時にタイムアウトしていないことをチェックする
  - いずれもタイムアウトチェックは既にタイムアウトしていることを確認するため、timeoutに指定した時間が経過したタイミングで例外が返却されるわけではない こと
  - タイムアウトチェック後に、関係ない業務処理にいくら時間がかかってもタイムアウトにはならない
- 例外線
  - `DataSourceTransactionManager`を利用した場合は、コミット時はチェックされない点
  - タイムアウトの挙動はJDBCの実装にも依存する点

これを参考に記載を検討してください。

**Comment by yoshikawaa** [comment]
@itouyun 
ガイドラインは現状、`DataSourceTransactionManager`ベース（JTAはちゃんとサポートしていない）だと思うので、

* クエリ発行時 ~~とコミット時~~ にタイムアウトしていないことをチェックする
* `JTATransactionManager`使うと、コミット時もチェックされるよ！

というアプローチのほうが良いかも。
いずれにしろ、https://github.com/terasolunaorg/guideline/issues/1776#issuecomment-326633709 のとおりJTAの仕様を確認してから書いたほうが良いですね。

**Comment by itouyun** [comment]
@yoshikawaa 
確かに、基本線をそっち側で書いたほうが良いですね！
ちょっと書き直してみました。

- 基本線
  - トランザクション開始から@Transaction#timeoutで指定した時間が経過するとタイムアウトであり、クエリ発行時~~とコミット時~~にタイムアウトしていないことをチェックする
  - タイムアウトチェック時に既にタイムアウトしていないかどうかを確認するため、timeoutに指定した時間が経過したタイミングで例外が返却されるわけではない こと
  - タイムアウトチェック後に、関係ない業務処理にいくら時間がかかってもタイムアウトにはならない こと
- 例外線
  - クエリ発行後のタイムアウトの挙動はJDBCの実装にも依存する点
  - `JTATransactionManager`を利用した場合は、コミット時もチェックされる点（と記載しちゃっていいかどうかは仕様確認次第、仕様が確認できない場合は、TransactionManagerによっては別のタイムアウトチェックタイミングも存在する、ぐらいの書き方のほうが良いかもしれない）

**Comment by btkamiyae** [comment]
JTA1.2 Specification(pdf)、 [JavaDoc](http://docs.oracle.com/javaee/7/api/javax/transaction/UserTransaction.html)、 [springでのJtaTransactionManagerの記載](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/jta/JtaTransactionManager.html)等を調査しましたが、タイムアウトが起きた場合の挙動について明記されている文面が確認できませんでした。

**Comment by itouyun** [comment]
@btkamiyae 
Thank you for your working!

@btsatouhrzzp 
Please make translation issue and close this issue.

**Comment by btsatouhrzzp** [comment]
I created #2954 issue. This issue is closed.
