### ISSUE TITLE
MyBatis 3.3使用時の@Transactinal(timeout=xxx)は意味がない

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#1777]
## Description
MyBatis 3.3 + MyBatis-Spring 1.2 だと、`@Transactinal` の `timeout` 属性に指定した値は使用されないため、指定しても意味がない。

## Possible Solutions
MyBatis 3.4 + MyBatis 1.3 (現時点ではリリース時期は未定)では、Springの`JdbcTemplate` 使用時と同様の動きになるように改善されるため、MyBatis + MyBatis-Spring のバージョンをアップするだけでよい。
5.1.1でMyBatisのバージョンアップを行わない場合は、ガイドライン上に補足説明を追加するか検討する。

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.4.RELEASE

## Fix Version/s
- [ ] 5.3.0_ja -> バージョンアップで対応予定
- [ ] 5.3.0_en
- [x] 5.2.0_ja -> バージョンアップしない場合は補足説明の追加
- [ ] 5.2.0_en 
- [x] 5.1.1_ja -> バージョンアップしない場合は補足説明の追加
- [ ] 5.1.1_en

## Issue Links
* #1776
* https://github.com/mybatis/spring/issues/115

**Comment by ikeyat** [comment]
TODO：MyBatis3.4向けは別Issue化

**Comment by sasakitsy** [comment]
5.2.0と5.1.1ともにバージョンを上げないため、補足説明を追加する。

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Please backport to 5.1.x .
@sasakitsy 
Please create new issue about https://github.com/terasolunaorg/guideline/issues/1777#issuecomment-214363443 .

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please assign to translate #1979 and #2005(backport) .

**Comment by sasakitsy** [comment]
I'll close this issue. The issues that remained supports as follows.
* https://github.com/terasolunaorg/guideline/issues/1777#issuecomment-214363443 -> #2008 
(5.3.0._ja,5.3.0_en)
* English translation for 5.2.0,5.1.1 -> #2009 
(5.2.0_en, 5.1.1_en)
