### ISSUE TITLE
problem ImplementationAtEachLayer ApplicationLayer.rst

### ISSUE THREAD

**Issue by btooshitahr** [terasolunaorg/guideline#1830]
## Description
* not enough quot
    * \`\`"sample/hello\`\`
    * \<c:out value=${helloBean.message}" /\>

## Fix Version/s
- [x] 5.2.0_ja
- [x] 5.2.0_en
- [x] 5.1.1_ja
- [x] 5.1.1_en

**Comment by btmaedahrs** [comment]
横並びで２箇所を追加で修正しました。
詳細は添付ファイル参照
[横並び修正箇所.xlsx](https://github.com/terasolunaorg/guideline/files/227425/default.xlsx)
