### ISSUE TITLE
Improvements in "Reading this documents" and "Tutorial"

### ISSUE THREAD

**Issue by itouyun** [terasolunaorg/guideline#1836]
## Description
 * 1.5. このドキュメントの読み方
 * 3. チュートリアル(Todoアプリケーション)

における各種手順の不備が存在する。

### 1. 手順の前後
 * 3.5.1. データベースのセットアップ

の作業は、

 * 3.5.2. MyBatis3を使用したインフラストラクチャ層の作成
 * 3.5.3. Spring Data JPAを使用したインフラストラクチャ層の作成

における「＊＊＊用のブランクプロジェクトの作成でプロジェクト作成し直し」た後でなければ実施できない。
　※blankのtodoではtodo-infra.propertiesが存在しないため

### 2. 手順の説明不足
 * 3.5.2. MyBatis3を使用したインフラストラクチャ層の作成
 * 3.5.3. Spring Data JPAを使用したインフラストラクチャ層の作成

の冒頭の説明で、以下の文章がある。

```
データベースのセットアップまでで作成したsrcフォルダ以下のうち、 TodoRepositoryImplクラス以外のファイルを新規作成したプロジェクトにコピーすること。`
```

この記載を信じ、srcフォルダを丸ごとコピーすると、書き換えていけないファイルが書き換わるため、アプリが正常に動作しなくなる。

### 3. 用語の誤用
3.6. おわりに
「ページング」は別のＩＴ用語である。

```
ページング処理
```

### 4. 項目列挙のミス
1.5. このドキュメントの読み方
の、Noteの「時間がない場合、まずは」の項番3と項番5の情報が同一。

```
1.はじめてのSpring MVCアプリケーション
2.アプリケーションのレイヤ化
3.チュートリアル(Todoアプリケーション)
4.TERASOLUNA Server Framework for Java (5.x)によるアプリケーション開発
5.チュートリアル(Todoアプリケーション)
6.入力チェック
```

### 1. 手順の前後
 * 3.5.1. データベースのセットアップ

の作業が、プロジェクトを作り直したあとであることを明記する。

 * Before

```
 まず、データベースのセットアップを行う。
 本チュートリアルでは、データベースのセットアップの手間を省くため、H2 Databaseを使用する。
```

 * After

```
 まず、データベースのセットアップを行う。
 本チュートリアルでは、データベースのセットアップの手間を省くため、H2 Databaseを使用する。
 ただし本セットアップは、後述のMyBatis3を使用したインフラストラクチャ層の作成およびSpring Data JPAを使用したインフラストラクチャ層の作成において、プロジェクト作成し直したあとに実施すること。
```

### 2. 手順の説明不足
次のような注意書きを追記する必要がある。

```
ただし、コピーするファイルは新規作成したファイル・変更を加えたファイルに限り、修正を加えていないファイルはコピーしないこと。
```

### 3. 用語の誤用
以下のように変更する。

```
ページネーション機能
```

### 4. 項目列挙のミス
以下のように変更する。

```
1.はじめてのSpring MVCアプリケーション
2.アプリケーションのレイヤ化
3.チュートリアル(Todoアプリケーション)
4.TERASOLUNA Server Framework for Java (5.x)によるアプリケーション開発
5.**********************（ここに入るべき章はなんでしょう？Spring Security？？）
6.入力チェック
```

## Affects Version/s
* 5.1.0.RELEASE
* All guide version

## Fix Version/s
- [x] 5.2.0_ja
- [x] 5.1.1_ja

## Issue Links
(Optional: Please link to related issues)
* #{issue no}
* or external url

**Comment by itouyun** [comment]
ドキュメント不備を1点追加（4. 項目列挙のミス）しました。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please check to need translation issue.

**Comment by sasakitsy** [comment]
English translation issue was opened bellow.
#2019 
So, this issue will be closed.
