### ISSUE TITLE
@DateTimeFormat causes NPE when StringTrimmerEditor is applied

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1863]
## Description
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Validation.html#null
``StringTrimmerEditor`` を適用したControllerのフォームで ``@DateTimeFormat`` を使用すると ``NullPointerException`` が発生する模様。

正しいソリューションがあればそれを、なければ ``StringTrimmerEditor`` の制約事項としてガイドラインへ追記すべき。（Springへ要望上げる？）

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.1.0.RELEASE以下

## Fix Version/s
- [ ] 5.2.0_ja
- [ ] 5.2.0_en
- [ ] 5.1.1_ja
- [ ] 5.1.1_en

**Comment by ikeyat** [comment]
assigned to ``btakahoshin``

**Comment by ikeyat** [comment]
assigned to ``btmaedahrs``

**Comment by kazuki43zoo** [comment]
要望じゃなくてバグとしてSpring JIRAにあげればいんじゃない？NPEはないな～と思うし。

**Comment by btmaedahrs** [comment]
``@DateTimeFormat``の対象フィールドのSetterにおいて、
独自実装している処理が原因で ``NullPointerException`` が発生していました。

そのため、``StringTrimmerEditor``が原因ではありませんでした。
（``@InitBinder``なしでも``NullPointerException`` が発生しました）

**Comment by btshimizukza** [comment]
単に実装ミスだったということでクローズします。
