### ISSUE TITLE
Change a badge extension of Travis CI (png -> svg)

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1869]
## Description
`svg` is clear image than `png`.

## Possible Solutions
Change to `svg`.

## Affects Version/s
* 5.1.0
* 5.0.1
* 1.0.4

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6

## Issue Links
N/A

**Comment by ikeyat** [comment]
@btmikamiysy 
https://raw.githubusercontent.com/terasolunaorg/guideline/master/README.md
> https://travis-ci.org/terasolunaorg/guideline.png?branch=master
