### ISSUE TITLE
[SOAP] To add a description about the Bean definition of SOAP client

### ISSUE THREAD

**Issue by btsatoukzn** [terasolunaorg/guideline#1871]
## Description
現在ガイドラインに記載されているSOAPクライアントBean定義は接続先Webサービスが起動している前提のものである。接続先が起動していない場合、SOAPクライアント側はアプリケーションを起動できない可能性がある。

## Possible Solutions
ガイドラインに、接続先サーバの起動状態を考慮しない設定方法をオプションとして記載する。

```xml
    <bean id="todoWebService" class="org.springframework.remoting.jaxws.JaxWsPortProxyFactoryBean">
        <property name="serviceInterface" value="${webservice.serviceInterface}" />
        <property name="serviceName" value="${webservice.serviceName}" />
        <property name="portName" value="${webservice.portName}" />
        <property name="namespaceUri" value="${webservice.namespaceUri}" />
        <property name="wsdlDocumentResource" value="${webservice.wsdlDocumentResource}" />
        <property name="endpointAddress" value="${webservice.todoWebService.endpointAddress}" />
    </bean>
```

　↓　（lazy-init要素と、lookupServiceOnStartupプロパティを追加）

```xml
    <bean id="todoWebService" class="org.springframework.remoting.jaxws.JaxWsPortProxyFactoryBean" lazy-init="true">
        <property name="serviceInterface" value="${webservice.serviceInterface}" />
        <property name="serviceName" value="${webservice.serviceName}" />
        <property name="portName" value="${webservice.portName}" />
        <property name="namespaceUri" value="${webservice.namespaceUri}" />
        <property name="wsdlDocumentResource" value="${webservice.wsdlDocumentResource}" />
        <property name="endpointAddress" value="${webservice.todoWebService.endpointAddress}" />
        <property name="lookupServiceOnStartup" value="false" />
    </bean>
```

## Affects Version/s
* 5.1.0.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE
- [x] 5.1.1.RELEASE

## Issue Links
* #XXX

**Comment by ikeyat** [comment]
wsdlが見つからないことが原因なだけかもしれない。その場しのぎに過ぎないlazy-initは推奨される解決策ではないと思われるが、いずれにしても注意書きと対応策は追記したほうが望ましい。、

**Comment by btyoshikawaa** [comment]
@btsatoukzn @ikeyat 
> wsdlが見つからないことが原因なだけかもしれない。

私もそう考えています。（検証は必要ですが。）
以下のような形でガイドラインに記載すると良いと思います。

* WebServiceが未公開（未起動など）でもクライアントアプリ起動可としたいなら、クライアントアプリ側でWSDLを保持するのが妥当である
* WebServiceのWSDLを参照しなければならない場合かつWebServiceが未公開（未起動など）でもクライアントアプリ起動可としたい場合のみ、例外的に`lazy-init`+`lookupServiceOnStartup`を使用すると良い

**Comment by iwanagah** [comment]
@btyoshikawaa 
そうですね。@btyoshikawaa さんが言っている通り追加したほうが良いと思います。

私も検証は一切できていないので検証次第ですが、`lookupServiceOnStartup`の設定だけではダメなんですかね？JavaDocに以下のように書いてあるので、`lazy-init`つけないで`lookupServiceOnStartup`だけ設定すればObjectは作成するけど、初期設定は最初のアクセス時に設定されるので、それで要件は満たせるような気がします。

>
Default is "true". Turn this flag off to allow for late start of the target server. In this case, the JAX-WS service will be lazily fetched on first access.

**Comment by ikeyat** [comment]
@iwanagah 
Springの問題ですかね？JIRAに上げてみますか。。。

**Comment by btyoshikawaa** [comment]
@ikeyat @iwanagah 
JIRAに関連しそうな（昔の）Issueがありましたが、再現せずで`resolved`になっていますね。
https://jira.spring.io/browse/SPR-5701

2つの要素を混同しているような気がしてきました。
`lookupServiceOnStartup`のJavadocからは、エンドポイントが公開されているかチェックしているように受け取れます。

* WSDLはWeb Serviceのインターフェイス情報で、プロキシ生成時にプロキシコードの妥当性を確認するために使用
  - クライアントで保持するWSDLを使用してプロキシを生成するか、`lazy-init="true"`を設定してプロキシ使用時（アクセス時）にWSDLを取得して生成するよう変更可能
* エンドポイントはWeb Serviceの実体で、これがなくてもプロキシは生成できるが、アクセスできないとしょうがないので起動時（プロキシ生成時）にチェック
  - lookupServiceOnStartup="false"`を設定してアクセス時に公開されているかチェックするよう変更可能

といった感じかな。
JIRAに上げるのはここらへんの整理（検証）した後で良い気がする。。。

以下の点も気になりました。
* WSDLを指定したらエンドポイントのアドレスは必要ないのでは（WSDLが持ってる）

**Comment by btijnb** [comment]
@ikeyat @btyoshikawaa @iwanagah 

**ガイドラインを参考にSOAPクラインとWEBサービスを作成し、Pivotal tc v3.1(Apache CXFを利用)で確認した結果です。**

- 前提条件としてクライアントではWSDLを保持してないです。

1. lookupServiceOnStartupをfalseに設定するだけで接続先（WEBサービス）が未起動の状態でもSOAPクライアントのアプリケーションは起動できました。設定値がtrue又はプロパティが未設定の場合はContext initialization failedエラーが発生、SOAPクライアントのアプリケーションは起動出来ませんでした。

2. lazy-init=true の設定だけではSOAPクライアントのアプリケーションは起動出来ませんでした。（設定ファイル読み込む時には大丈夫でしたが、SpringのFactoryBean type checkなどで参照している見たいです。）

3. lazy-initとlookupServiceOnStartupの組み合わせの場合lookupServiceOnStartupが優先され、lazy-init=trueでもlookupServiceOnStartup=true又はプロパティが未設定の場合はSOAPクライアントのアプリケーションは起動出来ませんでした。

WSDLをクライアントに保持した条件での検証は未実施です。検証終了次第結果をアップします。

**Comment by NaozumiTaromaru** [comment]
アプリを全く見ていませんが、
todoWebServiceがシングルトンのController(lazy-init="true"でない)にDIされているのではないですか？
この場合、todoWebServiceにlazy-init="true"をつけても付けなくても、ほとんど動作は変わりません。

すぐにインスタンスを作る必要のないtodoWebServiceを見つけたときにはlazy-init="true"でインスタンス生成が保留されますが、
todoWebServiceを何かにDIする必要があると、そのタイミングでtodoWebServiceのインスタンスも生成されます。
そのため、シングルトンのController(lazy-init="true"でない)にtodoWebServiceをDIすると、
todoWebServiceにlazy-init="true"をつけていてもつけていなくても、
アプリケーション起動時にtodoWebServiceのインスタンスが生成されます。

Controllerもlazy-init="true"にすればtodoWebServiceのインスタンス生成を遅れさせられそうですが、
lookupServiceOnStartup=trueだけで解決するならそちらの方がよいかと。

**Comment by kazuki43zoo** [comment]
> Controllerもlazy-init="true"にすればtodoWebServiceのインスタンス生成を遅れさせられそうですが、
lookupServiceOnStartup=trueだけで解決するならそちらの方がよいかと。

`lookupServiceOnStartup=false`ですかね？ｗ

> lazy-init="true"

lazyの話は @NaozumiTaromaru のコメントの通りだと思います！

**Comment by btijnb** [comment]
@NaozumiTaromaru @ikeyat @btyoshikawaa @iwanagah 
scopeはデフォルト設定なのでシングルトンです。scopeをシングルトン以外に設定した場合、 Soapクライアントのアプリケーションはlazy-init=true設定だけで起動出来ました。上記コメントにも書いてありますが、scope意識せずにlookupServiceOnStartup=trueのプロパティを追加するだけで解決できるので、lazy-init=true設定を追加する必要はないと思われます。

**Comment by btijnb** [comment]
@NaozumiTaromaru @ikeyat @btyoshikawaa @iwanagah 

**Soapクライアントで保持するWSDLを利用する場合の検証結果です。**

SoapクライアントアプリケーションはlookupServiceOnStartup、lazy-init設定値に関わらず常に起動出来ます。

> WSDLを指定したらエンドポイントのアドレスは必要ないのでは（WSDLが持ってる）

ガイドライン「5.18SOAP Web Service(サーバ/クライアント)」　[エンドポイントアドレスの上書き指定](http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/SOAP.html#soaphowtousewebserviceclient
)にも書いてありますが、WSDLファイルに記述されているURLではないURLにアクセスする場合は設定が必要です。

**Comment by btyoshikawaa** [comment]
@btijnb 
Please backport to 5.1.x .
