### ISSUE TITLE
説明内容の誤り

### ISSUE THREAD

**Issue by KunimitsuMasuda** [terasolunaorg/guideline#1872]
## Description
<箇所>
3. チュートリアル(Todoアプリケーション)
3.4.2.1. Controllerの作成
<URL>
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/TutorialTodo/index.html#controller
<内容>
「作成したインタフェースは～」とあるが、正しくは「作成したクラスは～」である。

## Affects Version/s
* All versions

## Fix Version/s

- [x] 5.2.0
- [x] 5.1.1

**Comment by kazuki43zoo** [comment]
Hi @KunimitsuMasuda , thanks for your reporting :+1:

**Comment by btkadotahr** [comment]
同様の修正が必要と思われる個所を見つけたので記載します。
<修正個所>
 - 3.4.1.4. Serviceの作成　(IMPLクラス作成のところ)
 - 3.4.2.2. Show all TODOの実装
   + 3.4.2.2.1. Formの作成
-
