### ISSUE TITLE
Add a description for @DateTimeFormat on Validation

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1873]
## Description
フォームの日付フィールドのパターン検証、型変換を実施してくれるSpringの ``@DateTimeFormat`` について、「アプリケーション層の実装」では紹介されているが、入力値検証相当の内容であるので、「入力チェック」章からも簡単な紹介と、既説明へのリンクを追加したほうが良い。

http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#applicationlayer-datetimeformat

## Possible Solutions
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Validation.html#validation-single-check
の配下に1つ節を追加するのがよさそう。

パターン検証で失敗した場合のメッセージに関しては、以下に関する言及＋リンクを追加する。
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Validation.html#id33

## Affects Version/s
* ~5.1.0.RELEASE
* ~5.0.2.RELEASE
* ~1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE_ja
- [x] 5.2.0.RELEASE_en move to #1927 
- [x] 5.1.1.RELEASE_ja
- [x] 5.1.1.RELEASE_en move to #1927

**Comment by iwanagah** [comment]
I will close this issue , Because I've create issue for translate #1927
