### ISSUE TITLE
Enable to validate string size in consideration of the surrogate pair

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/guideline#1874]
## Description
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Utilities/StringProcessing.html#id23
文字列処理の章でサロゲートペアを考慮した文字列長のガイドを提示しているが、入力チェックの章ではサロゲートペアを考慮した文字列長チェックのガイドが示されていない。

なお、`@Size`アノテーションのHibernate Validator実装では`String#length()`メソッドで文字列長を取得しており、サロゲートペアは考慮されていないように見える。

## Possible Solutions
* `@Size`アノテーションの説明にサロゲートペアについての注意を載せる
* ~~サロゲートペアを考慮したチェックを行う`@Size`アノテーション拡張方法を提示する~~

## Affects Version/s
* 5.1.0.RELEASE

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1

## Issue Links
* #1918

**Comment by ikeyat** [comment]
> @Sizeアノテーションの説明にサロゲートペアについての注意を載せる

は対応しましょう。

**Comment by ikeyat** [comment]
@sasakitsy 

> * サロゲートペアを考慮したチェックを行う`@Size`アノテーション拡張方法を提示する

についてはなるべくHibernate ValidatorなどOSS側での対応としたい。
次回リリース以降に検討したいので別Issueを作成し、本Issueにリンクさせておいてください。

**Comment by btyoshikawaa** [comment]
@btkukinom 
Please backport to 5.1.x.

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create issue to translate, and then close this.

**Comment by sasakitsy** [comment]
I will close this issue , Because I've created issue for translate #1981
