### ISSUE TITLE
Expansion of authentication process

### ISSUE THREAD

**Issue by thanhth90** [terasolunaorg/guideline#1877]
## Description
Following the gudeline: http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/Security/Authentication.html#expansion-of-authentication-process (6.3.3.8)
I implement authentication by username,password and companyId
I have issue in findOne function for get user from DB
In SampleUserDetailsService:
@Override
public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
   Account account = accountSharedService.findOne(username);
}
// this function to find user by username, but in this case, I need find user by username and companyId, so I don't know pass companyId parameter in loadUserByUsername by anyway?
Could you help me,please!

## Possible Solutions
In this example, primary key is username. But with me, primary key are username and companyId, I got companyId from login form, but I don't know how to pass it into UserRepository.xml

## Affects Version/s
* 5.1.0.RELEASE
* 1.X.X.RELEASE

## Issue Links
* #XXX

**Comment by ikeyat** [comment]
Thanks for the report.
In my understanding, the primary key should be ``username`` on the section because it is the universal rule for ``DaoAuthenticationProvider``.
That means the ``companyId`` is something like a credential.

If you need to regard ``companyId`` as a part of the primary key, you need to combine it into ``principal`` or leave ``DaoAuthenticationProvider`` for custom ``AuthenticationProvider``.

**Comment by thanhth90** [comment]
Thanks for your reply!
Therefor, in this case, login form include of username, password and companyId. How to get user info from both username and companyId. Because this guideline not mention how to pass companyId.
Could you help me, please!
Regards

**Comment by ikeyat** [comment]
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/Security/Authentication.html#creating-authentication-filter
Here you can find how to get ``companyId`` from the request and pass to ``AuthenticationToken``.

**Comment by thanhth90** [comment]
Dear ikeyat
In my understanding, creating-authentication-filter used to get companyId from login Form and pass it to AuthenticationToken, my issue is how to pass it to service to get user info from database: 
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/Security/Authentication.html#creating-userdetailsservice
PS: I tested, and I got companyId from login form as you mentioned above, but I can not pass companyId to loadUserByUsername to get user info from database 
Regards!

**Comment by ikeyat** [comment]
As I wrote, you can use only ``username`` as the primary key to pick up the user record from database in `` DaoAuthenticationProvider ``.
So you need to get the ``companyId`` from the record in database if you need to access it at Controller or Service classes as the credential is done.
After that, you can access it at a Controller as following.

```java
@RequestMapping("account")
@Controller
public class AccountController {
    public String view(
            @AuthenticationPrincipal AccountUserDetails userDetails) {
        String companyId = userDetails.getAccount().getCompanyId();
        // omitted
    }
}
```

**Comment by ikeyat** [comment]
Those are the spec and limitation of `` DaoAuthenticationProvider``.
If the guideline make you comfusing, we would like to fix or add explanations for it.

**Comment by thanhth90** [comment]
Dear ikeyat,

Thanks for your support, I got it, and to resolve my issue, I get all record by username from DB, then I filter them by companyId.
But I encounter small problem, could you help me, please!
I create 1 service to get companyId from Token as follow:
```
@Service
public class GetCompanyIdService {
	
	private String companyId;
	public String getCompanyId(){
		companyId = ??? // how to do it?
		return companyId;
	}
}
```
I don't know how to get companyId from input? 
As your mention, @AuthenticationPrincipal AccountUserDetails userDetails, but I think it just parameter, when service called, param must be passed for that. Would you recommend other way for me?

Regards

**Comment by ikeyat** [comment]
You mean you wolud like to access ``copmanyId`` of the user who operates, right?
In the case, I think the best way is to give ``companyId`` or ``Account`` object as a parameter from Controller to Service.
Here is an easiest example.

```java
@RequestMapping("account")
@Controller
public class AccountController {
    @Inject
    private AccountService accountService;

    public String view(
            @AuthenticationPrincipal AccountUserDetails userDetails) {
        Account accountWhoOperates = userDetails.getAccount();
        accountService.executeSomething(accountWhoOperates);
        // omitted...
    }
}

@Service
public class AccountServiceImpl implements AccountService {
    public void executeSomething(Account account) {
        String companyId = account.getCompanyId;
        // omitted...
    }
}
```

**Comment by thanhth90** [comment]
Dear ikeyat

I did it, it really useful for me.
Thank you very much!

**Comment by ikeyat** [comment]
I'm closing this issue. If you have another questions, please reopen or create another issue.
