### ISSUE TITLE
Typos in Mybatis Guideline

### ISSUE THREAD

**Issue by btundes** [terasolunaorg/guideline#1886]
## Description
It is identified that at several places as mentioned below, a whitespace is missing between to words.

1. [Typo1](http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/ArchitectureInDetail/DataAccessMyBatis3.html#implementation-of-resulthandler)
 At the warning section 'Precautions while using ResultHandler'
 Wrong word-->  ```ResultHandler```is

2. [Typo2](http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/ArchitectureInDetail/DataAccessMyBatis3.html#implementing-typehandler-for-joda-time)
The first line of the explanation-
wrong word-->  ```org.joda.time.LocalDate```etc.

3. [Typo3](http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/ArchitectureInDetail/DataAccessMyBatis3.html#sql-switching-by-the-database)
This is at the Note section of the Bean definition for database switching
wrong word-->	by specifying ```properties```property

4. [Typo4](http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/ArchitectureInDetail/DataAccessMyBatis3.html#mybatis-settings-for-using-lazy-load)
This is at the warning section of MyBatis settings for using Lazy Load configuration
wrong Word-->	When ```select``` attribute of ```association``` element or ```collection```element

5. [Typo5](http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/ArchitectureInDetail/DataAccessMyBatis3.html#sql-execution-mode-settings)
This is at the Description column of the BATCH execution mode.
wrong Word-->	However, when BATCH mode is used, MyBatis behavior operates in ```SIMPLE```mode

## Possible Solutions
The correct text for the above mentioned typos serially are as below-
1. ```ResultHandler``` is
2. ```org.joda.time.LocalDate``` etc.
3. by specifying ```properties``` property
4. When ```select``` attribute of ```association``` element or ```collection``` element
5. However, when BATCH mode is used, MyBatis behavior operates in ```SIMPLE``` mode

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s

- [x] 5.2.0
- [x] 5.1.0

**Comment by kazuki43zoo** [comment]
@btundes, thanks for reporting ! Good catch up !!
Can you fix these ?

**Comment by btundes** [comment]
@kazuki43zoo 
I have completed the changes & created the pull request. Please confirm.
