### ISSUE TITLE
Typo mistake in Tutorial (Todo Application REST)

### ISSUE THREAD

**Issue by btakahoshin** [terasolunaorg/guideline#1891]
## Description
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/TutorialREST/index.html#id10

## Possible Solutions
Sr.No (1) (2) (3) (3) -> Sr.No (1) (2) (3) (4)

## Affects Version/s
* 5.2.0.RELEASE
* 5.1.1.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE_ja
- [x] 5.1.1.RELEASE_ja

**Comment by btyoshikawaa** [comment]
@btyamadasun 
Please backport to 5.1.x .

**Comment by btyamadasun** [comment]
@btyoshikawaa 
I have completed the backport and created the pull request. Please confirm.
