### ISSUE TITLE
Fix and update mapping based on security measures

### ISSUE THREAD

**Issue by itouyun** [terasolunaorg/guideline#1893]
## Description
Now
1.7.1. Mapping based on security measures
A10 Authentication(Mention about Open Redirect Vulnerability measures)

But Not mention about Open Redirect Vulnerability measures for Authentication Page.

## Possible Solutions
Fix mapping.
- Command Injection #1957
- Directory Traversal #2010 
- 暗号化
- ブラウザのセキュリティ対策機能との連携
- 代表的なセキュリティ要件の実装例
- etc...

## Affects Version/s
* 5.1.0.RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- 5.2.0_en (at #2132)
- [x] 5.1.1_ja
- 5.1.1_en (at #2132)

## Issue Links
* #1701

**Comment by ikeyat** [comment]
@tiwatsuka 
How is this status?

**Comment by sasakitsy** [comment]
Reflection into English ver. will be done after each sections are translated.

**Comment by ikeyat** [comment]
Will be reflected to English ver. at #2132
