### ISSUE TITLE
The bad order of the Sr.No. in the description of the "3.3.3. Project Configuration"

### ISSUE THREAD

**Issue by btkadotahr** [terasolunaorg/guideline#1895]
## Description
「3.3.3. プロジェクトの構成」の説明において、
[MyBatis3用のブランクプロジェクトを作成した場合の構成]と
[O/R Mapperに依存しないブランクプロジェクト、JPA用のブランクプロジェクト用を作成した場合の構成]の
項番の順番が逆である。

先に説明される[MyBatis3用]で項番(8),(9)が使われ、
後に説明される[JPA用]で項番(1)～(7)が使われている。
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/TutorialTodo/index.html#id14

## Possible Solutions
[MyBatis3用のブランクプロジェクトを作成した場合の構成]と
[O/R Mapperに依存しないブランクプロジェクト、JPA用のブランクプロジェクト用を作成した場合の構成]の
説明順番を逆転させ、項番の順番を正しくする。

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [ ] 5.2.0_en
- [x] 5.1.1_ja
- [ ] 5.1.1_en

**Comment by btyoshikawaa** [comment]
@btyamadasun 
Please backport to 5.1.x.

**Comment by btyamadasun** [comment]
@btyoshikawaa 
I have completed the backport and created the pull request. Please confirm.

**Comment by sasakitsy** [comment]
This issue will be closed, because created new English translation issue ( #2015 ).
