### ISSUE TITLE
TERASOLUNA Server Framework for Java (5.x) Development Guidelineの5.12に誤記

### ISSUE THREAD

**Issue by cyoco** [terasolunaorg/guideline#1898]
## Description
TERASOLUNA Server Framework for Java (5.x) Development Guidelineの記載誤りがあり。

「5.12. 二重送信防止」-「5.12.2.2. PRG(Post-Redirect-Get)パターンの適用」
に記載の下記JSPに記載誤りがあり。
createForm.jsp
createConfirm.jsp
createComplete.jsp

## Possible Solutions

action="${pageContext.request.contextPath}/**rpgExample**/create"
↓
action="${pageContext.request.contextPath}/**prgExample**/create"

## Fix Versions
- [x] 5.2.0_ja
- [x] 5.2.0_en
- [x] 5.1.1_ja
- [x] 5.1.1_en

## Issue Links

**Comment by ikeyat** [comment]
@cyoco 
Thanks for your conrtibution. We'll fix them.

**Comment by btyoshikawaa** [comment]
@btyamadasun 
Please backport to 5.1.x .

**Comment by btyamadasun** [comment]
@btyoshikawaa 
 I have completed the backport and created the pull request. Please confirm.
