### ISSUE TITLE
Translate #1856 (Change the HTTP Proxy Server Setting in RestClient from System Property to ClientHttpRequestFactory)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#1899]
## Description
Please translate a modification #1856  
Modifications refer to https://github.com/terasolunaorg/guideline/pull/1862/files.

## Fix Version/s
- 5.2.0_en
    - [x] translation/5.2.0
    - [ ] 5.2.x
- 5.1.1_en
    - [ ] translation/5.1.1
    - [ ] 5.1.x_en
- 5.3.0_en
    - [ ] master

**Comment by attarudes** [comment]
This cannot done before merging PR #1925.
The directory structure has been changed under PR #1925
