### ISSUE TITLE
Wrong version of Spring IO Platform

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1900]
## Description
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ImplementationAtEachLayer/CreateWebApplicationProject.html#createwebapplicationprojectappendixprojecthierarchicalstructure
4.1.5.1. プロジェクトの階層構造

The version of Spring IO Platform "1.1.3" is wrong for 5.1.0.RELEASE and 5.0.2.RELEASE.
It should be 2.0.1 and 1.1.5. But it is shown on the another section. It is duplicated information. 
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/Overview/FrameworkStack.html#oss
2.1.3. 利用するOSSのバージョン

## Possible Solutions
Remove the actual version number and alternatively add a link to http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/Overview/FrameworkStack.html#oss

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [ ] 5.2.0_en
- [x] 5.1.1_ja
- [ ] 5.1.1_en

**Comment by sasakitsy** [comment]
@btyamadasun 
Please backport.

**Comment by sasakitsy** [comment]
English Translation Issue -> Coped with  #2014 
And This issue will be closed.
