### ISSUE TITLE
SOAPクライアントのBean定義をenvプロジェクトに記述すべきか

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/guideline#1901]
## Description
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/SOAP.html#id10
「(5) envプロジェクト」の説明
`プロキシクラスの定義は環境依存することが多いため、envプロジェクトで定義している。`

プロキシクラスのBean定義をenvプロジェクトに記述すべしと読み取れるが、複数環境向けにBean定義の重複部分が多くなり、管理が煩雑になる懸念がある。

## Possible Solutions
Bean定義から環境依存する値をプロパティファイルに集約し、プロパティファイルのみenvプロジェクトに配置するよう、記述を見直すと良い。

## Affects Version/s
* 5.1.0.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE jp
- [x] 5.1.1.RELEASE jp

## Issue Links
* none

**Comment by btyoshikawaa** [comment]
@btijnb 
5.1.x へバックポートお願いします。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please make and assign the issue to translate this issue content.

**Comment by kazuki43zoo** [comment]
@btyoshikawaa @sasakitsy @ikeyat 

I've added a comment.

https://github.com/terasolunaorg/guideline/pull/1945/files#r68415136

Please check.

**Comment by btijnb** [comment]
@btyoshikawaa 
[6a2c4447401f25d99a50206ea5abe9533c679472]
記述内容を追記しました。

**Comment by btyoshikawaa** [comment]
@btijnb 
Please backport to 5.1.x.
