### ISSUE TITLE
Translate #1699 (Add description to add a dependency of terasoluna-gfw-string)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#1911]
## Description
Please translate a modification #1699 
Modifications refer to https://github.com/terasolunaorg/guideline/pull/1906/files

## Fix Version/s
- [x] 5.2.0_en
- 5.1.1_en
    - [x] translation/5.1.1
    - [x] 5.1.x_en
- 5.3.0_en (done through 5.2.0_en)

**Comment by attarudes** [comment]
This issue can be taken after merging PR #1925.
The directory structure has been changed under PR #1925

**Comment by ikeyat** [comment]
@btmikamihdt 
Please backport to 5.1.1

**Comment by btmikamihdt** [comment]
@ikeyat 
I backported to 5.1.1. #2187 #2188 
Please review.
