### ISSUE TITLE
Add attribute checked to checkbox form with if condition true

### ISSUE THREAD

**Issue by thanhth90** [terasolunaorg/guideline#1913]
## Description
So I got this checkbox:
`<form:checkbox id="someCheckbox" path="someCheckbox"/>`
Now I would like to add an attribute - specifically checked="checked" if a condition is true. Is this possible without wrapping the entire element in an if statement?
Basically what I want (results in an error):
`<form:checkbox id="someCheckbox" path="someCheckbox" ${(condtion1&&condition2)? 'checked=checked' : ''}/>`

I also used :
```
<c:choose>
    <c:when test="${condition}">
        checked='checked'">
    </c:when>
</c:choose>
```
But it don't work, could you help me resolve this issue, please!
## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by ikeyat** [comment]
``<form:checkbox>`` generate ``checked`` attribute automatically from the model by Spring MVC.
Why do you need ``checked`` attribute manually?

If you don't like to tend to the Spring MVC automatic binding, you had not better use ``<form:checkbox>`` but use normal ``<checkbox>`` html tag.

**Comment by kazuki43zoo** [comment]
@thanhth90 Please repro project!

**Comment by thanhth90** [comment]
Sorry ikeyat, I'm forgot feedback!
You're right, I don't need to use `<form:checkbox>` and I resolved this issue with normal `<checkbox>` html tag.
So, I think automatic binding of checkbox form should be have option for programming choose, enable or disable, it's only my idea :)
Thanks for your support!

**Comment by ikeyat** [comment]
@thanhth90 
In my opinion, you had better use automatic binding instead of avoid programmatic form data binding as you mention if you adopt Spring MVC. If you encountered something that prevents automatic binding of Spring MVC, you can request improvements to Spring JIRA.

**Comment by thanhth90** [comment]
OK, I got it, thank you!
