### ISSUE TITLE
Add a description for the customization of JISX 0208 Codepoints

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1914]
## Description
https://github.com/terasolunaorg/terasoluna-gfw/blob/5.1.0.RELEASE/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_SpecialChars.java

``JIS_X_0208_SpecialChars`` has codepoints of JISX 208 characters.
In general,  ``JIS X 0208 01-29`` should be treated as ``U+2014(EM DASH)``
But Unicode consortium mis-define it as ``U+2015(HORIZONTAL BAR)`` as seen in the url.
http://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT

So we modify it to be treated as ``U+2014(EM DASH)`` at ``JIS_X_0208_SpecialChars``.
``U+2015=―``	-> ``U+2014=—``
https://github.com/terasolunaorg/terasoluna-gfw/blob/5.1.0.RELEASE/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_SpecialChars.java#L44

It is no problem but we should introduce it in the guideline.

## Possible Solutions
Add note or warning regarding it around  here.
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Utilities/StringProcessing.html#stringprocessinghowtousecodepointsclasses

## Affects Version/s
* 5.1.0.RELEASE

## Fix Version/s
- [x]  5.2.0_ja
- [ ]  5.2.0_en
- [x]  5.1.1_ja
- [ ]  5.1.1_en

## ChangeLog
- [x]  5.2.0_ja
- [ ]  5.2.0_en
- [x]  5.1.1_ja
- [ ]  5.1.1_en

**Comment by ikeyat** [comment]
@sasakitsy 
Please create an issue for translation.
After that close this issue.

**Comment by sasakitsy** [comment]
I will close this issue , Because I've created issue translate #1980
