### ISSUE TITLE
TutorialのWelcomeページのControllerについて

### ISSUE THREAD

**Issue by cyoco** [terasolunaorg/guideline#1917]
## Description

度々、すみません。

ガイドラインでチュートリアルを実施していると、
"/"ルートリクエストを受け付けるControllerが、
あるチュートリアルでは、HomeControllerであったり、
ほかのチュートリアルではHelloControllerであったりと、統一されていない気がしました。

統一されているほうがわかりやすいと思います。
もし、意図的に使い分けていたら、当issueをcloseしてください。
## Possible Solutions

**Comment by kazuki43zoo** [comment]
@cyoco レポートありがとうございます！！おそらく意図はないと思うので、対応を検討させていただきます。

**Comment by sasakitsy** [comment]
本件につきましては、引き続き検討を実施させていただきます。

**Comment by btkukinom** [comment]
本件はblankプロジェクトに差異が存在し、どちらをベースにして記述しているかでガイドラインにも差異が引き継がれていたのが原因になります。

terasoluna-gfw-web-blank        : HomeController.java
terasoluna-gfw-web-multi-blank  : HelloController.java

別issueにて上記の差異の修正が行われ、ガイドラインについても修正を実施しているため本issueでの対応は不要とさせてください。

## 対応Issue
* blankプロジェクト修正（ https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/237 ）
* ガイドライン修正（#2081）

**Comment by btyoshikawaa** [comment]
@btkukinom 
Thanks for your comment!
