### ISSUE TITLE
Add logging with message id

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/guideline#1928]
## Description
7.1. ロギングにHow to extendでログID付きログメッセージの出力方法を記載する

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0_ja
- [ ] https://github.com/terasolunaorg/guideline/issues/1928#issuecomment-228398371
- [ ] 5.2.0_en move to https://github.com/terasolunaorg/guideline/issues/1940

## Issue Links
N/A

## ChangeLog
- [x] if this issue need to update ChangeLog, please commit with it

**Comment by iwanagah** [comment]
I will close this issue , Because I've create issue for translate #1940

**Comment by kazuki43zoo** [comment]
@iwanagah @sasakitsy @ikeyat 

I've added some (many ....) comment. （後出しジャンケンで申し訳ないのですが・・・）

* https://github.com/terasolunaorg/guideline/pull/1929/files#r68416374
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68419446
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68419059
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68419059
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68420314
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68422050
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68421185
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68421185
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68422474
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68422350
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68422924
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68424111
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68424441
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68424548
* https://github.com/terasolunaorg/guideline/pull/1929/files#r68425309

間違いは直してください。
それ以外は、意図があって＋その意図が妥当であれば修正する必要ありません。ただし、ぱっと見では意図が伝わってこなかったので、意図が伝わるように説明を見直した方がいいと思います。

まずは、コメントを確認してほしいです。

**Comment by kazuki43zoo** [comment]
@iwanagah 

すべてをちゃんと見たわけじゃない（斜め読みしている箇所もある）ので、もう一度ピュアな目でちゃんとガイドになっているか？我々の意図が正しく伝わる構成・内容（ミスリードしない内容）になっているか？不自然な文書はないか（これは優先度は低）？などを見てほしいです。
