### ISSUE TITLE
Translate #1928(Add logging with message id)

### ISSUE THREAD

**Issue by iwanagah** [terasolunaorg/guideline#1940]
## Description
Please translate a modification #1928
Modifications refer to https://github.com/terasolunaorg/guideline/pull/1929/files

## Fix Version/s
- 5.2.0.RELEASE_en
    - [x] translation/5.2.0
    - [x] 5.2.x
- 5.3.0_en
    - [ ] master

**Comment by kazuki43zoo** [comment]
@attarudes 

In progress ? 
I will recommend to skip this translation if translation team has other tasks.
Because i added many comments for [original issue](https://github.com/terasolunaorg/guideline/issues/1928#issuecomment-228398371).

**Comment by attarudes** [comment]
@kazuki43zoo
Non of the task has been assigned to translation team yet.
The current status is Not yet started. Yes, I will skip the issue. Please close the issue.

**Comment by kazuki43zoo** [comment]
@attarudes 

Thanks for answer !!
Please watch a status of [original issue](https://github.com/terasolunaorg/guideline/issues/1928#issuecomment-228398371).
I will remove label of `in translate`.

**Comment by iwanagah** [comment]
I have merged and  closed  [original issue](https://github.com/terasolunaorg/guideline/issues/1928#issuecomment-228398371) again.

@attarudes Please translate.

**Comment by ikeyat** [comment]
@neetapimpalnerkar 
This issue needs translation but not assigned to you on GitHub.
Please consider this into your tasks.
