### ISSUE TITLE
Wrong description in description for ValidationMessages.properties

### ISSUE THREAD

**Issue by bthiguchitkm** [terasolunaorg/guideline#1948]
## Description
"5.5.2.4.1. ValidationMessages.propertiesに定義するメッセージ" Section

In this section, it is described as "(2)不正となった入力値は、{value}で埋め込むことができる。 ", but "{value}" means an attribute name of an annotation argument.

For example,
- **Java Src:**
    @Min(0) 
    private Integer age;

- **ValidationMessages.properties:**
    javax.validation.constraints.Min.message=can not be less than {value}.

- **Output Message:**
    can not be less than 0.

In this case, {value} is replaced 0 of @Min argument.
The same with this case is already written in description of (1).
So it is desirable to delete description of (2).

## Possible Solutions
Delete description of (2).

## Affects Version/s
* 5.1.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
* Delete description of (2).
  - [x] 5.2.0_ja
  - [ ] 5.2.0_en
  - [x] 5.1.1_ja
  - [ ] 5.1.1_en
* ~~Add description of `${validatedValue}`~~ This is correspond by #2002.

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by kazuki43zoo** [comment]
@sasakitsy 

Please assign to someone.

**Comment by kazuki43zoo** [comment]
I agree with possible solutions.
An invalid value (rejected value) can bind into a message using `${validatedValue}` variable. However. i think that not need to introduce about this variable.

**Comment by ikeyat** [comment]
For details of ``${rejectedValue}``, see http://docs.jboss.org/hibernate/validator/5.2/reference/en-US/html/ch04.html

**Comment by btyoshikawaa** [comment]
@kazuki43zoo @ikeyat 
If I display the error message near the input field, I not use `${validatedValue}`.
But if I display in the distant and when I want to found wrong input value quickly, I want to often use `${validatedValue}`.
Really Do we not need to introduce?

**Comment by ikeyat** [comment]
@btyoshikawaa 
たしかに必要になる場合はあるので、``${validatedValue}`` の紹介をしてもよいですが、紹介するのであればEL式を紹介しているTips部分

http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Validation.html#application-messages-properties
の直上のTips

の説明の中ですべき。
Tipsの中のHibernate Validatorへのリンクから、``${validatedValue}`` にたどり着けるので、ガイドライン上には書かなくてもよい気がしている。

**Comment by kazuki43zoo** [comment]
@btyoshikawaa 

明示的にガイドライン中で「`${validatedValue}`」にふれるなら、パスワードやクレジット番号などの機密情報に対する扱いに関して注意喚起を記載してほしいです。何も考えないと、機密情報がメッセージに表示されてしまう可能性があるので・・・。

**Comment by btyoshikawaa** [comment]
@ikeyat @kazuki43zoo 
Hibernate Validatorへのリンクに飛べば分かるとしても、必要なら一文でも触れておくほうが良い気がします。
Tipsに`${validatedValue}`を使用する例を追加して、入力値が機密情報を含む場合にはそのまま表示しないよう注意する旨を記載する方向で行こうと思います。

**Comment by ikeyat** [comment]
RC3にテストまで間に合わない可能性が高いので、いったん5.2.0向けには``${validatedValue}`` には触れないように修正しておく。
Issueは今後のために残しておく。

**Comment by btnoguchimnm** [comment]
@ikeyat @btyoshikawaa @kazuki43zoo 
テストまでは間に合わないため、いったんは${validatedValue}には触れないように修正します。

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Please backport #1986 to 5.1.x.

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please assign to translate #1986 and #1999(backport).

**Comment by ikeyat** [comment]
@sasakitsy 
Please separate an issue (Add description of ``${validatedValue}``) for 5.3.0 from this issue.

**Comment by sasakitsy** [comment]
I will close this issue, the issues of the below will be corresponded by others.
* "Add description of ${validatedValue}" 
 -> corresponded by #2002.
* "English translation"
 -> corresponded by #2003
