### ISSUE TITLE
ファイルアップロード機能について、Commons-FileUplaodのガイドライン化について検討する。

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#195]
WebLogic12c(12.1.2)とResin4(4.0.37)において、Servlet3.0のファイルアップロード機能を使用すると文字化けする事象が発生している。
Commons-FileUplaodを使用してファイルアップロードすれば、上記事象は発生しないため、ガイドラインに記載が必要と思われる。
まずは、どのようにガイドライン化するか検討する。

**Comment by kazuki43zoo** [comment]
close via #778 .
