### ISSUE TITLE
Add description of os command injection

### ISSUE THREAD

**Issue by bttakahashieib** [terasolunaorg/guideline#1957]
## Description
OSコマンドインジェクションの説明と、その対処方法をガイドラインに記載する

## Possible Solutions
N/A

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0_ja
- ~~[ ] 5.2.0_en~~ (at #2001)
- [x] 5.2.0_ja improvement
- ~~[ ] 5.2.0_en improvement~~ (at #2001)

## Issue Links
N/A

## ChangeLog
- [x] if this issue need to update ChangeLog, please commit with it

**Comment by ikeyat** [comment]
@sasakitsy 
To be translated.

**Comment by sasakitsy** [comment]
I will close this issue, Because I've created issue for translate #2001

**Comment by ikeyat** [comment]
コマンド実行=「cmdやshの実行」と解釈されると、以下の文は矛盾があるように読み取れるため、改善したほうが良い。

```
OSコマンドインジェクションを起こさないためには、可能な限りコマンドの実行を避ける。コマンドの実行が必要な場合、 以下の対策を行う。
•極力、/bin/sh（Unix系の場合）やcmd.exe（Windowsの場合）を使用したコマンド実行を行わない
•ユーザーにより入力された文字が、アプリケーションとして許可されたものであるかをホワイトリスト方式を用いてチェックする
```

改善例（「外部プロセスの実行」に置換）

```
OSコマンドインジェクションを起こさないためには、可能な限り外部プロセスの実行を避ける。
ただし諸般の理由により外部プロセスの実行がどうしても必要な場合は、 以下の対策を行った上で外部プロセス実行を実装すること。
•極力、/bin/sh（Unix系の場合）やcmd.exe（Windowsの場合）を使用したコマンド実行を行わない
•ユーザーにより入力された文字が、アプリケーションとして許可されたものであるかをホワイトリスト方式を用いてチェックする
```

**Comment by kazuki43zoo** [comment]
「1.7.1. セキュリティ対策に関するマッピング」に追加すべきでは？

**Comment by kazuki43zoo** [comment]
@sasakitsy @ikeyat 

「1.7.1. セキュリティ対策に関するマッピング」はcommand injection以外も全体的にも直した方がよい気がする。

* 暗号化
* ブラウザのセキュリティ対策機能との連携

あたりは、表に追加する候補な気がします。あとA10「Unvalidated Redirects and Forwards」は前バージョンから説明がなくなっている

などなど、他にもありそう。

**Comment by ikeyat** [comment]
@kazuki43zoo 
ありがとうございます。ただ、
https://github.com/terasolunaorg/guideline/issues/1893
こちらのIssueで対応すべき。転記しておきました。というか放置されてる？
