### ISSUE TITLE
Recover removed note regarding SessionAuthenticationStrategy

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1961]
## Description

http://terasolunaorg.github.io/guideline/5.0.2.RELEASE/ja/Security/Authentication.html#sec-concurrency-control

> Note
> 認証処理用のフィルタ(FORM_LOGIN_FILTER)をカスタマイズする場合は、 
> sec:concurrency-control要素の指定に加えて、
> 以下の２つのSessionAuthenticationStrategyクラスを有効化する必要がある。

のくだりが5.1.0ではなくなっているように見えます。
意図的に消したのではなく、認証認可に関する刷新タスク #1325 の中で、記述が消えてしまった可能性が高い。
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/Security/SessionManagement.html#springsecuritysessionmanagementconcurrency

Sprign Security 4.xの公式リファレンスにも同様の説明は存在する為、Spring Security4.xベースのver5.1.1やv.5.2.0でも同記述は必要。
http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#concurrent-sessions
## Possible Solutions

5.0.2の当該Noteを元に復元する。ただしSpring SecurityリファレンスのURLのverはそれぞれ対象となるverに修正すること。
## Affects Version/s
- 5.1.0.RELEASE
## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en
- [x] 5.2.1_ja
- [ ] 5.2.1_en
- ~~[ ] 5.1.1_ja~~
- ~~[ ] 5.1.1_en~~
## Issue Links
- #1325
## ChangeLog
- not required

**Comment by ikeyat** [comment]
@btmaedahrs 
Please reflect to English version.
http://terasolunaorg.github.io/guideline/5.0.2.RELEASE/en/Security/Authentication.html#setting-sec-concurrency-control

**Comment by asaharas** [comment]
we have fixed
you can close this issue I think.

**Comment by itouyun** [comment]
I have confirmed translation issue. I'll close this issue.
