### ISSUE TITLE
the wrong information about HTTP Response Header in the SystemExceptionResolver section

### ISSUE THREAD

**Issue by btyamadasun** [terasolunaorg/guideline#1965]
## Description
例外ハンドリング
→SystemExceptionResolverの設定項目について
 　→[HTTPレスポンスのキャッシュ制御有無](http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/ExceptionHandling.html#http)

のNOTEに ``preventResponseCaching`` を ``true`` にした時のHTTPレスポンスヘッダー一覧が記載されているが、5.2.0向けのSpringでは現行のバージョン(5.1.0)で出力される内容と一致していない。

> 
> 有を指定した場合のHTTPレスポンスヘッダー
> 
> HTTPレスポンスのキャッシュ制御有無を有にすると、以下のHTTPレスポンスヘッダーが出力される。
> Cache-Control:no-store
> Cache-Control:no-cache
> Expires:Thu, 01 Jan 1970 00:00:00 GMT
> Pragma:no-cache

## Possible Solutions
- 5.2.0向けのSpringのバージョンで出力される内容に修正する。(``preventResponseCaching`` 自体はSpringの仕組みなので、Springの仕様に準拠する)
-  ただし、列挙されている項目がSpringの仕変によるものなのかなど、妥当であるか調べる必要あり。

## Affects Version/s
N/A

## Fix Version/s
- [x]  5.2.0_ja
- [ ]  5.2.0_en

## ChangeLog
- [ ] Required (外部仕様の変更なため)

**Comment by bttanakagn** [comment]
下記が5.2.0でのレスポンスヘッダの内容。
> Cache-Control:no-cache, no-store, max-age=0, must-revalidate
> Cache-Control:no-store
> Expires:Thu, 01 Jan 1970 00:00:00 GMT
> Pragma:no-cache

**Comment by ikeyat** [comment]
https://github.com/spring-projects/spring-framework/commit/fc34b0c5926a40d2529b8cb4e0fd8f7b1b61a01b

あたりの変更の影響を受けているかも（ざっと見ですので関係ないかもです）

**Comment by kazuki43zoo** [comment]
Spring Securityの影響もあるかも！？

> Cache-Control:no-cache, no-store, max-age=0, must-revalidate
> Expires:Thu, 01 Jan 1970 00:00:00 GMT
> Pragma:no-cache

は、たぶんSpring Securityが付与しているものだと思う。

https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/header/writers/CacheControlHeadersWriter.java#L76-L83

**Comment by kazuki43zoo** [comment]
> Cache-Control:no-store

は、たぶん SpringのpreventResponseCaching=trueで付与されたもの。

https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/handler/AbstractHandlerExceptionResolver.java#L224

**Comment by btkawakamitor** [comment]
@ikeyat @kazuki43zoo 
コメント頂いている通り、
>Cache-Control:no-store

はガイドラインに記載のpreventResponseCaching=trueにより付与されたもので、Springのバージョンアップで5.1.0向けのガイドラインに記載のヘッダからCache-Control:no-storeのみに変更されています。
https://github.com/spring-projects/spring-framework/commit/38f32e38169f7779b9fe20d46b69024039f190ce#diff-4386c732a724a039db2007b1bac7d3d5L222

Spring Securityが付与するヘッダ
>Cache-Control:no-cache, no-store, max-age=0, must-revalidate
>Expires:Thu, 01 Jan 1970 00:00:00 GMT
>Pragma:no-cache

についてはpreventResponseCachingの設定によるものとは直接関連するものではなく、かつSpring Security 4.1系からはキャッシュ制御ヘッダが既に付与されている場合は付与しない実装に変わるようです（4.0系は付与する設定の場合は無条件で付与）。
https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/header/writers/CacheControlHeadersWriter.java#L60-L66

以上より、preventResponseCaching=trueの説明としては
>Cache-Control:no-store

のみを記載するのが適切かと思います。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create translate issue, after that close this.

**Comment by sasakitsy** [comment]
I create new English translate issue and close this issue.
