### ISSUE TITLE
Add to JSR310 corresponding guidelines of MyBatis and Jackson

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1966]
## Description
Add guidance for using terasolunaorg/terasoluna-gfw#562.

Please take care for the changes https://github.com/terasolunaorg/terasoluna-gfw/issues/508.

## Possible Solutions
TBD

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0_ja
- [ ] 5.2.0_en

## Issue Links
* terasolunaorg/terasoluna-gfw#562

## ChangeLog
- [ ] Required

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please assign member to translate this.

**Comment by sasakitsy** [comment]
I'll close this issue, because this issue will be done at #2024.
