### ISSUE TITLE
TransactionTokenがサポートしないフローの注意喚起

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#1967]
## Description
Write down alerting "Not support some special flows of TransactionToken" in the guideline.

## Possible Solutions
TBD

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.0-5.0.2.RELEASE
* 1.0.0-1.0.4.RELEASE

## Fix Version/s
- [ ] 5.2.0
- [ ] 5.1.1

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/565

## ChangeLog
(To be written later by project member)

**Comment by iwanagah** [comment]
@sasakitsy このissueは翻訳以外終わっているように見えますが閉じてよいか確認してもらってよいでしょうか？

**Comment by ikeyat** [comment]
@sasakitsy 
確認お願いします。#2071とduplicatedなので何も対応せずクローズで問題なければ、その旨記載してクローズしてください。

**Comment by sasakitsy** [comment]
#2071 と重複であったため、クローズします。
また、翻訳issueは#2071 中で起票しているため、不要です。
