### ISSUE TITLE
Confusion of @SessionAttributes and @SessionAttribute

### ISSUE THREAD

**Issue by kumagaikzk** [terasolunaorg/guideline#1970]
## Description
There are some words "@SessionAttribute" in Session Tutorial.
But it does not exist.
It should be "@SessionAttributes"

## Possible Solutions
Correct typo.

## Affects Version/s
* 5.0.2.RELEASE
* 5.1.0RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [x] 5.1.1_ja
- [x] 5.2.0_en
- [x] 5.1.1_en

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by ikeyat** [comment]
This mistaken should be resolved earlier because Spring 4.3 will introduce ``@SessionAttribute`` that is quite different from ``@SessionAttributes``. It will become much confusing.
