### ISSUE TITLE
Need comma

### ISSUE THREAD

**Issue by kumagaikzk** [terasolunaorg/guideline#1971]
## Description
In Session Tutorial, there is the sentence as below.

```
オンライン処理件数：10000件 / 月
```

Easy to understand, put comma between numbers like below.

```
オンライン処理件数：10,000件 / 月
```

## Possible Solutions
Put comma.

## Affects Version/s
* 5.0.2.RELEASE
* 5.1.0RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [x] 5.1.1_ja
- [x] 5.2.0_en
- [x] 5.1.1_en

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by btyoshikawaa** [comment]
@btkukinom 
Please backport to 5.1.x.

**Comment by btyoshikawaa** [comment]
Leave a comment
