### ISSUE TITLE
Reflect the separation of pom.xml dependencies for app and common lib

### ISSUE THREAD

**Issue by bttanakagn** [terasolunaorg/guideline#1982]
## Description
Refer to Issue Link

## Possible Solutions
Refer to Issue Link

## Affects Version/s
N/A

## Fix Version/s
 - [x] 5.2.0_ja
 - [ ] 5.2.0_en

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/508

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please assign to translate #2027 .

**Comment by sasakitsy** [comment]
English translate issue(#2067) was created, and this issue will be closed.
