### ISSUE TITLE
@DateTimeFormat is not strict with JSR310

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#1991]
## Description

http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#applicationlayer-datetimeformat

`@DateTimeFormat` で`pattern`でフォーマットを指定した場合、`java.util.Date` や`org.joda.time.LocalDate` に対してはSTRICTにフォーマットチェックが行われる（"2015/2/29"は間違った日付と判定される）が、JSR310の`java.time.LocalDate` ではSTRICTにチェックがされない。（"2015/2/29"は2015/3/1"を示す`java.time.LocalDate`` インスタンスへ変換される）
#1873 で示したよう、入力チェックとして存在しない日付チェックを`@DateTimeFormat` で行う場合に本仕様が問題となる可能性がある。

https://jira.spring.io/browse/SPR-13567

Spring 4.3で仕様が改善され、本問題が発生しなくなるが、Spring 4.2以下の場合は本問題の影響を受ける。
## Possible Solutions

http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#applicationlayer-datetimeformat

に本事象に関するwarningを記載し、SpringのJIRA Issueへのリンクを作成する。
ワークアラウンドについても示す必要があるがどこまでガイドラインに示すかは要検討
- `ConversionService`に代替となる簡易`Formatter` の追加  
  http://qiita.com/tag1216/items/25a64bba2bde98ea88d3#jsr-310%E3%81%AE%E5%AF%BE%E5%BF%9C%E6%96%B9%E6%B3%95-2
- `ConversionService`にSpringの修正を参考にした`Jsr310DateTimeFormatAnnotationFormatterFactory` クローンを追加  
  https://github.com/spring-projects/spring-framework/commit/7b1fcfc7c3ead828dc55a305598da75c781b8dee#diff-b507fcf636a73e88144e7c0989375f5b
## Affects Version/s
- 5.1.0.RELEASE
- ~5.0.2.RELEASE
- ~1.0.4.RELEASE
## Fix Version/s
- [ ] 5.3.0_ja 仕様が修正されたSpring 4.3導入により改善される
- [ ] 5.3.0_en 同上
- [x] 5.2.0_ja
- [x] 5.2.0_en
- [x] 5.1.1_ja
- [x] 5.1.1_en
## Issue Links
- #1873
- https://jira.spring.io/browse/SPR-13567
## ChangeLog
- [x] Required

**Comment by btyoshikawaa** [comment]
@bttanakagn 
testing required.

**Comment by sasakitsy** [comment]
Spring 4.3以降では、仕様の改善により、本issueの問題が解決されることから、
本事象の再現確認実施と、本事象の注意喚起をガイドラインに記載する。

**Comment by btyoshikawaa** [comment]
@btmaedahrs 
Please backport #2028 to 5.1.x .

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Remaining task is for 5.3.0 or later.

**Comment by sasakitsy** [comment]
5.2.0,5.1.1での対応が完了
Spring Framework 4.3以降では本事象は解消されるため、5.3.0以降でSpring のバージョンの確認を行い、必要に応じて、今回付与した注意喚起を削除する。

**Comment by ikeyat** [comment]
@sasakitsy 
5.3.0向け対応(Spring 4.3導入後の対応)は、Issueを分けておいたほうが良いと思います。新しいIssueの関連付けはしておき、こちらのIssueは2016 Summerリリースで対応済みとしてクローズする。

**Comment by kazuki43zoo** [comment]
@sasakitsy Issueわけましょう！

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Spring IO Platform Athenes (Spring 4.3.4) applied for 5.3.0 .

**Comment by btyoshikawaa** [comment]
Already done by #2505.

> Spring Framework 4.3以降では本事象は解消されるため、5.3.0以降でSpring のバージョンの確認を行い、必要に応じて、今回付与した注意喚起を削除する。
