### ISSUE TITLE
Correspond change Cache-Control header configuration specification of Spring Security 4.1.x

### ISSUE THREAD

**Issue by btkawakamitor** [terasolunaorg/guideline#1993]
## Description

Spring Security 4.1.0より、キャッシュ制御用ヘッダーの付与に関する仕様が変更されるため、フレームワークスタックにSpring Security 4.1.xが含まれるタイミングで当該機能に関する説明を付与する。

https://github.com/spring-projects/spring-security/issues/2953
https://github.com/spring-projects/spring-security/commit/242b831f20c11171975c1e2bdd50c9ae1cdbf445#diff-27921ebdc686738a3b090182472f63b5
## Possible Solutions
- Cache-Controlヘッダに関する説明を付与する。
  http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/Security/LinkageWithBrowser.html#cache-control （5.1.0.RELEASEにおける当該節へのリンク）
- 各Webリソースで細かいキャッシュ要件がある場合に対応可能となるため、必要に応じてその旨の説明を追加する。
## Affects Version/s

N/A
## Fix Version/s
- [x]  5.3.0_ja
- [ ]  5.3.0_en
## Issue Links
- #1965 
## ChangeLog
- [x] Required (外部仕様の変更なため)

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please write issue for translation, and close this.

**Comment by btyoshikawaa** [comment]
Sorry, this is already corresponded by #1965 .
