### ISSUE TITLE
createToken() of TransactionTokenContextImpl does not work properly

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/guideline#1995]
## Description
TransactionToken are not created when you run TransactionTokenContextImpl createToken method of an implementation of the TransactionTokenContext

## Possible Solutions
createToken and removeToken of TransactionTokenContext to deprecated.

## Affects Version/s
* 5.1.0.RELEASE
* ~5.0.2.RELEASE
* ~1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [ ] 5.2.0_en
- [x] 5.1.1_ja
- [ ] 5.1.1_en

## Issue Links
* #1967

## ChangeLog
- [x] Required

**Comment by btyoshikawaa** [comment]
@btkobayashirun 
Please backport to 5.1.x.

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please assign to translate.

**Comment by sasakitsy** [comment]
I created English translate issue(#2069), and will close this issue.

**Comment by iwanagah** [comment]
typoの修正が必要
「フレームワーク内部の挙動に影響を及ぼすような作り込ができてしまう」→「フレームワーク内部の挙動に影響を及ぼすような作り込**み**ができてしまう」
