### ISSUE TITLE
Translate #1957 (Add description of os command injection)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2001]
## Description
Please translate a modification #1957 

Modification refer to https://github.com/terasolunaorg/guideline/pull/1958/files

## Fix Version/s
- 5.2.0.RELEASE_en
    - [x] translation/5.2.0
    - [x] 5.2.x
- 5.3.0_en
    - [x] master

## ChangeLog
- [ ] 5.2.0_en

**Comment by ikeyat** [comment]
Please reflect https://github.com/terasolunaorg/guideline/pull/2112/files
