### ISSUE TITLE
Wrong description in description for ValidationMessages.properties (add description)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2002]
## Description

See https://github.com/terasolunaorg/guideline/issues/1948
## Possible Solutions

Add description of ${validatedValue}
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE
## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en
- [x] 5.2.1_ja
- [ ] 5.2.1_en
## Issue Links
- #1948
## ChangeLog
- [x]  required

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Please backport to 5.2.x.

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create translation issue. And after that, please close this.

**Comment by sasakitsy** [comment]
Translate in #2517 
So, close this issue.
