### ISSUE TITLE
Webサービス例外発生時のステータスコード取得方法について

### ISSUE THREAD

**Issue by btijnb** [terasolunaorg/guideline#2007]
## Description
[http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/SOAP.html#soaphowtousewebserviceclient](http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/SOAP.html#soaphowtousewebserviceclient)

   > レスポンスの情報取得
   >  リトライを考慮するなど、レスポンスの情報をクライアントで取得したい場合、以下のように
javax.xml.ws.BindingProviderクラスにキャストすることで取得できる。

   >  BindingProvider provider = (BindingProvider) todoWebService;
   >  int status = (int) provider.getResponseContext().get(MessageContext.HTTP_RESPONSE_CODE);

   > ただし、この場合Webサービス実行がプロキシクラスに依存してしまう。そのため、テスト時にスタブを使用する場合にも、スタブにjavax.xml.ws.BindingProviderを実装させる必要が発生する。
    この機能の利用は最小限に抑えることを推奨する。

Webサービス例外発生時に上記のステータスコード取得方法では取得出来ないAPサーバがある。
APサーバの環境依存による問題だと考えられる。

## Possible Solutions
APサーバ毎に取得できるか否かの情報をガイドラインに追記する。本格対応方法についての議論が必要。

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1

## ChangeLog
(To be written later by project member)

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create translation issue, after that close this.

**Comment by sasakitsy** [comment]
A translate issue(#2065) was created, and  this issue will be closed.
