### ISSUE TITLE
MyBatis 3.4使用時の@Transactinal(timeout=xxx)対応

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2008]
## Description

See #1777 
## Possible Solutions

MyBatis 3.4 + MyBatis-Spring 1.3にバージョンアップすることで、@Transactionalのtimeout属性に指定した値は、SpringのJdbcTemplate使用時と同様の動きになるように改善される。
そのため、MyBatisのバージョンアップかつ、#1777の対応にて5.2.0以前で補足説明を追加した場合、補足説明の個所を削除する必要がある。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- [x] 5.4.0_en (master)
- [x] 5.3.1_en (5.3.x)

## Final Solution
#1777 の対応により、補足説明が追加されており、
5.3.0.より、MyBatis 3.4 + MyBatis 1.3にバージョンアップし、@Transactinalのtimeout 属性に指定した値が使用されるように改善されたため、`Note「@Transactionalアノテーションのtimeout属性について」`　を削除する。
(追記)
#1776 (タイムアウト時間を超えての挙動をすることがある、という旨をNoteやWarning等への記載)と同時対応。

対応箇所
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ImplementationAtEachLayer/DomainLayer.html#transaction-management-declare-transaction-info-label
 Note「@Transactionalアノテーションのtimeout属性について」 

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [x] Required, handle with the same issue

## Migrating Guide
- [x] Required

## Issue Links
- #1777 
- https://github.com/terasolunaorg/terasoluna-gfw/issues/555

**Comment by ikeyat** [comment]
@sasakitsy 
これ5.3.0で未対応なのは良くなかったのでは？（MyBatis3.4へ上げているので、#1777 で対応した内容が内包するMyBatisの内容とずれている・・・）
嘘が書かれているわけではないので問題というわけではないですが、5.3.0では何かしらMyBatis3.4向けの関連情報を載せておいたほうが良かったかと。

**Comment by btsatouhrzzp** [comment]
マージが完了したため本issueをクローズします。
