### ISSUE TITLE
Translate #1777 (@Transactinal(timeout=xxx) does not work in MyBatis 3.3)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2009]
## Description
Please translate a modification #1777 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/1979/files

## Fix Version/s
- 5.2.0_en
    - [x] translation/5.2.0
    - [x] 5.2.x
- 5.1.1_en
    - [x] translation/5.1.1
    - [x] 5.1.x_en
- 5.3.0_en
    - [x] master

## ChangeLog
(To be written later by project member)

**Comment by btmikamihdt** [comment]
@ikeyat 
I backported to other lines. #2175 #2176 #2178 #2179 
Please review.
