### ISSUE TITLE
Add measures against directory traversal attack

### ISSUE THREAD

**Issue by tiwatsuka** [terasolunaorg/guideline#2010]
## Description
Add measures against directory traversal attack.

## Possible Solutions
N/A

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0_ja
- 5.2.0_en (at #2121)

## Issue Links
* #XXX

## ChangeLog
- [x] required

**Comment by ikeyat** [comment]
@sasakitsy 
To be translated.

**Comment by ikeyat** [comment]
Will be translated at #2121
