### ISSUE TITLE
複数フィールドのハイライト表示、エラーメッセージの統合を共通ライブラリに適用するかどうか検討する

### ISSUE THREAD

**Issue by btkukinom** [terasolunaorg/guideline#2013]
## Description
#1561 にてSpring ValidatorやBean Validatorの相関チェックにおいて、複数フィールドのハイライト表示、エラーメッセージの統合を検証した。

当該内容を共通ライブラリに適用するかどうかを検討する。
## Possible Solutions

検証段階では、メッセージ統合を空文字の設定を行い非表示とするようにしており、
共通ライブラリに採用すべきかどうかを検討する必要がある。
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE
## Fix Version/s

(To be written later by project member)
## Issue Links
- #1561
## ChangeLog

(To be written later by project member)

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please move this issue to `terasoluna-gfw`. This is not issue about guideline.

**Comment by btyoshikawaa** [comment]
@sasakitsy 
https://github.com/terasolunaorg/guideline/issues/2013#issuecomment-236870316 done.
