### ISSUE TITLE
Translate #1900 (Wrong version of Spring IO Platform)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2014]
## Description
Please translate a modification #1900 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/1907/files

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Fix Version/s
- [ ] 5.2.0_en
- [ ] 5.1.1_en

## ChangeLog
(To be written later by project member)

**Comment by ikeyat** [comment]
@sasakitsy 
Is this really needed?
The original PR #1907 lokks to contain reflections to English ver.

**Comment by sasakitsy** [comment]
This issue is already translated (#1907).
Therefor this issue will be closed.
