### ISSUE TITLE
Translate #1895 (The bad order of the Sr.No. in the description of the "3.3.3. Project Configuration")

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2015]
## Description
Please translate a modification #1895 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/1909

## Fix Version/s
- [ ] 5.2.0_en
- [ ] 5.1.1_en

## ChangeLog
(To be written later by project member)

**Comment by ikeyat** [comment]
@sasakitsy 
This does not contain any translation.

**Comment by sasakitsy** [comment]
This issue is no need for translation.
Therefor this will be closed.
