### ISSUE TITLE
Translate #1836 (Improvements in "Reading this documents" and "Tutorial")

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2019]
## Description
Please translate a modification #1836 

Modification refer to https://github.com/terasolunaorg/guideline/pull/1902/files

## Fix Version/s
- 5.2.0_en
    - [x] translation/5.2.0
    - [x] 5.2.x
- 5.1.1_en
    - [x] translation/5.1.1
    - [x] 5.1.x_en
- 5.3.0_en
    - [x] master

## Issue Links
* #1836 

## ChangeLog
(To be written later by project member)

**Comment by btmikamihdt** [comment]
@ikeyat 
I backported to other lines. #2180  #2181 #2183 #2184 
Please review.
