### ISSUE TITLE
Update new OSS stacks

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2020]
## Description
OSS stacks in the Guidelines is before version.

## Possible Solutions
Modify new OSS stacks version to Guide.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [x] 5.2.0_en
- [x] 5.1.1_ja
- [x] 5.1.1_en
- [x] 1.0.5_ja
- [x] 1.0.5_en

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/569
* #1992 

## ChangeLog
- [x] required

**Comment by btyoshikawaa** [comment]
@sasakitsy @btmikamihdt 
We need update OSS stacks of 5.1.1 and 1.0.5.
* 5.1.1 -> mybatis and mybatis-spring version raised.
* 1.0.5 -> spring framework version raised.

**Comment by sasakitsy** [comment]
I added Fix version, labels for 5.1.1 and 1.0.5.

**Comment by btmikamihdt** [comment]
@sasakitsy  @btyoshikawaa 

Please review #2073 and #2074 .
