### ISSUE TITLE
[SOAP] typo in 5.18.1.2.JAX-WSとは

### ISSUE THREAD

**Issue by btsatoukzn** [terasolunaorg/guideline#2026]
## Description
It's a kind of typo in 5.18.1.2.

"実装して__し__ないため、" should be "実装して__い__ないため、". 

## Possible Solutions
Correct typo.

## Affects Version/s
* 5.1.X.RELEASE

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1

## Issue Links
* #XXX

## ChangeLog
not required.

**Comment by btyoshikawaa** [comment]
@btsatoukzn 
Sorry, I couldn't understood difference between your description and possible solutions.
Could you revise it enough for me to understand?

**Comment by btsatoukzn** [comment]
@btyoshikawaa 
Modify contents of Description and Possible Solutions.

**Comment by btyoshikawaa** [comment]
@btsatoukzn 
し -> い！
I understood and modified description... Thanks.

**Comment by btyoshikawaa** [comment]
@btryuushou 
Please backport to 5.1.x .
