### ISSUE TITLE
modify inconsistent use of expressions in pom description

### ISSUE THREAD

**Issue by kashimakz** [terasolunaorg/guideline#2047]
## Description

「親プロジェクトで依存ライブラリのversionを管理するため、pom内に追加する依存ライブラリにversion指定をしないでよい。」という旨を説明する文章が揺れているため、統一する。

記載のあるRSTファイルの一覧：
\Appendix\Lombok.rst:     そのため、\ `<version>`\ 要素は指定していない。
\ArchitectureInDetail\MessagingDetail\Email.rst:     そのため、\ `<version>`\ 要素は指定していない。
\ArchitectureInDetail\WebApplicationDetail\FileDownload.rst:         poi-ooxmlのバージョンはSpring IO Platformにて定義されているものを利用するため、設定例では <version> を省略している。
\ArchitectureInDetail\WebApplicationDetail\TilesLayout.rst:     そのため、terasoluna-gfw-recommended-web-dependenciesの `<version>` の指定は不要である。
\ArchitectureInDetail\WebApplicationDetail\Validation.rst:     そのため、\ `<version>`\ 要素は指定していない。
\Security\SpringSecurity.rst:     本ガイドラインでは、Spring IO Platformを使用してライブラリのバージョンを管理する前提で記載しているため、\ `<version>`\ 要素は省略している。
## Possible Solutions

一番多い以下の表現に統一する。

.. note::

```
上記設定例では、依存ライブラリのバージョンは親プロジェクトで管理する前提である。
そのため、\ ``<version>``\ 要素は指定していない。
```
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE
## Fix Version/s
- [x] 5.3.0_jp
- [x] 5.2.1_jp
- [ ] 5.3.0_en
- [ ] 5.2.1_en
## Issue Links
- #XXX
## ChangeLog
not required.

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Plesae create issue for english translation, after that close this.

**Comment by asaharas** [comment]
I have created translation issue. #2713 
so you can close this issue.

**Comment by itouyun** [comment]
I have confirmed that. I'll close this issue.
