### ISSUE TITLE
Translate #1998 (Add guidance for solution of message when using Method Validation.)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2048]
## Description
Please translate a modification #1998 
Modifications refer to https://github.com/terasolunaorg/guideline/pull/2017/files

## Fix Version/s
- 5.2.0_en
    - [x] translation/5.2.0
    - [x] 5.2.x
- 5.1.1_en
    - [x] translation/5.1.1
    - [x] 5.1.x_en
- 5.3.0_en
    - [x] master

## Issue Links
* #1998 

## ChangeLog
(To be written later by project member)

**Comment by ikeyat** [comment]
Why fix versions cheched? It looks not yet done
 I remove checks.
