### ISSUE TITLE
ガイドライン記載のリンクが無効（リンク切れ等）になっていないか確認、修正する

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2052]
## Description
ガイドラインのバージョンアップに伴い、リンクが有効になっている（リンク切れ等ないか）か確認し、切れている場合、修正する。

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [x] 5.2.0_en
- [x] 5.1.1_ja
- [x] 5.1.1_en
- [x] 1.0.5_ja
- [x] 1.0.5_en

## Issue Links
* #XXX

## ChangeLog
Not required.

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Thx. Please correspond 5.1.x and 1.0.x .
