### ISSUE TITLE
Add framework stack for Support jsr310

### ISSUE THREAD

**Issue by iwanagah** [terasolunaorg/guideline#2068]
## Description
以下で追加したJSR310サポートに伴い追加したライブラリをframework stack(https://github.com/terasolunaorg/guideline/blob/master/source/Overview/FrameworkStack.rst) に追加すべきか検討する必要がある
https://github.com/terasolunaorg/terasoluna-gfw/issues/562
https://github.com/terasolunaorg/terasoluna-gfw/pull/574

## Possible Solutions
* 上記の通り、追加が必要か確認
* 追加不要であればクローズ、追加が必要であればFrameworkStack.rstに追記する

## Affects Version/s
* 5.2.0.RELEASE

## Issue Links
https://github.com/terasolunaorg/terasoluna-gfw/issues/562

## ChangeLog
(To be written later by project member)

**Comment by iwanagah** [comment]
@sasakitsy Please assign member for this issue.

**Comment by btyoshikawaa** [comment]
@iwanagah @sasakitsy 
すいません、#2036 で既に追加しちゃってます。

https://github.com/terasolunaorg/guideline/blob/master/source/Overview/FrameworkStack.rst#利用するossのバージョン
* mybatis-typehandlers-jsr310
* jackson-datatype-jsr310

これで問題なければ、当Issueはクローズしていただければ。

**Comment by iwanagah** [comment]
@btyoshikawaa 失礼しました。修正は上記で問題ないと思います。一応 @sasakitsy に確認してもらってからクローズにします。

**Comment by sasakitsy** [comment]
確認しました。差分はないため、当issueはクローズします。
