### ISSUE TITLE
TransactionToken does not support some special flows

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/guideline#2071]
## Description
トランザクショントークンに追加されたTransactionTokenType.CHECKに関するガイドラインを追加する。

terasolunaorg/terasoluna-gfw#565

## Affects Version/s
* 5.1.0.RELEASE
* ~5.0.2.RELEASE
* ~1.0.4.RELEASE

## Fix Version/s
 - [x] 5.2.0_ja
 - [ ] 5.2.0_en
 - [x] 5.1.1_ja
 - [ ] 5.1.1_en

## Issue Links
* terasolunaorg/terasoluna-gfw#565
* #1967 

## ChangeLog
 - [x] Required

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please assign somebody to translate this.

**Comment by sasakitsy** [comment]
I created new translation issue(#2071), and will close this issue.
