### ISSUE TITLE
Reflect the change of blank projects to guidelines

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/guideline#2081]
## Description

There is a reflect leakage of the change of blank projects.
## Possible Solutions

Reflect changes.
For example spring-mvc.xml in  http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/Overview/FirstApplication.html#id11
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE
## Fix Version/s
- ja
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6
- en
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6

## Fix Version/s (terasoluna-gfw-web-multi-blank#273)

Reflect changes.
For example spring-mvc.xml in  https://github.com/terasolunaorg/guideline/blame/master/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L766

- ja
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [ ] ~~1.0.6~~
- en
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [ ] ~~1.0.6~~

## Issue Links
- https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/273

## ChangeLog

Not required.

**Comment by btryuushou** [comment]
@btyoshikawaa  @sasakitsy 
皆様が調査した対象一覧（5.2.0、5.1.1、1.0.5）を修正しました、
ご確認をお願いいたします。

**Comment by btyoshikawaa** [comment]
@btryuushou @sasakitsy 
一覧確認しましたが、修正する必要がなさそうなものを多く修正してしまっているようです。
一覧を見る限りでは、下の3-Aあたりの判断プロセスが機能していなかったのでは。

1. ブランクプロジェクトを使用しているrst抽出
2. 抽出したrstから、ブランクプロジェクトと同名資材を抽出（ex. spring-mvc.xml ...）
3. 抽出した資材を修正する必要があるか判断
  - A. ブランクプロジェクトから生成したプロジェクトの設定ファイルを例示しているか否か
  - B. ↑に該当した場合、各バージョンの設定ファイルが使用されているか否か
4. 対象を修正

5.2.0リリース完了後に、修正対象の調査から仕切り直す形になると思います。
現在出ているPull Requestを再利用するかも、その後の相談になると思います。

なお、修正対象は概ね以下のファイルのみになるだろうと、私は考えています。
- Overview/FirstApplication
- Tutorial/TutorialTodo
- Tutorial/TutorialREST
- Tutorial/TutorialSecurity
- Tutorial/TutorialSession
- ImplementationAtEachLayer/CreateWebApplicationProject

**Comment by btyoshikawaa** [comment]
@btryuushou 
Thanks you for your long work.

**Comment by btyanagawamg** [comment]
Description

There is a reflect leakage of the change of blank projects.

Possible Solutions

Reflect changes.
 For example spring-mvc.xml in https://github.com/terasolunaorg/guideline/blame/master/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L766 .

Affects Version/s
•5.X.X.RELEASE
•1.X.X.RELEASE

Fix Version/s
•ja


 5.3.0


 5.2.1


 5.1.2


 5.0.3


 1.0.6
•en


 5.3.0


 5.2.1


 5.1.2


 5.0.3


 1.0.6

Issue Links
•#XXX

ChangeLog

Not required.

**Comment by btyoshikawaa** [comment]
@btyanagawamg 
I assigned you for task of https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/273#issuecomment-260525449 . Please correspond.

**Comment by btyanagawamg** [comment]
ガイドラインの1.0.x系には　https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/273#issuecomment-260525449　に該当する修正箇所が存在しなかったため、修正対象外でした
