### ISSUE TITLE
Add reference for Global Transaction into DomainLayer.rst

### ISSUE THREAD

**Issue by btijnb** [terasolunaorg/guideline#2090]
## Description

グローバルトランザクションについてのリファレンス(APサーバマニュアル)を追加したいです。
## Possible Solutions

「ドメイン層の実装」ページ内のトランザクション管理の節に追加

## Affects Version/s
- 5.2.0.RELEASE
## Fix Version/s
- [ ] 5.2.0_jp(Add DomainLayer)
- [ ] 5.2.0_jp(Add link from jms)
- [ ] 5.2.0_en(Add DomainLayer)
- [ ] 5.2.0_en(Add link from jms)
- [ ] 5.1.1_jp(Add DomainLayer)
- [ ] 5.1.1_en(Add DomainLayer)
## Issue Links
- #XXX

**Comment by kazuki43zoo** [comment]
@itouyun  See https://github.com/terasolunaorg/guideline/pull/2093#issuecomment-314422897

**Comment by itouyun** [comment]
本件について、必要性を改めて確認しました。
起因はJMSの章でグローバルトランザクションのことを言及しており、グローバルトランザクションはJMSに限った話ではないため、「ドメイン層の実装」ページに追加しよう、という目的でした。

現状のJMSの記述 [8.2.2.3.6. トランザクション管理](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/MessagingDetail/JMS.html#jmshowtousetransactionmanagementforasyncreceive) を確認したところ、例えば
`JMSとDBなど複数のトランザクションを厳密に管理する必要がある場合には、グローバルトランザクションの利用を検討する。 グローバルトランザクションについては、各種製品マニュアルを参照されたい。`
という記載がありました。
他にも記載がありますが、どれも、NoteやWorningで言及されており、メインストリームの話ではありません。

よって、以下の理由で本件はCloseとします。
* メインストリームではなく、必要性が低く、ガイドするべきではないため
* 各製品に特化する内容であるため、網羅するのが難しく、改めて開発ガイドラインでガイドすべきではないため
