### ISSUE TITLE
Add Tips for the risk that plaintext passwords are described log

### ISSUE THREAD

**Issue by itouyun** [terasolunaorg/guideline#2092]
## Description

以下のようなバグを踏むことで、平文パスワードがログに出力されてしまうリスクが存在する。

パスワードの管理形式を、平文(NoOpPasswordEncoderの使用等)からStandardPasswordEncoderによるハッシュに変更する場合、登録済みの平文パスワードのハッシュ化を怠ると、正常に認証できなくなるバグが発生するだけでなく、認証時に、例外メッセージに登録済みの平文パスワードが含まれ、ログに平文パスワードが出力されてしまう。

`java.lang.IllegalArgumentException: Non-hex character in input: (DB等で管理されている、平文パスワード)`
(平文パスワードの文字数が偶数の場合に、上記のような例外メッセージとなる。)

とはいえ、以下ガイド（リンク先）にNoOpPasswordEncoderは
「テスト用のクラスなであり、実際のアプリケーションで使用することはない。」
と記載されており、本番運用にてNoOpPasswordEncoderを
利用しているとは考えづらく、上記バグを踏むケースは発生しづらい認識。
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/Security/Authentication.html#springsecurityauthenticationpasswordhashing
## Possible Solutions

Tipsとして以下を追加する。

`パスワードの管理形式を、平文(NoOpPasswordEncoderの使用等)からStandardPasswordEncoderによるハッシュに変更する場合、登録済みの平文パスワードは、変更後APでの運用が開始される前に、すべてStandardPasswordEncoderでハッシュ化し直さなければならない。登録済みの平文パスワードのハッシュ化を怠ると、正常に認証できなくなるだけでなく、認証時に、例外メッセージに登録済みの平文パスワードが含まれ、ログに平文パスワードが出力されてしまう。`
## Affects Version/s

- 5.4.0.RELEASE以前
- 1.X.X.RELEASE

## Fix Version/s

~~5.4.0 (master)~~ 不要
- [x] 5.3.1 (5.3.x)
backport( セキュリティ系なので念のため )
- [ ] 5.2.2 (5.2.x)
- [ ] 5.1.2 (5.1.x)
- [ ] 5.0.3 (5.0.x)
- [ ] 1.0.7 (1.0.x)

## Issue Links
- #XXX

## Change log(should be updated at the same time)
- [ ] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
(To be written later by project member)

**Comment by btyoshikawaa** [comment]
```
パスワードの管理形式を、平文(NoOpPasswordEncoderの使用等)からStandardPasswordEncoderによるハッシュに変更する場合
```
この想定重要だろうか。。。普通こんな変更するときはテストするから気付くのでは。
それより、あまり状況を限定せずに一般的な情報として書いたほうが良いのでは、と思いました。
```
StandardPasswordEncoderによるハッシュでパスワードを管理する場合、管理するすべてのパスワードをStandardPasswordEncoderでハッシュ化しておく必要がある。
ハッシュ化されていないパスワードを用いると認証時に例外が発生し、例外メッセージに以下のような形でパスワードが露出してしまうため、注意すること。

 java.lang.IllegalArgumentException: Non-hex character in input: (DB等で管理されている、平文パスワード) 
```

とか。

**Comment by kazuki43zoo** [comment]
@itouyun  @btyoshikawaa 

これって・・・必要ですかね？（個人的には必要性を感じないのでが・・）
そもそも平文でパスワードを管理しているシステムってあるんですか？＋仮にあったとしても、パスワードがハッシュ化できている＋ハッシュ化後に認証が正しく行えることはデータ移行時の事後チェックで行うべきものであり、ハッシュ化が正しく行われていることを確認しないでサービスインを迎えるようなプロジェクトは存在しないと思います。
また、内容的にTERASOLUNAの開発ガイドラインのNoteやTipsに記載してもあまり意味がない気がするのですが・・・。

**Comment by btyoshikawaa** [comment]
@kazuki43zoo @itouyun 
そうですね。私もあまり必要とは思ってません。
あえて書くなら。。。みたいのを https://github.com/terasolunaorg/guideline/issues/2092#issuecomment-241705790 で書いてみましたが、特段注意しにくいポイントでもない気はします。

**Comment by NaozumiTaromaru** [comment]
安易に想定されるリスク(認証失敗)をはるかに上回るリスク(平文パスワード漏えい)が存在することは、書いておくべきだと思います。

全く別の例で説明すると…
HashMapを外部で同期化せずにマルチスレッドで使用しうるコードが持つリスクについて。
「まれに無限ループを引き起こす」ということを知っていれば、システムハングアップにつながる重大なリスクがあることが分かるため、まず見逃さないでしょう。
しかし、HashMapの実装の表層だけ確認して、「過去にputした値が次のputの戻り値(旧値)として得られないくらいなんじゃないの？(仕様通りに動かないのは。)」という、容易に想像がつきそうなリスクを前提とすると、「この使用方法なら問題なし」と誤った判定を下す可能性があります。
HashMapのputを同時に呼ぶと最悪何が起きるか書いておいてくれてもいいのに…と思ったことがあるのは私だけではないはず。

パスワードに話を戻すと、
「ハッシュ化漏れがあった場合、認証に失敗する」と、
「ハッシュ化漏れがあった場合、平文パスワードが漏えいする可能性がある」では、
ハッシュ化のプロセスの選択肢や、
ハッシュ化後の確認プロセスが異なると思います。
「ハッシュ化漏れがあった場合、そのアカウントは認証に失敗する」だけなら、
「この時間帯は新規にログインができない状態になる可能性があります」と画面に表示しておき、サービスを停止せずにパスワードのハッシュ化を行うというプロセスをとる可能性があります。
(サービスを停止する時間は必要最小限に、という要望は珍しいものではないかと。)
ハッシュ化後の確認も、
本番DBに仕込んだテストアカウント(個人情報漏えい元特定用ダミーアカウント等)を使用してログインできることを確認して終了だと思います。
(微妙なタイミングでアカウントを作成したことでハッシュ化が漏れてログインできない人は問い合わせにより個別対応すればよいという判断。)
しかし、
「ハッシュ化漏れがあった場合、そのアカウントの平文パスワードは漏えいする可能性がある(ログに載る)」ということを知っていれば、上記のようなハッシュ化プロセスを踏むことがどれだけ危険で難しいことかを容易に推測できると思います。
(平文パスワードがログに載りうる時間帯のログを安易に持ち出せないようセキュリティエリアに持っていくとか、ハッシュ化後のパスワードがすべて期待通りの形式に変わっているかDBをチェックするとか、新規アカウントのパスワードハッシュ化はDBに格納されたパスワードのハッシュ化よりも先に実施するとか、考えることが多そう…)

**Comment by kazuki43zoo** [comment]
@NaozumiTaromaru 詳しい解説ありがとうございます。記載内容は精査した方がよさそうですが、本リスクの対するアナウンスする方向でよいかと思います。個人的にはSpring Securityのソースを直したい。

**Comment by kazuki43zoo** [comment]
@itouyun @btyoshikawaa @NaozumiTaromaru @ikeyat 

https://github.com/spring-projects/spring-security/issues/4043 の対応により入力値(平文やハッシュ化後のパスワードなど)が例外メッセージに含まれないように改善されます。かわりにHex文字以外を検出した文字位置がメッセージ含まれるようになります。

現時点では4.2(9/20リリース予定)はマージ済みで、4.1系にはバックポートのPR中です。
なお、TERASOLUNAが現在利用している4.0系はSpring Security的にはGAバージョンではない？ようなので、PRしていません。PRした方がいい？

**Comment by kazuki43zoo** [comment]
4.0.xにもバックポートPR出してみたけど、mergeされるかは微妙。

**Comment by kazuki43zoo** [comment]
@itouyun @btyoshikawaa @NaozumiTaromaru @ikeyat

結局4.2系(master)だけmergeされたので、2017 WinterでSpring Security を4.2にあげればTERASOLUNA 5.3のガイドラインにはNoteの追加は不要かと思います。 過去バージョンのガイドラインでの扱いについては、別途検討お願いします。

**Comment by sasakitsy** [comment]
過去のバージョンについては、ガイドラインに注意喚起を記載する。

**Comment by kazuki43zoo** [comment]
> 過去のバージョンについては、ガイドラインに注意喚起を記載する。

IO Platform AthensはSpring Security 4.1系なので、最新バージョン(5.3系)でも注意喚起の記載が必要だと思います。

**Comment by itouyun** [comment]
2017 SummerのSpring Securityがどうなるかはわかりませんが、次回のアップデートでどうなるかの監視が必要。それによって対応も変化。

**Comment by itouyun** [comment]
次回取り込むSpring IO PlatformはBrussels-SR3以降の予定。
その場合、Spring Security は4.2系となるため、次回リリースの最新版では注意喚起は不要となります。

ただし、5.3.1向けには必要の認識。

**Comment by btsatouhrzzp** [comment]
マージが完了したため本issueをクローズします。

**Comment by btsatouhrzzp** [comment]
I created #2879 issue. This issue is closed.
