### ISSUE TITLE
Modify table layout.

### ISSUE THREAD

**Issue by kashimakz** [terasolunaorg/guideline#2116]
## Description
Failed to create PDF file...

## Possible Solutions
TBD

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0_jp
-  5.2.0_en (at #2133)
- [x] 5.1.1_jp
- 5.1.1_en (at #2133)
- [x] 5.0.3_jp
-  5.0.3_en (at #2133)
- [x] 1.0.5_jp
-  1.0.5_en (at #2133)

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by iwanagah** [comment]
Please backport

**Comment by iwanagah** [comment]
Please modify for English version.

**Comment by ikeyat** [comment]
Will be reflected to English ver. at #2133
