### ISSUE TITLE
Maintain contents for PDF. #2116

### ISSUE THREAD

**Issue by kashimakz** [terasolunaorg/guideline#2118]
## Description

PDF出力をしたところ、ガイドライン内へのリンク切れや、１ページに収まらないテーブルが存在しています。
## Possible Solutions
- リンク切れ
  - ディレクトリ構成の変更がリンクに影響しているようです。修正方法を考える必要があります。
    - 結論： #2131
- テーブルについて→ #2189　に別issueを作成しました。
  - 記述内容やテーブルカラムの横幅調整を行うなど対応を考える必要があります。
  - ページ下が見切れるものに対して、「次のページに続く」で改ページさせることを試しましたが、実現できませんでした。texの生成時点で、「次のページに続く」などが出力されていたため、rstファイルの記述の仕方や変換時の仕様に要因があると考えています。
    - 試した箇所：「2.1.4. 共通ライブラリの構成要素」
    - 試した方法：「2.1.3. 利用するOSSのバージョン」をベースにテーブル定義などを変更
      - `stub-columns`の追加
      - `widths`の調整　利用するOSSのバージョンは合計を100→95へ変更
      - カラム内の`*`にエスケープ`\`を追加
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE
## Fix Version/s

* PDFのリンク切れ問題
  * #2118 (本issue)
    * [x] 5.2.0_ja (master反映済）
  * #2827 
    ~~\* [ ] 5.4.0_en (master)~~
    ~~\* [ ] 5.3.1_en~~
    ~~\* [ ] 5.2.2_en~~
* テーブル収まらない問題
  * #2189
    * [x] 5.3.0_ja (master反映済)
    * [x] 5.3.0_en (master反映済)
    * [x] 5.2.1_ja
    * [x] 5.2.1_en
  * #2545
    ~~\* [ ] 5.1.2_ja~~
    ~~\* [ ] 5.1.2_en~~
    ~~\* [ ] 5.0.3_ja~~
    ~~\* [ ] 5.0.3_en~~
    ~~\* [ ] 1.0.7_ja~~

## Issue Links

* #2116 ( 親issue )
* #2118 ( PDFのリンク切れ問題 ja ) (本issue)
* #2827 ( PDFのリンク切れ問題 en )
* #2189 ( テーブル収まらない問題 ja/en master )
* #2545 ( テーブル収まらない問題 ja/en backport )

## ChangeLog
- not required

**Comment by btyoshikawaa** [comment]
@kashimakz @iwanagah @sasakitsy 
I found a solution to the problem that the `list-table` is not page break in PDF.
Cause that is not page break , class of table is not `longtable` but __default__ `tabulary`.
By setting class `longtable` as follows:, we can resolve this problem.
https://groups.google.com/forum/#!topic/sphinx-users/UOEcB7rTCx0

And I show an example of setting. Please try to set also other tables similarly this.
https://github.com/terasolunaorg/guideline/commit/2c0f5250ca56808193fc8aa4057807d996899576#diff-855c76cdf01b05c5883e7332bccd9166R644

**Comment by ikeyat** [comment]
@btmikamihdt 
To avoid conflicts, reflection to English ver. should be deferred.

**Comment by ikeyat** [comment]
@btmikamihdt 
Please create a new separated issue for 5.3.0 and 5.2.1.
This issue should manage for only 5.2.0_ja and 5.2.0_en.

**Comment by btsatouhrzzp** [comment]
未対応Issueは別Issueとして切り出しているため、本Issueはクローズする。
