### ISSUE TITLE
Translate #1701 (Enhance Secure Login Example)

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#2125]
## Description
Please translate a modification #1701
Modifications refer to https://github.com/terasolunaorg/guideline/pull/2101/files

## Fix Version/s
- 5.2.0_en
    - [x] translation/5.2.0
    - [ ] 5.2.x
- 5.3.0_en
    - [ ] master

## Issue Links
* #1701

## ChangeLog
- [ ] required

**Comment by sasakitsy** [comment]
@btkobayashirun 
Please backport to other branches.
