### ISSUE TITLE
Translate #1407 (Add JMS section)

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#2127]
## Description
Please translate a modification #1407
Modifications refer to https://github.com/terasolunaorg/guideline/pull/2113/files

## Fix Version/s
- 5.2.0_en
    - [x] translation/5.2.0
    - [x] 5.2.x
- 5.3.0_en
    - [x] master

## Issue Links
* #1407

## ChangeLog
- [ ] required

**Comment by sasakitsy** [comment]
@btkobayashirun 
Please backport to other branches.
