### ISSUE TITLE
Reflect Eng #2116 (Modify table layout.)

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#2133]
## Description
Please reflect a modification #2116 
Modification refer to ??

## Fix Version/s
- [x] 5.2.0_en
    * translation/5.2.0
    * 5.2.x
- [x] 5.1.1_en
    * translation/5.1.1
    * 5.1.x
- [x] 5.0.3_en
- [x] 1.0.5_en
    * translation/1.0.5
    * 1.0.x
- [x] 5.3.0_en
    * master

## Issue Links
* #2116 

## ChangeLog
- none

**Comment by sasakitsy** [comment]
@btkobayashirun 
Please backport to master.
