### ISSUE TITLE
Settings for mybatis-typehandlers-jsr310 is not enough

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2140]
## Description

mybatis-typehandlers-jsr310から提供されているタイプハンドラの設定例に`YearTypeHandler`と`MonthTypeHandler`がないが、表内の説明文は存在している。
## Possible Solutions

設定例に`YearTypeHandler`と`MonthTypeHandler`を追加する。

``` xml
<typeHandler handler="org.apache.ibatis.type.YearTypeHandler" />
<typeHandler handler="org.apache.ibatis.type.MonthTypeHandler" />
```
## Affects Version/s
- 5.2.0.RELEASE
## Fix Version/s
- [x] 5.3.0  ? (MyBatis 3.4系にアップするなら、この説明自体不要になる)
- [x] 5.2.1
- [ ] 5.3.0_en 
- [ ] 5.2.1_en
## Issue Links
- http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.html#typehandler
## ChangeLog

(To be written later by project member)

**Comment by kazuki43zoo** [comment]
We need to apply this change to the English version.

**Comment by ikeyat** [comment]
Oh, sorry.

**Comment by ikeyat** [comment]
@sasakitsy 
Please assign reflection task after ``translation/xxx`` branches are merged to main stream branch.
Avoid the conflicts.

**Comment by sasakitsy** [comment]
Close this issue.
This issue will be translated for #2479
