### ISSUE TITLE
Add standardized authentication and authorization

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#2145]
## Description

Add sections that introduce  standardized authentication and authorization for integrated apps.
## Possible Solutions

Here are candidates
- [x] OAuth2.0 for resource access authorization ([spring-security-oauth2](http://projects.spring.io/spring-security-oauth/))
- [ ] OpenId Connect for external authentication delegation with OAuth2.0 ([mitreid](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server))
- [ ] Pre-authentication (e.g. LoadBalancer's authentication. id or roles are provided with HTTP header by LB)
  - http://docs.spring.io/spring-security/site/docs/4.0.4.RELEASE/reference/htmlsingle/#preauth
  - http://qiita.com/masatsugumatsus/items/7111983f04c08a5df1f8
- [ ] LDAP
- [ ] etc...

**Readme**
- Please create breakdown issues for each technologies that have been adopted.
- Please create additional issues at https://github.com/terasolunaorg/terasoluna-gfw/issues if libraries need to be added.
## Affects Version/s

N/A
## Fix Version/s
- [ ] 5.3.0_en
- [ ] 5.3.0_ja
## Issue Links
- #1938
## ChangeLog
- [ ] required

**Comment by kazuki43zoo** [comment]
I've merged section for OAuth.

@sasakitsy 

Plesae create a translatin issue and backlogs for other topics(e.g. OpenID connect, LDAP, etc...).

**Comment by itouyun** [comment]
I have confirmed that.
I maked backlog issue #2715.
I'll close this issue.
