### ISSUE TITLE
Typo in JMS section.

### ISSUE THREAD

**Issue by kashimakz** [terasolunaorg/guideline#2153]
## Description

以下のTypoを発見しました。

608, 617, 624行目
この設定を使用する場合、後述する\ `explicitQosEnabled`\ を\ `true`\ を設定する必要があるので注意すること。

1432行目
ヘッダ属性の編集については、\ :ref`JMSHowToUseSettingForSendWithHeader`\ を参照されたい。
## Possible Solutions

「\ `explicitQosEnabled`\ を\ `true`\ を」　→　「\ `explicitQosEnabled`\ に\ `true`\ を」

「\ :ref`JMSHowToUseSettingForSendWithHeader`\ 」→ 「\ :ref:`JMSHowToUseSettingForSendWithHeader`\ 」
## Affects Version/s
- 5.2.0.RELEASE
## Fix Version/s
- [x] 5.3.0_ja
- [x] 5.3.0_en (should be reflected to #2127 if needed)
- [x] 5.2.1_ja
- [x] 5.2.1_en (should be reflected to #2127 if needed)
## Issue Links
- #2085
## ChangeLog
- not required

**Comment by ikeyat** [comment]
@sasakitsy 
Please close this issue after checking  #2127 has no similar errors.

**Comment by sasakitsy** [comment]
"1432行目 ヘッダ属性の編集については、\ :refJMSHowToUseSettingForSendWithHeader\ を参照されたい。"
should be fixed same errors in English version.
