### ISSUE TITLE
Improve the description of secure random workaround

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#2177]
## Description

http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/Authentication.html#bcryptpasswordencoder

```
Warning: SecureRandomの使用について
JDK 7のb20以降のバージョンでは、修正されている。
```

JDK 7b20以降はバグが解消され、本ワークアラウンドが不要なようにも読み取れてしまうが、
[バグissueの内容](http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6521844)を見る限り、

`-Djava.security.egd=file:/dev/./urandom`
の`/./` のトリックが不要になっただけで、
乱数生成の遅延問題自体の対処としては依然、
`-Djava.security.egd=file:/dev/urandom`
が必要だと思われる。前出の記述はその事実に対し誤解を与える可能性がある。
## Possible Solutions

前述の事実確認、および当該記述の修正。
## Affects Version/s
- 5.2.0.RELEASE
- ~5.1.1.RELEASE
- ~5.0.2.RELEASE
## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en
- [x] 5.2.1._ja
- [ ] 5.2.1._en
## Issue Links
- #1502
## ChangeLog
- [x] yes

**Comment by btkobayashirun** [comment]
@ikeyat 
バグの事実確認を行う上で質問があります。

①spring-functionaltestについて
　ガイドラインに変更がありますがspring-functionaltestにテストの追加は必要でしょうか？
　Linux環境限定でハードウェア依存のバグなため必要ないような気がしていますが確認させてください。

②使用するLinuxの環境について
　Linux環境を用意する必要があるので、vagrantでtomcat8のVMを立ち上げてそこで作業を行おうと思ってます。
　この方法で問題ないでしょうか？

③証跡について
　バグの事実確認について証跡を載せる必要があると思うのですが、コマンドログやコンソールログを
　PRに載せる形で問題ないでしょうか？

**Comment by btyoshikawaa** [comment]
@btkobayashirun 
内部情報はGithubに書かないでください。

**Comment by kazuki43zoo** [comment]
@sasakitsy plz create an issue for translation.

**Comment by sasakitsy** [comment]
Translating in #2516 
So, close this.
