### ISSUE TITLE
The table which is not delivered to one page for PDF build.#2118

### ISSUE THREAD

**Issue by btmikamihdt** [terasolunaorg/guideline#2189]
## Description

PDF出力をしたところ、１ページに収まらないテーブルが存在しています。
## Possible Solutions
- 記述内容やテーブルカラムの横幅調整を行うなど対応を考える必要があります。
- ページ下が見切れるものに対して、「次のページに続く」で改ページさせることを試しましたが、実現できませんでした。texの生成時点で、「次のページに続く」などが出力されていたため、rstファイルの記述の仕方や変換時の仕様に要因があると考えています。
  - 試した箇所：「2.1.4. 共通ライブラリの構成要素」
  - 試した方法：「2.1.3. 利用するOSSのバージョン」をベースにテーブル定義などを変更
    - `stub-columns`の追加
    - `widths`の調整　利用するOSSのバージョンは合計を100→95へ変更
    - カラム内の`*`にエスケープ`\`を追加
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE
## Fix Version/s
* width
- [x] 5.3.0_ja
- [x] 5.3.0_en
- [x] 5.2.1_ja
- [x] 5.2.1_en
* height
- [x] 5.3.0_ja
- [x] 5.3.0_en
- [x] 5.2.1_ja
- [x] 5.2.1_en
## Issue Links
- #2116 
- #2118 
## ChangeLog
- not required

**Comment by btyoshikawaa** [comment]
Please see https://github.com/terasolunaorg/guideline/issues/2118#issuecomment-243433946 .

**Comment by btishimats** [comment]
ページ横が見切れるものに対しても対処が必要です。
PDFのページ横の見切れが発生しないようにtabularcolumnsを調整して対処します。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
このIssueは5.3.0および5.2.1向けで良いですが、他バージョンもリリースする場合に備えて、全バージョン対応しておいたほうが良いと思います。

**Comment by btfurukawatkr** [comment]
以下のSphinxのドキュメントでtables節の末尾のWarningに
`Tables with more than 30 rows are rendered using longtable, not tabulary, in order to allow pagebreaks.`
という記述がありました。

http://www.sphinx-doc.org/en/1.5.2/markup/misc.html#tables

縦が見切れるのは、30行以下だけどテーブル内の改行や折り返しによって1ページに収まらなくなったため、と思われます。

tableに`:class: longtable`を追加することで30行以内のテーブルでもlongtableとして改ページできるようになります。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please decide reflect all version (create new reflection issue).

**Comment by sasakitsy** [comment]
Other versions will be reflected in #2545 .
So, close this.
