### ISSUE TITLE
[Sending E-mail (SMTP)]Sometimes termination character is garbled

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2190]
## Description

メール本文がマルチバイトで終わっていると、終端に余計な文字（「?」や「w)」など）が出力されることがある。
## Possible Solutions

本質的な対応ではないかもしれないが、この事象を解消するための回避策として以下が知られているので、注意事項としてガイドラインに記載しておいてもよいと思いました。
- メール本文の終端文字を半角文字にする
- メール本文の終端を改行コード（CRLF）にする
## Affects Version/s
- ~5.2..RELEASE
- ~5.1.1.RELEASE
## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en
- [x] 5.2.1_ja
- [ ] 5.2.1_en
## Issue Links
- https://tools.ietf.org/html/rfc821
- http://www.symmetric.co.jp/blog/archives/36
- http://ffy.afy-system.jp/tips/t_001.html
## ChangeLog
- [x] required

**Comment by btyoshikawaa** [comment]
@btkobayashirun 
Sorry, please write change log to master, and backport to 5.2.x .

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please assign to translation issue.

**Comment by asaharas** [comment]
I have created translation issue #2709 
so you can close this issue.

**Comment by itouyun** [comment]
I have confirmed that. I'll close this issue.
