### ISSUE TITLE
AbstractBLogic structure prevents a creation of proxy class that may lead AOP disabled or mis-injection

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#2219]
## Description

http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ImplementationAtEachLayer/DomainLayer.html#id19
3.2.5.2.3. メソッドのシグネチャを限定するようなインタフェースや基底クラスについて

で紹介されている `AbstractBLogic` を継承するServiceの作成方法について、使用条件によってはSpringが正しくProxyクラスを生成できないため、適用したはずのAOP（宣言的なトランザクション制御含む）が適用されない可能性がある。
理由は以下と考えられる。
- Bean内のメソッドにAOP適用した場合、SpringはJDK Proxyにより「Bean対象クラスが実装しているインターフェイス」を実装したProxyクラスのインスタンスを生成しBeanとして扱う（この例の場合は`BLogic`）。AOPが適用できるメソッドはProxyクラスのメソッド、すなわち「Bean対象クラスが実装しているインターフェイス」のメソッドに限られるし、**Proxyクラスのメソッドを経由して**Bean対象クラスのメソッドが呼び出される必要がある。
- 現在紹介している、テンプレートメソッドパターンで `AbstractBLogic` を拡張してServiceクラスを作成する方法では、Serviceを呼び出す際に、以下のようにBean対象クラスの型ベースでインジェクションを行っている。
  
  ``` java
  @Inject
  XxxBLogic<XxxInput, XxxOutput> xxxBLogic;
  ```
- 当該ServiceにAOPが適用された場合は、ServiceのBeanのクラス型は先述の通り「Bean対象クラスが実装しているインターフェイス」を実装したProxyクラス（今回の場合は`BLogic`を実装したProxyクラス）である必要がある。**このクラス型はインジェクション先で指定している`XxxBLogic` とは直接的な互換性が無いため、期待したBeanのインジェクションが行われない。** 
- この条件の場合でかつSpring 4.2以下の場合※は、先述したProxyクラスがインジェクションされず、元のServiceクラス（今回の場合は`XxxBLogic`クラス）としてインジェクションされてしまっている。すなわち前述のとおり**Proxyクラスのメソッド経由での呼び出しとならないためAOPが機能しない。**

※Spring 4.2の代わりに当該条件下でSpring IO Platform Athens(Spring 4.3ベース)を適用した場合は、DIコンテナ生成時に型解決に失敗し例外が発生してしまう模様。Spring 4.3単体適用でも類似の例外が発生する模様。発生例外などについては、追って更新する。
## Possible Solutions

最低限の対応としては、現状のクラス構造時におけるAOP（宣言的トランザクション制御含む）の利用時の制約を促すべき。
ただし間違った利用の仕方であることには変わらないため、本箇所で紹介している手法のクラス構造を見直し、JDK Proxy利用時に正しくProxyクラスが適用されるよう、本来あるべき状態に修正する。

例）
- `AbstractBLogic`に対しインターフェイスを作成する(`AbstractBLogicIF`とする)。`BLogic` インターフェイスをextendsしておく。
- `AbstractBLogicIF`をextendsした`XxxBLogicIF`インターフェイスを作成する(Injectの型解決するためのマーカー)
- `XxxBLogic` に`XxxBLogicIF`をimplementsする
- Controller側を`XxxBLogicIF`でInjectさせるようにする
  
  ``` java
  @Inject
  XxxBLogicIF<XxxInput, XxxOutput> xxxBLogic;
  ```

Bean名を扱うことに抵抗が無ければ、Serviceクラス毎にインターフェイスを切らず、`AbstractBLogicIF` でInjectさせ、`@Resource`、`@Inject+@Named` (`@Autowired+@Qualifier`)などを用いることでServiceのbean名を指定するでも実現できる。
## Affects Version/s
- 5.2.0.RELEASE
- ~5.1.1.RELEASE
- ~5.0.2.RELEASE
- ~1.0.5.RELEASE
## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en
- [x] 5.2.1_ja
- [ ] 5.2.1_en
- [x] 1.0.6_ja
- [ ] 1.0.6_en

---
follwoing versions are low priority

- [x] 5.1.2_ja
- [ ] 5.1.2_en
- [x] 5.0.3_ja
- [ ] 5.0.3_en
## ChangeLog
- [ ] required

**Comment by kazuki43zoo** [comment]
@ikeyat 

Possible Solutionsに記載されている内容の妥当性（裏付け）ってあります？ ` AbstractBLogicIF`を作るところとか・・怪しさ満点（このインタフェースが必要な合理的な理由が見つからない）な気がしています。

**Comment by kazuki43zoo** [comment]
@ikeyat @bthayashidi @btyoshikawaa 

現在のガイドラインの記載には、２つの不備と一つの改善点があると思っています。

## Controllerへのインジェクションに関する説明が間違っている （→不備）

Controllerにインジェクションする型をインタフェース(`BLogic`)ではなくクラス(`XxxBLogic<XxxInput, XxxOutput>`)にしているため、インジェクションできる/できない以前にコンパイルエラーになる。
    
問題のコード）

```java
@Inject
XxxBLogic<XxxInput, XxxOutput> xxxBLogic;
```

これは、以下のように`BLogic`インタフェース型で受けるようにする必要がある。

```java
@Inject
@Named("xxxBLogic")
BLogic<XxxInput, XxxOutput> xxxBLogic;
```

## `@Transactional`を定義する場所の説明がない（→不備）

ガイドラインではトランザクション境界を`@Transactional`を使って指定する方法を推奨しているが、サンプルコード上に`@Transactional`に対する説明がない。
`@Transactional`を例に説明すると、継承関係をもつBeanのメソッドにインタセプタを適用したい場合は、大まかに以下の条件を満たす必要がある。

* 対象にしたいメソッドにアノテーションを付与する
* 対象にしたいメソッドが実装されているクラスにアノテーションを付与する
* 対象にしたいメソッドが実装されているクラスのスーパークラスにアノテーションを付与する

つまり、今回のケースで、`XxxBLogic`クラスに`@Transactional`を付与しても意味がなく、`AbstractBLogicImpl`の方に`@Transactional`を付与する必要がある。

> **Note:**
>
> 同じ理屈で、共通ライブラリで提供している`ResultMessagesLoggingInterceptor`を適用するためには、`@Service`を`AbstractBLogic`にも付与する必要がある。


## タイプセーフなインジェクション方法の紹介（→改善）

現在のガイドラインでは、BLogicという共通的なインタフェースを実装するサンプルになっているため、`@Named`などを使って名前による絞込みが必要となる。名前による絞込みが悪いわけではないが、クラス名を変更すると名前の不一致が起こりやすくなるというデメリットがある。これは、BLogic毎にインタフェース(マーカーインタフェース的な役割として`BLogic`のサブインタフェース)を設け、ControllerではBLogic毎のインタフェースを使ってインジェクションすることで解消できる。

* BLogic毎のインタフェースの作成

```java
public interface XxxBLogic extends BLogic<XxxInput, XxxOutput> {
}
```

* BLogic毎のインタフェースを実装

```java
@Service
public class XxxBLogicImpl extends AbstractBLogic<XxxInput, XxxOutput> implements XxxBLogic {
    // ...
}
```

* BLogic毎のインタフェースでインジェクション

```java
@Inject
XxxBLogic xxxBLogic;
```

**Comment by ikeyat** [comment]
> Possible Solutionsに記載されている内容の妥当性（裏付け）ってあります？ AbstractBLogicIFを作るところとか・・怪しさ満点（このインタフェースが必要な合理的な理由が見つからない）な気がしています。

記憶が定かではないですが、
* ``AbstractBLogicIF``がないと、``XxxxBLogicIF``の定義が冗長になる（``preExecution()``, ``doExecution()``を``XxxBLogic()``毎に定義しないと行けない）

のため、``AbstractBLogicIF``を用意したと思います。``XxxBLogicIF``はtype解決によるInjectionのためのマーカとして割り切っている想定。
``@Named``を使うなら、``XxxBLogic``は不要になり、``AbstractBLogicIF``だけを定義しておけば十分かと思います。

**Comment by kazuki43zoo** [comment]
> AbstractBLogicIFがないと、XxxxBLogicIFの定義が冗長になる（preExecution(), doExecution()をXxxBLogic毎に定義しないと行けない）

preExecution とdoExecutionはprotectedなabstract メソッドなので、インタフェースにメソッドを定義する必要はないという認識です。クラス設計として・・・Abustractクラスに対応するインタフェースを用意することにかなり違和感があります。

**Comment by ikeyat** [comment]
そうなのですが、そうしない限りタイプセーフなインジェクションの目的を達成できないのでは？と考えていました。

> タイプセーフなインジェクション方法の紹介（→改善）

の方法で解決できれば、そちらの構造の方が良いと思います。（``AbstractBLogic``は``BLogic``をimplementsしてる？）

**Comment by kazuki43zoo** [comment]
> AbstractBLogicはBLogicをimplementsしてる？

yes.

**Comment by kazuki43zoo** [comment]
@btfurukawatkr Please backport to 1.0.x.

**Comment by kazuki43zoo** [comment]
必須バージョン（5.3.0, 5.2.1, 1.0.6）での対応は完了

**Comment by kazuki43zoo** [comment]
日本語版は対応完了。

**Comment by sasakitsy** [comment]
I will close this issue, Because I've created issue for translate #2432
