### ISSUE TITLE
URL constraint description is misleading

### ISSUE THREAD

**Issue by btarakists** [terasolunaorg/guideline#2260]
## Description

http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validation-validator-list
4.1.4.1.2. Hibernate Validatorのチェックルール
@URLの説明について

「RFC2396に準拠しているかどうか検証する。」とあるが、正確な説明ではありません。
RFC2396のスキーマの章をみると、`alpha *( alpha | digit | "+" | "-" | "." )` が許容される値になっています。
https://www.ietf.org/rfc/rfc2396.txt

Hibernate Validator の`@URL`の実装では、`java.net.URL`のコンストラクタに入力値を設定し、
インスタンスを生成することで、例外が発生しないことをチェックしています。
`@URL`のJavaDocより・・・Java標準でサポートしているスキーマ(http, https, ftp, file ...) を許容している
そのため、モバイルアプリを呼び出すようなURLスキームを入力すると、入力チェックエラーとなります。
`ex : myApp:/callback/test?aaa=123`

上記の問題は、Hibernate Validator のJIRA(https://hibernate.atlassian.net/browse/HV-886)にもあがっており、5.2.0.Alpha1 で修正されております。
## Possible Solutions

・Hibernate Validator の最新版のJavaDocでは、java標準でサポートしているスキーマ以外は許容していない旨記述が追加されているので、追随する。
・カスタムURLスキームの入力チェックは `org.hibernate.validator.constraintvalidators.RegexpURLValidator` を利用することを記載する
## Affects Version/s
- 5.2.0.RELEASE
- ~5.1.1.RELEASE
- ~5.0.2.RELEASE
- ~1.0.5.RELEASE
## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en
- [x] 5.2.1_ja
- [ ] 5.2.1_en
## Issue Links
- https://hibernate.atlassian.net/browse/HV-886
## ChangeLog
- required

**Comment by ikeyat** [comment]
@btarakists 
レポートありがとうございます。Hibernate Validatorの作法に準拠していると思いますので、Possible Solutionsに書いていただいた通りの対応を取りたいと思います。

> 上記の問題は、Hibernate Validator のJIRA(https://hibernate.atlassian.net/browse/HV-886)にもあがっており、5.2.0.Alpha1 で修正されております。

これは``@URL``のjavadocのミスリードな記述が修正された、と理解しました。

**Comment by btarakists** [comment]
@ikeyat 
> これは@URLのjavadocのミスリードな記述が修正された、と理解しました。

[HV-886](https://hibernate.atlassian.net/browse/HV-886) はご認識の通りJavaDocの修正のみです。
わかりづらい記載で申し訳ありません。

**Comment by btyoshikawaa** [comment]
@btfurukawatkr 
Please backport to 5.2.x !

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create translation issue and close this.

**Comment by sasakitsy** [comment]
I will close this issue, because I've created an issue for translate #2433
