### ISSUE TITLE
Add mapping about notes of AP server 's behavior difference

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#227]
Add mapping about notes of AP server 's behavior difference to CriteriaBasedMapping.rst.

**Comment by iwanagah** [comment]
@kazuki43zoo 詳細の記述をお願いします

**Comment by btshimizukza** [comment]
@ikeyat @iwanagah 

以前、APサーバに起因する環境依存をガイドラインにまとめるという話がありました。
ただ、 https://github.com/terasolunaorg/terasoluna-gfw/wiki にまとめる方針になった？ので、このissueはクローズしてよい気がします。

**Comment by ikeyat** [comment]
@btshimizukza 
承知しました。 個々の箇所ではNoteに書きつつ、全体通しではhttps://github.com/terasolunaorg/terasoluna-gfw/wiki にまとめる方針なのでクローズします。
