### ISSUE TITLE
@ControllerAdvice(annotations = RestController.class) is not listed on TutorialREST 

### ISSUE THREAD

**Issue by btkatagiriyu** [terasolunaorg/guideline#2281]
## Description

チュートリアル(Todoアプリケーション REST編)の
10.2.3.7.4. REST APIのエラーハンドリングを行うクラスの作成 において、
@ControllerAdviceに(annotations = RestController.class)属性を付与することが推奨されているが、
その後のサンプルにはannotations属性なしとなっている。
サンプルに追加した方が良いと思われる。

ただし、annotations属性を付与して、動作確認を行うと、下記結果となる。
　①10.2.3.7.6. HTTPレスポンスBODYにエラー情報を出力するための実装（405 Method Not Allowedのエラー）
　　　　⇒ Handlerが機能せず、レスポンスがHTML形式で返却される
　②10.2.3.7.8. 業務例外のエラーハンドリングの実装（409 Conflictの業務エラー）
　　　　⇒ Handlerが機能し、レスポンスがJSON形式で返却される

①の場合のみHandlerが機能しない原因は下記と思われ、
同原因からassignableTypesやbasePackages等も機能しない。
　・URL不備のためにControllerクラスが特定できず、@RestControllerアノテーションが見つからない
## Possible Solutions

●サンプルソースの@ControllerAdviceに(annotations = RestController.class)属性を付与する
●annotations属性の対処法を追記する
　　・対象Exceptionで分類し、Handlerを分類する
　　・RESTプロジェクトとJSPプロジェクトは個別にすることを推奨する
　　・RESTリクエストとJSPリクエストとでサーブレット分ける
　　・(annotations )は設定せず、path（api/app）を判別し、それぞれの処理を行う
　　・405 Method Not Allowedは救えないことを記述し、実装側で気をつける
　　・その他
## Affects Version/s
- ~5.2.0.RELEASE
## Fix Version/s
- [x] 5.4.0
- [x] 5.3.1
- [ ] Create issue for translation
## Issue Links
- #http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Tutorial/TutorialREST.html#id19
## ChangeLog
not required

**Comment by kazuki43zoo** [comment]
@btkatagiriyu 

ガイドラインを見直してみましたが、API用のサーブレットを用意する前提になっているので、適用対象を絞る属性「`(annotations = RestController.class)`」の指定は不要ですね。

なので・・・コードを正として説明文を修正してほしいです。
（`@ControllerAdvice`に属性を何も指定しなかった場合に、ガイドラインに記載されている動作になる事は確認してほしいです）

アサインしちゃいます。

**Comment by btmatsumotoms** [comment]
`@ControllerAdvice` に属性を何も指定しなかった場合に、ガイドラインに記載されている動作になる事を確認しました。

**Comment by yoshikawaa** [comment]
> @ControllerAdvice に属性を何も指定しなかった場合に、ガイドラインに記載されている動作になる事を確認しました。

追記：内部の検証アプリでも、上記の通り `@ControllerAdvice` に属性を何も指定していません。

**Comment by yoshikawaa** [comment]
@itouyun @takahashihrzg 
Please create issue for translation, and close this.

@btmatsumotoms 
Thanks for your work.

**Comment by itouyun** [comment]
I created #2783 issue. This issue is closed.
