### ISSUE TITLE
Reflect Eng (Change the reference path to a release version)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2307]
## Description
Change the reference path to a release version.
Now, some references are "master".

For examples;
now:
`terasoluna-gfw-common <https://github.com/terasolunaorg/terasoluna-gfw/tree/master/terasoluna-gfw-common-libraries/terasoluna-gfw-common>`

change for 5.2.0:
`terasoluna-gfw-common <https://github.com/terasolunaorg/terasoluna-gfw/tree/5.2.0.RELEASE/terasoluna-gfw-common-libraries/terasoluna-gfw-common>`

## Fix Version/s
- 5.2.0_en
    - [x] translation/5.2.0
    - [x] 5.2.x
- 5.1.1_en
    - [x] translation/5.1.1
    - [x] 5.1.x
- 5.0.3_en
    - none
- 1.0.5_en
    - none
- 5.3.0_en
    - none

## Issue Links
- none

## ChangeLog
- none

**Comment by btkobayashirun** [comment]
No subject to 1.0.x
