### ISSUE TITLE
Reconsider Form class separation policy

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/guideline#2347]
## Description
現在、以下の節で、似たような項目を持つFormは１つのフォームクラスに集約し、グループ化したほうが修正コストが小さくなるような記述がある。
しかし、フォームクラスがJSPの``<form:form>`` に1対1にバインドされることを考えると、JSPの変更に対して同期をするためには、JSPファイルの分割ポリシーとフォームクラスの分割ポリシーは合わせておいたほうがリーズナブルなように思われる。記述内容を見直したほうが良い。

http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Tutorial/TutorialTodo.html#id29
Note

## Possible Solutions
TBD

## Affects Version/s
* ~5.2.0.RELEASE
* ~5.1.1.RELEASE
* ~5.0.2.RELEASE
* ~1.0.5.RELEASE

## Fix Version/s
- [ ] 5.3.0_ja
- [ ] 5.3.0_en
- [ ] 5.2.1_ja
- [ ] 5.2.1_en

## ChangeLog
- [ ] required?

**Comment by itouyun** [comment]
「集約する方が修正コストが小さくなる」とは明記されていない気がします。
記載されている内容は以下です。
* 新規作成処理用と完了処理用を別々のFormクラスとして作成しても良い
* 処理毎にFormクラスを作成した場合、～～～修正コストが高くなる可能性がある

高くなる可能性がある、とは記載されていますが、その逆もまた然りであり、集約することで、修正コストが小さくなる可能性がある、の域を超えないと読めます。
特に集約を推している記述は見当たらないため、現状維持でも問題ないのではないでしょうか。
