### ISSUE TITLE
[RESTful Web Service] 脱字

### ISSUE THREAD

**Issue by KunimitsuMasuda** [terasolunaorg/guideline#2349]
## Description
「5.1.2.7. 関連のあるリソースへのリンク」にて、「疎結合性を高めることが出来る理由」の項番(2)に脱字がある。

## Possible Solutions
誤）クライアントアプリケーショ
正）クライアントアプリケーショ**ン**

## Affects Version/s
* All versions

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1

## Issue Links
*　http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/WebServiceDetail/REST.html#restoverviewaboutrestfulwebservice

## ChangeLog
N/A

**Comment by kazuki43zoo** [comment]
@KunimitsuMasuda 報告ありがとうございます！ 

次回からIssueテンプレートにそって報告頂けると助かります。
