### ISSUE TITLE
[ファイルアップロード]4.9.2.6.1 文章中の脱字について

### ISSUE THREAD

**Issue by btkigamim** [terasolunaorg/guideline#2357]
## Description
以下の項目の文章中にて、脱字と思われる個所を確認。

■4.9.2.6.1. Controllerの実装
　-　Warning
 　　- 「 データベースに保存す処理を」
 　　　⇒保存する処理 の「る」が抜けています。

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0
- [x] 5.3.1

## ChangeLog
(To be written later by project member)

**Comment by btkamatayst** [comment]
5.4.0、5.3.1ともに#2645で修正済みでした。
英語版には関係無い内容です。

**Comment by btsatouhrzzp** [comment]
#2645 で修正されていることを確認。本Issueはクローズします。
