### ISSUE TITLE
Spring Securityチュートリアルにあるソース例のハイライトがずれている

### ISSUE THREAD

**Issue by iwanagah** [terasolunaorg/guideline#2358]
## Description
Spring Securityチュートリアルにあるソース例のハイライトがずれている。

「アプリケーション層の実装/Spring Securityの設定」のspring-security.xmlのソース例において、
番号とは関係ない部分にハイライトがされている

## Possible Solutions
要方針検討だが、(1)などのハイライトをしているソースとしていないソースがあるので、
外してしまっていいと思っています。
もしくは、他にあわせてハイライトの行数を調整する。

ガイドライン全体としてどうするか？という話は別途必要だが、とりあえず、上記の部分は
見当違いの場所のハイライトなので直しておきたい。

## Affects Version/s
* 5.2.0.RELEASE以下。他は未確認

## Fix Version/s
- [ ] 5.3.0
- [ ] 5.2.1

## ChangeLog
(To be written later by project member)

**Comment by btyoshikawaa** [comment]
@iwanagah 
#2081 Reflect the change of blank projects to guidelines の対応で、既に併せて修正しています。
