### ISSUE TITLE
Spring Security チュートリアルのfirst-springsecurity-env.xmlの設定の手順が不要

### ISSUE THREAD

**Issue by btnoguchimnm** [terasolunaorg/guideline#2360]
## Description
ブランクプロジェクトにjdbcのスキーマ定義および<jdbc:initialize-database>タグが追加されているため、
[10.4.4.1.5. データベースの初期化スクリプトの設定](http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Tutorial/TutorialSecurity.html#id12)
で行っていた「first-springsecurity-env.xmlに設定を追加する」手順は不要。

該当箇所の必要性について検討し、説明として残す場合には、
first-springsecurity-env.xmlのソースコード例の「REMOVE THIS LINE IF YOU USE MyBatis3」のコメント行を削除する必要がある。
（mybatis3のブランクから作成した手順の一貫性が失われているため）

## Possible Solutions
See Description

## Affects Version/s
* 5.3.0.RELEASE
* 5.2.1(and0).RELEASE
* 5.1.1.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1
- [x] 5.2.2
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.7

※軽微なエラーだが、ブランクプロジェクトとの整合性担保のため、影響のある全バージョン対応する

## Issue Links
* nothing

## ChangeLog
no

**Comment by yoshikawaa** [comment]
> 該当箇所の必要性について検討し、説明として残す場合には、
> first-springsecurity-env.xmlのソースコード例の「REMOVE THIS LINE IF YOU USE MyBatis3」のコメント行を削除する必要がある。
> （mybatis3のブランクから作成した手順の一貫性が失われているため）

これは単純にバグですね。
リポジトリ上のコードをそのままコピペしたせいで、実際に使うとき（MyBatis3用プロジェクトとしてビルドされたとき）の形になっていないだけでしょう。

**Comment by yoshikawaa** [comment]
@btsuzukisnzh 
全バージョン対応完了した認識ですが、一応5.0以前は対応しなくて良いことも確認していただけますか？

**Comment by btsuzukisnzh** [comment]
@yoshikawaa 
5.0.xと1.0.xを確認致しました。
どちらのバージョンもブランクプロジェクトのenvファイルが変更されているため、
ガイドラインと整合性が取れていません。
そのため5.0.xと1.0.xについても修正を行ったほうがよいと考えております。

**Comment by yoshikawaa** [comment]
@btsuzukisnzh 
ありがとうございます！修正しましょう！

**Comment by yoshikawaa** [comment]
@itouyun 
Please write issue for translation, and close this.

**Comment by itouyun** [comment]
I made translation issue.
And this issue is closed.
