### ISSUE TITLE
Descriptions about Spring Validator supports method are insufficient

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2363]
## Description
http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#spring-validator
「Spring Validatorによる相関項目チェック実装」の節で、`org.springframework.validation.Validator#supports`メソッドの役割を「このValidatorのチェック対象であるかどうかを判別する。」と紹介しているが、チェック対象でない場合に以下のような例外が発生することについて言及していない。
```console
[INFO] [talledLocalContainer] java.lang.IllegalStateException: Invalid target for Validator [com.exapmle.app.validation.ConfirmValidator@2b72dbe0]: com.exapmle.app.validation.ValidationForm@26c677a9
```
Noteに「一つのControllerで複数のフォームを扱う場合は、Validatorの対象を限定するために、@InitBinder("xxx")でモデル名を指定する必要がある。」という記載があるが、実際には`Model`に登録されたカスタム型オブジェクトすべてに対してValidatorが登録されるため、例えば`RedirectAttributes`にカスタム型オブジェクトを追加する場合も同様の注意が必要である。

実装時にハマるポイントの一つなので、記述を追加したほうが良い。

## Possible Solutions
以下を追記する。
* `@InitBinder`でモデル名を指定しない場合は`Model`に登録されたカスタム型オブジェクトすべてに対してValidatorが登録される
* Validatorのチェック対象でないオブジェクトでは、`IllegalStateException`が発生する
* 複数のフォームを扱う場合でなくても、`@InitBinder`でモデル名を指定が必要な場合がある

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (guideline/master) 【共通】
-  ~~5.4.0_en (guideline/master) 【共通】~~ (other issue)
- [x] 5.3.1_ja (guideline/5.3.x) 【共通】
- ~~5.3.1_en (guideline/5.3.x) 【共通】~~ (other issue)
- [x] 1.5.0_ja (guideline-macchinetta-jsp/master) 【共通】
- [x] 1.4.1_ja (guideline-macchinetta-jsp/1.4.x) 【共通】
- [x] 1.5.0_ja (guideline-macchinetta-thymeleaf/master) 【共通】

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by itouyun** [comment]
ハマるポイントであるため、Noteに追加するイメージ。

**Comment by btsuzukisnzh** [comment]
@yoshikawaa
Possible Solutionsに
「複数のフォームを扱う場合でなくても、 @InitBinder でモデル名を指定が必要な場合がある」
とありますが、必要な場合というのはどのようなときでしょうか。
Noteに追記するにあたり、理由もあわせて併記したほうが良いと考えております。

**Comment by yoshikawaa** [comment]
@btsuzukisnzh 
Descriptionに記載の通りです。
> 例えば`RedirectAttributes`にカスタム型オブジェクトを追加する場合も同様の注意が必要である。

これは一例なので、どのようなパターンがあるかは検討したほうが良いと思います。

**Comment by itouyun** [comment]
@btoohashimc 
Thank you for your work!!
