### ISSUE TITLE
'aggressiveLazyLoading' change to false since the MyBatis 3.4.2

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2364]
## Description
まだ正式リリースされていないが、MyBatis 3.4.2より、`aggressiveLazyLoading`のデフォルト値がガイドラインで推奨している`false`に変更される。

## Possible Solutions
[ガイドライン](http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.html#lazy-load
)ではaggressiveLazyLoadingを`false`にすることを推奨する旨の説明があるため、ガイドラインの記載を見直す。

今書いている内容は削除し、代わり・・・

* 動作を変更するパラメータがあるという事実
* そのデフォルト値がガイドライン上の推奨値(`false`)に変わったこと

をNoteで書いておくぐらいでよいと思っています。

## Affects Version/s
\-

## Fix Version/s
(To be written later by project member)

## Issue Links
* https://github.com/mybatis/mybatis-3/pull/825

## ChangeLog
- [ ] Yes

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please write translation issue, and close this.

**Comment by sasakitsy** [comment]
Translating #2501 .
And close this issue.
