### ISSUE TITLE
Can detect type handlers for JSR-310 automatically since MyBatis 3.4

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2365]
## Description

MyBatis 3.4以降では、JSR-310用のType Hanlderを自動検出するようになっている。

## Possible Solutions

ガイドラインは3.3系ベースでマニュアルで追加する方法になっているため、この部分の記載を見直す。

## Affects Version/s
* 5.2.0.RELEASE

## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en

## Issue Links
* https://github.com/mybatis/mybatis-3/pull/597

## ChangeLog
- [x] Yes

**Comment by bturamatuyu** [comment]
対応方法としては、下記の通りでよいでしょうか？
・対応
"6.2.2.3.5. TypeHandlerの設定"の"JSR-310 Date and Time APIを使う場合の設定"の記述(設定方法とTip)削除。
・理由
TERA 5.3.0では、mybatis 3.4.Xを採用しており、JSR-310のtypehandlerは自動検出されるため、
その設定方法及びTipは不要となる。

**Comment by kazuki43zoo** [comment]
@sasakitsy Please create a new issue for translation.

**Comment by sasakitsy** [comment]
I will close this issue because I've created an issue for translate for #2463
