### ISSUE TITLE
Can omit the @Param when use JDK 8's -parameters option since MyBatis 3.4.1

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2366]
## Description

MyBatis 3.4.1以降では、JDK 8から追加された `-parameters`オプションを付けてコンパイルすると`@Param`を省略できる。

## Possible Solutions

省略することを推奨する必要はないと思うが、`-parameters`付きでコンパイルすることで省略できる旨はNoteで記載しておきたい。

## Affects Version/s
\-

## Fix Version/s
- [x] 5.4.0
- [x] 5.3.1
- [ ] write issue for translation

## Issue Links
* https://github.com/mybatis/mybatis-3/issues/549

## ChangeLog
not required(improvement)
- [x] create version outline for change log.

**Comment by itouyun** [comment]
@kazuki43zoo 
記載するとしたら以下のページですかね。
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.html#dataaccessmybatis3howtousefindmultiple

**Comment by kazuki43zoo** [comment]
@itouyun 
現在のガイドラインベースに追記するなら・・・

http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.html#id27

のTipで`@Param`について説明してるので、そこに追加かな～と思います。

**Comment by btmatsumotoms** [comment]
@itouyun 
Tipを記載したので確認をお願いします。
記載内容ですが、
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/Authorization.html#id16
のtipにも似た内容があったので出来るだけ合わせてみました。

ローカルでの動作確認も実施済みです。
http://qiita.com/kazuki43zoo/items/c0603931c9f0a655a9a4を参照しました。
「-parameters」オプションを指定しない場合は、
「Parameter 'tUser' not found. Available parameters are [arg1, arg0, param1, param2]」の
Exceptionのメッセージが出ることを確認しています。

**Comment by yoshikawaa** [comment]
@itouyun @takahashihrzg 
Please write issue for translation, and close this.

@btmatsumotoms 
Thanks for your work.

**Comment by itouyun** [comment]
Thanks for your work and I made translation issue.
