### ISSUE TITLE
@ExceptionHandler is able to process Error thrown from handler method since Spring MVC 4.3

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2368]
# Description
@ExceptionHandlerでErrorやThrowableもハンドリングできるようになった。

## Possible Solutions
以下の内容をガイドラインの「4.2.例外ハンドリング」へ反映する。
java.lang.Exceptionやjavax.servlet.ServletExceptionをハンドリングするようにしていると、意図せずjava.lang.Throwableやjava.lang.Errorを継承したクラスもハンドリングされてしまうため注意が必要。

## Affects Version/s
 * 5.3.0.RELEASE

## Fix Version/s
 - [x] 5.3.0.RELEASE

#### reflect changes
* https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/304
* https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/270
* https://github.com/terasolunaorg/terasoluna-tourreservation/issues/445
* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/517

## Issue Links
* http://qiita.com/kazuki43zoo/items/53d2ca25c174ff618331#spring-mvc%E3%81%AE%E4%BE%8B%E5%A4%96%E3%83%8F%E3%83%B3%E3%83%89%E3%83%A9%E3%81%A7error%E3%82%84throwable%E3%82%92%E3%83%8F%E3%83%B3%E3%83%89%E3%83%AA%E3%83%B3%E3%82%B0%E3%81%A7%E3%81%8D%E3%82%8B-1
* https://jira.spring.io/browse/SPR-11106

## ChangeLog
- [x] Yes

**Comment by bthondasui** [comment]
致命的エラーのハンドリングの考え方について検討中。

案１．SystemExceptionとする。
    ・HandlerExceptionResolverの仕組みを使い、例外ハンドリングを行う。

案２．ServletExceptionとする。（Terasoluna5.2と同じ動作）
　・@ExceptionHandlerアノテーションを使い、アプリケーションコードで例外ハンドリングし、サーブレットコンテナにthrowする。
　・SystemExceptionResolverのexcludedExceptionsプロパティにNestedServletExceptionを指定する。

**Comment by bthondasui** [comment]
**案１　サーブレット単位のハンドリングを推奨**
    ・・・ HandlerExceptionResolverの仕組みを使い、例外ハンドリングを行う。

**＜メリット＞**

- Springの考え方（致命的エラーをMVCでハンドリング可能になった）に合う。

**＜デメリット＞**
- 既存プロジェクトへの改修量が多い。
- ログ出力のされ方や、エラー画面遷移の動きが既存プロジェクト(Terasoluna5.2まで)から変わる。
- @ExceptionHandlerを使用したNestedServletExceptionのハンドリングについて、十分な検証が出来ていない。
- ガイドライン、ブランクプロジェクトに関する修正量が多い。

**案２　Webアプリケーション単位のハンドリングを推奨**
    ・・・ SystemExceptionResolverのexcludedExceptionsプロパティにNestedServletExceptionを指定する。

**＜メリット＞**

- 案１に比べて、既存プロジェクトに対する改修量が少ない。
- Terasoluna 5.2以前の動きと同様になり、致命的エラーを個別ハンドリングしない方針に合う。
- ガイドライン、ブランクプロジェクトに関する修正量が少ない。

**＜デメリット＞**

- 既存の実装で@ExceptionHandlerを実装している場合、キャッチされてしまう可能性がある。
　※基本的に無いはず(元々java.lang.ErrorはNestedServletExceptionにラップされていた為)

**⇒検討した結果、デメリットが少ない事から案２の方向で進める方針**

**Comment by sasakitsy** [comment]
I will close this issue because I've created an issue for translate for #2461

**Comment by bthondasui** [comment]
再検証したところ、@ExceptionHandler(NestedServletException.class)でハンドリングしリスローするだけではサーブレットコンテナに通知されないことが分かった。そのため、リスローしている場合でもSystemExceptionResolverの除外設定が必要になる。ガイドラインに反映が必要なため、再オープンする。

**Comment by bttakehirah** [comment]
Change excludedExceptions to the following.
<set> to <array>

**Comment by kazuki43zoo** [comment]
@bthayashidi @btyoshikawaa 

これブランクPJに反映する必要があると思っています。

**Comment by kazuki43zoo** [comment]
@bthayashidi @btyoshikawaa 

あと、サンプルアプリ（tour reservation）も。
