### ISSUE TITLE
Added AsyncRestTemplate interceptors since Spring MVC 4.3

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2369]
## Description
AsyncRestTemplateにインタセプター(RestTemplateでいうところのClientHttpRequestInterceptor相当)の仕組みが追加された。

## Possible Solutions
現状、明確に「できない」旨が記載されているため、当該記述を削除する。
また、必要に応じて使用例等追記する。

## Affects Version/s
\-

## Fix Version/s
 - [x] 5.3.0.RELEASE

## Issue Links
* http://qiita.com/kazuki43zoo/items/53d2ca25c174ff618331#asyncresttemplate%E3%81%AB%E3%82%A4%E3%83%B3%E3%82%BF%E3%82%BB%E3%83%97%E3%82%BF%E3%83%BC%E3%82%92%E7%B5%84%E3%81%BF%E8%BE%BC%E3%82%81%E3%82%8B-1
* https://jira.spring.io/browse/SPR-12538
* http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/WebServiceDetail/RestClient.html#asyncresttemplatebean

## ChangeLog
- [x] Yes

**Comment by kazuki43zoo** [comment]
@sasakitsy Please create a new issue for English translation.

**Comment by sasakitsy** [comment]
I will close this issue , Because I've created issue for translate #2462
