### ISSUE TITLE
java.io.IOException occurs in WAS-LP version 16.0.0.2

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2370]
## Description
WAS-LP version 16.0.0.2にてRESTでアクセスした際にjava.io.IOExceptionが発生する。
詳細は[SPR-14784](https://jira.spring.io/browse/SPR-14784)参照。

## Possible Solutions
上記の件に関して調査の上、必要であれば対処を行う。

## Affects Version/s
 - [ ] 5.3.0.RELEASE

## Fix Version/s
 - [ ] 5.3.0.RELEASE

## Issue Links
* https://jira.spring.io/browse/SPR-14784

## ChangeLog
- [ ] Yes

**Comment by btyoshikawaa** [comment]
再現性も含めて調査が必要。我々のテストで再現できなければ、クローズで良いと思う。

**Comment by kazuki43zoo** [comment]
@bthoshikt 

What state is this ?

**Comment by bthoshikt** [comment]
再現しないためクローズ。
