### ISSUE TITLE
HttpRequestMethodNotSupportedException occurs when accessing Path set by <mvc: view-controller> with POST method

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2371]
## Description
<mvc:view-controller>で設定したPathにPOSTメソッドでアクセスするとHttpRequestMethodNotSupportedExceptionが発生するようになった。

## Possible Solutions
上記内容についてガイドラインへ反映する。
可能なら回避方法や代替案を挙げる。

## Affects Version/s
 - 5.3.0

## Fix Version/s
 - [x] 5.3.0.RELEASE

## Issue Links
* https://jira.spring.io/browse/SPR-13130
* https://github.com/spring-projects/spring-framework/commit/135738f9bfb5b9dacf164d6561144589dc98deb8

## ChangeLog
- [x] Yes

**Comment by sasakitsy** [comment]
@sasakitsy
Translate it.

**Comment by sasakitsy** [comment]
translating for #2472 
so, close this issue.
