### ISSUE TITLE
"select for update nowait" can not be used in Hibernate 5.0(PostgreSQL)

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2372]
## Description
Hibernate 5.0でPostgreSQLを使用している際にnowaitを使うように指定しても使用されない。
Hibernate 5.2.1でFixされている。

## Possible Solutions
ガイドラインで上記問題があることを明記する。

## Affects Version/s
 -  5.3.0.RELEASE

## Fix Version/s
 - [x] 5.3.0.RELEASE

## Issue Links
* https://hibernate.atlassian.net/browse/HHH-10797

## ChangeLog
- [x] Yes

**Comment by bthayashidi** [comment]
本Issueの対応内容としてはPostgreSQL使用時にNOWAITが使用できない旨のWarningを記載するのみとする。
Hibernate5.2系からDialect実装をバックポートして本格対処を行う件に関しては優先順位を下げて本Issueの範囲外とする。

**Comment by kazuki43zoo** [comment]
@sasakitsy 

Please create a new issue for translation.

**Comment by sasakitsy** [comment]
Translate in #2483 
And close this issue.

**Comment by kazuki43zoo** [comment]
nowaitが付くケースがあることが判明したので、補足します。

現時点でわかっていることは、`EntityManager#find`が呼び出されるケース(例：`JpaRepository#findOne`)についてはnowaitが適用されます。

* nowaitが適用されるケース

```java
@Lock(LockModeType.PESSIMISTIC_WRITE)
@QueryHints(@QueryHint(name = "javax.persistence.lock.timeout", value = "0"))
Todo findOne(Integer id);
```

逆にnowaitが適用されないのは、`@Query`を使用して明示的にJPQLを指定している場合や、Spring Data JPAがJPQLを組み立てるケース(例：`JpaRepository#findAll`)です。
ガイドラインでは悲観ロック用のメソッド(`findOneForUpdate`)を別途用意する方法を紹介しており、このケースにおいてはnowaitが適用されません。（ひょっとしたら適用されるケースもあるかもしれませんが、網羅的に調べてはいません）

* nowaitが適用されないケース

```java
@Lock(LockModeType.PESSIMISTIC_WRITE)
@QueryHints(@QueryHint(name = "javax.persistence.lock.timeout", value = "0"))
@Query("SELECT t FROM Todo t WHERE t.id = :id")
Todo findOneForUpdate(@Param("id") Integer id);
```

or

```java
@Lock(LockModeType.PESSIMISTIC_WRITE)
@QueryHints(@QueryHint(name = "javax.persistence.lock.timeout", value = "0"))
List<Todo> findAll();
```

また、Hibernate ORM 5.2.1へアップデートすることでnowaitが付くことは確認できましたが、usertypeを6.0.0.GA+にしないとAPIの互換性の問題でエラーになるので、Hibernate ORMのバージョンとあわせて修正が必要です。

* Hibernate ORM + usertypeの更新する場合のpomの定義例

```xml
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-entitymanager</artifactId>
    <version>5.2.1.Final</version>
</dependency>

<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-core</artifactId>
    <version>5.2.1.Final</version>
</dependency>

<dependency>
    <groupId>org.jadira.usertype</groupId>
    <artifactId>usertype.core</artifactId>
    <version>6.0.0.GA</version>
</dependency>
```
