### ISSUE TITLE
Should be enable the rollbackOnCommitFailure option

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2375]
## Description
RDBMSとしてOracleを使用する場合、commitフェーズでエラーが起きると暗黙コミットされる可能性がある。

Note : 他のRDBMS上での動作は検証していないので、別途検証する必要あり。

## Possible Solutions
`DataSourceTransactionManager#setRollbackOnCommitFailure=true`にすることで、commitフェーズでエラーが発生した場合にrollbackメソッドを呼び出すことができる。
rollbackでエラーが発生した場合にどうなるのかは不定であるが、rollbackを試みるように設定しておくことで、意図しない状態にデータ更新されてしまうリスクを下げることができる。

現時点で問題になることはわかっているのはOracleだけだが、他のRDBMSも含めて一律設定するようにガイドした方が安全な気がします。（ブランクプロジェクトの設定変更も要検討）

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1

## Issue Links
* http://qiita.com/kazuki43zoo/items/73225b41a2c36a720a4b

## ChangeLog
- [x] Yes

**Comment by kazuki43zoo** [comment]
とりあえず、PostgreSQLとMySQLは暗黙コミットされませんでした。

**Comment by kazuki43zoo** [comment]
DB2も試しました。そして、PostgreSQLとMySQLの結果が微妙に正しくなかった。

結果としては、

* defaultAutoCommitがtrueの場合は、Oracleを含めてすべての全てのRDBMSでコミットされた。
* defaultAutoCommitがfalseの場合は、Oracleのみコミットされた。

というのが正確な結果でした。

ちなみに・・・コネプの実装によっては↑の結果もかわる可能性があると思います。
上記の結果になったのは、Spring Boot上でTomcat JDBCのコネプを使った時の結果です。

**Comment by kazuki43zoo** [comment]
再度訂正・・・

コネクションプールを使っていると、defaultAutoCommitをfalseにしていても、Oracle以外でもコミットされちゃう可能性がありました。
エラーが発生した直後にコミットされることはないのですが、コネプに戻された後に同じコネクションを使った処理が正常成功したタイミングで一緒にコミットされてしまいます。

**Comment by kazuki43zoo** [comment]
http://qiita.com/kazuki43zoo/items/73225b41a2c36a720a4b にまとめました。

**Comment by yggd** [comment]
コネクションclose()による暗黙commitもあかんけど、

> Commitはされませんでしたが・・・コネプションプールを使っていると、プールに戻ったコネクション(エラーが発生したコネクション)を別の処理で使った時に逆にCommitできませんでした（ある意味想定内の動きかも！？）・・・

プールとしては想定内の動きですが、これは原因究明を困難にさせる事象であり非常にイヤですね。

**Comment by kazuki43zoo** [comment]
@sasakitsy 
Please create a issue for translation.

**Comment by sasakitsy** [comment]
Translate here (#2482).
And close this issue.
