### ISSUE TITLE
Support for "HTTP Public Key Pinning (HPKP)"

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2401]
## Description
Spring Security 4.1から"HTTP Public Key Pinning (HPKP)"のHTTPレスポンスヘッダが出力できるようになった。
http://docs.spring.io/spring-security/site/docs/4.1.4.RELEASE/reference/htmlsingle/#headers-hpkp

## Possible Solutions
"HTTP Public Key Pinning (HPKP)"の使用方法等一式を追記する。
http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/LinkageWithBrowser.html

## Affects Version/s
- 5.3.0.RELEASE

## Fix Version/s
- [x] 5.3.0.RELEASE
- [x] 5.3.0.RELESAE ([rework](https://github.com/terasolunaorg/guideline/issues/2401#issuecomment-278839158))
- [-] 5.3.0.RELEASE for en -> #2435
## ChangeLog
- [x] Yes

**Comment by kazuki43zoo** [comment]
@sasakitsy 

please create a new issue to translate this.

**Comment by sasakitsy** [comment]
I will close this issue because I've created an issue for translate for #2435

**Comment by kazuki43zoo** [comment]
@btideues 

修正漏れみつけたので対応してほしいです。

「Spring Securityがデフォルトでサポートしているレスポンスヘッダは以下の5つである。」 -> 「Spring Securityがデフォルトでサポートしているレスポンスヘッダは以下の**7**つである。」
