### ISSUE TITLE
Support JBoss 7

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2403]
## Description
JBoss 7をサポートするにあたり、ガイドラインへの影響を調べて必要に応じて反映する。

## Possible Solutions
See https://github.com/terasolunaorg/guideline/issues/2403#issuecomment-279654223

## Affects Version/s
\-

## Fix Version/s
- [x] 5.3.0

## Issue Links
* #XXX

## ChangeLog
No

**Comment by kazuki43zoo** [comment]
あと、JBoss EAP 7向けの[Wiki](https://github.com/terasolunaorg/terasoluna-gfw/wiki/JBoss_ja)に載せる情報も併せて整理してほしいです。

**Comment by bttamuratsh** [comment]
- jboss-deployment-structure.xmlの作成と設定
何も設定しなくてもデプロイは出来ますが、最低限"org.slf4j"を除外しないと正しくログ出力されずgfwのテストに失敗します。またwarのライブラリとバージョンが同じでたまたま問題が起こっていないモジュールがいくつかあるので、それらについても除外リストに追加したほうが無難です。

- URIエンコーディングの設定
JBoss6ではstandalone.xmlにエンコーディングの設定を追加する必要がありますが、JBoss7では不要です。

- ファイルアップロード（Commons FileUpload）の設定
Servlet3のファイルアップロード機能を使えますが、そのままではマルチバイト文字のファイル名が文字化けしてしまいます。standalone.xmlのservlet-containerタグにパラメータdefault-encoding="UTF-8"を追加するか、WEB-INF下にjboss-web.xmlを作成しdefault-encodingをUTF-8に設定すると回避できます

**Comment by bttamuratsh** [comment]
JBoss7をサポートするにあたり、ガイドラインに記載が必要なものをまとめました

|対象のファイル|必要な修正|
|--------------------|---------------------------|
| [DataAccessCommon.rst](https://github.com/terasolunaorg/guideline/blob/fee6537a5d74e94d1dbd0e5eabc6dcf57eb65858/source/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst)|JBoss7のデータソースに関するドキュメントを紹介する|
| [Email.rst ](https://github.com/terasolunaorg/guideline/blob/abd9d1a4992ca0915b7a528d6b29461dc8a8fde0/source/ArchitectureInDetail/MessagingDetail/Email.rst)|JBoss7のメールセッションに関するドキュメントを紹介する|
| [SOAP.rst  ](https://github.com/terasolunaorg/guideline/blob/fee6537a5d74e94d1dbd0e5eabc6dcf57eb65858/source/ArchitectureInDetail/WebServiceDetail/SOAP.rst)|JBoss7のJAX-WSに関するドキュメントを紹介する|
|[FileUpload.rst](https://github.com/terasolunaorg/guideline/blob/84942b7c11b0faef61b4b3cca82cb070074301b7/source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst) |JBoss7ではServlet 3.0のファイルアップロード機能を使用する際に文字化けを回避する設定があることを記載する|
|[JMS.rst](https://github.com/terasolunaorg/guideline/blob/abd9d1a4992ca0915b7a528d6b29461dc8a8fde0/source/ArchitectureInDetail/MessagingDetail/JMS.rst)|JBoss7のJMS設定に関するドキュメントを紹介する|

**Comment by kazuki43zoo** [comment]
@sasakitsy 

please create a translation issue.

**Comment by sasakitsy** [comment]
Translate in #2522 .
So, close this issue.
