### ISSUE TITLE
Update JDBC Jar version for postgresql

### ISSUE THREAD

**Issue by btfurukawatkr** [terasolunaorg/guideline#2405]
## Description
The version described in guideline for postgresql jdbc jar is old now( postgresql-9.3-1102-jdbc41.jar )

## Possible Solutions
Change the version to the latest one.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6 description not found.

## Issue Links
* #XXX

## ChangeLog
not required.

**Comment by btyoshikawaa** [comment]
@btfurukawatkr 
Please backport!

**Comment by btfurukawatkr** [comment]
@btyoshikawaa 
I've created backport PR's except for 1.0.x since there wasn't any jdbc driver versions mentioned in that version

**Comment by btyoshikawaa** [comment]
@btfurukawatkr 
OK, I had excluded 1.0.6 from target.
