### ISSUE TITLE
Typo in sample of spring-mvc.xml

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2410]
## Description
There is a typo in sample of `spring-mvc.xml`

same with https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/master/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml#L25.

## Possible Solutions

`workarround` > `workaround`

## Affects Version/s
* 5.2.0.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1

## Issue Links
\-

**Comment by btyoshikawaa** [comment]
Both Japanese and English version are completed.
