### ISSUE TITLE
Japanese text in an Image

### ISSUE THREAD

**Issue by btratodos** [terasolunaorg/guideline#2413]
## Description
There exists Japanese text 「リソースのアクセスポリシーの連携」 in 9.3.1.1. Authorization process architecture of English documentation.
Same in case of 9.3.1.1. 認可処理のアーキテクチャ of Japanese documentation.
Refer link: http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/en/Security/Authorization.html#authorization-process-architecture 

## Possible Solutions
Ideally there should not be any Japanese text in any image as per the standards.
All the text in images should be in English irrespective of whether the documenation is in Japanese or English.
Solution would be translate the Japanese text in English and replace the image in both English and Japanese documentation.

## Affects Version/s

* 5.1.0 or later

## Fix Version/s

- [x] 5.4.0(master) ja
- [x] 5.3.1 ja
- [x] 5.4.0(master) en
- [x] 5.3.1 en

**Comment by kazuki43zoo** [comment]
Oh ... @btratodos , thanks for your reporting.
I agree with your suggestion !!

**Comment by itouyun** [comment]
「リソースのアクセスポリシーの連携」を英語化するうえで、ガイド上の記述「クライアントがアクセスしようとしたリソースに指定されているアクセスポリシーを連携する。」も含め、そもそも元の日本語の文章が誤っているのではという意見が挙がり、確認しました。

結論としては、誤っておらず、現状の日本語でOKです。

よって、本imageの英語化は、以下のような文章となります。
`Linking with access policy of resource`

＜余談＞
誤っていない理由は、単純にintercept-urlで指定されたアクセスポリシーを連携するにすぎないからです。
例えばOAuthの認証などの場合は「クライアントがアクセスしようとしたリソース`から`指定されているアクセスポリシーを`参照`する。」などになりそうですが、本件には関係ありません。

**Comment by yoshikawaa** [comment]
@itouyun 
Completed including English version.

**Comment by itouyun** [comment]
@btsuzukisnzh @yoshikawaa 
Thank you for your work!!
