### ISSUE TITLE
Writing clearly when internationalization is not applicable

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/guideline#2427]
## Description
国際化のOverviewに、以下の記述があるが、どのような例を指しているのかが分かりづらく、
ガイドラインの他章では、国際化を意識していないコード例もあるため、実装者がハマりやすい。
http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Internationalization.html#overview
```text
エラー画面を国際化する必要がある場合、Spring MVCのControllerを使用してエラー画面に遷移すること。 Spring MVCを介さずエラー画面に直接遷移した場合、メッセージが意図した言語で出力されない場合がある。
```
例えば以下のコード例では、`errorPage`で直接JSPを指定すると、Spring MVCを介さずに遷移するため、`LocaleChangeInterceptor`等が作用せず、意図した国際化が適用されない。
http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/Authorization.html#springsecurityauthorizationaccessdeniedhandler
```xml
<bean id="accessDeniedHandler"
      class="com.example.web.security.JsonDelegatingAccessDeniedHandler">
    <constructor-arg>
        <bean class="org.springframework.security.web.util.matcher.AntPathRequestMatcher">
            <constructor-arg value="/api/**"/>
        </bean>
    </constructor-arg>
    <constructor-arg>
        <bean class="org.springframework.security.web.access.AccessDeniedHandlerImpl">
            <property name="errorPage"
                      value="/WEB-INF/views/common/error/accessDeniedError.jsp"/>
        </bean>
    </constructor-arg>
</bean>
```

## Possible Solutions
国際化の章にて、Spring MVCを介さずに遷移する具体例を示しつつ、注意喚起する。

Intercepterを効かせるためには、直接JSPに遷移せずにControllerを経る必要がある。
* Spring 4.2- or Spring 4.3+でGETでしか使わないなら、`view-controller`を使えばよい
* Spring 4.3+でGET以外（POSTなど）でも使うなら、Controllerクラスを作成する必要がある

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0_ja
- [x] 5.2.1_ja
- [ ] 5.3.0_en
- [ ] 5.2.1_en

## Issue Links
* #1439

## ChangeLog
- [ ] required

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please write translate issue, and close this.

**Comment by sasakitsy** [comment]
Translating in #2502 .
And close this issue.
