### ISSUE TITLE
In Spring Security 4.1, AntPathRequestMatcher is case sensitive

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2428]
## Description
Spring Security 4.1からAntPathRequestMatcherのデフォルトがcase sensitiveになった。
https://github.com/spring-projects/spring-security/issues/3831

Spring Securityの<sec:intercept-url pattern>で設定するパスと、Spring MVCの@RequestMappingで設定するパスが大文字小文字まで合っていないと、認可をすり抜けるなどの問題を引き起こす可能性がある。
特に5.3.0より前のバージョンから5.3.0へバージョンアップした場合に問題が起きやすいと思われる。
※Spring MVCは以前からcase sensitive

## Possible Solutions
パス設定に関する注意喚起をガイドラインへ記載する。

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
 - [x] 5.3.0.RELEASE

## Issue Links
　* http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/Authorization.html#access-policy-designate-web-resource

## ChangeLog
 - [x] Yes

**Comment by kazuki43zoo** [comment]
@sasakitsy 

Please create translation issue!

**Comment by sasakitsy** [comment]
Translating in #2500 .
So, close this issue.
