### ISSUE TITLE
Translate #1775 (MyBatis 3.4よりJDBC4.0実装のBLOB/CLOB用のTypeHandlerが追加される)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2429]
## Description
Please translate a modification #1775 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2386/files

## Fix Version/s
- [x]  5.3.0_en

## ChangeLog
- [x]  5.3.0_en

**Comment by asaharas** [comment]
change log is included in #2587
