### ISSUE TITLE
Translate #2260 (URL constraint description is misleading)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2433]
## Description
Please translate a modification #2260 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2376/files

## Fix Version/s
- [x]  5.3.0_en
- [x]  5.2.1_en

## ChangeLog
- [x]  5.3.0_en
- [x]  5.2.1_en

**Comment by asaharas** [comment]
change log (5.3.0) is included #2587 
change log (5.2.1) is included #2599

**Comment by asaharas** [comment]
5.3.0_en is fixed (#2580)

**Comment by asaharas** [comment]
5.2.1_en is fixed (#2655
