### ISSUE TITLE
Translate #2401 (Support for "HTTP Public Key Pinning (HPKP)")

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2435]
## Description
Please translate a modification #2401 

Modifications refer to 

* https://github.com/terasolunaorg/guideline/pull/2419/files
* https://github.com/terasolunaorg/guideline/pull/2493/files

## Fix Version/s
- [x]  5.3.0_en

## ChangeLog
- [x]  5.3.0_en

**Comment by kazuki43zoo** [comment]
I've added target pull-request.

* https://github.com/terasolunaorg/guideline/pull/2493/files

**Comment by asaharas** [comment]
one pull request(#2411) is missed I think.

**Comment by asaharas** [comment]
#2624 is including #2411

**Comment by asaharas** [comment]
When #2624 is closed, this issue close.
