### ISSUE TITLE
Minor typos in SpringSecurity.rst

### ISSUE THREAD

**Issue by kmiya** [terasolunaorg/guideline#2437]
## Description
There are some typos in `SpringSecurity.rst`.
<http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/SpringSecurity.html>

### 1
<http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/SpringSecurity.html#id8>

> Javaのメソッドに対して認可機能を適用する際にAspectJの機能を使用する際に必要となるコンポーネントが格納されています。

should be

> Javaのメソッドに対して認可機能を適用する際にAspectJの機能を使用する際に必要となるコンポーネントが格納**されている**。

and the following suggestion would be more natural:

> AspectJを使用してJavaのメソッドに認可機能を適用する際、必要となるコンポーネントが格納されている。

### 2
<http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/SpringSecurity.html#id15>

> 「1つのIDで複数のサイトにログインできるようする」

should be

> 「1つのIDで複数のサイトにログインできるよう**に**する」

### 3
-   <http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/SpringSecurity.html#springsecurityprocess>
-   <http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/SpringSecurity.html#httpfirewall>

There are two `ファイアフォール機能`, which should be `ファイアウォール機能`.

### 4
~~<http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/SpringSecurity.html>~~

~~Should use either `ユーザ` or `ユーザー`, but not both.~~
"inconsistent spelling" is handled by #2828

### 5
<http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/SpringSecurity.html#bean>
> 詳細は フォーム認証 を参照されたい
> 詳細は セッション管理 を参照されたい

should add `。' as follows:

> 詳細は フォーム認証 を参照されたい。
> 詳細は セッション管理 を参照されたい。

## Affects Version/s
* 5.2.0.RELEASE
* 5.1.1.RELEASE

## Fix Version/s
- [x] 5.4.0
- [x] 5.3.1

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by btkamatayst** [comment]
This issue affects Japanese ver only.
This issue was fixed by #2645 except 4(`ユーザ` or `ユーザー`).
and 4 is handled by #2828.
(research target : 5.4.0 and 5.3.1)

**Comment by btsatouhrzzp** [comment]
マージが完了したため本issueをクローズします。
