### ISSUE TITLE
Update new OSS stacks for 5.3.0 and 1.0.6

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2441]
## Description
OSS stacks in the Guidelines is before version.

## Possible Solutions
Modify new OSS stacks version to Guide.

## Affects Version/s
- 5.3.0.RELEASE
- 1.0.6.RELEASE

## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en
- [x] 1.0.6_ja
- ~~1.0.6_en~~

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/643
* https://github.com/terasolunaorg/terasoluna-gfw/issues/645
* https://github.com/terasolunaorg/terasoluna-gfw/issues/624
 
## ChangeLog
- [ ] required

**Comment by btyoshikawaa** [comment]
@bturamatuyu 
Please PR for version 1.0.x .

**Comment by kazuki43zoo** [comment]
@sasakitsy 

Please create translation issue.

**Comment by sasakitsy** [comment]
Translate in #2535 
So, close this issue.
