### ISSUE TITLE
Check broken or old link and update for 2017 Winter

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2453]
## Description
リンク切れや古い情報を参照しているリンクがないか調査して、必要であれば更新を行う。

## Affects Version/s
* 5.3.0.RELEASE
* 5.2.1.RELEASE
* 1.0.6.RELEASE

## Fix Version/s
 - [x] 5.3.0_ja
 - [x] 5.3.0_en
 - [x] 5.2.1_ja
 - [x] 5.2.1_en
 - [x] 1.0.6_ja
 - [x] 1.0.6_en

## Issue Links
* #2052 

## ChangeLog
 Not required.

**Comment by kazuki43zoo** [comment]
@sasakitsy 

please assign.

**Comment by btfurukawatkr** [comment]
* fix for 5.3.0_en was done in #2548 
https://github.com/terasolunaorg/guideline/pull/2548/files#diff-279b6f44d6b1c76f5ca6095efdc47bf1L1662

* fix for 5.2.x_en was done in #2570 
https://github.com/terasolunaorg/guideline/pull/2570/files#diff-279b6f44d6b1c76f5ca6095efdc47bf1L1615

**Comment by btkukinom** [comment]
* fix for 1.0.6 was done in #2574
  * https://github.com/terasolunaorg/guideline/pull/2574/files#diff-a7ec67cbcd2dd034781c31de8fca507cL42
  * https://github.com/terasolunaorg/guideline/pull/2574/files#diff-570a2658722f41945dfaf6b3d5da19f1L164


* fix for 1.0.6_en was done in #2573
  * https://github.com/terasolunaorg/guideline/pull/2573/files#diff-4c645fef4777f14c97c8cc6c57637989L177
  * https://github.com/terasolunaorg/guideline/pull/2573/files#diff-3c116441e16c8c0ff81d0ddb295a8ae1L42
  * https://github.com/terasolunaorg/guideline/pull/2573/files#diff-f41003de77acc70b43eda8a35566dc2bL164
  * https://github.com/terasolunaorg/guideline/pull/2573/files#diff-51669988ce2ddf1ee4ebcd1c7a3370c2L118
