### ISSUE TITLE
Translate #2368 (@ExceptionHandler is able to process Error thrown from handler method since Spring MVC 4.3)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2461]
## Description
Please translate a modification #2368  

Modifications refer to 

* https://github.com/terasolunaorg/guideline/pull/2409/files
* https://github.com/terasolunaorg/guideline/pull/2475/files

## Fix Version/s
- [x]  5.3.0_en

## ChangeLog
- [x]  5.3.0_en

**Comment by kazuki43zoo** [comment]
I've added #2475 as translation target pull-request.
