### ISSUE TITLE
Fixing incorrect description that default value of "aggressiveLazyLoading" is false

### ISSUE THREAD

**Issue by bturamatuyu** [terasolunaorg/guideline#2470]
## Description
aggressiveLazyLoadingのデフォルト値は**true**だが、aggressiveLazyLoadingのデフォルト値は**false**だと記載されてしまっている。

該当箇所：
「6.2.4.5.2.3. Lazy Loadの実行タイミングを制御するための設定」の章のwarning内の下記記述
>上記例では、”Lazy Load”対象のプロパティであるcategoriesプロパティにアクセスしていないが、 Item#codeプロパティにアクセスした際に、”Lazy Load”が実行される。
>「false」（デフォルト）の場合、上記のケースでは”Lazy Load”は実行されない。

## Possible Solutions
下記文の「デフォルト」を削除する。
> 「false」（デフォルト）の場合、上記のケースでは”Lazy Load”は実行されない。

↓

> 「false」の場合、上記のケースでは”Lazy Load”は実行されない。

## Affects Version/s
以下のバージョン以前が該当。
* 5.2.X.RELEASE

## Fix Version/s
- [x] 5.2.1

## Issue Links
* #2364 

## ChangeLog
No

**Comment by kazuki43zoo** [comment]
@bturamatuyu 

優先度は低くてよいので対応お願いします。
