### ISSUE TITLE
Translate #2140 (Settings for mybatis-typehandlers-jsr310 is not enough)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2479]
## Description
Please translate a modification #2140 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2142/files

## Fix Version/s
- [x]  5.3.0_en
- [x]  5.2.1_en

## ChangeLog
- [x]  5.3.0_en
- [x]  5.2.1_en

**Comment by asaharas** [comment]
the English target file have been already changed

**Comment by asaharas** [comment]
ChangeLog is not existing in Japanese file.
so, close this issue.
