### ISSUE TITLE
Misdescription in chapter of downloading Excel file

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2480]
## Description
4.10.2.2. Excelファイルのダウンロード - 4.10.2.2.1. カスタムViewの実装
http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/FileDownload.html#id4
記述誤り、および不明な点がある

* **AbstractXlsxViewを継承したクラスの実装例**
`SampleExcelView#getCell`メソッドや`setText`メソッドを使っているが、実装（またはそれを省略）している記述がないため、実装例をコピーして使おうとすると動かない。
```java
@Component  // (1)
public class SampleExcelView extends AbstractXlsxView {  // (2)

    @Override
    protected void buildExcelDocument(Map<String, Object> model,
            Workbook workbook, HttpServletRequest request,
            HttpServletResponse response) throws Exception {  // (3)
        Sheet sheet;
        Cell cell;

        sheet = workbook.createSheet("Spring");
        sheet.setDefaultColumnWidth(12);

        // write a text at A1
        cell = getCell(sheet, 0, 0);
        setText(cell, "Spring-Excel test");

        cell = getCell(sheet, 2, 0);
        setText(cell, (Date) model.get("serverTime")).toString());
    }
}
```

* **Mavenのpom.xmlに POIの定義を追加する**
`exclusions`タグのある位置がおかしい。Mavenビルド時にエラーとなる。
```xml
<dependencies>
    <!-- omitted -->
    <dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi-ooxml</artifactId>
    </dependency>
    <exclusions>
        <exclusion>
            <groupId>stax</groupId>
            <artifactId>stax-api</artifactId>
        </exclusion>
    </exclusions>
</dependencies>
```

## Possible Solutions
* **AbstractXlsxViewを継承したクラスの実装例**
`// omitted`とか書けば、ドキュメントとしての整合性は保てるが、
本質的には、実際にセルを取得してテキストをセットする実装例を書いたほうが良い。

* **Mavenのpom.xmlに POIの定義を追加する**
`exclusions`タグを`dependency`タグの中に移動する。

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1

## Issue Links
N/A

## ChangeLog
not required.

**Comment by btyoshikawaa** [comment]
@sasakitsy 
記述が誤っているので、できれば5.3.0&5.2.1で対応できると良いです。

**Comment by kazuki43zoo** [comment]
@bttamuratsh 

これ対応してほしいです。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please write translation issue, and close this.

**Comment by asaharas** [comment]
I have created translation issue #2711 
so you can close this issue.

**Comment by itouyun** [comment]
I have confirmed that. I'll close this issue.
