### ISSUE TITLE
Translate #2375 (Should be enable the rollbackOnCommitFailure option)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2482]
## Description
Please translate a modification #2375 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2440/files

## Fix Version/s
- [x]  5.3.0_en
- [x]  5.2.1_en

## ChangeLog
- [x]  5.3.0_en
- [x]  5.2.1_en

**Comment by asaharas** [comment]
5.3.0_en is fixed (#2595)

**Comment by asaharas** [comment]
5.2.1_en is fixed (#2661)
