### ISSUE TITLE
Fix wrong word in SOAP Web Service page in English guideline

### ISSUE THREAD

**Issue by bttamuratsh** [terasolunaorg/guideline#2490]
## Description
In SOAP Web Service page, section 5.3.1.5. URL to be published as Web service, context "route" is written as コンテキストルート in English.  I think context "root" is correct.

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1

## Issue Links
N/A

## ChangeLog
No

**Comment by kazuki43zoo** [comment]
@bttamuratsh 

Please fix this!
