### ISSUE TITLE
Investigation and correction of description on nexus accompanying Maven central's transition

### ISSUE THREAD

**Issue by bturamatuyu** [terasolunaorg/guideline#2496]
## Description
下記の章などでnexusに関する記述があり、Maven centralへの移行に伴う対応(リンク更新など)が必要かどうか調査・修正を実施
* nexusに関する章
http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Appendix/Nexus.html

## Possible Solutions
- [x] 1. nexusに関する記述がある対象を調査
- [x] 2. 手順1で調査した内容にMaven centralへの移行に伴う対応が必要ならば修正

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
* 5.3.0.RELEASE

## Issue Links
* #2444 

## ChangeLog
- [x] Required

**Comment by bturamatuyu** [comment]
nexusに関する記述がある対象を調査しました。
・調査方法
　[調査1]
　nexusの章(11. Appendix(Know How) → NEXUSによるMavenリポジトリの管理)を読み、
　修正対象がないかチェックします。
　[調査2]
　下記のnexus関連キーワードでGREP検索を行い、修正対象がないかチェックします。
　nexus
　repo.terasoluna
　archetypecatalog
　settings.xml

・調査結果
　[調査1]
　「11.1.3 Add TERASOLUNA Server Framework for Java (5.x) repository」は除去する方向で修正したほうがよいです。
　[調査2]
　修正対象はありませんでした。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please write issue for translation, and close this.

**Comment by sasakitsy** [comment]
Translating in #2581 , so close this issue.
