### ISSUE TITLE
Translate #2428 (In Spring Security 4.1, AntPathRequestMatcher is case sensitive)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2500]
## Description
Please translate a modification #2428  

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2456/files

## Fix Version/s
- [x]  5.3.0_en

## ChangeLog
- [x]  5.3.0_en

**Comment by asaharas** [comment]
I couldn't find previous translation issue about #1976 
previous issue has to be translated

**Comment by asaharas** [comment]
5.3.0_en is fixed in #2603
