### ISSUE TITLE
Translate #2427 (Writing clearly when internationalization is not applicable)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2502]
## Description
Please translate a modification #2427 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2459/files

## Fix Version/s
- [x]  5.3.0_en
- [x]  5.2.1_en

## ChangeLog
- [x]  5.3.0_en
- [x]  5.2.1_en

**Comment by asaharas** [comment]
5.3.0_en is fixed (#2601)

**Comment by asaharas** [comment]
5.2.1_en is fixed (#2662)
