### ISSUE TITLE
[5.3.x]Due to the upgrading of dependency library version,misdescription has occured in ApplicationLayer.rst.

### ISSUE THREAD

**Issue by bturamatuyu** [terasolunaorg/guideline#2505]
## Description
TERASOLUNA Server Framework for Javaとその依存ライブラリバージョンアップに伴い、
下記の対象の記述に誤りが発生している。

ApplicationLayer.rst#L2401

## Possible Solutions
* ApplicationLayer.rst#L2401

**引用**
```
.. warning::
    \ ``@DateTimeFormat`` \ の pattern でフォーマットを指定し、プロパティとして  JSR-310 Date and Time APIが提供する\ ``java.time.LocalDate`` \を使用した場合、STRICTにチェックがされない
   (\ ``"20150229"`` \を変換した場合、本来は型ミスマッチエラーとなるはずが、\ ``2015年2月28日`` \ がバインドされる)。
   Spring Framework  4.3で仕様が改善されて発生しなくなるが、TERASOLUNA Server Framework for Java (5.x)では Spring Framework 4.2 を使用しているので影響を受ける。
   本事象の詳細は「`@DateTimeFormat's JSR-310 formatter is not strict in case of pattern <https://jira.spring.io/browse/SPR-13567>`_\」を参照されたい。
```
**修正方法**
Spring Framework 4.3になったため、上記のwarningを除去する。

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
- [x] 5.3.0.RELEASE JP
- [ ] 5.3.0.RELEASE EN

## Issue Links
* PR #2460 

## ChangeLog
- [x] required

**Comment by kazuki43zoo** [comment]
@bturamatuyu 

``@DateTimeFormat`の件ですが、実装に動かして問題解決しているを確認できてますか？
もししてないなら、ブランクＰＪベースに簡単なアプリつくって確認してほしいです。

**Comment by bturamatuyu** [comment]
@kazuki43zoo san
> @DateTimeFormat の件ですが、実装に動かして問題解決しているを確認できてますか？
>もししてないなら、ブランクＰＪベースに簡単なアプリつくって確認してほしいです。

実際に動かして確認しておりませんでした。
そこで、ブランクPJを作成し、5.2.RELEASE版と5.3.RC5版で、`java.time.LocalDate `の挙動を確認しました。
結果としては、確かに5.2.RELEASE版で起きていた問題が、5.3.RC5版でフィックスされていることを確認しました。

**Comment by btyoshikawaa** [comment]
@bturamatuyu 
* Authorization.rst#L358 について
修正方法「Spring Framework 4.2.xの記述をSpring Framework 4.3.xに修正する。」だけだと、以下のようになり、一文目と二文目で明らかに矛盾が起こります。
```text
    Spring Framework 4.3.1 以降、Spring Security 4.1.1 以降では \ `MvcRequestMatcher` \ を使用することで本事象は解消されるが、
    TERASOLUNA Server Framework for Java (5.3.x)が使用しているSpring Framework 4.3.x では、Spring MVCで \ `trimTokens` \ プロパティに \ `false` \ を設定した \ `org.springframework.util.AntPathMatcher` \ を使用する必要がある。
```
以下のように、ちょっと記述自体見直す必要あり。
```text
    以下のいずれかを適用することにより、本事象を解消することができる。
    * Spring MVCで \ `trimTokens` \ プロパティに \ `false` \ を設定した \ `org.springframework.util.AntPathMatcher` \ を使用する。
    * \ `MvcRequestMatcher` \ を使用する。（Spring Framework 4.3.1 以降、Spring Security 4.1.1 以降で使用可能）
```
なお、#2373 のとおり、`MvcRequestMatcher`の適用は未検証のため、こちらはいったん削除してしまうという選択肢もあり。

**Comment by bturamatuyu** [comment]
@btyoshikawaa san
Authorization.rst#L358対応に関しては、別途issueを立てました。
そのため、本issueのAuthorization.rst#L358対応は取り消します。
#2525

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create issue for translation, and close this.

**Comment by sasakitsy** [comment]
translate in #2543 
so, close this issue.
