### ISSUE TITLE
minor typos in flow images

### ISSUE THREAD

**Issue by btkouei** [terasolunaorg/guideline#2513]
## Description
minor typos in flow images. 
defile --> define
e.g. 
each image in the following chapter
http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html?highlight=logger#controller

## Possible Solutions
defile --> define

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0
- [x] 5.3.1

## Issue Links
* #XXX

## ChangeLog
(To be written later by project member)

**Comment by btsatouhrzzp** [comment]
#2645 で修正されていることを確認。本Issueはクローズします。
