### ISSUE TITLE
「9.9.3.7.4. コード解説」でポイントとなる@RequestMappingがomittedされています。

### ISSUE THREAD

**Issue by 5zm** [terasolunaorg/guideline#2515]
## Description

* 9.9.3.7.4. コード解説
  * パスワード再発行のための認証情報の有効期限の検査
    * Controllerの実装

ポイントとなる@RequestMappingがomittedされています。

``` java
@Controller
@RequestMapping("/reissue")
public class PasswordReissueController {

    @Inject
    PasswordReissueService passwordReissueService;

    // omitted

    public String showPasswordResetForm(PasswordResetForm form, Model model,
            @RequestParam("token") String token) { // (1)

        PasswordReissueInfo info = passwordReissueService.findOne(token); // (3)

        form.setUsername(info.getUsername());
        form.setToken(token);
        model.addAttribute("passwordResetForm", form);
        return "passwordreissue/passwordResetForm";
    }

    // omitted

}

```

 * パスワード再発行画面のURLのメール送付
     以下の箇所ですが、このURLが重要なので、出力されるURLの例を記載した方が次のControllerの実装が分かりやすいかと思います。

``` java
        UriComponentsBuilder uriBuilder = UriComponentsBuilder.fromUriString(baseUrl);
        uriBuilder.pathSegment("reissue").pathSegment("resetpassword")
                .queryParam("form").queryParam("token", info.getToken());  // (2)
        String passwordResetUrl = uriBuilder.build().encode().toUriString();
```

```
(1)で取得した値と、生成したパスワード再発行用の認証情報に含まれるトークンを使用して、ユーザに配布するパスワード再発行画面のURLを作成する。

URLの作成には org.springframework.web.util.UriComponentsBuilder を利用する。UriComponentsBuilder については、ハイパーメディアリンクの実装 の中で説明されている。
```

例）　http://localhost:8080/app/reissue/resetpassword?form&token=512f1a33-da20-4b9f-9e26-8961e9071618

## Possible Solutions

* 正しい@RequestMapping を追加する
* パスワード再発行画面のURLの例を追加する

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] mastar
- [x] 5.3.1
- [ ] 5.2.2
- And English Ver. (Shoud create another issue)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@itouyun @takahashihrzg 
Please create issue for translation, and close this.

@btkitsunedukam 
Thanks for your work.

**Comment by itouyun** [comment]
@btmatsumotoms 
Please backport 5.2.x branch and asign member.

**Comment by itouyun** [comment]
I eat my words. You don't need to backport 5.2.x branch.
Now, maintenance branch is 5.3.x.
