### ISSUE TITLE
Translate #2177 (Improve the description of secure random workaround)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2516]
## Description
Please translate a modification #2177 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2402/files

## Fix Version/s
- [x]  5.3.0_en
- [x]  5.2.1_en

## ChangeLog
- [x]  5.3.0_en
- [x]  5.2.1_en

**Comment by asaharas** [comment]
5.3.0_en is fixed (#2604)

**Comment by asaharas** [comment]
@btkubotamo 
please resolve conflict

**Comment by asaharas** [comment]
5.2.1_en is fixed in #2663
