### ISSUE TITLE
Translate #2002 (Wrong description in description for ValidationMessages.properties (add description))

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2517]
## Description
Please translate a modification #2002 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2218/files

## Fix Version/s
- [x]  5.3.0_en
- [x]  5.2.1_en

## ChangeLog
- [x]  5.3.0_en
- [x]  5.2.1_en

**Comment by asaharas** [comment]
5.3.0_en is fixed (#2608)

**Comment by asaharas** [comment]
@btkubotamo 
please resolve conflict

**Comment by asaharas** [comment]
5.2.1_en is fixed in #2664
