### ISSUE TITLE
Build fails with "mvn archetype:generate"

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2523]
## Description
In maven-archetype-plugin:3.0.0, the behavior of the "archetypeCatalog" parameter has changed and it is no longer possible to directly specify the URL.
Therefore, build fails because it can not find archetype-catalog.xml.

## Possible Solutions
* Add a "repository" to settings.xml

    Add a repository with "http://repo.terasoluna.org/nexus/content/repositories/terasoluna-gfw-releases/" specified.

    http://maven.apache.org/ref/3.3.9/maven-settings/settings.html#class_repository

or

* Explicitly use maven-archetype-plugin:2.4

    In version 2.4, the archetypeCatalog parameter works as expected.
    ```console
    mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate
    ```
    

## Affects Version/s
* before 5.2.0.RELEASE
* before 1.0.5.RELEASE

## Fix Version/s
MUST
- [x] 5.2.1.RELEASE_jp
- [ ] 5.2.1.RELEASE_en
- [x] 1.0.6.RELEASE_jp
- [ ] 1.0.6.RELEASE_en

Low Pri.
- [x] 5.1.2.RELEASE
- [x] 5.0.3.RELEASE

## Issue Links
* https://issues.apache.org/jira/browse/ARCHETYPE-519

## ChangeLog
 - [x] required

**Comment by bthayashidi** [comment]
一般的にsettings.xmlを編集することはハードルが高く、実際に試してみようと思う人を遠ざけてしまう可能性が高い。
「Explicitly use maven-archetype-plugin:2.4」を採用する。

**Comment by kazuki43zoo** [comment]
@bturamatuyu 
please backport.

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create issue for translation, after that close this.

**Comment by btyoshikawaa** [comment]
@bturamatuyu 
Sorry, you need correct this.
https://github.com/terasolunaorg/guideline/pull/2539/files#diff-1bf077ae089f3e412d9590765c13686fR168
https://github.com/terasolunaorg/guideline/pull/2539/files#diff-1bf077ae089f3e412d9590765c13686fR176

**Comment by btyoshikawaa** [comment]
Japanese version is completed.

**Comment by sasakitsy** [comment]
translate in #2542 
so, close this issue.
