### ISSUE TITLE
Example of escaping the output value with the f: js () function is described Inappropriately

### ISSUE THREAD

**Issue by btkigamim** [terasolunaorg/guideline#2531]
## Description
The following result is described as the result of escaping, but when you actually run the script, the escaped script is executed.
```
<script  type="text/javascript">
    var aaa = '<script>\x3c\/script\x3e\x3cscript\x3ealert(\'XSS Attack!\');\x3c\/script\x3e<\/script>';
    document.write(aaa);
</script>
```
## Possible Solutions
Fix to an example that does not use document.write.

- Before
```
<html>
  <script  type="text/javascript">
      var aaa = '<script>${warnCode}<\/script>';
      document.write(aaa);
  </script>
<html>
```
- After
```
<html>
  <script  type="text/javascript">
      ${warnCode};
  </script>
<html>
```

## Final Solution
 - 修正箇所
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/XSS.html#id3

		

JavaScript Escapingのサンプルコードの修正

XSS問題が発生する例
`var aaa = '<script>${warnCode}<\/script>';`　->　`var aaa='${warnCode}';`
` document.write(aaa)`  ->  `alert(aaa) `

f:js()の使用例
`var message = '<script>${f:js(message)}<\/script>';` -> `var aaa = '${f:js(warnCode)}';
`
`<!-- omitted -->`  ->  `alert(aaa) `（alert(aaa)のみの記載を省略する必要はないと判断）

 攻撃用の値
`<script></script><script>alert('XSS Attack!');</script><\/script>` 
->` ';alert('XSS Attack!');aaa='message
`

にそれぞれ修正(それに伴い出力結果も修正)
出力方法をalertへ変更することにより、「出力値をf:js()関数でエスケープする例」にalertの画像(Picture - Escape Result)を追加する。 

document.write()使用時の脆弱性をWarningとして追記。

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- [x] 5.2.2_ja (5.2.x)
- [x] 5.1.2_ja (5.1.x)
- [x] 5.0.3_ja (5.0.x)
- [x] 1.0.7_ja (1.0.x)

## Change log(should be updated at the same time)
- Required

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by ikeyat** [comment]
Are you mentioning to this part?
http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/ja/Security/XSS.html#id3
Please let me know which browser you use to reproduce.

Anyway the "After" solution makes no sense. We need to modify the example that looks real.

**Comment by yoshikawaa** [comment]
@ikeyat @btkigamim 
I confirmed to reappears the problem at the following code with IE 11 amd Firefox 54.0.1.
```html
<script  type="text/javascript">
    var aaa = '<script>\x3c\/script\x3e\x3cscript\x3ealert(\'XSS Attack!\');\x3c\/script\x3e<\/script>';
    document.write(aaa);
</script>
```
----

And I think the following code example reflects the intention correctly.
* input
```java
model.addAttribute("warnCode", "</script><script>alert('XSS Attack!');</script>");
```
* jsp
```jsp
<script  type="text/javascript">
    var aaa = '${f:js(warnCode)}';
    document.write(aaa);
</script>
```
* output html
```html
<script  type="text/javascript">
    var aaa = '\x3c\/script\x3e\x3cscript\x3ealert(\'XSS Attack!\');\x3c\/script\x3e';
    document.write(aaa);
</script>
```
But the problem reappears in the above code.
This means that `${f: js()}` can not prevent the above problem.
I think that when need to `document.write()` should check that the input value does not contain a `script` tag.

**Comment by NaozumiTaromaru** [comment]
${f:js()}は、JavaScriptの文字列リテラルに値を埋め込む際のエスケープをするものです。
(シングルクオートが閉じられるのを防いだり…)

単に
```
var aaa = '${message}';
```
では
messageに
「';alert('XSS Attack!');aaa='message1」
のような値を入力されると、
出力結果は
```
var aaa = '';alert('XSS Attack!');aaa='message1';
```
という具合になり、任意のスクリプトを投入されますが、
```
var aaa = '${f:js(message)}';
```
とすれば、
出力結果は
```
var aaa = '\';alert(\'XSS Attack!\');aaa=\'message1';
```
つまり、JavaScriptの変数aaaに、
messageの値「';alert('XSS Attack!');aaa='message1」が代入されるコードが出力されます。

これが、${f:js()}がやってくれることです。

なので、例としては、

ダメな例：
```
<html>
  <script  type="text/javascript">
      var aaa = '${message}';
      alert(aaa);
  </script>
<html>
```

攻撃用のmessageの値：
```
';alert('XSS Attack!');aaa='message1
```

よい例：
```
<html>
  <script  type="text/javascript">
      var aaa = '${f:js(message)}';
      alert(aaa);
  </script>
<html>
```

が妥当です。

攻撃用の値は変わりますが、ダメな例として、
```
<html>
  <script  type="text/javascript">
      alert('${message}');
  </script>
<html>
```
というのもあります。

ちなみに、
```
var aaa = '${f:js(warnCode)}';
document.write(aaa);
```
は、warnCodeの値をそのままJavaScriptの変数aaaに投入し、
＃そのまま変数aaaに入るよう、${f:js()}がある意味適切にエスケープしてくれる。
JavaScriptで変数aaaの内容をHTMLのソースとして出力するという内容なので、
warnCodeにHTMLソースを投入すればそれをブラウザにHTMLソースとして解釈させるという、
攻撃者に優しいコードです。
＃JavaScript用のエスケープを攻撃者が行わなくてよいあたりが、攻撃者に優しい。

**Comment by kazuki43zoo** [comment]
とりあえず、例が意味不明（＝実際こんなことやるやつはいない・・・）なコードですね。実際にやってしまいそうなコード例を題材に説明した方がよいと思います。

**Comment by yoshikawaa** [comment]
> 本例は、あくまで参考例として載せているだけなので、以下のような実装は、決して行わないこと。

と前置きはしているようですが、実効的でないコード例なのは良くないです。
全バージョンこのコード例っぽいので、修正したほうが良さそうですね。

**Comment by NaozumiTaromaru** [comment]
@kazuki43zoo
> とりあえず、例が意味不明（＝実際こんなことやるやつはいない・・・）なコードですね。実際にやってしまいそうなコード例を題材に説明した方がよいと思います。

コメントのタイミングが微妙だったので確認。
ガイドラインの(修正前の)このコード
```
<html>
  <script  type="text/javascript">
      var aaa = '<script>${warnCode}<\/script>';
      document.write(aaa);
  </script>
<html>
```
もしくは、Possible SolutionsのAfter
```
<html>
  <script  type="text/javascript">
      ${warnCode};
  </script>
<html>
```
に対するコメントですよね？

**Comment by kazuki43zoo** [comment]
@NaozumiTaromaru 

> ガイドラインの(修正前の)このコード
> もしくは、Possible SolutionsのAfter
> に対するコメントですよね？

yesです！

**Comment by yoshikawaa** [comment]
@btnonakasts 
`f:js()`を使用する例を`document.write()`から`alert()`に変更するのは良いと思いますが、
`document.write()`する場合の注意喚起はしなくて大丈夫ですか？

ガイドラインがしばらく間違えてたくらいなので、間違えて使ってしてしまう人もいるかも。

**Comment by btnonakasts** [comment]
@yoshikawaa
ご指摘の通り、`document.write()`を使用する際にも注意が必要と思われますので、Warningとして注意喚起するようConclusion Solutionに加筆致しました。

**Comment by NaozumiTaromaru** [comment]
```
「document.write()を使用する場合も同様にXSSの脆弱性が生じるため、注意すること。」
<script  type="text/javascript">
     var aaa='${warnCode}';
    document.write(aaa);
</script>
```
これは、
var aaa='${warnCode}';
を
var aaa='${f:js(warnCode)}';
にしてもXSSの脆弱性が残るパターンです。
warnCodeに「<script>～</script>」まで投入すればスクリプトが動作します。

ついでに言うと、
```
<script  type="text/javascript">
     var aaa='${warnCode}';
    document.write(aaa);
</script>
```
(ここにwarnCodeを出力)
のようなことがしたい場合は、
JSPなんだから、
```
${f:h(warnCode)}
```
って書けばいいんですよ。

あえてこれをdocument.writeで出力したい場合は、
・HTMLエスケープ用のJavaScript関数を用意して、document.writeの引数(aaa)の内容をエスケープする
・(全エスケープをサーバでやるなら、)warnCodeをHTMLエスケープしてからJavaScriptの文字列リテラル用のエスケープを行う(イベントハンドラ属性内のJavaScriptの文字列リテラルのエスケープに使うf:hjs()とはエスケープ順が逆なので要注意)
という方法もあります。

**Comment by btkamiyae** [comment]
@yoshikawaa @NaozumiTaromaru 
document.write()使用の注意喚起をFinal Solutionにて修正いたしました。

**Comment by NaozumiTaromaru** [comment]
> スクリプトタグが含まれる値をf:js()でエスケープさせて出力する際、document.write()を使用すると、
> ブラウザにHTMLソースとして解釈させるよう出力するので、XSSの脆弱性が生じる。 

スクリプトタグが含まれる値(入力値をエスケープしていない)をもらってからエスケープしようとしている時点で負け決定です。(機能させたいスクリプトタグが機能しなくなるか、入力値に不正に混入したスクリプトタグも機能するようになるか。どっちに転んでも負け。)
逆に、スクリプトタグが含まれる値というのが、入力値をHTMLエスケープ済みのものであるなら、XSSの脆弱性はありません。

といいますか、ダメな例がないと、どこでf:js()を使おうとした場合にダメなのかが伝わらないと思いました。

> document.write()を使用して出力させたい場合は、HTML特殊文字をエスケープするf:h()を使用することが望ましい。

これだと、
document.write('${f:h(xxx)}');
って書いてしまいそうです。
後半の、望ましいといっている方法は、document.write()を使用しない方法ですよね？
そのことが文面から伝わってきません。

> あえてf:js()を使用し、document.write()で出力したい場合は、
> HTMLエスケープ用のJavaScript関数を用意して、document.write()の出力する値をエスケープする、

document.write()の引数をエスケープしてください。

**Comment by yoshikawaa** [comment]
@NaozumiTaromaru 
貴重なご指摘ありがとうございます。

@btkamiyae @btsatouhrzzp @itouyun 
もはやレビューになってきているので、PR出してコメントつけてもらったほうが良いと思います。
IssueのSolutionにはざっくりとした対応内容だけ書けば良いはずです。

**Comment by itouyun** [comment]
@yoshikawaa 
確かに、Final Solutionはあくまで対応方針の確定版であり、あまりに詳細すぎる内容はPRにおけるRvでコメントされていたほうが、コメント履歴等が残って、そっちの方がふさわしいですね。

@btkamiyae @btsatouhrzzp
既に方針は固まっているので、日本語や表現方法はPRしてから推敲するようにしましょう。

**Comment by itouyun** [comment]
@btsatouhrzzp 
Please make English Translation issue.

**Comment by btsatouhrzzp** [comment]
I created #2951 issue. This issue is closed.

**Comment by making** [comment]
サンプルのJavaScriptコードがそもそも脆弱という話と、エスケープの話がごっちゃになっているような？ユーザーが入力した値を`document.write`とか`Element.innerHTML`で出力するとXSSになるのは、その通りで、記憶が確かならば`f:js`は`Element.innerText`などJavaScriptはXSSじゃない前提で、サーバーサイドで値を埋め込んだ時にXSSになるのを防ぎたかったはず。
サンプルコードが`document.write`になっちゃってるのは、サンプルを`alert`にするとXSS攻撃例としての`alert`なのか、元のコードの`alert`なのかわかりづらいからで、適当に選んじゃった気がする。

想定していたケースは、

``` java
@GetMapping("hoge")
public String hoge(@RequestParm String name, Model model) {
  model.addAttribute("name", name);
  return "hoge";
}
```

``` html
<p>Hello <span id="name"></span>!</p>
```

``` js
var name = document.getElementById('name');
name.innerText = '$f:js(name)';
```

って感じコードで、
http://localhost:8080/hoge?name=<攻撃コード> で攻撃されるのを防ぎたかったはず。

**Comment by itouyun** [comment]
@making 
コメントありがとうございます。
ちょっと内部で検討いたします。ガイドラインで何を記述するべきなのか、ガイドを読むシステム開発者として、どんな情報が提供されているとXSSの発生しないシステムを構築できるようになるか、などの観点で見つめなおしてみます。

**Comment by NaozumiTaromaru** [comment]
まずは、DOM Based XSSの脆弱性のないJavaScript例の例が、```alert```と```innerText```、どちらがよいか…
元のコードが```alert```の場合にXSS攻撃による```alert```なのか元のコードの```alert```なのかが分かりづらい(？)という点は、画像の工夫で問題なくなっていると思います。
また、サーバからHTMLを返す際に、```f:h```ではなく、あえて```innerText```を使うこともそうそうないかと。
ということで、元のコードは```alert```のままでよいと思います。

あとは、最後のWarningを、旧ガイドラインで踏んでいたdocument.write()にとどめるか、DOM Based XSSもきちんと説明するか、ですね。

ちなみに、現在XSSの種類は大きく分けると、2つではなく3つです。
 * Type1: Reflected XSS Attacks (←ガイドラインに既に書いてある)
 * Type2: Stored XSS Attacks (←ガイドラインに既に書いてある)
 * Type0: DOM Based XSS (←ガイドラインに書いていない)

([IPAテクニカルウォッチ「DOM Based XSS」に関するレポート～JavaScriptでHTMLを操作するアプリは要注意！～](https://www.ipa.go.jp/files/000024729.pdf)より)

**Comment by itouyun** [comment]
結局、ガイドラインの現状記述としては一貫はしているが、敢えて考えなければいけないポイントとしては、Type0のXSSについて、言及するかしないか、という観点ですかね。

とりあえず本issueではその議論はスコープ外としつつ、考えるとしたら別issueで、という感じですかね。
