### ISSUE TITLE
Check version for 2017 winter

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2532]
## Description
ガイドラインに直接記載されているバージョン情報等が2017winter向けに正しく更新されているか確認し、更新されていないようであれば更新する。

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0_ja
- [x] 5.3.0_en
- [x] 5.2.1_ja
- [x] 5.2.1_en
- [x] 1.0.6_ja
- [x] 1.0.6_en

#### additional check (low priority).
- [ ] 5.1.2_ja
- [ ] 5.1.2_en
- [ ] 5.0.3_ja
- [ ] 5.0.3_en

## Issue Links
* #2076 
* #2453 

## ChangeLog
N/A

**Comment by btyoshikawaa** [comment]
@bthondasui @bttakehirah 
Please check 5.2.x and 1.0.x to.

**Comment by yoshikawaa** [comment]
@sasakitsy 
日本語版と英語版の現状の差異により、当Issueでの対応にも以下の差異が出ています。

* source_en/Appendix/Nexus.rst 
英語のみ->英訳のリンク修正漏れ->このIssueで解決
* source_en/ArchitectureInDetail/DataAccessJpa.rst 
英語のみ->英訳のリンク修正漏れ->このIssueで解決
* source/ArchitectureInDetail/FileUpload.rst 
最後が日本語のみ-> #778 が英訳されていない（バックポートされていない）->**未解決**
* source/ArchitectureInDetail/REST.rst 
日本語のみ-> #374 が英訳されていない（バックポートされていない）->**未解決**
* source_en/Overview/ApplicationLayering.rst 
英語のみ->英訳のリンク修正漏れ->このIssueで解決

**Comment by yoshikawaa** [comment]
@sasakitsy 
The versions for 2017 winter release is completed.
If you want to close this, please new issue for low priority versions.

**Comment by sasakitsy** [comment]
New issue for low priority versions were created. (#2634)
So, close this issue.
