### ISSUE TITLE
Translate #2523 (Build fails with "mvn archetype:generate")

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2542]
## Description
Please translate a modification #2523 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2528/files

## Fix Version/s
- [ ]  5.2.1_en

## ChangeLog
- [ ]  5.2.1_en

**Comment by asaharas** [comment]
@neetapimpalnerkar 
please raise pull request into translation/5.2.1 branch

**Comment by asaharas** [comment]
5.2.1_en is fixed in #2668
