### ISSUE TITLE
Translate #2518 (Support Tomcat 8.5)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2564]
## Description
Please translate a modification #2518 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2533/files

## Fix Version/s
- [x]  5.3.0_en

## ChangeLog
- [x]  5.3.0_en

**Comment by asaharas** [comment]
#2547 (ChangeLog.rst) has to be translated!
