### ISSUE TITLE
Add change logs for 5.1.2

### ISSUE THREAD

**Issue by btkukinom** [terasolunaorg/guideline#2616]
## Description
Add changes log for 5.1.2 on ChangeLog.rst

## Fix Version/s
- [x] 5.1.2_ja
- [ ] 5.1.2_en

## Issue Links
N/A

## ChangeLog
(To be written later by project member)

**Comment by yoshikawaa** [comment]
@sasakitsy 
Please assign to translate this.

**Comment by btsatouhrzzp** [comment]
I created #2851 issue. This issue is closed.
