### ISSUE TITLE
Translate #2047 (modify inconsistent use of expressions in pom description)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2622]
## Description
Please translate a modification #2047 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2289/files

## Fix Version/s
- [x]  5.3.0_en
- [x]  5.2.1_en

## ChangeLog
- [x]  5.3.0_en
- [x]  5.2.1_en

**Comment by asaharas** [comment]
5.3.0_en is fixed in #2702

**Comment by asaharas** [comment]
5.2.1_en is fixed in #2703
