### ISSUE TITLE
Apply new double copyright notices.

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2628]
## Description
TERASOLUNA Development Guideline apply new copyright after 5.3.0.

* As is
`© Copyright 2013-2016, NTT DATA.`
* To be
`© Copyright 2013-2017, NTT DATA Corporation. © Copyright 2017, NTT Corporation.`

## Possible Solutions
* Change copyright in conf.py
  - As is
  `2013-2017, NTT DATA Corporation`
  - To be
   `© Copyright 2013-2017, NTT DATA Corporation. © Copyright 2017, NTT Corporation.`
* Change template of copyright in layout.html
  - As is
    ```python
      {%- if hasdoc('copyright') %}
        {% trans path=pathto('copyright'), copyright=copyright|e %}&copy; <a href="{{ path }}">Copyright</a> {{ copyright }}.{% endtrans %}
      {%- else %}
        {% trans copyright=copyright|e %}&copy; Copyright {{ copyright }}.{% endtrans %}
      {%- endif %}
    ```
  - To be
    ```python
      {% trans copyright=copyright|e %}{{ copyright }}{% endtrans %}
    ```

## Affects Version/s
* 5.3.0.RELEASE and later

## Fix Version/s
- [x] 5.3.0 ja
- [x] 5.3.0 en

## Issue Links
* #XXX

## ChangeLog
- not required

**Comment by yoshikawaa** [comment]
@btyanagawamg 
ざっくり、今回なぜこの方式を採用したか纏めておきました。

### Possible Solutionsの解説
----

#### Sphinxの仕様
* Sphinx設定ファイル（conf.py）の[`copyright`変数](http://www.sphinx-doc.org/ja/stable/config.html#confval-copyright)に`2008, Author Name`の形式で指定した値を、[Jinja](http://jinja.pocoo.org/)テンプレート（layout.html）の`@Copyright {{copyright}}.`に埋め込んで反映する。
* conf.pyで解釈される変数は仕様で決まっており、自由に定義はできない。

#### 今回の要件での問題点
  - 上記の仕組みに則ると、`@Copyright `が固定のためコピーライトは1つしか付与できない。

#### 対応策
  以下の二つが考えられるが、今回は前者で対応。
* **conf.pyの`copyright`変数に`@Copyright xxx`を2つセットし、テンプレート側は`{{copyright}}`と変数のみ出力するように変更する。**
* conf.pyの`copyright`変数は変更せず、テンプレート側での[Relpace](http://jinja.pocoo.org/docs/2.9/templates/#replace)により、2つめのコピーライトを生成する。

※後者はRelpaceのためにどうしてもテンプレート側に値をべた書きする必要があるため、メンテ性が下がる。値をconf.pyに集約し、よりメンテしやすい前者を採用するほうが良い。

#### 対応策の問題点
**既存のSolarテンプレートで実現できることが、一部実現できなくなる。**

Solarテンプレートのコピーライト出力部分は以下の通り。
```python
  {%- if hasdoc('copyright') %}
    {% trans path=pathto('copyright'), copyright=copyright|e %}&copy; <a href="{{ path }}">Copyright</a> {{ copyright }}.{% endtrans %}
  {%- else %}
    {% trans copyright=copyright|e %}&copy; Copyright {{ copyright }}.{% endtrans %}
  {%- endif %}
```

分岐の後者はコピーライトをテキスト出力するだけだが、前者は「コピーライトのファイルを指定して、そこへのリンクを張る」というもの。

**[問題]今回の対応でリンクは実現できなくなる。**（テンプレートで`a`タグ使わなくなるので）
-> guidelineリポジトリでは、コピーライトのファイルは用意していないので、オミットしても問題なし

----

ということで、こちらを採用。

**Comment by yoshikawaa** [comment]
@btyanagawamg 
もっと良い方法を確立しましたorz。。。次リリースの時にでも反映しましょう。

----
#### conf.py
`copyright`変数に代入する値を、文字列から文字列配列に変更する
```python
copyright = [(u'2013-2017, NTT DATA Corporation'), (u'2017, NTT Corporation')]
```
#### layout.html
For文で繰り返して、配列の要素数分コピーライトを出力する
```python
{%- if show_copyright %}
 {%- for copy in copyright %} # For文で繰り返す
  {%- if hasdoc('copy') %}
    {% trans path=pathto('copy'), copy=copy|e %}&copy; <a href="{{ path }}">Copyright</a> {{ copy }}.{% endtrans %}
  {%- else %}
    {% trans copy=copy|e %}&copy; Copyright {{ copy }}.{% endtrans %}
  {%- endif %}
 {%- endfor %}
{%- endif %}
```
これなら、`copyright`変数はSphinxの文法に則った形式で記述できますし、
layout.htmlでコピーライトのリンクが実現できなくなる問題も発生しません。

デメリットなし！

**Comment by yoshikawaa** [comment]
別のやり方として、conf.pyの`html_context`を使って、`copyright`ではない任意の変数を定義する方法もあります。
http://www.sphinx-doc.org/ja/stable/config.html#confval-html_context

5.4で再修正が必要なのでre-openします。

**Comment by yoshikawaa** [comment]
@itouyun @btsatouhrzzp 
ラベルを付け直すか、派生Issueを作ってこちらをクローズしてください。

**Comment by itouyun** [comment]
@yoshikawaa 
2つのやり方 https://github.com/terasolunaorg/guideline/issues/2628#issuecomment-287049983 と https://github.com/terasolunaorg/guideline/issues/2628#issuecomment-320160576 は、どちらがベターでしょうか。
特にメリデメがなくて好みの問題（決めの問題）だったりしますか？

なんとなく、あくまで`copyright`なので、前者のほうが意味を正しく使っているような気はしていますが、いかがでしょうか。

**Comment by yoshikawaa** [comment]
@itouyun 
大きな意味でのメリデメはないですが、前者のほうが今後の実装がシンプルになりそうで、良いと思います。
（個人的には、前者のほうがSphinx仕様を無視してる感はありますが）

**Comment by itouyun** [comment]
@yoshikawaa 
現状、前者でデメリットがないので、前者を採用したいと思います。
Sphinx仕様の隅っこ利用をしたことで、将来のSphinxのバージョンでうまく動作しなくなるかも、というリスクはあるかもしれませんが、その時はその時考えましょう。（リスクを飲む）

@btsatouhrzzp
派生Issueを作ってこちらをクローズおねがいします。
