### ISSUE TITLE
oauth chapter link better be label than url full path.

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/guideline#2631]
## Description
詳細については http://docs.spring.io/spring-security/site/docs/4.1.4.RELEASE/reference/html/basic.html を参照されたい。

## Possible Solutions
added label : Basic and Digest Authentication

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0_ja (master)
- [ ] 5.3.1_ja (5.3.x)
- [ ] 5.4.0_en (master)
- [ ] 5.3.1_en (5.3.x)

## Change log(should be updated at the same time)
- Not Required

## English Translation
(To be selected later by project member)
- [ ] Required, handle with the same issue
- [ ] Required, create a new issue for handling
- Not Required 

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by btkigamim** [comment]
@btishiwatasns
Thank you for your comment.
I will respond to this issue on issue #2891.
