### ISSUE TITLE
Check version for 2017 winter (for 5.1.x, 5.0.x)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2634]
## Description
#2532 で実施していない以下のバージョンについてバージョン情報の確認を行う。
* 5.1.2_ja / _en
* 5.0.3_ja / _en

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [ ] 5.1.2_ja
- [ ] 5.1.2_en
- [ ] 5.0.3_ja
- [ ] 5.0.3_en

## Issue Links
* #2532 

## ChangeLog
N/A

**Comment by itouyun** [comment]
2017 winter では、5.1.2と5.0.3はリリースしないため、クローズする。
リリースする際に同様のissueを発行してチェックする必要がある。
