### ISSUE TITLE
The table which is not delivered to one page for OAuth PDF build. #2189

### ISSUE THREAD

**Issue by btmatsudayul** [terasolunaorg/guideline#2635]
## Description
PDF出力をしたところ、OAuth章において１ページに収まらないテーブルが存在しています。

## Possible Solutions
OAuth章の各テーブルに以下を付与する。
`:class: longtable
`
## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0_ja
- [ ] 5.3.0_en

## Issue Links
* #2189
## ChangeLog
(To be written later by project member)

**Comment by yoshikawaa** [comment]
@sasakitsy 
Please write Issue that reflect to English version, and close this.

**Comment by asaharas** [comment]
I have created issue for English version #2710 
so you can close this issue.
