### ISSUE TITLE
Translate #1704 ([RESTful Web Service] Spring 4.3よりOPTIONSとHEADがデフォルトでサポートされる)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2640]
## Description
Please translate a modification #1704 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2394/files

## Fix Version/s
- [x]  5.3.0_en

## ChangeLog
- [x]  5.3.0_en

**Comment by asaharas** [comment]
5.3.0_en is fixed in #2686
