### ISSUE TITLE
Translate #1293 (@SessionAttributesで管理している読み取り専用オブジェクトの取得方法について)

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/guideline#2641]
## Description
Please translate a modification #1293 

Modifications refer to https://github.com/terasolunaorg/guideline/pull/2404/files

## Fix Version/s
- [x]  5.3.0_en
- [x]  5.2.1_en

## ChangeLog
- [x]  5.3.0_en
- [x]  5.2.1_en

**Comment by asaharas** [comment]
5.3.0_en is fixed in #2687

**Comment by asaharas** [comment]
5.2.1_en is fixed in #2698
