### ISSUE TITLE
minor typos in StringProcessing.rst

### ISSUE THREAD

**Issue by shimodatkh** [terasolunaorg/guideline#2642]
## Description

> @ConsisOf(JIS_X_0208_Hiragana.class)    // (1)
> private String firstName;

> @ConsisOf({JIS_X_0208_Hiragana.class, JIS_X_0208_Katakana.class})    // (1)
> private String firstName;

Japanese ver and English ver 

## Possible Solutions
@ConsisOf -> @ConsistOf

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
none

## ChangeLog
(To be written later by project member)

**Comment by yoshikawaa** [comment]
Already resolved.
