### ISSUE TITLE
Update README.md (after "2017 winter" release)

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/guideline#2660]
## Description
* fix travis-ci badge in README.md on 5.3.x branch (branch=master -> branch=5.3.x)
* modify "How to contribute" URL, from absolute path to relative path on 1.x,5.x and master branchs.
* modify "Terms of use" URL, from absolute path to relative path on 1.x,5.x and master branchs.

## Fix Version/s
* fix travis-ci badge in README.md on 5.3.x branch 
- [x] 5.3.x

* modify "How to contribute" URL, from absolute path to relative path
- [x] master
- [x] 5.3.x
- [x] 5.2.x
- [x] 5.1.x
- [x] ~~5.0.x (5.0.x has no CONTRIBUTING.md)~~
- [x] ~~1.0.x (1.0.x has no CONTRIBUTING.md)~~

* modify "Terms of use" URL, from "master" to "5.x.x" on 5.1.x,5.2.x,5.3.x branchs.
- [x] master
- [x] 5.3.x
- [x] 5.2.x
- [x] 5.1.x
- [x] 5.0.x
- [x] 1.0.x

## Issue Links
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/610

**Comment by kazuki43zoo** [comment]
Leave a comment
