### ISSUE TITLE
Improve the example of request header configuration process for Basic authentication

### ISSUE THREAD

**Issue by bttamuratsh** [terasolunaorg/guideline#2689]
## Description
In REST Client page, section 5.2.3.2.2, BasicAuthInterceptor class is published as an example of request header configuration process for Basic authentication.
In this class, userId and password values are injected by using ```@Value``` annotaion.
I think this class is used as generic, so I reccomend the values are injected from constructor.

## Possible Solutions
change the example like below

- BasicAuthInterceptor.java
```BasicAuthInterceptor.java
// omitted
public class BasicAuthInterceptor implements ClientHttpRequestInterceptor {
	private static final Logger log = LoggerFactory.getLogger(BasicAuthInterceptor.class);
	private String clientId;
	private String password;

	public BasicAuthInterceptor(String clientId, String password) {
		this.clientId = clientId;
		this.password = password;
	}
	// omitted
```

- xml file
```xml 
    <bean id="basicAuthInterceptor" class="xxx.yyy.BasicAuthInterceptor" >
        <constructor-arg name="clientId" value="aaa" />
        <constructor-arg name="password" value="bbb" />
    </bean>
```

## Affects Version/s
* All versions

## Fix Version/s
- [ ] 5.4.0
- [ ] 5.3.1

## Issue Links
- #2742

## ChangeLog
- [ ] Yes

**Comment by kazuki43zoo** [comment]
I vote to @bttamuratsh's opinion.
I prefer adding `final` on `clientId` and `password` field.

**Comment by kazuki43zoo** [comment]
I've assigned with you. Please resolve this!

**Comment by kazuki43zoo** [comment]
We need to consider together with #2742.

**Comment by kazuki43zoo** [comment]
@itouyun @yoshikawaa 

I decided that not fix this issue because it will resolved via #2742.
If you agree with my opinion, please close this issue.

**Comment by itouyun** [comment]
I see that this commit of L1717
https://github.com/terasolunaorg/guideline/pull/2830/files#diff-8789bfa75c0d1c4677dc077b62200b3c

**Comment by yoshikawaa** [comment]
@itouyun @kazuki43zoo 
OK, already resolved.

**Comment by kazuki43zoo** [comment]
@itouyun @yoshikawaa 

thanks for your confirmation !
