### ISSUE TITLE
Single quotations and double quotations are mixed in jsp example

### ISSUE THREAD

**Issue by bttamuratsh** [terasolunaorg/guideline#2690]
## Description
In Spring Security Tutorial page, section 10.4.4.2.2, single quotations and double quotations are mixed in login.jsp example.
``` login.jsp
<td><label for="username">User:</label></td>
<td><input type="text" id="username" name="username" value='demo'>(demo)</td>
```

## Possible Solutions
unify the quote style into double quotations.

## Affects Version/s
* All versions

## Fix Version/s
- [x] mastar
- [x] 5.3.1
- [ ] 5.2.2

## Issue Links
N/A

## ChangeLog
No

**Comment by kazuki43zoo** [comment]
I've assigned with you. Please resolve this!

**Comment by kazuki43zoo** [comment]
@itouyun Done! Please check and close this issue.

**Comment by itouyun** [comment]
I checked and close.

**Comment by itouyun** [comment]
@btmatsumotoms 
Please backport 5.2.x branch and asign member.

**Comment by itouyun** [comment]
I eat my words. You don't need to backport 5.2.x branch.
Now, maintenance branch is 5.3.x.
