### ISSUE TITLE
Typo mistake in Tutorial (Todo Application REST : Creation of spring-mvc-rest.xml)

### ISSUE THREAD

**Issue by btmatsumotoms** [terasolunaorg/guideline#2694]
## Description
「10.2.3.2.2. spring-mvc-rest.xmlの作成」の
src/main/resources/META-INF/spring/spring-mvc-rest.xml
で説明番号(3)が2つ登場する
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Tutorial/TutorialREST.html#spring-mvc-rest-xml

## Possible Solutions
誤）    `<context:component-scan base-package="todo.api" /> <!-- (3) -->`
正）    `<context:component-scan base-package="todo.api" /> <!-- (4) -->`

## Affects Version/s
* 5.3.0.RELEASE
* 5.2.1.RELEASE
* 5.1.1.RELEASE
* 5.0.2.RELEASE（Labelsは5.0.3しかありませんがドキュメントは5.0.2で確認しました）

## Fix Version/s
- [x] 5.4.0
- [x] 5.3.1
- ~~[ ] Other ?~~

## Issue Links
* #XXX

## ChangeLog
No

**Comment by yoshikawaa** [comment]
@itouyun @takahashihrzg 
This issue is completed contains English version.
