### ISSUE TITLE
Typo of version

### ISSUE THREAD

**Issue by asaharas** [terasolunaorg/guideline#2695]
## Description
5.2.1ブランチ内で5.2.1と記載すべき箇所に5.2.0と記載されている箇所が複数存在している。
日本語版、英語版双方に存在する。

## Possible Solutions
横展開して全て修正する
（Changelog内は不要なものもある）

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
   - [x] 5.2.x
   - [x] 1.0.x

## Issue Links
* #2730

## ChangeLog
not required

**Comment by itouyun** [comment]
5.3.x, 5.2.x, 1.0.x に対し、横展開調査を実施したところ、5.3.xは問題がないことを確認しました。  
5.2.x, 1.0.x に対し、問題がありそうな箇所を以下抽出しました。  

以下、置換ツール等で置換するのではなく、1件1件、本当に問題があるかどうかを確認する必要があります。  

#### 5.2.x
##### 5.2.0.RELEASE という記載が残っています
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst#L188 (188,92)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst#L385 (385,89)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst#L1783 (1783,53)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ArchitectureInDetail/WebApplicationDetail/Validation.rst#L4045 (4045,80)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ArchitectureInDetail/WebApplicationDetail/Validation.rst#L4067 (4067,84)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ArchitectureInDetail/WebApplicationDetail/Validation.rst#L4088 (4088,83)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ImplementationAtEachLayer/CreateProject.rst#L225 (225,218)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ImplementationAtEachLayer/CreateProject.rst#L238 (238,191)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L113 (113,25)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L164 (164,126)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L1550 (1550,120)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L1606 (1606,122)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L1654 (1654,17)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L1655 (1655,61)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Overview/FirstApplication.rst#L55 (55,25)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Overview/FirstApplication.rst#L68 (68,31)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Overview/FirstApplication.rst#L86 (86,111)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Overview/FrameworkStack.rst#L122 (122,9)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Overview/FrameworkStack.rst#L138 (138,16)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Security/SecureLoginDemo.rst#L500 (500,126)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Security/SecureLoginDemo.rst#L501 (501,99)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Tutorial/TutorialSecurity.rst#L103 (103,25)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Tutorial/TutorialTodo.rst#L222 (222,29)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Tutorial/TutorialTodo.rst#L243 (243,25)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Tutorial/TutorialTodo.rst#L262 (262,25)
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Tutorial/TutorialTodo.rst#L281 (281,25)

##### 1.0.0.RELEASE という記載が残っています
https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Overview/FirstApplication.rst#L84 (84,126)
  > なぜ1.0.0が残っているのか、確認が必要

#### 1.0.x
##### 1.0.5.RELEASE という記載が残っています
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Appendix/CreateProjectFromBlank.rst#L59 (59,27)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Overview/FirstApplication.rst#L51 (51,25)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Overview/FirstApplication.rst#L64 (64,31)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Overview/FirstApplication.rst#L82 (82,111)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Overview/FrameworkStack.rst#L112 (112,9)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Security/Tutorial.rst#L93 (93,25)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Security/Tutorial.rst#L106 (106,31)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Security/Tutorial.rst#L124 (124,120)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialREST/index.rst#L126 (126,25)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialREST/index.rst#L139 (139,31)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialREST/index.rst#L157 (157,120)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialTodo/index.rst#L210 (210,25)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialTodo/index.rst#L223 (223,25)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialTodo/index.rst#L236 (236,25)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialTodo/index.rst#L249 (249,31)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialTodo/index.rst#L267 (267,111)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialTodo/index.rst#L325 (325,29)

##### 1.0.0.RELEASE という記載が残っています
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Overview/FirstApplication.rst#L80 (80,126)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Security/Tutorial.rst#L122 (122,135)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialREST/index.rst#L155 (155,135)
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialTodo/index.rst#L265 (265,126)

##### その他
https://github.com/terasolunaorg/guideline/blob/1.0.x/source/index.rst#L6 (6,491)
  > 5.* 系と同様の記載にしてよいのでは？

**Comment by btkoremurakn** [comment]
[Version of maven command differs from log version #2730 ](https://github.com/terasolunaorg/guideline/issues/2730)
この調査により以下は修正しない

>1.0.0.RELEASE という記載が残っています
>https://github.com/terasolunaorg/guideline/blob/5.2.x/source/Overview/FirstApplication.rst#L84 (84,126)
>なぜ1.0.0が残っているのか、確認が必要

>1.0.0.RELEASE という記載が残っています
>
>https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Overview/FirstApplication.rst#L80 (80,126)
>https://github.com/terasolunaorg/guideline/blob/1.0.x/source/Security/Tutorial.rst#L122 (122,135)
>https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialREST/index.rst#L155 (155,135)
>https://github.com/terasolunaorg/guideline/blob/1.0.x/source/TutorialTodo/index.rst#L265 (265,126)

**Comment by btkoremurakn** [comment]
以下のブランチ内で1.0.0-SNAPSHOTと記載すべき箇所に1.0-SNAPSHOTと記載されている箇所が複数存在している。日本語版、英語版双方に存在する。本issue作業中に見つけたということでついでに修正する。

1.0.x
C:\workspace\guideline\guideline\source\Appendix\EnvironmentIndependency.rst(113,50)
C:\workspace\guideline\guideline\source\Security\Tutorial.rst(96,16)
C:\workspace\guideline\guideline\source\Security\Tutorial.rst(109,22)
C:\workspace\guideline\guideline\source\Security\Tutorial.rst(128,39)
C:\workspace\guideline\guideline\source\Security\Tutorial.rst(132,39)
C:\workspace\guideline\guideline\source\TutorialREST\index.rst(129,16)
C:\workspace\guideline\guideline\source\TutorialREST\index.rst(142,22)
C:\workspace\guideline\guideline\source\TutorialREST\index.rst(161,39)
C:\workspace\guideline\guideline\source\TutorialREST\index.rst(165,39)

5.0.x
C:\workspace\guideline\guideline\source\Appendix\EnvironmentIndependency.rst(149,50)

5.1.x
C:\workspace\guideline\guideline\source\Appendix\EnvironmentIndependency.rst(149,50)

5.2.x
C:\workspace\guideline\guideline\source\ImplementationAtEachLayer\CreateProject.rst(361,50)

5.3.x
C:\workspace\guideline\guideline\source\ImplementationAtEachLayer\CreateProject.rst(361,50)

master
C:\workspace\guideline\guideline\source\ImplementationAtEachLayer\CreateProject.rst(361,50)

**Comment by itouyun** [comment]
1.0.0-SNAPSHOT の件は別件なので、別issueとして分離します。
