### ISSUE TITLE
Not "request" but "view logical name" is evaluated on selecting Apache tile's definition.

### ISSUE THREAD

**Issue by ynojima** [terasolunaorg/guideline#2717]
## Description

Apache Tilesで複数の画面レイアウトを構成する際、何のパラメータに基づいてApache Tilesのdefinitionが選択されるかの説明が誤っています。

http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/TilesLayout.html#id3

```
     <definition name="*/search*" extends="layoutsOfSearch"> <!-- (2) -->
         <put-attribute name="title" value="title.{1}.search{2}" /> <!-- (3) -->
         <put-attribute name="body" value="/WEB-INF/views/{1}/search{2}.jsp" /> <!-- (4) -->
     </definition>
```

上記のdefinitionに対して、
「今回追加するレイアウトについて、描画のリクエストの際にnameのパターンと同じ場合に呼ばれるレイアウト定義。リクエストが<contextPath>/*/search*に該当する場合、このレイアウト定義が読み込まれる。」と表現されています。実際には、リクエスト（のURL）ではなく、Controllerのハンドラメソッドの戻り値のView論理名がマッチングの評価の対象です。

## Possible Solutions

View論理名とする

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1
- [x] 5.2.2
- [x] 5.1.2 ※リンク先が異なるので注意
- [x] 5.0.3 ※リンク先が異なるので注意
- [x] 1.0.7 ※リンク先が異なるので注意

## Issue Links
* #XXX

## ChangeLog
- [x] required

**Comment by kazuki43zoo** [comment]
コメントありがとうございます。ご指摘の通り、全体的に「リクエスト」と「View名」を混同してしまっているので見直したいと思います。

**Comment by yoshikawaa** [comment]
@itouyun @btsatouhrzzp 
Please write issue for translation, and close this.

**Comment by itouyun** [comment]
バグなのでバックポート範囲を広げました。

**Comment by yoshikawaa** [comment]
@itouyun 
Please write issue for translation, and close this.

**Comment by btsatouhrzzp** [comment]
I created #2853 issue. This issue is closed.
