### ISSUE TITLE
Initialization sql files are not found.

### ISSUE THREAD

**Issue by btumezaway** [terasolunaorg/guideline#2718]
## Description
The link for initialization sql files at [SecureLoginDemo.html#implement-description](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/SecureLoginDemo.html#implement-description) is broken.

## Possible Solutions
Just fix the url which the link refers. :-)

## Affects Version/s
* 5.3.0.RELEASE
* 5.1.1.RELEASE

**NOTE:** 5.2.1.RELEASE has a correct link.

## Fix Version/s
- [x] 5.4.0
- [x] 5.3.1
- [x] 5.1.2

## Issue Links
* N/A

## ChangeLog
No

**Comment by kazuki43zoo** [comment]
done!
