### ISSUE TITLE
Wrong sample of @Compare

### ISSUE THREAD

**Issue by btumezaway** [terasolunaorg/guideline#2728]
## Description

I think there are THREE problems.

First, the usage sample of `@Compare` at [SecureLoginDemo](http://terasolunaorg.github.io/guideline/5.1.1.RELEASE/ja/Security/SecureLoginDemo.html#id27) cannot be compiled. The attributes must be `left` and `right`, not `source` and `destination` .

Second, the value of `source` should be `newPassword`, not `newPasssword` (there are too much 's'). This typo causes IntrospectionException at runtime.

And Third, the sample code of this guide uses [custom `@Comfirm` validation](https://github.com/terasolunaorg/tutorial-apps/blob/59750a1115a15d6cb7074884df8d23f252311e32/secure-login-demo/secure-login-web/src/main/java/org/terasoluna/securelogin/app/passwordchange/PasswordChangeForm.java#L28)  like below, instead of `@Compare` . The difference between guides and codes may confuse readers.

```java
@Confirm(propertyName = "newPassword")
public class PasswordChangeForm implements Serializable {
...
```

## Possible Solutions
Fix the documentation and source code to use `@Compare` correctly :-)

## Affects Version/s
* 5.3.0.RELEASE
* 5.2.1.RELEASE
* 5.1.1.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- [x] 5.2.2_ja (5.2.x)
- [x] 5.1.2_ja (5.1.x)
- [x] 5.4.0_en (master)
- [x] 5.3.1_en (5.3.x)
- [x] 5.2.2_en (5.2.x)
- [x] 5.1.2_en (5.1.x)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- Required, handle with the same issue

## Migrating Guide
- Not Required

## Issue Links
* terasolunaorg/tutorial-apps#94

**Comment by yoshikawaa** [comment]
@btumezaway 
And, 4th probrem... 
> @Compare(source = "newPasssword", destination = "confirmNewPassword", operator = Compare.Operator.EQUAL) // (1)
> (1) 新しいパスワードの二回の入力が一致しているかをチェックするためのアノテーション。詳細は terasoluna-gfw-commonのチェックルール を参照すること。

Usage of `@Compare` must reference [5.5.4.3.3. terasoluna-gfw-validatorのチェックルール](http://terasolunaorg.github.io/guideline/5.1.1.RELEASE/ja/ArchitectureInDetail/Validation.html#terasoluna-gfw-validator), not [5.5.4.3.1. terasoluna-gfw-commonのチェックルール](http://terasolunaorg.github.io/guideline/5.1.1.RELEASE/ja/ArchitectureInDetail/Validation.html#terasoluna-gfw-common) .

**Comment by kazuki43zoo** [comment]
@btumezaway and @yoshikawaa 

> And Third, the sample code of this guide uses custom  @Comfirm  validation like below, instead of  @Compare  . The difference between guides and codes may confuse readers.

I think better that we will consider to change example on ["5.5.3.2.2. 相関項目チェックルール"](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validation-correlation-item-check). A current example(`@Confirm`) can be replaced the `@Compore` provided by common library. I am afraid to give misreading that need creating custom validator like a `@Confirm` for checking same value to developers.
What do you think ? If you agree with my opinion, I hope to create a new issue for finxing this.

**Comment by kazuki43zoo** [comment]
> First, the usage sample of  @Compare  at SecureLoginDemo cannot be compiled. The attributes must be  left  and  right , not  source  and  destination  .

Oh.. , these attributes are changing to `left` and `right` instead of `source` and `destination` under developing of version 5.1.0(see https://github.com/terasolunaorg/terasoluna-gfw/commit/cf2cd1cd475994cecf05ed2de74b7080d83a0aa2#diff-14e6d37920a5a279e8e0b68bfc40d8de).

**Comment by btumezaway** [comment]
> I am afraid to give misreading that need creating a custom validator like @Confirm for checking same value to developers.

I think the example of `@Confirm` is concise and easy to understand. In addition, [the correlation check by SpringValidator](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#spring-validator) also shows password confirmation as an example, too.

So, I think it's enough to add some notes to show that the TERASOLUNA's `@Compare` is very useful :-)

**Comment by btumezaway** [comment]
> these attributes are changing to left and right instead of source and destination under developing of version 5.1.0

Thanks! 

The issue [#372](https://github.com/terasolunaorg/terasoluna-gfw/issues/372) was very interesting for me, and I thought it would be fun if I could work with @making together :relieved:

**Comment by yoshikawaa** [comment]
@itouyun See https://github.com/terasolunaorg/tutorial-apps/issues/94#issuecomment-325856189

**Comment by itouyun** [comment]
@yoshikawaa @btkatoutmj
Thanks. We will extend target of backport to 5.2.x, 5.1.x.
