### ISSUE TITLE
Create blank project with maven Log at build time

### ISSUE THREAD

**Issue by btkoremurakn** [terasolunaorg/guideline#2730]
## Description

記録のために起票しただけなのですぐクローズする。

「archetypeVersion=5.2.0.RELEASE」を指定してブランクプロジェクトを作成した際のログに「archetype:1.0.0.RELEASE」と出力される。
動作としてどうログが出力されるのが正しいかを確認する

結論：対応しない
INFOログだしあまり気にすることもない

チャットでのやり取り

```
archetype-idが一致する中でarchetype-catalog.xmlの先頭のバージョンがでてるだけなのかも？
「terasoluna-gfw-web-blank-mybatis3-archetype」と検証したところ、「terasoluna-gfw-web-blank-mybatis3-archetype:5.0.0.RC5」となった。
catalog.xml検索してみると、最初にあわられるバージョンは5.0.0.RC5だった
初期バージョンの編集等繰り返したときの残骸の可能性も。
このログの目的が不明。
```

mavenコマンド
```
mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -B^
 -DarchetypeCatalog=http://repo.terasoluna.org/nexus/content/repositories/terasoluna-gfw-releases^
 -DarchetypeGroupId=org.terasoluna.gfw.blank^
 -DarchetypeArtifactId=terasoluna-gfw-web-blank-archetype^
 -DarchetypeVersion=5.2.0.RELEASE^
 -DgroupId=todo^
 -DartifactId=todo^
 -Dversion=1.0.0-SNAPSHOT
```

ログ抜粋
```
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [org.terasoluna.gfw.
blank:terasoluna-gfw-web-blank-archetype:1.0.0.RELEASE -> http://repo.terasoluna
.org/nexus/content/repositories/terasoluna-gfw-releases] found in catalog http:/
/repo.terasoluna.org/nexus/content/repositories/terasoluna-gfw-releases
```

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.2.X.RELEASE
* 5.1.X.RELEASE
* 5.0.X.RELEASE
* 1.0.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #2695 

## ChangeLog
(To be written later by project member)

**Comment by yoshikawaa** [comment]
@btkoremurakn @kazuki43zoo 
`maven-archetype-plugin:2.4`のソースコードを見ると、
カタログを`groupId`+`artifactId`で検索し、最初に見つけた`archetype`をログ出力しているようです。

* カタログを検索しているところ(`DefaultArchetypeSelector#findArchetype`)
  https://github.com/apache/maven-archetype/blob/maven-archetype-2.4/maven-archetype-plugin/src/main/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeSelector.java#L279-L293
* ログ出力しているところ（`DefaultArchetypeSelector#selectArchetype`）
  https://github.com/apache/maven-archetype/blob/maven-archetype-2.4/maven-archetype-plugin/src/main/java/org/apache/maven/archetype/ui/generation/DefaultArchetypeSelector.java#L96-L97

よって、「プラグインの実装上、カタログから最初に取得したバージョンがログが出ます。」というだけの話で、
我々のアーキタイプの作り方や登録の仕方に問題があるわけではなさそう、という結論になりそうです。

参考までに。

**Comment by kazuki43zoo** [comment]
@yoshikawaa のコメントのとおりアーキタイプの作り方や登録の仕方などに問題があるわけではないことが確認できたので、本Isuueはクローズ。
