### ISSUE TITLE
The sample code of account locking cannot be compiled :-(

### ISSUE THREAD

**Issue by btumezaway** [terasolunaorg/guideline#2734]
## Description

The [AuthenticationEventSharedServiceImpl#findLatestFailureEvents](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/SecureLoginDemo.html#id31) cannot be compiled, because it calls `failedAuthenticationRepository.findLatestEvents(username, count)` that does not exist.

It must call `findLatest` instead of `findLatestEvents`.

## Possible Solutions

Just fix the document to match [the source code](https://github.com/terasolunaorg/tutorial-apps/blob/59750a1115a15d6cb7074884df8d23f252311e32/secure-login-demo/secure-login-domain/src/main/java/org/terasoluna/securelogin/domain/service/authenticationevent/AuthenticationEventSharedServiceImpl.java#L53).

## Affects Version/s
* 5.3.0.RELEASE
* 5.2.1.RELEASE
* 5.1.1.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- [x] 5.4.0_en (master)
- [x] 5.3.1_en (5.3.x)

## Issue Links
* N/A

## Change log(should be updated at the same time)
* Not Required

## English Translation
* [x] Required, handle with the same issue

## Migrating Guide
* Not Required

**Comment by itouyun** [comment]
@btumezaway 
Thank you for your finding sample code bug.

**Comment by itouyun** [comment]
バグのため、バックポート先を広げました。

**Comment by yoshikawaa** [comment]
@itouyun @btsuzukisnzh 
これ、`bug`じゃなくて、`clerical error`扱いが良いんじゃないですかね？
2つ前以前のバージョンまで修正するのは良いけど、ChangeLogは要らないと思います。

**Comment by kazuki43zoo** [comment]
> これ、bugじゃなくて、clerical error扱いが良いんじゃないですかね？

:+1: 

> ChangeLogは要らないと思います。

:+1: 

> 2つ前以前のバージョンまで修正するのは良いけど、

これは（原則的な）基準をちゃんと定義した方がよいですね。
このIssueを過去バージョンにbackportするなら、内容的に見ると #2822 をbackportする方が大事です。（ガイドライン自体のbugなので）
個人的には、5.3.xまでのbackportでいいと思っています。

**Comment by yoshikawaa** [comment]
@kazuki43zoo @itouyun 
そうですね、「2つ前以前のバージョンまで修正するのは良いけど、」は簡単だからやるのは構わないけど、特に必要だとは思ってないよ、の意です。

**Comment by itouyun** [comment]
本件、コンパイルできないコードがある、という理由で`bug`扱いしていましたが、
対象が`代表的なセキュリティ要件の実装例`であり、本質的には
「ガイドしている主張が異なっていた」ではなく
「ガイドしている主張をする上で記載ミスがあった」であるため、
`clerical error`扱いとします。

また、たとえ本ミスを参考にした利用者にとっては、コンパイルエラーになることでむしろミスに気付けるため、致命的な結果につながりにくいと考えるため、修正対象も、基本の2バージョンとして見直します。
