### ISSUE TITLE
[Rest Client] Drop how to creating a ClientHttpRequestInterceptor for basic authentication

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2742]
## Description
Spring Framework 4.3.1からBasic認証用の`ClientHttpRequestInterceptor`(`BasicAuthorizationInterceptor`)が追加されており、[ガイドラインで紹介しているクラス](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebServiceDetail/RestClient.html#restclienthowtoextendclienthttprequestinterceptorbasicauthentication
)を作成する必要はなくなっている。

## Possible Solutions
クラスの作成方法の紹介は削除し、Spring Frameworkから提供されているクラスの使い方(Bean定義例)の説明のみにする。

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
- [x] 5.4.0
- [x] 5.3.1

## Issue Links
- #2689

## ChangeLog
- [x] Yes

**Comment by kazuki43zoo** [comment]
#2689 と一緒に検討する。

**Comment by kazuki43zoo** [comment]
@itouyun 

日本語版の対応完了しました。修正内容を確認の上、問題なければ英語翻訳のIssue作成お願いします。

**Comment by btsatouhrzzp** [comment]
I created #2854 issue. This issue is closed.
