### ISSUE TITLE
typo of caret at maven command in english guideline

### ISSUE THREAD

**Issue by btkoremurakn** [terasolunaorg/guideline#2761]
## Description
メンテナンスブランチ5.2.xの英語版10.1. Tutorial (Todo Application)でWindows用のMavenコマンドが、本来「^」となるところ、Bash用の「\」になっている。

https://github.com/terasolunaorg/guideline/edit/5.2.x/source_en/Tutorial/TutorialTodo.rst#L240 (240,103)
https://github.com/terasolunaorg/guideline/edit/5.2.x/source_en/Tutorial/TutorialTodo.rst#L259 (259,103)
https://github.com/terasolunaorg/guideline/edit/5.2.x/source_en/Tutorial/TutorialTodo.rst#L278 (278,103)

## Possible Solutions
誤）-DarchetypeCatalog=http://repo.terasoluna.org/nexus/content/repositories/terasoluna-gfw-releases\
正）-DarchetypeCatalog=http://repo.terasoluna.org/nexus/content/repositories/terasoluna-gfw-releases^

他のバージョンや日本語版の影響調査が必要。

## Affects Version/s
* 5.2.1.RELEASE

## Fix Version/s
   - [x] 5.2.x

## Issue Links
* 

## ChangeLog
not required

**Comment by yoshikawaa** [comment]
￥＋改行でGrepした結果、以下に問題がありそうです。

##### 開発プロジェクトのビルド（日本語/英語）
* [3.5.1.3.3.3. アプリケーションサーバへのリリース](http://terasolunaorg.github.io/guideline/5.2.1.RELEASE/ja/ImplementationAtEachLayer/CreateProject.html#id11) ※リンクは日本語版
  この章全体的にはWindowsコマンドプロンプトで入力してる風なのに、最後のNoteだけ断りなくBash

**Comment by itouyun** [comment]
@yoshikawaa さんが発見した問題は、別issueとして対応しましょう。issue切ります。
