### ISSUE TITLE
typo of caret at maven command

### ISSUE THREAD

**Issue by itouyun** [terasolunaorg/guideline#2762]
## Description
Windows用のMavenコマンドで記載されるべきコマンドが、本来「^」となるところ、Bash用の「\」になっている。

##### 開発プロジェクトのビルド（日本語/英語）
* [3.5.1.3.3.3. アプリケーションサーバへのリリース](http://terasolunaorg.github.io/guideline/5.2.1.RELEASE/ja/ImplementationAtEachLayer/CreateProject.html#id11) ※リンクは日本語版
  この章全体的にWindowsコマンドプロンプトで入力してる風なのに、最後のNoteだけ断りなくBash

## Possible Solutions
特に断りのないコマンドは、Windowsコマンドプロンプトのコマンドで記載する。
つまり、「^」とする。

## Affects Version/s
* All Version

## Fix Version/s
- [x] 5.4.0(master)
- [x] 5.3.1(5.3.x)

## Issue Links
* https://github.com/terasolunaorg/guideline/issues/2761#issuecomment-301653326

## ChangeLog
not required

**Comment by yoshikawaa** [comment]
@itouyun 
Completed including English version.
