### ISSUE TITLE
「SOAP Web Service」ページで使用されている@Injectを@Autowiredに変更する

### ISSUE THREAD

**Issue by bttsuchiyahrh** [terasolunaorg/guideline#2763]
## Description
「SOAP Web Service」ページで使用されている`@Inject`を、Springが提供する機能である`@Autowired`に変更する。
【背景】
SOAPサーバ上の処理は、ガイドラインに記載のある他機能と異なり、
Springが実装するサーブレットではなく、JAX-WSエンジンが実装するサーブレット上で動作する特徴がある。
その場合、インジェクションをJavaEEの@Injectで実施すると、実行環境の各APサーバのDIの挙動に依存した動作になる。インジェクションを安定して実施するために、Springが提供する@Autowiredに変更する。

## Possible Solutions
「SOAP Web Service」ページに記載のある`@Inject`を`@Autowired`に変更する。

## Affects Version/s
* 5.1.0.RELEASE and later

## Fix Version/s
- [x] 5.4.0(master)
- [x] 5.3.1
- [ ] write issue for English translation

## Issue Links
* #2770 

## ChangeLog
- [x] required

**Comment by kazuki43zoo** [comment]
> 「SOAP Web Service」ページでSpringで推奨されていない@Injectを使用されている。

リファレンスやjavadocに推奨していない旨が記載されている？

**Comment by bttsuchiyahrh** [comment]
申し訳ございません。こちらの勘違いです。
SpringではなくWASが主体でした。今回のテスト対象の一つである、WASのテストの実行条件(CDIを無効化)下においてのWASの話です。かつ、WASにしても、はっきりと非推奨という文章を目にしているわけではないため、
「Description」の記載を「Springの機能である@Autowiredに変更する」とします。

**Comment by yoshikawaa** [comment]
@bttsuchiyahrh @kazuki43zoo 
WASに限ったお話にする必要はないと思いますが。

* TERAガイドラインでは基本的にSpringのサーブレット、SpringのDIで動作することを前提としていて、その中では`@Inject`と`@Autowired`は同等の扱い、どちらを使ってもOK
* SOAPの章だけはJavaEEのJAX-WS＋SpringのDIで動作する前提で、その中では`@Inject`はJavaEEのDIの影響を受ける可能性があり、ちょっと微妙かも
    -> SpringのDI使いたいなら、`@Inject`より`@Autowired`使ったほうが安定するよねー

という話だと思っているのですが、そういう前提をIssueのDescriptionに書くべきですね。

**Comment by kazuki43zoo** [comment]
@yoshikawaa @bttsuchiyahrh 

> そういう前提をIssueのDescriptionに書くべきですね。

そうですね。 :+1:

**Comment by bttsuchiyahrh** [comment]
@yoshikawaa @kazuki43zoo
指摘内容を、IssueのDescriptionに追記しました。

**Comment by yoshikawaa** [comment]
@bttsuchiyahrh 
Please write change log for 5.4, and backport to 5.3.

**Comment by yoshikawaa** [comment]
@itouyun 
Please write issue for English translation, and close this.

**Comment by itouyun** [comment]
I made #2779 and close.
