### ISSUE TITLE
The description of the SOAP server architecture is incorrect...

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2770]
## Description
[5.3.1.3. Spring FrameworkのJAX-WS連携機能について](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebServiceDetail/SOAP.html#spring-frameworkjax-ws)
> Spring FrameworkはJAX-WSの連携機能をサポートしており、その機能を使用することでSOAPサーバ、クライアントともに簡単に実装することができる。

と書いてあるが、この書きぶりだとガイドラインではいかにもSpringのJAX-WS連携機能を利用して開発するように見える。実際に説明していることと乖離している。

##### SOAPクライアント
Springの`JaxWsPortProxyFactoryBean`を利用する実装方法を紹介しているので、正しい。

##### SOAPサーバ
JAX-WSの`@WebService`を利用して、JavaEEサーバのJAX-WSエンジンで、Tomcatの場合はApache CXF上で動作させている。その上でSpringのDI機能などを利用できる実装方法を紹介しているだけなので、SpringのJAX-WS連携機能を使っているわけではない。

なお、SpringのJAX-WS連携機能としては、JDKビルトインのHTTP Serverに連携する`SimpleJaxWsServiceExporter`が存在する。

## Possible Solutions
* Springは関係なく、JAX-WS準拠の`@WebService`を利用して開発し、JavaEEサーバのJAX-WSエンジンで動作させることを前提としている旨を説明する
  - `DispatcherServlet`上で動作していないため、Controllerにかけるインターセプタなど一部機能が使えないことに留意する必要がある
  - JavaEEサーバの実装によりWebサービスの動作が異なるため、サーバごとにガイドラインで紹介している実装方法を一部カスタマイズする必要がある
  
## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (guideline/master) 【共通】
- [x] 5.3.1_ja (guideline/5.3.x) 【共通】
- ~5.4.0_en (guideline/master) 【共通】~ another issue
- ~5.3.1_en (guideline/5.3.x) 【共通】~ another issue
- [x] 1.5.0_ja (guideline-macchinetta-jsp/master) 【共通】
- [x] 1.4.1_ja (guideline-macchinetta-jsp/1.4.x) 【共通】
- [x] 1.5.0_ja (guideline-macchinetta-thymeleaf/master) 【共通】

## Final Solution
Possible Solutionの対応を行う。

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
* #2763 - 当Issueと同リリース内で対応する必要がある

**Comment by yoshikawaa** [comment]
@itouyun 
#2763 からの派生Issueであることを考慮してアサインしましょう。

**Comment by btnonakasts** [comment]
PossibleSolutionsのポイントに対して以下の対応を考えております。
ご確認の程、よろしくお願いいたします。
【変更対象】
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebServiceDetail/SOAP.html


＞•Springは関係なく、JAX-WS準拠の @WebService を利用して開発し、JavaEEサーバのJAX-WSエンジンで動作させることを前提としている旨を説明する
【変更箇所】
[5.3.1.3. Spring FrameworkのJAX-WS連携機能について]の本文
【変更前】
`Spring FrameworkはJAX-WSの連携機能をサポートしており、その機能を使用することでSOAPサーバ、クライアントともに簡単に実装することができる。
以下はその機能を用いた、推奨アクセスフローの概要である。
ここではSOAPのクライアント(図左)であるWebアプリケーションがSOAPサーバ(図右)にアクセスすることを前提としている。`
【変更後】
`Spring FrameworkはJAX-WSの連携機能をサポートしており、その機能を使用することでSOAP Web Serviceのアプリケーションを簡単に実装することができる。
以下はSOAPクライアントにその機能を用いた、推奨アクセスフローの概要である。（SOAPサーバについてはJavaEEサーバのJAX-WS実装を使用する。）
ここではSOAPのクライアント(図左)であるWebアプリケーションがSOAPサーバ(図右)にアクセスすることを前提としている。`


＞◦ DispatcherServlet 上で動作していないため、Controllerにかけるインターセプタなど一部機能が使えないことに留意する必要がある
【変更箇所】
[5.3.1.3. Spring FrameworkのJAX-WS連携機能について (4)] にNote追加
【追加文言】
`ここではSOAPサーバの実装にJavaEEサーバのJAX-WS実装を使用するため、
SpringMVCの機能（DispatcherServletを利用する機能など）については利用できない点に留意されたい。`


＞◦JavaEEサーバの実装によりWebサービスの動作が異なるため、サーバごとにガイドラインで紹介している実装方法を一部カスタマイズする必要がある
【変更箇所】
[5.3.1.4. JAX-WSを利用したWebサービスの開発について]にWarning追加
【追加文言】
`SOAPサーバのWebサービスはAPサーバのJAX-WS実装を利用しているため、利用するAPサーバによってWebサービスの実装、動作に違いが出る可能性があるので注意すること。
意図しない動作となった場合には、本実装例を利用するAPサーバに応じて適宜カスタマイズされたい。`

※動作の違いについて https://github.com/terasolunaorg/terasoluna-gfw/wiki の [Notes for each application server] を参照しましたが、Webサービスの動作に特化した違いを見つけることができなかったため、実例の記載を省略させていただきました。

**Comment by bttsuchikawaf** [comment]
利用するAPサーバによるWebサービスの動作の違いについての実例を再確認し、
以下の4つが見つかりました。

1. WAS Libertyでは、バインディング形式がSOAP1.1の場合はWSDLが自動生成され公開されるが、SOAP1.2の場合は自動生成されない。

2. WAS Libertyのサーバライブラリとアプリケーションで使用するライブラリが競合した場合、正常に動作しないことがある。また、Web ProfileはWebアプリケーションが動作する最低限の機能のみ備えており、SOAP Web Serviceの機能は含まれない。そのため、server.xmlの<featureManager>要素を変更し、WAS Liberty側のライブラリの構成を変える必要がある。

3. WAS traditionalのクラスローダのモードをparent_firstに設定すると、デフォルトでサーバライブラリに含まれるAXIS2が有効になる。HTTPステータスコードが400番台及び500番台の場合には、WAS Libertyに含まれるApache-CXFとAXIS2で発生する例外が異なる。

4. WebOTX9.3ではSpringの SpringBeanAutowiringSupportが正しく機能せずService実装クラスなどのDIが実現できないため、WebOTXから提供されているnec-jaxws.xmlを使わずに、web.xmlを利用する。

アプリケーションの実装へ影響するものを実例として紹介したいと考えています。
3のみAPサーバの動作の違いがアプリケーションの実装（例外処理）へ影響しているため、
上記の中では3のみを紹介したいと考えています。

**Comment by yoshikawaa** [comment]
@itouyun @bttsuchikawaf 
現時点でオープンにすべきでない情報が含まれるため、記述を削除してinternal で検討しましょう。

**Comment by itouyun** [comment]
@bttsuchikawaf 
Thank you for your work!!
