### ISSUE TITLE
Explanation of how to use the codepoints libraries is not kind

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/guideline#2785]
## Description
terasoluna-gfw-codepointsを利用するにあたり、ブランクプロジェクトに含まれていないが、利用する方法がわかりづらい。
かつ、terasoluna-gfw-codepointsしか記述がなく
terasoluna-gfw-codepoints
terasoluna-gfw-codepoints-jisx0201
terasoluna-gfw-codepoints-jisx0208
terasoluna-gfw-codepoints-jisx0208kanji
terasoluna-gfw-codepoints-jisx0213kanji
の5つあることがわからない。
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Overview/FrameworkStack.html#frameworkstack-common-library

## Possible Solutions
共通ライブラリの構成要素には複数あることは※ででも説明を入れてほしい。
実際に何があるのかはリンクでよい。
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.html#stringprocessinghowtousecodepointsclasses

## Affects Version/s
* 5.3.0.RELEASE
* 5.2.1.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (guideline/master) 【共通】
- [x] 5.3.1_ja (guideline/5.3.x) 【共通】
- [x] 1.5.0_ja (guideline-macchinetta-jsp/master) 【共通】
- [x] 1.4.1_ja (guideline-macchinetta-jsp/1.4.x) 【共通】
- [x] 1.5.0_ja (guideline-macchinetta-thymeleaf/master) 【共通】
- 5.4.0_en (guideline/master) 【共通】 another issue
- 5.3.1_en (guideline/5.3.x) 【共通】 another issue

## Final Solution
Possible Solutionの対応を行う。

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #2937 
- https://github.com/terasolunaorg/terasoluna-gfw/issues/734

**Comment by itouyun** [comment]
@btishiwatasns 
5つあることは利用者が意識する必要のある情報でしょうか。
https://github.com/terasolunaorg/terasoluna-gfw/blob/master/README.md
の定義においては、`terasoluna-gfw-codepoints`の定義1つで問題ない気がしました。

**Comment by kazuki43zoo** [comment]
@itouyun 

利用者が明示的に`pom.xml`に追加しないと使えないので、必要な情報だと思います。

**Comment by itouyun** [comment]
@kazuki43zoo 
ありがとうございます。
https://github.com/terasolunaorg/terasoluna-gfw/blob/master/README.md が正だと思ってコメントしましたが、このリンク先においても、codepoint系の5つを網羅したほうが良いですね。

そして、ガイドライン上でも書き直すべきですね。

代表として`terasoluna-gfw-codepoints`だけ書いて、補足で他にも4つある、と書くか、行レベルで分離させて5つ並列で網羅するかは、要検討ですね。

**Comment by kazuki43zoo** [comment]
> 要検討ですね。

そうですね。なんとなく前者でいいかな～という気はしています。

**Comment by yoshikawaa** [comment]
ちなみに、このissueと直接関係はないですが、コードポイントなどは5.1.0から追加と記載があるのに、dependencies系に5.2.0から追加と記載がないのも気になりました。

**Comment by kazuki43zoo** [comment]
> dependencies系に5.2.0から追加と記載がないのも気になりました。

ですね。

**Comment by itouyun** [comment]
@yoshikawaa @kazuki43zoo 
統一感がなく、誤解を与えてしまう（カッコ書きのないものは初版からあるように見える）ので、いけてないですね。

- カッコ書きで正しく記述する
- 新たに列を作って、その列に追加されたVerを記載する

の2種のimprovementが考えられますが、頻繁に機能が増えていくわけではないので、とりあえず前者対応がベターかと思いました。別issue作って本issueのついでに対応しちゃいます。

@btsatouhrzzp 
https://github.com/terasolunaorg/guideline/issues/2785#issuecomment-316646413 のissue作成と、前述している別件のissue作成をお願いします。

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
