### ISSUE TITLE
Validation - Explanation of group validation is incorrect.

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/guideline#2792]
## Description
グループバリデーションの説明に誤りがある。
「明示的に全グループを指定する必要がある。」場合の方
1.@Maxにグループが設定されておらず、Default.class以外ではチェックされない。
```
@Max(200)
private Integer age;
```

2.説明箇所誤り
「(1)ageフィールドの…」とあるが、(1)が指定しているのはnameフィールドである。

## Possible Solutions
 - 修正該当箇所   
 http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validationgroupvalidation 

 - 1.@Maxにグループが設定されておらず、Default.class以外ではチェックされない。
「明示的に全グループを指定する必要がある。」場合の方のソースを
　`@Max(200)`　->　`@Max(value= 200, groups = { Default.class, Japanese.class, Singaporean.class })`
に修正する。
<br>

 - 2.説明箇所誤り
「XXXフィールドの@yyy」という説明のされ方は、グルーブバリテーション以外の説明に見受けられなかった点と、該当部分で@ Minを使用しているのはageフィールドのみである点から、
 ``ageフィールドの@Min以外のアノテーション``　->``@Min以外のアノテーション``
に修正する。（二箇所）
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- [x] 5.4.0_en (master)
- [x] 5.3.1_en (5.3.x)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [x] Required, handle with the same issue

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by itouyun** [comment]
記票された
```
2.説明箇所誤り
「(1)ageフィールドの…」とあるが、(1)が指定しているのはnameフィールドである。
```
は、指摘誤りの可能性があります。

主語が`ageフィールドの`にもかかわらず、指定が`nameフィールド`になっているため、
一見誤っているようにも見えますが、ここに関してガイドをよくよく見てみると、
`ageフィールドの@Min`以外の`全フィールドの全アノテーション`にも…という意味が正しいです。

そのような意味においては、全フィールドの一番最初の行に(1)が指定されているのは、違和感がありません。

よくよく読めばこのような結論に達しますが、日本語がわかりにくいことが原因だと思われるため、日本語の修正（改善）が良いのではないでしょうか。

**Comment by itouyun** [comment]
なお、`2.説明箇所誤り`について英語版を確認しましたが、以下の英語の文章となっており、特に誤解を生まないと予想されるため、英語版の対応は不要とする。
`Set all groups to annotations other than @Min of age field as well.`

**Comment by btsatouhrzzp** [comment]
マージが完了したため本issueをクローズします。
