### ISSUE TITLE
Description of HandlerExceptionResolverLoggingInterceptor is wrong

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2794]
## Description
[例外ハンドリング#4.2.2.3.2. ユースケース単位でControllerクラスがハンドリングする場合の基本フロー](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-basic-flow-annotation-label)
> `HandlerExceptionResolverLoggingInterceptor`は、`ExceptionLogger`を呼び出し、例外コードに対応するレベル(info, warn, error)のログ(監視ログとアプリケーションログ)を出力する。

現状の`HandlerExceptionResolverLoggingInterceptor`はHTTPステータスコードに応じてログレベルを決定しており、例外コード(メッセージID)に応じてログレベルを決定しているわけではない。上記の説明は誤っていると思われる。
詳細は https://github.com/terasolunaorg/terasoluna-gfw/issues/702 参照。

## Possible Solutions
https://github.com/terasolunaorg/terasoluna-gfw/issues/702 の対応に応じて、正しい記述に修正する。
共通ライブラリ側を対応しない場合は、現状の正しい記述に修正する。

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1
- [x] 5.2.2
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.7

## Change log(should be updated at the same time)
- [x] Required

#### add change log.
- [x] 5.4.0 (master)
- [x] 5.3.1
- [x] 5.2.2
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.7

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- [ ] Required

## Issue Links
- https://github.com/terasolunaorg/terasoluna-gfw/issues/702

**Comment by bttanakaysd** [comment]
* 修正箇所と修正案

項番 | 場所 | 記述 | 修正案
---- | ---- | ---- | ------
1 | [4.2.2.3.2. ユースケース単位でControllerクラスがハンドリングする場合の基本フロー](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-basic-flow-annotation-label) | HandlerExceptionResolverLoggingInterceptorは、ExceptionLoggerを呼び出し、**例外コード**に対応するレベル(info, warn, error)のログ(監視ログとアプリケーションログ)を出力する。 | HandlerExceptionResolverLoggingInterceptorは、ExceptionLoggerを呼び出し、**HTTPステータスコード**に対応するレベル(info, warn, error)のログ(監視ログとアプリケーションログ)を出力する。
2 | [4.2.2.3.3. サーブレット単位でフレームワークがハンドリングする場合の基本フロー](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-basic-flow-resolver-label) | HandlerExceptionResolverLoggingInterceptorは、ExceptionLoggerを呼び出し、**例外コード**に対応するレベル(info, warn, error)のログ(監視ログとアプリケーションログ)を出力する。 | HandlerExceptionResolverLoggingInterceptorは、ExceptionLoggerを呼び出し、**HTTPステータスコード**に対応するレベル(info, warn, error)のログ(監視ログとアプリケーションログ)を出力する。
3 | [4.2.2.3.4. Webアプリケーション単位でサーブレットコンテナがハンドリングする場合の基本フロー](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#web) | ExceptionLoggingFilterは、ServletExceptionを捕捉し、ExceptionLoggerを呼び出す。ExceptionLoggerは、**例外コードに対応するレベル**（**info, warn, error**）のログ(監視ログとアプリケーションログ)を出力する。ExceptionLoggingFilterは、ServletExceptionを再スローする。 | ExceptionLoggingFilterは、ServletExceptionを捕捉し、ExceptionLoggerを呼び出す。ExceptionLoggerは、**errorレベル**のログ(監視ログとアプリケーションログ)を出力する。ExceptionLoggingFilterは、ServletExceptionを再スローする。
4 | [4.2.2.3.4. Webアプリケーション単位でサーブレットコンテナがハンドリングする場合の基本フロー](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#web) | info,warn,errorレベルのログを出力する図になっている。 | errorレベルのみログ出力する図となるよう修正する。
5 | [4.2.3.1.1. 共通設定 項番(2)](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-how-to-use-application-configuration-common-label) | "BusinessException"が含まれている場合は、"***w***.xx.fw.8001"、 "ResourceNotFoundException"が含まれている場合は、"***w***.xx.fw.5001"が「例外コード(メッセージID)」となる。 | "BusinessException"が含まれている場合は、"***e***.xx.fw.8001"、 "ResourceNotFoundException"が含まれている場合は、"***e***.xx.fw.5001"が「例外コード(メッセージID)」となる。
6 | [4.2.3.1.1. 共通設定 項番(2)](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-how-to-use-application-configuration-common-label) | ここでは、”BusinessException”に、メッセージIDが指定されなかった場合の対応で定義をしているが、後述の”BusinessException”を発生させる実装側で、**「例外コード**(**メッセージID**)」を指定することを推奨する。“BusinessException”に対する「例外コード(メッセージID)」の指定は、”BusinessException”発生時に指定されなかった場合の救済策である。 | ここでは、”BusinessException”に、メッセージIDが指定されなかった場合の対応で定義をしているが、後述の”BusinessException”を発生させる実装側で、**メッセージID**を指定することを推奨する。“BusinessException”に対する「例外コード(メッセージID)」の指定は、”BusinessException”発生時に指定されなかった場合の救済策である。
7 | [4.2.3.1.1. 共通設定 項番(3)](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-how-to-use-application-configuration-common-label) | 例外コードは、ログに出力するのみ。（画面での取得もできる。JSPへのリンク） | 例外コードは、ExceptionLoggerによりログに出力される。（画面での取得も可能である。View(JSP)から例外コードを参照する方法については、\ :ref:`exception-handling-how-to-use-codingpoint-jsp-exceptioncode-label`\ を参照されたい。）
8 | [4.2.3.2.3. 例外をキャッチして、処理を継続させる Warning](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-how-to-use-codingpoint-service-continue-label) | exceptionLoggerで、log()を使用した場合には、errorレベルで出力されるため、デフォルトで監視ログにも出力される。 | ExceptionLoggerでlogメソッドを使用した場合には、例外コードによりログレベルを判定する。アプリケーションログと同時に監視ログも出力したい場合は、デフォルト設定ではerrorレベルを監視ログに出力するため、errorメソッドを使用すると良い。
9 | [4.2.5.1. 共通ライブラリから提供している例外ハンドリング用のクラスについて 項番(13)](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-about-classes-of-library-label) | Spring MVCより提供されているSimpleMappingExceptionResolverを継承し、**例外コードのResultMessages**を、Viewから参照できるように機能追加を行っている。 | Spring MVCより提供されているSimpleMappingExceptionResolverを継承し、**例外コード及びResultMessages**を、Viewから参照できるように機能追加を行っている。
10 |[4.2.5.1. 共通ライブラリから提供している例外ハンドリング用のクラスについて 項番(14)](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html#exception-handling-about-classes-of-library-label) | なし | なお、HTTPレスポンスコードによるログ出力レベルの切り替えが、プロジェクトの要件に合わない場合は、logメソッドを拡張する事で、デフォルトの挙動を変更する事が可能である。

**Comment by yoshikawaa** [comment]
@bttanakaysd 
ChangeLogを書きましょう。
* 5.4は共通ライブラリの変更による修正 + 既存の誤り修正
* 5.3以前は既存の誤り修正

**Comment by yoshikawaa** [comment]
@itouyun or @btsatouhrzzp 
plz write issue for translation, and close this.

**Comment by btsatouhrzzp** [comment]
I created #2906 issue. This issue is closed.
