### ISSUE TITLE
Add 'Translation' section to Issue Template

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2798]
## Description
This is maintenance task.
Now, it's hard to judge from issue description whether a task in one Issue contains a translation.

## Possible Solutions
Add new section **Translation**.
Make it possible to choose from `correspond` or `not correspond(create new issue)`.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] master

Backport is not necessary. 
Because only `ISSUE_TEMPLATE.md` of `master` branch is affected.
~~- [ ] 5.3.x~~
~~- [ ] 5.2.x~~
~~- [ ] 5.1.x~~
~~- [ ] 5.0.x~~
~~- [ ] 1.0.x~~

## Issue Links
* #XXX

## ChangeLog
not required

**Comment by btsatouhrzzp** [comment]
マージが完了したため本issueをクローズします。
