### ISSUE TITLE
Remove english guideline from 1.0.x branch

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2803]
これはメンテナンスタスクです。
## Description

現状、TERASOLUNA Server Framework for Java (5.x) Development Guidelineは日本語版と英語版の両方をHTMLで公開しているが、TERASOLUNA Global Framework Development Guidelineは日本語版のみしか公開していない。

にもかかわらず、TERASOLUNA Global Framework Development Guidelineのメンテナンスブランチ（`1.0.x`ブランチ）には英語版のリソースが存在し、開発者がメンテすべきか混乱する。

## Possible Solutions
`1.0.x`ブランチから英語版のリソースを削除し、日本語版のみメンテする。

* フォルダごと削除
source_en
conf\latexpdfen
* ファイル削除
build-html_en.bat
build-html_en.sh
build-pdf_en.sh
* ファイル内容変更
.gitignoreから`build_en`を削除
.travis.ymlから`  - sh ./build-html_en.sh`を削除
Makefileから`latexpdfen:`の箇所を削除
* README.md変更
*Source files*内の`English version`を削除
*Build HTML files for the English*を削除
*Build a PDF file for the English*を削除
*Terms of use refer to here*のリンク先を変更

## Affects Version/s
* 1.X.X.RELEASE

## Fix Version/s
- [x] 1.0.7

## Change log(should be updated at the same time)
- Not Required

## English Translation
- Not Required 

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by itouyun** [comment]
Thank you for your work!!
This issue is closed.
