### ISSUE TITLE
[JMS] The transaction setting for AsyncReceive should be reviewed.

### ISSUE THREAD

**Issue by btkouei** [terasolunaorg/guideline#2814]
## Description
``DefaultMessageListenerContainer``には独自のトランザクション管理機構がある為、``ChainedTransactionManager``は使用しない方が正しいと思われる。``<jms:listener-container>``に``ChainedTransactionManager``を指定した場合は、DBのトランザクションよりも先にJMSのトランザクションがcommitされてしまう。

#### 詳細
このIssueは、以下の2つのトランザクションについての話になる。
* spring-jmsのDefaultMessageListenerContainer(以下、DMLC)が管理するjms sessionのTx
  * 現状、@JmsListenerのtransaction-managerにChainedTransactionManagerを設定している
* Serviceが利用するDBのTx
  * 現状、Serviceに`@Transactional`を付与している

もともとガイドが実現したいのは以下の事項。
* JMSのRequest-Replyを1Txで実現する。
  * 受信はDMLCで行う。
  * 送信はService内のJmsTemplateで行う。
* ServiceではDBアクセスする。
* DBTxはLocalTxとし、JMSTxの内側にDBTxが存在するようにする。

現状の問題点は、**DMLCのTxMgrはJTAを使う時のためのものなのに**、これを使っている結果、Tx境界が入れ子になり意図しない挙動をする点である。
※ このことはDefaultMessageListenerContainerのjavadocにも記載あり。
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jms/listener/DefaultMessageListenerContainer.html

DMLCにおけるTx処理の順序は、

. DMLCがTxMgrをbegin
. DMLCがsessionをtransacted=trueでcreate
. DMLCがsessionをcommit
. DMLCがTxMgrをcommit

という流れになっている。(条件次第で異なる可能性あり)

これを前述のとおりの順序(＝以下の順序)にすることが、本Issueが解決したい対象になる。

. JMSがbegin
. DBがbegin
. DBがcommit
. JMSがcommit

## Possible Solutions
非同期受信のトランザクション管理(8.2.2.3.6. トランザクション管理)など関連箇所を以下のように修正する。
-   非同期受信では``JmsTransaction``や``ChainedTransactionManager``は使用せず、DMLCにJMS Tx管理は委ねる
-  ``listener-container``の``acknowledge``は``transacted``にする（現状の記載の通りで変更なし）
- Serviceの入れ子構造にしなくてJMS Tx と DB Tx は分割されるので、Serviceの入れ子によるTxの分割の紹介は削除する

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
* [x] 5.4.0 (master) ja
* [x] 5.4.0 (master) ja [rework](#issuecomment-313432598)
* [x] 5.3.1 (5.3.x) ja

## Issue Links
* #XXX

## Change log(should be updated at the same time)
 - [ ] Required

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- Not Required

**Comment by kazuki43zoo** [comment]
DMLCは`DefaultMessageListenerContainer`の略？所見の人は何の略語なのかわからないと思うのでクラス名で記載してほしいです。

**Comment by btkouei** [comment]
クラス名に修正しました。

**Comment by itouyun** [comment]
@btkouei 
Thank you for your correspondence.
English Translation issue is #2835 , this issue is closed.

**Comment by kazuki43zoo** [comment]
@itouyun 

Is not need a change log ?
I think it is need.

**Comment by kazuki43zoo** [comment]
@itouyun 

Is  5.4.0 only ? I think this issue should backport to 5.3.1 because it is major bug.

**Comment by itouyun** [comment]
@kazuki42zoo @btsatouhrzzp 
This issue needs change log but  we cannot write change log for new format because new format is not specified.
...
更新履歴のフォーマットが今後変更となるため、最近のissueは、change log が必要としても、一旦未対応で進んでいた経緯がありまして、リリース前に遡及して新フォーマットとして書き込もうと思っていました。
しかし、この際今までのフォーマットで一旦記載してしまい、リリース前にそれを変更する、のほうがやりやすいかもしれないですね・・・と今考え直しました。
というわけで、本issueで更新履歴も修正してもらうようにします。

**Comment by itouyun** [comment]
@kazuki43zoo @btkouei 
当初は非同期の場合は`proxy`を基本的に入れましょう、という、バグ対応としてそもそも非同期実装のやり方（推奨の仕方）を変更するため、**仕様変更**レベルの変更であるとして、5.4.0のみに対応する予定でした。
しかし、possible solutionに見直しが入り、**仕様変更**レベルの変更ではなくなり、単純なbug fixとなったため、 @kazuki43zoo さんの言う通り、5.3.1にもバックポートするようissueを変更します。

**Comment by kazuki43zoo** [comment]
please backport to 5.3.x branch.

**Comment by itouyun** [comment]
`Change log`が修正されていないので（`master`,`5.3.x`共に）リリース前に他のissueのChangeLog精査とともに実施する必要あり。
他issueと同様に、その残タスクはあるが、このissueそのものはcloseする。
