### ISSUE TITLE
'Parent project' is no longer referable.

### ISSUE THREAD

**Issue by btkouei** [terasolunaorg/guideline#2815]
## Description
「親プロジェクト」という記載が見られるが、フラットなプロジェクト構成に変わったため表現を見直すべき。

e.g.
8.2.3.1.1. Apache ActiveMQを利用する場合
```
上記設定例は、依存ライブラリのバージョンを親プロジェクトである terasoluna-gfw-parent で管理する前提であるため、pom.xmlでのバージョンの指定は不要である。 上記の依存ライブラリはterasoluna-gfw-parentが利用しているSpring IO Platformで定義済みである。
```
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/MessagingDetail/JMS.html#apache-activemq

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

## Change Log
(To be written later by project member)

**Comment by kazuki43zoo** [comment]
「親プロジェクト」=「pom.xmlの`<parent>`要素内で指定しているプロジェクト」のことを指していると思うので、特に問題ない気がします。どこが問題ですか？

**Comment by itouyun** [comment]
親プロジェクトとして `terasoluna-gfw-parent` という名称を使っていること、な気がします。

**Comment by itouyun** [comment]
`terasoluna-gfw-parent`は terasoluna-gfwの`artifactId`ですね、失礼しました。
そういうプロジェクト名があるのだと錯覚しました。
本件は問題なさそうなのでクローズします。
