### ISSUE TITLE
improve the chapter structure of oauth

### ISSUE THREAD

**Issue by btmatsudayul** [terasolunaorg/guideline#2818]
## Description
現在のOAuth章は各機能（認可サーバ、リソースサーバ、クライアント）の一連の実装方法説明の中で
 グラントタイプ別の設定差異を説明している。

本章を利用する際には、業務要件に合わせたグラントタイプ（例：インプリシットグラント）からそれに必要な
実装方法を参照する（したい）ケースが多いと考えられるが、現在、当該情報が本文中に埋もれており、
全量が把握しづらい形となっているため、これを改善する。

## Possible Solutions
* How to use節を現在のサーバ単位からグラントタイプ単位に説明を行うよう変更。
　その上で、最も利用するケースが多いと考えられる認可コードグラントを基本として、
　その他グラントタイプの節では認可コードグラントからの差分を紹介するよう変更する。
* How to use節の先頭に、利用するグラントタイプ、または作成するアプリケーションに応じた
　ガイドラインの読み進め方の紹介を追加する。

## Affects Version/s
* 5.3.1.RELEASE
* 5.4.0.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)

## Change log(should be updated at the same time)
* [x] Required

## English Translation
* [x] Required, create a new issue for handling

## Migrating Guide
* Not Required

## Issue Links
* #XXX

**Comment by itouyun** [comment]
issueの内容を更新しました（Change log、English Translation、Migrating Guide）。
ご確認ください。

**Comment by yoshikawaa** [comment]
@itouyun @btsatouhrzzp 
Please write issue for translation, and close this.

**Comment by btsatouhrzzp** [comment]
I created #2929 issue. This issue is closed.
