### ISSUE TITLE
add error handling section for oauth

### ISSUE THREAD

**Issue by btmatsudayul** [terasolunaorg/guideline#2819]
## Description
OAuth章で紹介している、Spring Security OAuthを利用した認可機能の実装では、
リソースオーナなどのユーザ操作によりAPIにおいて様々な例外が発生する可能性がある。

通常、アプリケーション開発を行う際にはこれらの適切なハンドリングが必要となるが、
現在、その実装方法に関する説明が不足しているため、追加を行う。

## Possible Solutions
以下の修正を行う。
* How to use節
  * 認可サーバの各エンドポイント、およびリソースサーバにおいてリソースオーナ起因で
　発生しうるエラーを整理し、そのハンドリング方法の実装例の説明を追加。
* Appendix節
  * 節の追加。
  * 問題解析時の参考となるよう、Spring Security OAuthのAPIを利用した際に
　　発生しうるエラー（リソースオーナ起因、環境起因等）の一覧を追加。

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- [x] Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@btsatouhrzzp or @btideues 
Please write issues for translation and migration, and close this.

**Comment by btsatouhrzzp** [comment]
I created #2934 issue. This issue is closed.
