### ISSUE TITLE
add description of oauth extension points

### ISSUE THREAD

**Issue by btmatsudayul** [terasolunaorg/guideline#2820]
## Description
OAuthを利用したアプリケーション開発では、要件に沿って独自のリクエストパラメータなどを
追加するケースが考えらる。

OAuth章で紹介している、Spring Security OAuthを利用した認可機能の実装においては
Spring Security OAuthの拡張ポイントを把握し、要件に沿った改修を行う必要があるが、
現在、拡張ポイントの説明がないため、追加を行う。

## Possible Solutions
Appendix節へSpring Security OAuthのアーキテクチャ詳細を説明する節を追加する。

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@btsatouhrzzp 
Pleaes write issue for translation, and close this!

**Comment by yoshikawaa** [comment]
@btideues @btkigamim 
Thanks for your work!

**Comment by btsatouhrzzp** [comment]
I created #2939 issue. This issue is closed.
