### ISSUE TITLE
Minor typos of Exception Name

### ISSUE THREAD

**Issue by itouyun** [terasolunaorg/guideline#2824]
## Description

not Ru`m`timeException but Ru`n`timeException.
on this guideline http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.html

## Possible Solutions

RumtimeException -> RuntimeException
* 4 points.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
* [x] 5.4.0(master) ja
* [x] 5.3.1 ja
  * Already English version is fixed.

## Issue Links
* #XXX

## ChangeLog
* not required

**Comment by btsatouhrzzp** [comment]
マージが完了したため本issueをクローズします。
