### ISSUE TITLE
The table layout collapse of ChangeLog in guideline of English version.

### ISSUE THREAD

**Issue by btsuzukisnzh** [terasolunaorg/guideline#2862]
## Description
英語版ガイドラインの変更履歴の表のレイアウトが途中から崩れてしまっています。

英語版ガイドライン (5.3.0.RELEASE)
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/en/Introduction/ChangeLog.html

## Possible Solutions
ChangeLog.rstの186行目の先頭3桁分のスペースがNo Break Space (U+00A0) であるため、
半角スペース (U+0020) に修正する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_en (master)
- [x] 5.3.1_en (5.3.x)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- Not Required 

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by kazuki43zoo** [comment]
内容的な不具合ではないのでbug->clerical errorにしました。

**Comment by yoshikawaa** [comment]
@btsatouhrzzp 
Fix Version/s を `ja` -> `en` に変更して、`5.4.0`にチェックつけておきました。

**Comment by btsatouhrzzp** [comment]
マージが完了したため本issueをクローズします。
