### ISSUE TITLE
Order of index in English version is wrong

### ISSUE THREAD

**Issue by kumagaikzk** [terasolunaorg/guideline#2872]
## Description
Compare between Japanese version and English version, the order of index is different. 

```
9.9. Implementation Example of Typical Security Requirements
9.10. OAuth
```

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

According to the original version(Japanese version), it should be...

```
9.9. OAuth
9.10. Implementation Example of Typical Security Requirements
```

## Affects Version/s
- 5.3.0.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0_ja (master)
- [ ] 5.3.1_ja (5.3.x)
- [ ] 5.4.0_en (master)
- [ ] 5.3.1_en (5.3.x)

## Change log(should be updated at the same time)
(To be selected later by project member)
- [ ] Required
- Not Required

## English Translation
(To be selected later by project member)
- [ ] Required, handle with the same issue
- [ ] Required, create a new issue for handling
- Not Required 

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #2855 重複

**Comment by btsatouhrzzp** [comment]
本件#2855 と重複しているため、クローズする。対応は#2855 で実施。
