### ISSUE TITLE
[Typo] oorg.springframework

### ISSUE THREAD

**Issue by kumagaikzk** [terasolunaorg/guideline#2878]
## Description
There is typo in OAuth.rst

```
oorg.springframework.security.oauth2.provider.ClientDetailsService
```

## Possible Solutions
It should be...

```
org.springframework.security.oauth2.provider.ClientDetailsService
```

## Affects Version/s
- 5.3.0.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0_ja (master)
- [ ] 5.3.1_ja (5.3.x)
- [ ] 5.4.0_en (master)
- [ ] 5.3.1_en (5.3.x)

## Change log(should be updated at the same time)
(To be selected later by project member)
- [ ] Required
- Not Required

## English Translation
(To be selected later by project member)
- [ ] Required, handle with the same issue
- [ ] Required, create a new issue for handling
- Not Required 

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by btkigamim** [comment]
Thank you for your pointing out the typo.

Because We modify the typo with a different issue(#2891),
Set this issue as @dupricate and close it.
