### ISSUE TITLE
[1.0.x, 5.0.x] Error on Building PDF

### ISSUE THREAD

**Issue by btsatouhrzzp** [terasolunaorg/guideline#2882]
## Description
1.0.Xおよび5.0.xのPDFのビルド時にエラーが発生する。
一方、5.1.x以降（master含む）のPDFのビルドではエラーが発生せずに、正常終了する。

■エラー
```
make -C build/latex all-pdf-ja
make[1]: ディレクトリ `/opt/jenkins/jobs/guideline-github/workspace/build/latex` に入ります
make[1]: *** ターゲット `all-pdf-ja` を make するルールがありません.  中止.
make[1]: ディレクトリ `/opt/jenkins/jobs/guideline-github/workspace/build/latex` から出ます
make: *** [latexpdfja] エラー 2
```

## Possible Solutions
1.0.xおよび5.0.xのMakefileをmasterにあわせる。

## Affects Version/s
- 5.0.X.
- 1.0.X.

## Fix Version/s
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- Not Required 

## Migrating Guide
- Not Required

## Issue Links
- #1504 (バックポート漏れ対象issue) ※本原因
- #1838 (バックポート漏れ対象issue)
- #818 (1.0.x対応をする上で考慮しなければならないissue)
- #2803 本issue対応後に実施するべきissue

**Comment by itouyun** [comment]
PDFをビルドできないエラーを確認したところ、issue(#1504)のバックポート漏れであることが判明。
原因と結果は異なるが、本対応をしている場合、本issueの問題は起こらない。

よって、#1504のバックポートと、ついでに#1838のバックポートを行う方針で、対応する。

しかし、単純なバックポートにはならない想定。

**Comment by btsatouhrzzp** [comment]
5.0.xについては、#818 の対応で`TERASOLUNAServerFrameworkForJavaDevelopmentGuideline.tex`に変更されたが、1.0.xは、`TERASOLUNAGlobalFrameworkDevelopmentGuideline.tex`のままである。
そのため、差異があり単純なバックポートが行えない。

**Comment by itouyun** [comment]
@btkamiyae @btsatouhrzzp 
Thank you for your work!

This issue is closed.
