### ISSUE TITLE
"f:js()" code sample is invalid.

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2890]
## Description
[XSS対策/9.7.1.3.2. 出力値をf:js()関数でエスケープする例](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/XSS.html#f-js)
`f:js()`を使用してエスケープした出力結果HTMLを実行すると、スクリプトの実行に成功してしまう。
コード例だがセキュリティに関わる部分なので、修正したほうが良い。

そもそもユーザ入力値を`<script>${f:js(message)}<\/script>`で埋め込んでいるが、実際には`<script>`タグを含んだユーザ入力値が問題になるのであって、この例は妥当ではないのでは？

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0_ja (master)
- [ ] 5.3.1_ja (5.3.x)
- [ ] 5.4.0_en (master)
- [ ] 5.3.1_en (5.3.x)

## Change log(should be updated at the same time)
(To be selected later by project member)
- [ ] Required
- Not Required

## English Translation
(To be selected later by project member)
- [ ] Required, handle with the same issue
- [ ] Required, create a new issue for handling
- Not Required 

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by ikeyat** [comment]
#2531

**Comment by yoshikawaa** [comment]
@ikeyat 
Thanks, closed with `duplicate`.
