### ISSUE TITLE
Broken link "vkvn" of copyright.

### ISSUE THREAD

**Issue by btkamiyae** [terasolunaorg/guideline#2901]
## Description
コピーライト部分「Theme by `vkvn`」の リンク（"http://github.com/vkvn"） が切れている。

## Possible Solutions
Update footer!

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1 (5.3.x)
- [x] 5.2.2 (5.2.x) ~~；修正不要~~
- [x] 5.1.2 (5.1.x) ~~：修正不要~~
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)
- [x] private(master/J)
- [x] private(1.4.x/J)
- [x] private(master/T)

## Final Solution
~~Sphinxビルド時の`solar-theme`のバージョンを1.3.3に上げる。
以下を1.3.3へ更新する必要がある。
https://github.com/terasolunaorg/guideline/tree/master/theme/solar~~

バージョンを1.3.3に上げると、影響が大きいため、リンク切れになっている箇所の修正のみ行う。

## Change log(should be updated at the same time)
- Not Required

## English Translation
- Not Required 

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by itouyun** [comment]
Themeの著作者のGitHubアカウントが消えてしまったんですかね。
著作権にかかわる問題なので、著作者のライセンスルールを参照したいですが、大本が消えてしまったとなると、確認が難しいですかね。。。

＜考えられる Possible Solution＞
1. vkvnさんの現在のアカウント、現在のテーマの配信場所を特定し、ライセンスを確認し、あるべき姿へ更新
2. ライセンスルールは変わっていないとして、敢えて現状維持
3. 記述を削除

とりあえずは1の方向性で調査してから、見つからない場合は2か3を採用する、という流れがベターですね。

**Comment by yoshikawaa** [comment]
@itouyun
今年度に入ってから、私もリンク切れに気づいたので調べてみたことがあります。

https://devhub.io/repos/vimalkvn-solar-theme
devhubのページからリンクがある通り、少し前までMr. @vimalkvn がリポジトリを公開して、github.ioに紹介ページも公開していましたが、今では削除してしまったようです。(調査時そちらで公開されていたsolarテーマのコード上も、著作権表示は @vkvn のままでした)
アカウント名は @vkvn から変更したのだと思われます。(これは想像)

このため、以前の調査時は特に問題なしで、むしろ修正すべきでないと判断していました。

OSS公開をやめてしまったのだとすれば、このまま使ってて良いのかという議論もありそうですが、Mr. @vimalkvn に事実確認して、著作権表示を更新すれば良いのであれば、修正すれば良いと思われます。

**Comment by vimalkvn** [comment]
I had changed my user name from vkvn to vimalkvn and also deleted the solar-theme repository as it was not being updated. I will upload the last version at http://github.com/vimalkvn/solar-theme. Please use that link. Theme is also available on [PyPI](https://pypi.python.org/pypi/solar-theme). 

License is BSD. 

Sorry for the confusion!

**Comment by yoshikawaa** [comment]
Mr. @vimalkvn 
Awesome! Thank you so much for your polite correspondence to my mentions.

**Comment by vimalkvn** [comment]
No problem @yoshikawaa Repository is now back online https://github.com/vimalkvn/solar-theme.

**Comment by itouyun** [comment]
Mr. @vimalkvn
Thank you so much for your comments and updating theme!

@btkamiyae
Our Guide will update solar-theme version to 1.3.3.
This issue will fix!

**Comment by bttsuchikawaf** [comment]
1.3.3のsolar-themeを現在のガイドラインにそのまま適用し、
（guideline/theme/solar 配下をsolar-theme/solar_theme 配下で上書く）
sphinxビルドでhtmlを出力して確認したところ、以下の問題点が見つかりました。

- フォントが異なる(ヘッダ部、章タイトル、英字など)
- README.rstが存在しない
	⇒似たファイルがsolar-themeに存在する
	https://github.com/vimalkvn/solar-theme/blob/master/README.rst
- NEWS.txtが存在しない
	⇒似たファイルがsolar-themeに存在する
	https://github.com/vimalkvn/solar-theme/blob/master/HISTORY.rst
- スクロールバーの各章の項目が畳まれない
- © Copyright が重複する
	`© Copyright © Copyright 2013-2017, NTT DATA Corporation. © Copyright 2017, NTT Corporation.. Created using Sphinx 1.6.3.Theme is Solar`　と出力される

また、 [guideline/theme/solar](https://github.com/terasolunaorg/guideline/tree/master/theme/solar) と[guideline/theme/solar/solar_for_githubpages](https://github.com/terasolunaorg/guideline/tree/master/theme/solar_for_githubpages) が存在しますが
どちらも1.3.1のsolar-themeを適用するという認識で間違いないでしょうか。

**Comment by itouyun** [comment]
@bttsuchikawaf 
ビルド後の話とビルド前の話が混ざっています。わかりやすく書き直してもらえますか？
ビルド前の話はGitHub運用の話なので重要じゃなさそうですが、ビルド後の変化については、要検討ですね。

> スクロールバーの各章の項目が畳まれない

こちらどういう意味でしょうか、□マークの＋－記号をクリックしてたたむ機能そのものがなくなってしまったということでしょうか。その場合、どこまで展開された状態で表示されるのでしょうか。例えば、OAuth章など、目次が長いですが、目次と同レベルの展開量なのでしょうか（そうなると相当読みづらい気がします）

> © Copyright が重複する

デフォルトで接頭語に含まれる仕組みなんですね。
現在のCopyrightが以下のようになっているからですね。
https://github.com/terasolunaorg/guideline/blob/8bc5ba74c3d1ba017bcce1df38ba7ec6be7fffe4/conf/html/conf.py#L44 
これは、 #2628 の対応の時に、`layout.html` を独自修正したので、現在は重複していません。新しいものを導入したとき、独自修正も再度反映する必要があります。
また本件は、 #2898 と一緒に考える必要がありそうです。（努力目標）

> また、 [guideline/theme/solar](https://github.com/terasolunaorg/guideline/tree/master/theme/solar) と[guideline/theme/solar/solar_for_githubpages](https://github.com/terasolunaorg/guideline/tree/master/theme/solar_for_githubpages) が存在しますが
どちらも1.3.1のsolar-themeを適用するという認識で間違いないでしょうか。

ソースコード検索をすると [guideline/theme/solar](https://github.com/terasolunaorg/guideline/tree/master/theme/solar) が使われているように見えました。 [guideline/theme/solar/solar_for_githubpages](https://github.com/terasolunaorg/guideline/tree/master/theme/solar_for_githubpages) はどこで利用されているのでしょう…。内部確認が必要です。

**Comment by bttsuchikawaf** [comment]
@itouyun 
1.3.3のsolar_themeとの差分について
ビルド前（GitHub運用関連）とビルド後（html）の話に分けてを整理しました。

ビルド後（html）については、1.3.3での変更箇所が現行と比べた場合に
htmlにどのように影響したかを確認しました。

【ファイル構成について】
[1.3.0（現在のガイドライン）]
 guideline / theme / solar
 / static
 　　・solar.css
 　　・solarized-dark.css 
 　　・jquery.treeview.css
 　　・jquery.treeview.js
 　　・subtle_dots.png
 　　・その他(画像)
 ・NEWS.txt
 ・README.rst
 ・layout.html
 ・theme.conf

[1.3.3]
 solar-theme / solar-theme
 / static
 　　・solar.css
 　　・solarized-dark.css 
 　　・subtle_dots.png
 ・init__.py 
 ・README.rst
 ・layout.html
 ・theme.conf

【ビルド前（GitHub運用関連）】
- README.rstが存在しない
似たファイルはsolar-theme直下に存在する
https://github.com/vimalkvn/solar-theme/blob/master/README.rst
- NEWS.txtが存在しない
似たファイルはsolar-theme直下に存在する
https://github.com/vimalkvn/solar-theme/blob/master/HISTORY.rst
- [guideline/theme/solar](https://github.com/terasolunaorg/guideline/tree/master/theme/solar) と[guideline/theme/solar/solar_for_githubpages](https://github.com/terasolunaorg/guideline/tree/master/theme/solar_for_githubpages) が存在するが、solar_for_githubpagesはどこで利用されているのか

【ビルド後（html）】
- 英数字のフォントが異なる
- Note、Warning、Tipsのpaddingが異なる(1.3.3では0.2em少ない)
- スクロールバーについて
1.3.3ではlaout.htmlにスクロールバーに関する記載がないため、以下の状態となる。
    - ＋－記号をクリックして畳む機能がない
章番号が付与された状態のもくじの内容が、全て展開された状態でスクロールバーに表示される。
解像度1920×1080の画面でOAuthのページを見ると、スクロールバーの長さがページ先頭から「9.9.1.2.1. ロール」の章と同程度の長さになる。（とても長くて読み辛い）
    - scroll sidebar（スクロールするとついてくる機能）がない
- © Copyright が重複する
 `© Copyright © Copyright 2013-2017, NTT DATA Corporation. © Copyright 2017, NTT Corporation.. Created using Sphinx 1.6.3.Theme is Solar` と出力される
⇒　#2628 の修正を反映させる必要がある。また、#2898 と一緒に考える必要がある

**Comment by bttsuchikawaf** [comment]
@itouyun 
スクロールバーについて、
ガイドラインのリポジトリをgitHubにinitial commitした時点のthemeの状態を確認しましたが、
＋－記号をクリックして畳む機能とscroll sidebar（スクロールするとついてくる機能）が存在していました。
こちらでthemeを修正しているのは、copyrightの部分のみのようです。

**Comment by itouyun** [comment]
@bttsuchikawaf 
ということはバージョン更新によってスクロール機能と畳む機能は削除されてしまったんですね。。。
自力でその機能を差し込むのもナンセンスな気がするので、開発元に対して依頼するかなりして、今回は更新を見送ったほうが良いかもしれませんね・・・。

**Comment by bttsuchikawaf** [comment]
@itouyun 
themeのバージョン更新はスクロール機能の問題があるため一旦置いておくとのことですが、
リンク切れの部分については https://github.com/vimalkvn/solar-theme に変えたほうが良いでしょうか？

**Comment by itouyun** [comment]
Mr. @vimalkvn

We have modified and used solar-theme 1.3.0.
May we continue to use soler-theme 1.3.0?
And... Would we be better to update URLs( from vkvn to vimalkvn ) on 1.3.0 that we use?

**Comment by vimalkvn** [comment]
@itouyun Please go ahead and use 1.3.0 and update URLs if that makes it easy for you.

**Comment by itouyun** [comment]
Mr. @vimalkvn
Thank you so much for your comments!
We will do so.

**Comment by itouyun** [comment]
@bttsuchikawaf 
アップデートは取りやめにして、リンクを修正することになりました。
Final Solutionの更新をお願いします。

リンク修正の際は、こちらをご参考に（プラス横展開も）おねがいします。
https://github.com/vimalkvn/solar-theme/commit/aa29dadb735b05697920818e932e1524bdb00344

**Comment by bttsuchikawaf** [comment]
@itouyun 
横展開を行ったところ、theme配下に置かれているREADME.rst
( https://github.com/terasolunaorg/guideline/blob/master/theme/solar/README.rst )について
いくつか気になる点がありました。

* 以下のリンクがリンク切れとなっている
Preview のリンクはhttps://vimalkvn.github.io/solar-theme に変更で良さそうですが
Downloadのリンクに該当するものはどこになるのでしょうか。
https://github.com/terasolunaorg/guideline/blob/bcfcf74936668ad725106dd27967a452a8906e62/theme/solar/README.rst#L5-L7
https://github.com/terasolunaorg/guideline/blob/bcfcf74936668ad725106dd27967a452a8906e62/theme/solar/README.rst#L9-L11

* Lisenseが現在のものと異なる
GNU General Public License から現在はBSD licenseに変更されています。
https://github.com/terasolunaorg/guideline/blob/master/theme/solar/README.rst#license
https://github.com/vimalkvn/solar-theme/blob/master/README.rst

以上を踏まえまして、README.rstについて
どのように対応すればよろしいでしょうか？

**Comment by itouyun** [comment]
@bttsuchikawaf 
バージョンそのものは1.3.0なので、ファイルそのものの差し替え等は不要です。
今回はリンク切れのみ、各種ファイル修正しましょう。
ダウンロードは  https://pypi.python.org/pypi/solar-theme ですかね？

**Comment by yoshikawaa** [comment]
@hosoitk 
Please assign anyone to backport.

**Comment by yoshikawaa** [comment]
@btiidakua 誰かが5.2と5.1は修正不要と書いてますが、修正対象のように見えますね。

* 5.2 : https://github.com/terasolunaorg/guideline/blob/0acdcdf3bd8d9a80bc5ce5edc76f72bca421c03e/theme/solar/layout.html#L34
* 5.1 : https://github.com/terasolunaorg/guideline/blob/3beacaa254fe64f7fbac42d151ba32efb0876b25/theme/solar/layout.html#L34

**Comment by btiidakua** [comment]
@yoshikawaa 
5.2と5.1も修正します。

**Comment by btiidakua** [comment]
@yoshikawaa 
5.0の修正も必要でしょうか？

**Comment by yoshikawaa** [comment]
@hosoitk 
English version is also supported.
