### ISSUE TITLE
Inappropriate code-highlight

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#2903]
## Description
コードハイライトを行っているところがあるが、適切な位置にコードハイライトが行われていないところがある。

たとえば・・・

* [4.1.2.2.4. バリデーションのグループ化](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validationgroupvalidation)の2つめのコード例(JSPの例)
  説明は「JSPに大きな変更はない。」だけだが、コードにはハイライトがある。 ハイライトするなら何かしら説明を追加する方がよいと思います。

* [4.1.2.2.4. バリデーションのグループ化](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validationgroupvalidation)の3つめのコード例(Controllerクラスの例)
  説明項番がふられている部分ではないところにハイライトがかかっている。

あたりが不適切な感じをうけます。

## Possible Solutions

* ハイライトを適切な位置に変更する + ハイライトしている部分に適切な説明を加える
* ハイライトを消す

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (guideline/master) 【共通】
- [x] 5.3.1_ja (guideline/5.3.x) 【共通】
- [x] 5.4.0_en (guideline/master) 【共通】
- [x] 5.3.1_en (guideline/5.3.x) 【共通】
- [x] 1.5.0_ja (guideline-macchinetta-jsp/master) 【共通】
- [x] 1.4.1_ja (guideline-macchinetta-jsp/1.4.x) 【共通】
- [x] 1.5.0_ja (guideline-macchinetta-thymeleaf/master) 【共通】

## Final Solution
ハイライトを消す。
See https://github.com/terasolunaorg/guideline/issues/2903#issuecomment-328439630

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [x] Required, handle with the same issue

## Migrating Guide
- Not Required

## Issue Links
\-

**Comment by itouyun** [comment]
@kazuki43zoo 
issueの起票ありがとうございます。
以下確認し、可能な限り横展開して改善いたします。
- ハイライトバグが生じた原因の特定
- ハイライトをつけるルールの確認

文字の誤植ではないですが、色的な誤植なのでclerical errorとします。

**Comment by itouyun** [comment]
本件に関して横展開してすべてのページにおいてルールを統一化する、などは難しいですが、指摘された箇所とその同ファイルの周辺（同じ開発者がミスしている可能性があるため）の横展開として、少なくともバグっているところの修正までは最低実施する方針としましょう。

ハイライトバグの直接原因は`emphasize-lines: 18-26,38-42`などの行数設定ミス、ですね。
根本原因は不明ですが、コードを書き換えたにもかかわらず、この定義を修正し忘れた、、などでしょうか。。。

**Comment by itouyun** [comment]
本件のissue対応範囲は「clerical error」箇所の修正、とします。
その横展開範囲は、同rstファイル内、とします。（前回コメント参照）
修正方針は、『ハイライトを消す』とします。

横展開調査をしたところ、ハイライトする、しない、の方針がブレ、実際のガイドラインもハイライトの有無はコードによって基準がブレていました。
しかし、そちらはエラーではないため、ガイドライン全体の統一に関しては、ルールそのものの策定を経て、「improvement」として別issueで対応します。

**Comment by itouyun** [comment]
@btkamiyae 
Thank you for your work!
