### ISSUE TITLE
Improve inline code block style

### ISSUE THREAD

**Issue by kumagaikzk** [terasolunaorg/guideline#2910]
## Description
The position of double qotation is mismatch in ImplementationAtEachLayer/ApplicationLayer.rst. 

```
このメソッドに割り当てられるリクエストURLは、\ "``{コンテキストパス}/hello"``\ となる。
```

## Possible Solutions

```
このメソッドに割り当てられるリクエストURLは、\ ``"{コンテキストパス}/hello"``\ となる。
```

## Final Solution
* インラインコードブロックの文法ミス（上記ミス含む）を横展開で修正。
* インラインコードブロックを囲むダブルクォートを削除。
```
\ ``"xxx"``\ or "\ ``xxx``\"
```
↓
```
\ ``xxx``\
```

```
``"xxx"`` or "``xxx``"
```
↓
```
``xxx``
```
ただし、インラインコードが一文字の場合、ダブルクォートで
インラインコードブロックを囲う。
```
"\ ``x``\" or "``x``"
```

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 1.5.0 (m-j/master)
- [x] 1.5.0 (m-t/master)
- [x] 1.4.2 (m-j/1.4.x)

## Change log(should be updated at the same time)
- Not Required

## English Translation
~~Required, handle with the same issue~~
執筆者意図を判断しかねる場面が多いため、英語版修正は翻訳チームに依頼します。
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
ダブルクォートで囲うか、インラインコードブロックにするか、いずれかで良いと思います。
（インラインコードブロック内でダブルクォートで囲う必要はありません）

**Comment by itouyun** [comment]
現在のガイドラインの記述を確認してみました。

http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#controller-method-argument-pathvariable-label
たとえばこの章だと、ダブルクォートを含めてインラインコードブロック化しています。

http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#view-jsp-outnumber-label
この辺の章になると、逆になっていたりします。

つまり、ダブルクォートを含める場合のインラインコードブロック化に関して、現在統一されていないことも問題ですね。

本issueは上記のどちらでもない（両方を併せ持つNGパターン）ですが、この際、横展開も含めて修正した方が良いかもしれません。（その場合はissueタイトルを修正する必要あり）

**Comment by btkigamim** [comment]
日本語版では「」（カッコ）で囲まれた部分が、英語版では""（ダブルクオート）で表記されている。
英語版の""の意図がコードブロック由来なのか、「」の翻訳か判断がつかないため、今回は日本語版のみ修正対象とします。

**Comment by yoshikawaa** [comment]
@hosoitk
議論の結果、以下のようにし、ガイドライン記述のルールにも反映してもらいました。

* 日本語版ガイドラインでは、インラインコードブロックを囲むダブルクォートは一律削除する
* ただし、1文字のみのインラインコードブロックは地の文と同化しやすく判別しにくいため、コードブロックの外側をダブルクォートで囲む

※Final Solutionsの記載も同様になっています。

Thanks for @btkawanofm

**Comment by yoshikawaa** [comment]
@hosoitk @btkawanofm 
m-t版は、ガイドの記載内容が大きく違うので、cherry-pickだけでなく修正箇所の再洗い出しが必要なことに注意してください。

**Comment by yoshikawaa** [comment]
See https://github.com/terasolunaorg/guideline-macchinetta-jsp/pull/77/files#diff-6e2f3ef943abaf729e3d260409f7ace6R587

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
