### ISSUE TITLE
Display conditions of the Friendly HTTP Error Pages

### ISSUE THREAD

**Issue by btkigamim** [terasolunaorg/guideline#2912]
## Description
例外ハンドリング章の4.2.3.4. コーディングポイント（JSP編）に記載されているTipの内容が間違っています。
 簡易メッセージの表示条件はステータスコードによって異なります。
(参考情報)
https://blogs.msdn.microsoft.com/ieinternals/2010/08/18/friendly-http-error-pages/

## Possible Solutions
参考情報を元に、OAuth章にある同一Tipの修正（対応issue：#2891）と合わせて、
簡易メッセージの表示条件を修正する。
　-> 注意喚起のみにし、具体的な対策はマイクロソフトのリンクを参照する方向で修正する。
* 対象
 - [x] OAuth章
 - [x] 例外ハンドリング章

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- 5.4.0_en (master) another issue
- 5.3.1_en (5.3.x) another issue
- [x] m-j 1.5.0
- [x] m-j 1.4.1
- [x] m-t 1.5.0

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- [ ] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #2891 (同時対応推奨issue)

**Comment by kazuki43zoo** [comment]
ステータスコードによって閾値違うんですね・・。

私が思うに・・・
ガイドラインに特定製品の製品仕様（細かい表示条件）を載せたのが間違っていた気がします。
ここで大事なのは、「エラーページの作り方によってIEで用意したエラーページが表示できない（簡易エラーページが表示されてしまう）ケースがあることを注意喚起する」ことなので、具体的な条件はマイクロソフトのページにリンクさせる方がよいと思います。

**Comment by yoshikawaa** [comment]
@kazuki43zoo 
確かに。冷静に考えれば、我々はIEの保守してるわけじゃないですからね。

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.

**Comment by yoshikawaa** [comment]
@btideues 
Private repositories remaining.
