### ISSUE TITLE
Add warning that respons header of cashed control is not set on occasions

### ISSUE THREAD

**Issue by itouyun** [terasolunaorg/guideline#2913]
## Description
Spring Securityには、HTTPヘッダ付与機能が存在する。
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/LinkageWithBrowser.html#id10

しかし、Spring Security 4.1.0より、キャッシュ制御用ヘッダーの付与に関する仕様が変更され、その仕様変更が原因により、 **『APサーバによってはキャッシュコントロールされているレスポンスヘッダが正しく設定されないことがある問題』** が発生することが判明した。

なお、この仕様変更は、4.2.0ではリバート済で修正されているため、Spring Security 4.2.x以降は発生しない。つまり、Spring Security 4.1.0のみが本問題の対象となる。

## Possible Solutions
「APサーバによってはキャッシュコントロールされているレスポンスヘッダが正しく設定されないことがある問題」に関して、Warningを追加する。

## Affects Version/s
- 5.3.0.RELEASE only

## Fix Version/s
- [x] 5.3.1_ja (5.3.x)
- 5.3.1_en (5.3.x) another issue
- [x] 1.4.2 (m-j/1.4.x)

## Final Solution
- Warningの追加
  - そのWarningには回避策（Workaround）も紹介

## Change log(should be updated at the same time)
- [ ] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by itouyun** [comment]
#### 回避策案（フィルタ）

1. SpringSecurityの[HeaderWriterFilter.java](https://github.com/spring-projects/spring-security/blob/df3b8bc2847252689347bc6ed9ffefb4e832dbb4/web/src/main/java/org/springframework/security/web/header/HeaderWriterFilter.java)をコピーして適当なところに配置します。
↓の例では、このクラスをHeaderWriterFilterExとしています。

2. HeaderWriterFilterExをbean定義し、既にあるsecureCacheControlHeadersWriterをコンストラクタの値として指定します。

3. （HeaderWriterFilterExと既存のフィルタを入れ替えたい場合はheadersタグにパラメータdisabled="true"を指定します。）
指定しないで後述のpositionパラメータ設定するとフィルタが競合してデプロイに失敗します。

4. custom-filterタグを追加し、HeaderWriterFilterExを適用したいタイミングを指定します。
タイミングはbefore, position, afterパラメータと既存のフィルタ名で指定します。beforeとafterは既存のフィルタの前後に挿入し、positionは既存のフィルタと入れ替えます。既存のフィルタはエイリアス名で指定します。エイリアス名は[ドキュメント](http://docs.spring.io/spring-security/site/docs/4.1.x/reference/htmlsingle/#security-filter-chain)の表6.1に記載されています。

```
    <!-- spring-security.xml -->
    <sec:http pattern="/@@@@@@@@@@@@@/**" >
        <sec:headers defaults-disabled="true" disabled="true" />
        <sec:custom-filter position="HEADERS_FILTER" ref="customizedHeaderWriterFilter"/>
        <sec:form-login />
        <sec:logout />
    </sec:http>

~(略)~

    <bean id="customizedHeaderWriterFilter" class= "@@@@@@@@@@@@@.HeaderWriterFilterEx" >
        <constructor-arg ref="secureCacheControlHeadersWriter" /> 
    </bean>
```

**Comment by bttamuratsh** [comment]
ガイドラインでは、_"/secure/というパスの配下に格納されていて、保護対象のコンテンツへアクセスした時だけCache-Controlヘッダを出力する"_ 例を挙げているので、それにそったテストを実施しているのだと思いますが、Spring Securityの対象のissueをみると、キャッシュコントロールされているレスポンスヘッダと言うよりは**HeaderWriterで書き込まれるレスポンスヘッダ全般**が出力されないケースがあるの方が正しいかもしれません。
厳密にどのような状況下で出力されないのかは調査できていませんが、JBoss EAP 7.0.0ではブランクプロジェクトにセキュリティヘッダ出力機能を適用したアプリを起動ところ、問題なく出力されました。
ちなみに回避策案の
`  <sec:headers defaults-disabled="true" disabled="true" />` 
は
` disabled="true"`だけ指定すればOKです。

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.

**Comment by yoshikawaa** [comment]
@bttanakamsc 
Private repository(jsp1.4.x) remaining.
