### ISSUE TITLE
Is @Email based on RFC2822 ?

### ISSUE THREAD

**Issue by 5zm** [terasolunaorg/guideline#2930]
## Description
ガイドラインでは`@Email`の説明として「RFC2822に準拠したEmailアドレスかどうか検証する。」とありますが、2バイト文字等のascii以外の文字でも入力チェックを通過してしまいます。
これで正しいのでしょうか。
仕様の確認になります。

http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validation-validator-list

* 以下のJUnitテストはグリーンになります。
```java
public class DemoFormTest {

    /**
     * validator
     */
    Validator validator = null;

    /**
     * initialize validator
     * @throws Exception
     */
    @Before
    public void setUp() throws Exception {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }

    /**
     * {@code @Email}はユーザ部分が２バイト文字でも入力チェックを通過する。
     */
    @Test
    public void test01() {
        // input
        DemoForm form = new DemoForm();
        String mailAddress = "あいうえお@exmaple.com";
        form.setMailAddress(mailAddress);
        // execute
        Set<ConstraintViolation<DemoForm>> constraintViolations = validator
                .validate(form);
        // asssert
        assertEquals(0, constraintViolations.size());
    }

    /**
     * {@code @Email}はドメイン部分が２バイト文字でも入力チェックを通過する。
     */
    @Test
    public void test02() {
        // input
        DemoForm form = new DemoForm();
        String mailAddress = "あいうえお@あ.jp";
        form.setMailAddress(mailAddress);
        // execute
        Set<ConstraintViolation<DemoForm>> constraintViolations = validator
                .validate(form);
        // asssert
        assertEquals(0, constraintViolations.size());
    }

    /**
     * {@code @Email}はユーザ部分が64文字までであれば入力チェックを通過する。
     */
    @Test
    public void test03() {
        // input
        DemoForm form = new DemoForm();
        // @の前が64文字
        String mailAddress = "1234567890123456789012345678901234567890123456789012345678901234@example.com";
        form.setMailAddress(mailAddress);
        // execute
        Set<ConstraintViolation<DemoForm>> constraintViolations = validator
                .validate(form);
        // asssert
        assertEquals(0, constraintViolations.size());
    }

    /**
     * {@code @Email}はユーザ部分が65文字以上であれば入力チェックでエラーとなる。
     */
    @Test
    public void test04() {
        // input
        DemoForm form = new DemoForm();
        // @の前が65文字
        String mailAddress = "12345678901234567890123456789012345678901234567890123456789012345@example.com";
        form.setMailAddress(mailAddress);
        // execute
        Set<ConstraintViolation<DemoForm>> constraintViolations = validator
                .validate(form);
        // asssert
        assertEquals(1, constraintViolations.size());
    }
}
```

## Possible Solutions
* RFC2822に準拠していない場合、正しい説明に修正する。
* 準拠している場合、noteやtipsに補足説明を追加する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- ~5.4.0_en (master)~ 別issue対応とする
- ~5.3.1_en (5.3.x)~ 別issue対応とする
- [x] 1.5.0 (m-j/master)
- [x] 1.4.2 (m-j/1.4.x)
- [x] 1.5.0 (m-t/master)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Required
  - 今一度更新履歴からWarningを読んでもらいたい内容なので

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required
  - 移行時に追加必須、みたいなわけではない

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
See [EmailValidator.java](https://github.com/hibernate/hibernate-validator/blob/5.2.4.Final/engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/EmailValidator.java#L104-L119)
入力をASCII文字に変換したうえでチェックをかけているため、全角文字は入力チェックを通過するようです。

例）入力 `あいうえお` -> 変換後 `xn--l8jegik`

**Comment by yggd** [comment]
↑その上のコメントにもありますが、Hibernate Validatorもトレードオフにより、RFC2822に100%準拠してるわけではないようです。

https://github.com/hibernate/hibernate-validator/blob/5.2.4.Final/engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/EmailValidator.java#L27

ここでは日本語ではなく、ダブルクォートやコメント（これも厳密に実装しようとすると相当カオスになる）を無視していることですが。

RFC2822自体があまり現実性のない（コメント入りや空白n個+改行入りとか）を許容していたり、@yoshikawaa さんからもありますが後付けでPunycode変換が可能になったり、
さらについ数年前にとあるベンダの都合からか国際化に対応したメール規格が出てきたりと、
既にRFC2822の頃の厳密性は崩れていると考えます。

https://googleblog.blogspot.jp/2014/08/a-first-step-toward-more-global-email.html
https://www.rfc-editor.org/rfc/rfc6530.txt

以上よりいただいた事例を参考にさせていただいた上で、ご使用のSMTPサーバ等メール利用環境要件に合わせて入力チェックルールを組み合わせていただく旨とするのが現実的ではないかと考えます。

**Comment by 5zm** [comment]
yoshikawaa さん、yggd さん

回答ありがとうございます。
`@Email`ではなく、[4.1.3.1. 既存ルールを組み合わせたBean Validationアノテーションの作成](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validation-convine-existing-constraint) を参考に、独自のアノテーションを作成してチェックしようと思います。

**Comment by itouyun** [comment]
`@Email` が、RFC2822に100%準拠してるわけではない旨や、そもそもRFC2822自体の厳密性が微妙なので、それに依存するよりも、ご使用のSMTPサーバ等メール利用環境要件に合わせて入力チェックルールを組み合わせていただくのがよい

という旨を、ガイドラインへWarningとして、追記する、というのがガイドライン対応としてベター、ですかね？

**Comment by kazuki43zoo** [comment]
すくなくても、「RFC2822に準拠したEmailアドレスかどうか検証する。」は、Hibernate
 Validator実装だとウソになるみたいなので、ウソにならないような補足は必要かと。

で、メール（URLも？）は利用・サポートする環境とかを考慮してチェックルールを定義（組み合わせによるチェックやチェックルールの追加など）してね！をガイドするのがよさそう。

**Comment by kazuki43zoo** [comment]
あ・・`@Email`ってHibernate固有でしたっけ？たしかBean Validation 2.0から`@Email`が追加になる予定だった気がするが。

**Comment by kazuki43zoo** [comment]
やっぱBean Validation 2.0から[`@Email`](http://beanvalidation.org/2.0/spec/#builtinconstraints-email)追加されますね。とくにRFCに準拠とかはスペック上は記載されてなさそうです。（＝実際のチェックルールはプロバイダに委ねられているみたいです）

**Comment by itouyun** [comment]
RFC2822についてちょっと調査してみましたが、分量が膨大で正確な情報を取り出すのは大変そうですね。。。
かつ、そもそも携帯キャリアメールなど、RFC2822に準拠していなくても正常稼働しているメールアドレスもあるそうな・・・。

すると、Warningとして示すべき観点は以下でしょうか。
- Hibernateの `@Email` は正確にRFC2822に準拠しているわけではなく、たとえばマルチバイト文字がアドレスに含まれていても入力チェックをパスする
- 過去のキャリアメールのメールアドレスには、RFC2822に準拠していないものも存在する
  - （本当かどうかは要調査＠ちょっとググったら出てきたけど信ぴょう性はまだ謎）
- ご使用のSMTPサーバ等メール利用環境要件に合わせて入力チェックルールを定義（組み合わせによるチェックやチェックルールの追加など）するべき
  - 実装の際は [4.1.3.1. 既存ルールを組み合わせたBean Validationアノテーションの作成](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validation-convine-existing-constraint) を参照されたい

こんな感じですかね。Bean Validation 2.0に関する内容や、URLについては言及せずに考えてみました。

**Comment by itouyun** [comment]
今一度更新履歴からWarningを読んでもらいたい内容なのでChangeLogは必要、しかし、MigrationGuideは不要、としました。

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
