### ISSUE TITLE
Add start information to Building blocks of Common Library

### ISSUE THREAD

**Issue by btsatouhrzzp** [terasolunaorg/guideline#2937]
## Description
`2.1.4. 共通ライブラリの構成要素`にコードポイントなどは（5.1.0から追加）と記載があるのに対して、dependencies系に5.2.0から追加と記載がない。

[2.1.4. 共通ライブラリの構成要素](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Overview/FrameworkStack.html#frameworkstack-common-library)

## Possible Solutions
カッコ書きで正しく記述する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 5.2.2_ja (5.2.x)
- [x] 1.5.0 (m-j/master)
- [x] 1.4.2 (m-j/1.4.x)
- [x] 1.5.0 (m-t/master)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
(To be selected later by project member)
- [ ] Required
- Not Required

## English Translation
(To be selected later by project member)
- [ ] Required, handle with the same issue
- [ ] Required, create a new issue for handling
- Not Required 

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #2785

**Comment by yoshikawaa** [comment]
@hosoitk 
English version remaining.

**Comment by yoshikawaa** [comment]
@btkobayashirun 
Private repositories remaining.
