### ISSUE TITLE
Remove definition of trimTokens for Guideline

### ISSUE THREAD

**Issue by itouyun** [terasolunaorg/guideline#2941]
## Description
Definition of `trimTokens=false` is default, `trimTokens=false` is not necessary.
Read here https://github.com/terasolunaorg/guideline/issues/2700#issuecomment-320895098
ブランクプロジェクトで terasolunaorg/terasoluna-gfw-web-multi-blank#334 の対応を行う。
それに伴い、ガイドラインも修正をする。

## Possible Solutions
- `trimTokens` のデフォルト値に関する記述を書きかえる
  - http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/Authorization.html#access-policy-designate-web-resource
- その他、ブランクプロジェクトの`trimTokens`の箇所をガイドラインへ転記している箇所をすべてブランクプロジェクトの修正の通りに書き換える
  - guideline上を`trimTokens`でgrepして1つ1つ調査

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (guideline/master) 【共通】
- 5.4.0_en (guideline/master) 【共通】 (other issue)
- [x] 5.3.1_ja (guideline/5.3.x) 【共通】
- 5.3.1_en (guideline/5.3.x) 【共通】 (other issue)
- [x] 1.5.0_ja (guideline-macchinetta-jsp/master) 【共通】
- [x] 1.4.1_ja (guideline-macchinetta-jsp/1.4.x) 【共通】
- [x] 1.5.0_ja (guideline-macchinetta-thymeleaf/master) 【共通】

## Final Solution
PossibleSolutionの対応を行う。

## Change log(should be updated at the same time)
- Required

## English Translation
- [x] Required, create a new issue for handling

## Migrating Guide
- Required
  - https://github.com/terasolunaorg/guideline/issues/2941#issuecomment-331139462 参照

## Issue Links
- terasolunaorg/guideline#2700 (起因となったissue)
- terasolunaorg/terasoluna-gfw-web-multi-blank#334 (ブランクプロジェクトの修正＠同時対応必須)

**Comment by kazuki43zoo** [comment]
@itouyun 

ブランクをかえるならMigration Guideも必要という認識です。「ブランクを直す＝推奨の設定方法をかえる」という認識なので、「任意のタスク」としてMigration Guideに乗せておいた方がよいと思います。

**Comment by itouyun** [comment]
@kazuki43zoo 
コメントありがとうございます。
確かに、動作が変わらないとはいえ、利用者がバージョンアップしたときに記述内容が最新ブランクと異なるのは、場合によってはよくないかもしれないですね。

Migration Guideに載せるよう、見直します。

@bttsuchikawaf 
Migration Guide更新に関する内部issue作成をお願いします。

**Comment by itouyun** [comment]
@bttsuchikawaf 
Thank you for your work!!
