### ISSUE TITLE
[5.5 Validation]  Probably description about @GroupSequence is not correct.

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#296]
In note of "[5.5.2.1.1. 基本的な単項目チェック](http://terasolunaorg.github.io/guideline/public_review/ArchitectureInDetail/Validation.html#validation-basic-validation)",describe to be able to control the display order by using the `@GroupSequence`.I tried it, but could not control the display order by using the `@GroupSequence`.

`@GroupSequence` can be control **the execution order of checks** .If generates constraint violations in the group sequence checks, bean validator **will not execute the checks of the groups later**.
Detail see the [JSR-303 specification](http://beanvalidation.org/1.0/spec/#constraintdeclarationvalidationprocess-groupsequence-groupsequence).

**Comment by btshimizukza** [comment]
master & 1.0.x への反映＋英語化issueを作成したのでクローズ。
