### ISSUE TITLE
Modified Chapter of Introduction in Thymeleaf

### ISSUE THREAD

**Issue by bthayakawaako** [terasolunaorg/guideline#2987]
## Description
Modified Chapter of Introduction in Thymeleaf

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0_ja (master)
- [ ] 5.3.1_ja (5.3.x)
- [x] 1.5.0 (m-j/master)
- [ ] 1.5.0 (m-t/master)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
(To be selected later by project member)
- [ ] Required
- Not Required

## English Translation
(To be selected later by project member)
- [ ] Required, handle with the same issue
- [ ] Required, create a new issue for handling
- Not Required 

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by bthayakawaako** [comment]
修正対象が存在しないため、Closeします。

**Comment by kazuki43zoo** [comment]
「このドキュメントの対象読者」にある「Servlet/JSPを使用してWebアプリケーションを開発したことがある」はそのままでよいのでしょうか？
↑の記載はあってよい気はしますが、ガイドラインが前提としているThymeleaf力（Thymeleafの知識レベル）が初心者レベルでないなら、Thymeleafに対する記述を追加した方がよいと思います。

**Comment by yoshikawaa** [comment]
@kazuki43zoo 
フォローありがとうございます！再検討ですね。

@bthayakawaako 
そもそも修正対象なしでIssueをクローズしてよいかどうかは、レビュアに判断してもらってね。

**Comment by bthayakawaako** [comment]
@kazuki43zoo 
コメントありがとうございます。
ご指摘の行についてはそのままでいいのではないかと話をしていたのですが、確かに1行追加があってもいいかもしれませんね。
ガイドラインが前提とするThymeleafの知識は新章次第なところもあり私にはわかりかねますが、後ほど検討してみます。

@yoshikawaa
Reopenありがとうございます。
今回は一応確認をとっていますが、今後も必要に応じてレビュアの判断を仰ぐことにしますね。
