### ISSUE TITLE
「メッセージ管理」章のSPRING_SECURITY_LAST_EXCEPTIONの説明が誤っている

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#2994]
## Description
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/MessageManagement.html#resultmessages
> 例えば、Spring Securityは認証エラー時に、”SPRING_SECURITY_LAST_EXCEPTION”という属性名で発生した例外クラスをリクエストスコープに設定する。

実際にはフォワード時はリクエストに、リダイレクト時はセッションにセットするはず。
誤解しそうなので修正したほうが良いと思います。

http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/Authentication.html#springsecurityauthenticationloginform
> なお、認証エラーが発生した場合は、セッション又はリクエストスコープに"SPRING_SECURITY_LAST_EXCEPTION"という属性名で例外オブジェクトが格納される。

こちらは正しいです。（が説明が不親切な気はする。）

## Possible Solutions
* 「メッセージ管理」章を以下のように修正すればOK。

    例えば、Spring Securityは認証エラー時に、”SPRING_SECURITY_LAST_EXCEPTION”という属性名で発生した例外クラスを**セッション又は**リクエストスコープに設定する。

* フォワード時は～のような条件を書くかどうかも検討したほうが良いとおもいます。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.3.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) in #3247 
- [x] 1.5.2_ja (m-t/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by btkomatsubaratka** [comment]
http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/Tutorial/TutorialSecurity.html#id16
でも、
> 認証が失敗した場合、認証エラーの例外オブジェクトが"SPRING_SECURITY_LAST_EXCEPTION"という属性名でセッションスコープに格納される。

となっているので、こちらも修正が必要かと

**Comment by yoshikawaa** [comment]
#### Spring Security デフォのまとめ

##### [SimpleUrlAuthenticationFailureHandler](https://github.com/spring-projects/spring-security/blob/4.1.4.RELEASE/web/src/main/java/org/springframework/security/web/authentication/SimpleUrlAuthenticationFailureHandler.java#L104-L117)
* フォワードならリクエスト、リダイレクトならセッションにエラー情報を登録する
* `sec:form-login`や`sec:session-management`のデフォ設定で使用される
* 継承クラスに`ExceptionMappingAuthenticationFailureHandler`がある
##### [ForwardAuthenticationFailureHandler](https://github.com/spring-projects/spring-security/blob/4.1.4.RELEASE/web/src/main/java/org/springframework/security/web/authentication/ForwardAuthenticationFailureHandler.java#L49-L52)
* リクエストにエラー情報を登録する
* `sec:form-login#authentication-failure-forward-url`をセットした場合に使用される
* Spring Security 4.1から

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
