### ISSUE TITLE
ガイドラインのPDF化時にエラーが発生する。

### ISSUE THREAD

**Issue by btkigamim** [terasolunaorg/guideline#3010]
## Description
ガイドラインをPDF化しようとしたとき、OAuth.rstファイルでエラーが発生する。

## Possible Solutions
tabularcolumnsが修正できていない。
以下の箇所を修正する必要がある。
* **エンドポイント**
* **フォワード先**
* Note (本実装例では～)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.1_ja (5.3.x)
- [ ] 5.4.0_en (master)
- [ ] 5.3.1_en (5.3.x)
- [x] m-j 1.5.0
- [x] m-j 1.4.1
- [x] m-t 1.5.0

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- Not Required 

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
English version remaining.

**Comment by yoshikawaa** [comment]
@btkigamim 
Private resositories remaining?
