### ISSUE TITLE
Wrong statement about transition destination in SessionManagement.rst

### ISSUE THREAD

**Issue by bthayakawaako** [terasolunaorg/guideline#3026]
## Description
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/SessionManagement.html

> 上記例では、 例外発生時の遷移先として、/WEB-INF/views/common/error/operationError.jspを指定している。
例外発生時の遷移先として指定されているのはcommon/error/operationErrorである。

## Possible Solutions
「4.3 セッション管理」の該当箇所(2箇所)について修正する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (guideline/master)【共通】
- [x] 5.3.1_ja (guideline/5.3.x)【共通】
- [x] 1.5.0_ja (guideline-m-jsp/master)【共通】
- [x] 1.4.1_ja (guideline-m-jsp/1.4.x)【共通】
- [x] 1.5.0_ja (guideline-m-thymeleaf/master)【共通)】

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by kazuki43zoo** [comment]
Possible Solutionsに修正案が書かれてないので、具体的にどのように直そうとしているのかわかりませんが・・・

* `common/error/operationError`はView名
* `/WEB-INF/views/common/error/operationError.jsp`は`ViewResolver`を介して解決した具体的な遷移先のファイルパス（JSPファイルのパス）

という関係を意識して修正案（改善案）も考えた方がよいかと思います。
また、他の章でどのような表現になっているのか確認した方がよいと思う。

**Comment by bthayakawaako** [comment]
用語の意味をよく理解していなかったようです。
他章などを確認したところ、「遷移」とは「画面への遷移」を指しているようですね。
となると、この記述そのものはWrongではないことになりますね。

…とはいえ、コード例におけるView名の説明として、(prefix/suffixなどの説明なしに)遷移先のファイルパスを記述するのはやや飛躍があるようにも感じます。
修正するのであれば、「上記例では、 例外発生時の遷移先のView名として、common/error/operationErrorを指定している。」とかになりそうです。

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
