### ISSUE TITLE
Not good source code of jsp in SessionManagement.rst

### ISSUE THREAD

**Issue by bthayakawaako** [terasolunaorg/guideline#3027]
## Description
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/SessionManagement.html#sessionbeancontroller

「カート画面(JSP)」のソースコードについて、カートが空であるかどうかを特に必要もないのにわざわざ2回判定している。

## Possible Solutions
複雑になっている画面の構造について、必要があれば修正する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (guideline/master)【個別(JSP)】
- [x] 5.3.1_ja (guideline/5.3.x)【個別(JSP)】
- [x] 1.5.0_ja (guideline-m-jsp/master)【個別(JSP)】
- [x] 1.4.1_ja (guideline-m-jsp/1.4.x)【個別(JSP)】
- [x] 1.5.0_ja (guideline-m-t/master)【個別(JSP)】 ※Thymeleaf版は既に修正済み

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
