### ISSUE TITLE
Modify Small Letter 'csrf' to Capital Letter 'CSRF' in DoubleSubmitProtection.rst

### ISSUE THREAD

**Issue by bthayakawaako** [terasolunaorg/guideline#3028]
## Description
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.html#view-jsp
「csrfトークン」となっている箇所が2つある。

## Possible Solutions
「csrfトークン」を「CSRFトークン」に変更する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (guideline/master)【共通】
- [x] 5.3.1_ja (guideline/5.3.x)【共通】
- [x] 1.5.0_ja (guideline-m-jsp/master)【共通】
- [x] 1.4.1_ja (guideline-m-jsp/1.4.x)【共通】
- [x] 1.5.0_ja (guideline-m-thymeleaf/master)【共通)】
※Thymeleafは既に対応済み

## Final Solution
-

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
