### ISSUE TITLE
Check broken or old link and update for Guideline

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/guideline#3041]
## Description
ガイドラインについて、リンクが有効になっている（リンク切れ等ないか）か確認し、切れている場合、修正する。

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 5.3.1_ja
- [x] 1.5.0 (m-j/master)
- [x] 1.4.2 (m-j/1.4.x)
- [x] 1.5.0 (m-t/master)

#### English version is corresponded at another issue
- [ ] 5.4.0_en (master)
- [ ] 5.3.2_en (5.3.x)
- [x] 5.3.1_en

## Final Solution
-

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #2453

**Comment by yoshikawaa** [comment]
@hosoitk @sasakitsy @btkobayashirun 
こちらのIssueは日本語版5.4.0+5.3.2系の対応に利用してしまったので、
英語版のリンク切れ問題は別途Issueを立てて対応していただく形にしたいと思います。
