### ISSUE TITLE
Typo in MessageManagement.rst

### ISSUE THREAD

**Issue by bthayakawaako** [terasolunaorg/guideline#3043]
## Description
http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/MessageManagement.html#resultmessages

>  (1)
   結果メッセージ表示用のCSSを再掲する。実際はCSSファイルに記述することを強く推奨する。
   (1)
   ``Exception``\ オブジェクトが格納されている属性名を\ ``messagesAttributeName``\ 属性で指定する。
   また、\ ``ResultMessages``\ オブジェクトとは異なり、メッセージタイプの情報をもたないため、
   \ ``messagesType``\ 属性で、明示的に、メッセージタイプを指定する必要がある。

(1)が2つある。

## Possible Solutions
下の(1)を(2)に修正する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (guideline/master)【共通】
- [x] 5.3.1_ja (guideline/5.3.x)【共通】
- [x] 1.5.0_ja (guideline-m-jsp/master)【共通】
- [x] 1.4.1_ja (guideline-m-jsp/1.4.x)【共通】
- [x] 1.5.0_ja (guideline-m-thymeleaf/master)【共通)】
※Thymeleafは既に対応済み

## Final Solution
-

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
