### ISSUE TITLE
Typo in Pagination

### ISSUE THREAD

**Issue by btiidakua** [terasolunaorg/guideline#3054]
## Description
[4.4.2.4.2.](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Pagination.html#id20)

「最初のページに移動するためのリンク」と「最後のページに移動するためのリンク」を削除するための

## Possible Solutions
「前のページに移動するためのリンク」と「次のページに移動するためのリンク」を削除するための

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 1.5.0 (m-j/master)
- [x] 1.4.2 (m-j/1.4.x)
- [x] 1.5.0 (m-t/master)

## Final Solution
「前のページに移動するためのリンク」と「次のページに移動するためのリンク」を削除するための
に修正した

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
