### ISSUE TITLE
Typo in SpringSecurityAuthorization.  

### ISSUE THREAD

**Issue by btiidakua** [terasolunaorg/guideline#3055]
## Description
[9.3.2.2.2.1.](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/Security/Authorization.html#access-policy-designate-web-resource)

At Tip
`<sec:intercept-url pattern="/admin/accounts/.*" access=hasRole('ACCOUNT_MANAGER')" />`
access start `"` is none.

## Possible Solutions
`<sec:intercept-url pattern="/admin/accounts/.*" access="hasRole('ACCOUNT_MANAGER')" />`

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 1.5.0 (m-j/master)
- [x] 1.4.1 (m-j/1.4.x)
- [x] 1.5.0 (m-t/master)

## Final Solution
<sec:intercept-url pattern="/admin/accounts/.*" access="hasRole('ACCOUNT_MANAGER')" />

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
