### ISSUE TITLE
The number of blank project archetypes is wrong.

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/guideline#3056]
## Description
The number of blank project archetypes is wrong.
Although [it is introduced that multi blank project's archetype is three kinds](https://github.com/terasolunaorg/guideline/blame/master/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L32), it is actually two kinds.
And although [it is introduced that single blank project's archetype is four kinds](https://github.com/terasolunaorg/guideline/blame/master/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L41), it is actually three kinds.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 5.2.2_ja (5.2.x)
- [x] 5.1.2_ja (5.1.x)
- [x] 5.0.3_ja (5.0.x)
- [ ] 1.0.7_ja (1.0.x)

all private repository are already acknowledged

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
* マルチブランクは、[MyBatis3, JPA]の2種類
* シングルブランクは、[MyBatis3, JPA, O/R Mapperなし, WTP用]の4種類

が正しいように思いますが、どうでしょう？
その上で、ガイドの説明はおかしいので修正したほうが良いと思います。

**Comment by btyanagawamg** [comment]
https://github.com/terasolunaorg/guideline/commit/da3bc4942d4e1302c85e2247505bbdc03c65a332
元々はMyBatis2用のブランクプロジェクトをMyBatis3用のブランクプロジェクトと別に数えていたため、シングル４種類、マルチ３種類と記載していたようです。
MyBatis2用のブランクプロジェクトが5.0.x以降のガイドラインから削除された際に、ブランクプロジェクトの種類の数を変更していなかったことが、現在、ガイドラインに記載されているブランクプロジェクトの種類の数が異なっている原因のようです。

- マルチブランクは、[MyBatis3, JPA]の2種類
- シングルブランクは、[MyBatis3, JPA, O/R Mapperなし]の3種類

と記載する事が正しいと思われます。

**Comment by yoshikawaa** [comment]
1.0は該当するページなし

@hosoitk 
English translation remaining.
