### ISSUE TITLE
Update versions TERASOLUNA(5.4.0.RELEASE, 5.3.2.RELEASE), Spring IO Platform (Brussels-SR5), and more.

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/guideline#3061]
## Description
* Update TERASOLUNA 5.3.0.RELEASE 5.3.1.RELEASE -> 5.4.0.RELEASE or 5.3.2.RELEASE
* Update Spring IO version Athens-SR2 -> Brussels-SR5
* Update related libraries version

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 1.5.0_ja (private(jsp)/master)【共通・個別(JSP)】
- [x] 1.4.2_ja (private(jsp)/master)【共通・個別(JSP)】
- [x] 1.5.0_ja (private(Thymeleaf)/master)【共通・個別(Thymeleaf)】

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- [ ] Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
See #2842 
5.3.1から追加する想定だった、`@Compare`の比較オペレータ`NOT_EQUAL`を5.3.2で追加するように修正した

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.

**Comment by yoshikawaa** [comment]
@hosoitk 
English version remaining.
