### ISSUE TITLE
Definition of access policy that uses path variables in Spring Security is insufficient.

### ISSUE THREAD

**Issue by btideues** [terasolunaorg/guideline#3090]
## Description
「9.3.2.2.2.1. アクセスポリシーを適用するWebリソースの指定」のWarningに記載されている通り、Spring MVCとSpring Securityのリクエストマッチングの仕組みを吸収するようにアクセスポリシーを定義する必要がある。
しかし、「9.3.2.2.2.3. パス変数の参照」に記載されているアクセスポリシーは、ワイルドカードを使用せず、末尾に/を付与した定義もなくアクセスポリシーとして不完全なため、修正する必要がある。
また、拡張子が指定されたパターンについても考慮されていない（現状の定義の場合、パス変数に拡張子まで含まれる）。

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 1.5.0 (m-j/master)
- [x] 1.4.2 (m-j/1.4.x)
- [x] 1.5.0 (m-t/master)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- [ ] Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
