### ISSUE TITLE
Reflect the format change of the blank project

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/guideline#3106]
## Description
Reflect the format change of the blank project
see 
- [terasoluna-gfw-web-blank #341](https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/341)
- [terasoluna-gfw-web-multi-blank #381](https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/381)

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 5.2.2_ja (5.2.x)
- [x] 5.1.2_ja (5.1.x)
- [x] 5.0.3_ja (5.0.x)
- [x] 1.0.7_ja (5.0.x)
- [x] 5.4.0_private-jsp (master)
- [x] 5.3.2_private-jsp (5.3.x)
- [x] 5.4.0_private-thymeleaf (master)

## Final Solution
ブランクプロジェクトに入った変更をガイドラインに反映した。
加えて、ブランクプロジェクトのインデントサイズを半角スペース４つに統一したため、本ISSUEの対応で、合わせて、ガイドラインで紹介されているソースコードのインデントサイズも全体的に半角スペース４つに統一した。

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@btyanagawamg 
From next time, please write "final solution" after discuss in comments.
Since we do not understand the flow of discussion just by rewriting the solution,
I think that it is necessary to reflect the results discussed in comments on solution.

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
