### ISSUE TITLE
[m-t 1.5.0] expression difficult to understand.

### ISSUE THREAD

**Issue by btkatoutmj** [terasolunaorg/guideline#3124]
## Description
（m-t 1.5.0）ImplementationAtEachLayer/ApplicationLayer.rstにあいまい、または、わかりづらい表現が存在する。

773行目
「XSS対策のため、HTMLエスケープは必ず行うことを推奨する。」
必須か推奨かわからない。

1739-1741行目
「基本的には次に挙げるもののみを使用すること。
- String(View論理名)」
String(View論理名)が表している内容があいまい。

1778行目
「 - ハンドラメソッドの返り値として ``"sample/hello"`` というView名を返却した場合、 ``ThymeleafViewResolver`` の設定により ``"/WEB-INF/views/sample/hello.html"`` が呼び出されHTMLが応答される。」
HTMLを静的に表示するようにも読み取れてしまう。

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] m-t 1.5.0

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
(To be selected later by project member)
- [ ] Required
- Not Required

## English Translation
(To be selected later by project member)
- [ ] Required, handle with the same issue
- [ ] Required, create a new issue for handling
- Not Required 

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
> 773行目
> 「XSS対策のため、HTMLエスケープは必ず行うことを推奨する。」
> 必須か推奨かわからない。

「XSS対策のため、HTMLエスケープは必ず行うこと。」に修正する。

**Comment by yoshikawaa** [comment]
> 1739-1741行目
> 「基本的には次に挙げるもののみを使用すること。
> 
>     String(View論理名)」
>     String(View論理名)が表している内容があいまい。

TERA, m-jともに同様の表現。何が曖昧なのか分からないので修正する必要もないと思うが。。。

※ここの趣旨は、ModelAndViewなどではなくView名（String）を返却することを推奨しているが、
　直上のリンク先（Springのリファレンス）を見ないと言っていることが理解できないと思われる。

**Comment by yoshikawaa** [comment]
> 1778行目
> 「 - ハンドラメソッドの返り値として "sample/hello" というView名を返却した場合、 ThymeleafViewResolver の設定により "/WEB-INF/views/sample/hello.html" が呼び出されHTMLが応答される。」
> HTMLを静的に表示するようにも読み取れてしまう。

「テンプレートHTML "/WEB-INF/views/sample/hello.html" が解決され、HTMLが応答される。」

くらいが適当か。
