### ISSUE TITLE
reflect ojdbc group ID and postgres version for blank project

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/guideline#3130]
## Description
reflect ojdbc group ID and postgres version for blank project 
blank project
https://github.com/terasolunaorg/terasoluna-gfw-web-blank/blob/master/pom.xml#L191
guideline
https://github.com/terasolunaorg/guideline/blame/master/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst#L744

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 5.2.2_ja (5.2.x)
- [x] 5.1.2_ja (5.1.x)
- [x] 5.0.3_ja (5.0.x)
- [ ] 1.0.7_ja (1.0.x)
- [x] 1.5.0 (m-j/private)
- [x] 1.4.2 (m-j/private)
- [x] 1.5.0 (m-t/private)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- terasolunaorg/terasoluna-gfw-web-blank#289
- terasolunaorg/terasoluna-gfw-web-blank#248

**Comment by yoshikawaa** [comment]
@btyanagawamg Please correspond older versions, or write new issue for older versions.

**Comment by btiidakua** [comment]
`1.0.x`には該当する修正箇所が無いようです。

**Comment by yoshikawaa** [comment]
@btiidakua 確認ありがとうございます！

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
