### ISSUE TITLE
fix table height for PDF

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/guideline#3131]
## Description
fix table height for PDF
- Private Thymeleaf
```
Thymeleaf + Spring を適用した処理フロー
```
```
4.1.2 How to use
```
- Both public and private
```
WebService 実装クラスの作成
```
```
クライアントから認可サーバ、リソースサーバアクセス時に発生するエラー
```
```
リソースサーバで発生するエラー
```

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0_ja (master)
- [x] 5.3.2_ja (5.3.x)
- [x] 1.5.0 (m-j/private)
- [x] 1.4.2 (m-j/private)
- [x] 1.5.0 (m-t/private)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- create issue

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
Endlich translation remaining.
