### ISSUE TITLE
Delete "JSP Tag Libraries & EL Functions" chapter.

### ISSUE THREAD

**Issue by bttanakaysd** [terasolunaorg/guideline#3136]
## Description
Delete "JSP Tag Libraries & EL Functions" chapter.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] m-t 1.5.0

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk 
English translation remaining.
