### ISSUE TITLE
Modify Deliverables for m-j/m-t

### ISSUE THREAD

**Issue by bttanakaysd** [terasolunaorg/guideline#3159]
## Description
Modify Deliverables for m-j/m-t

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 1.5.0_ja (m-j/1.5.x)
- [x] 1.4.1_ja (m-j/1.4.x)
- [x] 1.5.0_ja (m-t/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
(To be selected later by project member)
- [ ] Required
- Not Required

## English Translation
(To be selected later by project member)
- [ ] Required, handle with the same issue
- [ ] Required, create a new issue for handling
- Not Required 

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
