### ISSUE TITLE
The TOC in TagLibAndELFunctions.rst has disappeared.

### ISSUE THREAD

**Issue by btkitsunedukam** [terasolunaorg/guideline#3172]
## Description
The TOC in TagLibAndELFunctions.rst is disappeared.

## Possible Solutions
Add the TOC(` .. contents:: 目次`) section to TagLibAndELFunctions.rst.

## Affects Version/s
- 5.3.1.RELEASE
- 1.0.6.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
(To be selected later by project member)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk English version remaining.
