### ISSUE TITLE
Improve label of code block in the OAuth chapter in JSP

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3179]
## Description
improve label of code block in the OAuth chapter.

## Possible Solutions
before
`<input type="radio" name="${f:h(scope.key)}" value="true"/>Approve`
after
`<input type="radio" name="${f:h(scope.key)}" value="true"/><label for="${f:h(scope.key)}">Approve</label>`

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 1.6.0_ja (m-j/master)
- [ ] 1.5.1_ja (m-j/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
(To be selected later by project member)
- [ ] Required

## English Translation
(To be selected later by project member)

- Not Required 

## Migrating Guide
(To be selected later by project member)

- Not Required

## Issue Links
- #3173

**Comment by yoshikawaa** [comment]
#3178 の重複のためクローズした（っぽい）
