### ISSUE TITLE
DepYearCodeList is bean defined by xml instead of @Component

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3181]
## Description
ガイドラインのコードリストの章で`DepYearCodeList`が`@Component`で定義されていますが、コードリストのBean定義をxxx-codelist.xmlに集約するという観点からxmlで定義したほうが良いのではないでしょうか？

## Possible Solutions
xxx-codelist.xmlで以下のようにbean定義するようにガイドラインの記述を修正する。
```
<bean id="CL_YEAR_CODELIST" class="xxxx.DepYearCodeList">
    <constructor-arg name="dateFactory" ref="dateFactory" />
</bean>
```
`DepYearCodeList.java`から`@Component`を削除する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0_ja (master)
- [x] 5.4.1_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.1_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) in #3175 
- [x] 1.5.1_ja (m-t/1.5.x)
## Final Solution
updated at 2018/01/26 
```
package com.example.sample.domain.codelist;

    ...

    public class DepYearCodeList extends AbstractCodeList {

        private JodaTimeDateFactory dateFactory;

        public void setDateFactory(JodaTimeDateFactory dateFactory) {
            this.dateFactory = dateFactory;
        }

        @Override
        public Map<String, String> asMap() {
            DateTime dateTime = dateFactory.newDateTime();
            DateTime nextYearDateTime = dateTime.plusYears(1);

            Map<String, String> depYearMap = new LinkedHashMap<String, String>();

            String thisYear = dateTime.toString("Y");
            String nextYear = nextYearDateTime.toString("Y");
            depYearMap.put(thisYear, thisYear);
            depYearMap.put(nextYear, nextYear);

            return Collections.unmodifiableMap(depYearMap);
        }
    }
```

- xxx-codelist.xml
```
    <bean id="CL_YEAR" class="com.example.sample.domain.codelist.DepYearCodeList">
        <property name="dateFactory" ref="dateFactory" />
    </bean>
```

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- [ ] Required

## Issue Links
- #3175

**Comment by yoshikawaa** [comment]
@btkomatsubaratka 
「xmlで定義したほうが良い」という結論からではなく、どうするのが妥当かの議論から始めるべきじゃないでしょうか？

**Comment by btkomatsubaratka** [comment]
@yoshikawaa 
そうですね。提案する形式に変更しました。

**Comment by NaozumiTaromaru** [comment]
XMLに書く場合でも、
 * dateFactoryは```@Inject```でフィールドインジェクションしている
 * Bean IDは```CL_YEAR```

なので、
```
<bean id="CL_YEAR_CODELIST" class="xxxx.DepYearCodeList">
    <constructor-arg name="dateFactory" ref="dateFactory" />
</bean>
```
ではなく
```
<bean id="CL_YEAR" class="xxxx.DepYearCodeList"/>
```
でしょうね。

**Comment by yoshikawaa** [comment]
@NaozumiTaromaru さん
そうですね。
ただ、XMLでBean定義する前提であれば、`dateFactory`はオートワイヤではなくXMLでインジェクションの定義を書くはずという意味合いで書いてるのかなと思いました。

**Comment by NaozumiTaromaru** [comment]
まあ、それはそれで、クラスの方の修正も```@Component```の削除ではすまなくなるので、
どちらにせよ、Possible Solutionsの記述が不完全ですね。

**Comment by yoshikawaa** [comment]
ですねー

**Comment by btkomatsubaratka** [comment]
@yoshikawaa さん、@NaozumiTaromaru さん
[7.5.2.2. サーバーのシステム時刻を返却する](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/ArchitectureInDetail/GeneralFuncDetail/SystemDate.html#id5)
などでは、`@Inject` で dateFactory をフィールドインジェクションしているので、それに合わせるのがよさそうですね。

なので、
@NaozumiTaromaru さんが提案してくださった以下の形式が良さそうですね
> `<bean id="CL_YEAR" class="xxxx.DepYearCodeList"/>`

**Comment by btkomatsubaratka** [comment]
@yoshikawaa 
> 個人的には、Bean定義する前提のクラスにオートワイヤするのは、可読性や再利用性の観点で問題あるかと思います。以下の整理が自然かなと。
> - コンポーネントスキャンするクラスではオートワイヤでインジェクション
> - Bean定義するクラスでは、Bean定義のコンストラクタやプロパティでインジェクション

そうするとコンストラクタ or プロパティ インジェクションになりますね。
数多の例に倣って、プロパティインジェクションに変更します。

Possible Solutions としては以下のように修正

- DepYearCodeList.java
```
package com.example.sample.domain.codelist;

    ...

    public class DepYearCodeList extends AbstractCodeList {

        private JodaTimeDateFactory dateFactory;

        public void setDateFactory(JodaTimeDateFactory dateFactory) {
            this.dateFactory = dateFactory;
        }

        @Override
        public Map<String, String> asMap() {
            DateTime dateTime = dateFactory.newDateTime();
            DateTime nextYearDateTime = dateTime.plusYears(1);

            Map<String, String> depYearMap = new LinkedHashMap<String, String>();

            String thisYear = dateTime.toString("Y");
            String nextYear = nextYearDateTime.toString("Y");
            depYearMap.put(thisYear, thisYear);
            depYearMap.put(nextYear, nextYear);

            return Collections.unmodifiableMap(depYearMap);
        }
    }
```

- xxx-codelist.xml
```
    <bean id="CL_YEAR" class="com.example.sample.domain.codelist.DepYearCodeList">
        <property name="dateFactory" ref="dateFactory" />
    </bean>
```
