### ISSUE TITLE
Improve input tag of code block in the OAuth chapter.

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3186]
## Description
delete unused attributes in the OAuth chapter
add `id` attribute

## Possible Solutions
before
`<input name="authorize" value="Authorize" type="submit"/>`
after
`<input type="submit" id="authorize" value="Authorize"/> `

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) ※in #3173
- [x] 1.5.2_ja (m-t/1.5.x)

## Final Solution
`<input value="Authorize" id="authorize" type="submit"/>`

## Change log(should be updated at the same time)
Not Required

## English Translation
- [ ] Required, handle created another issue

## Migrating Guide
Not Required

## Issue Links
- #3173

**Comment by yoshikawaa** [comment]
@bthondamsb 
リクエストパラメータauthorizeは特に使われてなかったってことで良いんですかね？
※Description見てもなぜこの修正するのか分からないので、書き直したほうが良さそうです。

**Comment by bthondamsb** [comment]
@yoshikawaa 

name,value属性が存在しない状態のThymeleaf版で正常に動作したことを 確認しました。
Descriptionも修正します。

**Comment by bthondamsb** [comment]
@yoshikawaa 
ボタンの表示名は変更しないほうがよいと思いますので、
name属性の削除のみを行いたいと思います。

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
