### ISSUE TITLE
[4.3 Implementation of Application Layer] Description of include.jsp in English version is wrong

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#319]
Description(translation) of (4) is wrong.

Detail, please refer to http://terasolunaorg.github.io/guideline/1.0.x/en/ImplementationAtEachLayer/ApplicationLayer.html#creating-common-jsp-for-include .

Reason of bug exists in Japanese version.

Therefore...

* Step 1, modify description in the Japanese version.
* Step 2, reflect to the English version.

**Comment by btshimizukza** [comment]
@attarudes 

Could you please check this ?

**Comment by attarudes** [comment]
I think existing explanation is bit confusing to understand.
It should be modified with below line.

The content of the include jsp (/WEB-INF/views/common/include.jsp) will be placed at the top of each jsp which is specified at url-pattern (*.jsp).

**Comment by btshimizukza** [comment]
@attarudes 

Thanks for your suggestion !! Very good :+1: 
I modify Japanese version and reflect your suggestion into English version.
