### ISSUE TITLE
Delete extra space(file upload)

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3192]
## Description
Delete extra space(file upload)

## Possible Solutions
before
`<form:errors  path="description" />`
　　　　　　　　^^^
　　　　　　Two spaces

after
`<form:errors path="description" />`
　　　　　　　　^^^
　　　　　　One space

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.1_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.1_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) ※in #3182
~~- [ ] 1.5.1_ja (m-t/1.5.x) ※in #3182~~

## Final Solution
`<form:errors path="description" />`

## Change log(should be updated at the same time)
Not Required

## English Translation
- [ ] Required, handle created another issue

## Migrating Guide
Not Required

## Issue Links
- #3182

**Comment by yoshikawaa** [comment]
@bthondamsb ぱっと見、Possible Solutionsの意味が分からないですね。

**Comment by bthondamsb** [comment]
スペースの数を記載しておきました。
