### ISSUE TITLE
Consider deleting explanation that defines View Resolver with bean element

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#3197]
## Description
例えば、[3.4 アプリケーション層の実装 - 3.4.1.5.1. HTMLを応答する](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#html)

> `<bean>`要素を使用する場合の定義例
> ```xml
> 
> <bean class="org.springframework.web.servlet.view.InternalResourceViewResolver">
>     <property name="prefix" value="/WEB-INF/views/" /> 
>     <property name="suffix" value=".jsp" /> 
>     <property name="order" value="1" /> 
> </bean>
> ```

Spring 4.1より前の、昔の文法をずっと残しておいても新規開発で使うことはないため、
特に`mvc:view-resolvers`でできない利用方法がないのであれば、削除しまって良いと思われる。
（新しい文法に切り替えを促すべき）

## Possible Solutions
削除する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.1_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.1_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master)
- [x] 1.5.1_ja (m-t/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- [ ] Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk @bthondamsb 
PR出してもらってるようですが、`<bean>`要素を使用する場合は5.4.1以降サポートしない（利用者がアップデートする際には`mvc:view-resolvers`に切り替えてもらう）で良いですね？

**Comment by NaozumiTaromaru** [comment]
exposeContextBeansAsAttributesとか使いたいときは、展開されたbean定義が無いと厳しいんじゃないかと。(多分サンプルでは使ってないと思いますが。)

**Comment by bthondamsb** [comment]
検討した結果、
ガイドラインで推奨する範囲ではないので、
`mvc:view-resolvers`のみの紹介とすることとなりました。

**Comment by bthondamsb** [comment]
Bean定義による設定が必要なものは以下
`alwaysInclude`
`exposeContextBeansAsAttributes`
`exposedContextBeanNames`

上記はガイドラインで扱っておらず前述のとおり推奨する範囲ではないため
今回の対応により`<bean>`要素を使う例は削除をする。

**Comment by bthondamsb** [comment]
追記
Bean定義による設定が必要なものは以下です。

alwaysInclude ：Viewファイルに対してフォワードまたはインクルードのどちらを行うかを制御する。

exposeContextBeansAsAttributes ：コンテキスト内のすべてのBeanをリクエスト属性として使用できるようにする。→EL式から参照できる。

exposedContextBeanNames ：nullでない場合、すべてのBeanとは対照的に、指定したリスト内のBeanを公開することができる。→EL式から参照できる。

上記3点はインターネット上でのコード例も少なく、日付も古いため使用頻度が低いと考えられます。
よって今後ガイドラインで扱う可能性は低いと判断し、今回の対応により`<bean>`要素を使う例は削除します。

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
