### ISSUE TITLE
Modified reference label exception-handling-how-to-use-codingpoint-jsp-exceptioncode-label

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3202]
## Description
Unify View Name of Sphinx label

## Possible Solutions
before
`exception-handling-how-to-use-codingpoint-jsp-exceptioncode-label`

after
`exception-handling-how-to-use-codingpoint-view-exceptioncode-label`

and more...

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.1_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.1_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) 
- [x] 1.5.1_ja (m-t/1.5.x) 

## Final Solution
`exception-handling-how-to-use-codingpoint-view-exceptioncode-label`

## Change log(should be updated at the same time)
Not Required

## English Translation
- [ ] Required, handle created another issue

## Migrating Guide
Not Required

## Issue Links
- #3182

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
