### ISSUE TITLE
Adjust the size of the image file in chaptor of Codelist

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3215]
## Description
コードリストの章でThymeleaf 版と以下の画像ファイルの大きさが異なるため、揃える必要がある。
1. codelist-simple.png
1. codelist-number.png
1. codelist-jdbc.png
1. codelist-i18n.png
1. codelist-enum.png

## Possible Solutions
対象画像を
幅:960px
横:720px
に統一する

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.1_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.1_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) in #3175 
- [x] 1.5.1_ja (m-t/1.5.x)
## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #3175

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
