### ISSUE TITLE
Optimize framework stack order (Thymeleaf)

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/guideline#3230]
## Description
Optimize order.

## Possible Solutions
Order as follows.

* thymeleaf
* thymeleaf-spring
* thymeleaf-extras-springsecurity4
* thymeleaf-extras-java8time (new!
* unbescape
* ognl
* attoparser
* javassist

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 1.6.0_ja (m-t/master)
- [x] 1.5.1_ja (m-t/5.4.x)

## Final Solution
See Possible Solutions

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by hosoitk** [comment]
Please backport.
