### ISSUE TITLE
Typo in Codelist.rst

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3234]
## Description
[4.8.2.1.2. JSPでのコードリスト使用](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Codelist.html#id31)

出力HTML
```
<select id="orderStatus" name="orderStatus">
   <option value="">"--Select--</option>
   <option value="1">Received</option>
   <option value="2">Sent</option>
   <option value="3">Cancelled</option>
</select>
```

`"--Select--` となっているが、 `"` は出力されない

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0_ja (master)
- [x] 5.4.1_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.1_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) in #3175
- [x] 1.5.1_ja (m-t/1.5.x)
## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
