### ISSUE TITLE
Modified CodeListInterceptor Description  in Codelist.rst

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3237]
## Description

[4.8.2.1.2. JSPでのコードリスト使用](
http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Codelist.html#jsp)

> "CL\_"で定義したbeanIDは、リクエストスコープに設定されるため、JSPで使用可能となる。

とありますが、「使用可能」となるわけではなく、「容易に参照できる」に変更したほうが良いのではないでしょうか？

> codeListIdPatternを省略した場合は、すべてのコードリスト(org.terasoluna.gfw.common.codelist.CodeListインタフェースを実装しているbean)がJSPで使用可能となる。

も同様に、「JSPで使用可能となる」ではなく、「リクエストスコープに設定される」ではないでしょうか？

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) in #3175 
- [x] 1.5.2_ja (m-t/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
