### ISSUE TITLE
How to get Request Attribute from View?

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3241]
## Description

Thymeleafで リクエスト属性からオブジェクトを取得する際には `${}` か、`${#request.getAttribute()}`  のどちらかに統一したほうが良いのではないでしょうか？

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 1.6.0_ja (m-t/master) 

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- Not Required 

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by btmorikawanoh** [comment]
口頭でお話したとおり、`${#request.getAttribute('')}`を使用している箇所を`${}`に修正します。
