### ISSUE TITLE
Modifi Description of CodeListInterceptor in Codelist.rst

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3243]
## Description

1. `SimpleI18nCodeList` で fallBackTo 機能についての概要説明を追加。

1. [4.8.2.6. 特定のコード値からコード名を表示する](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Codelist.html#id49)

  > JSPからコードリストを参照する場合は、` java.util.Map` インタフェースと同じ方法で参照することができる。

とあるが、コードリスト = `Map` の意味に取れるので、
`CodeListInterceptor` を用いて、参照する方法の説明を以下のように修正

> JSPからコードリストを参照する場合は、 ``CodeListInterceptor`` がリクエストスコープにコードリストを  ``java.util.Map`` で格納しているため、``Map`` インターフェースと同じ方法で参照することができる。

## Possible Solutions
Please read description.

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) in #3247
- [x] 1.5.2_ja (m-t/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
