### ISSUE TITLE
Codelist bean direct reference from JSP by SpEL expression

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3246]
## Description
[4.8.2.1.1. コードリスト設定例](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Codelist.html#id30)
では、`CodeListInterceptor` でコードリストをリクエスト属性に設定していますが、コードリストの数が多くなると、リクエスト毎のオーバーヘッドの増加が懸念されます。

オーバーヘッドを防ぐ手法の一つとして、Bean定義したコードリストをJSPからSpEL式で参照して、取得する方法の紹介もAppendixであっても良いと思いますいかがでしょうか？

## Possible Solutions

xxx-codelist.xml
```
<bean id="CLDR_ORDERSTATUS" class="org.terasoluna.gfw.common.codelist.SimpleMapCodeList">
    <property name="map">
        <util:map>
            <entry key="1" value="Received" />
            <entry key="2" value="Sent" />
            <entry key="3" value="Cancelled" />
        </util:map>
    </property>
</bean>
```

jsp
```
<spring:eval var="orderStatus" expression="@CLDR_ORDERSTATUS.asMap()"/>
<form:select items="${orderStatus}" path="codelistForm.code" />
```

`CodeListInterceptor` の設定は外す。ただし、 `SimpleI18nCodeList` を使用する場合は、`CodeListInterceptor` が提供している fallBackTo が使用できない旨を記述する。

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master)  in #3175 
~~- [ ] 1.5.2_ja (m-t/1.5.x) ~~

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- [ ] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- terasolunaorg/terasoluna-gfw#636
- #3231

**Comment by kazuki43zoo** [comment]
ちなみに、共通ライブラリ側にも関連Issueがあるので合わせて検討するのが良いかと思います。

terasolunaorg/terasoluna-gfw#636
