### ISSUE TITLE
Modify description of "add logout button" image in TutorialSecurity.rst

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3256]
## Description
[10.4.4.2.4. ログアウトボタンの追加](
http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/Tutorial/TutorialSecurity.html#id17)
で

> Logoutボタンを押下し、アプリケーションからログアウトする(ログインページが表示される)。

となっているが、画像は、`welcome/home.jsp` のものとなっている。
Logoutボタンが追加されたことを画像で説明したいと言うのが主旨だと思われるので、画像の内容と一致していない。

## Possible Solutions
「Logoutボタンを押下すると、アプリケーションからログアウトする(ログインページが表示される)。
」

に修正する。

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) in #3247
- [x] 1.5.2_ja (m-t/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #3247

**Comment by yoshikawaa** [comment]
@btkomatsubaratka 言葉尻だけ変えても、あまり意味がないと思われます。

画像を二枚用意して、

* ウェルカムページにLogoutボタンが表示される。
* Logoutボタンを押下し、アプリケーションからログアウトする(ログインページが表示される)。

と説明するのが適切かと。

**Comment by btkomatsubaratka** [comment]
8fed7430286b8b2e58a1b6cfbda22aca64255c9e で対応 @btkomatsubaratka

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
