### ISSUE TITLE
Confirm the description of the problem that has already been fixed(OAuth)

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3263]
## Description
[認可サーバにおけるパスのカスタマイズ - パスのカスタマイズ - エンドポイントのカスタマイズ](https://github.com/terasolunaorg/guideline/blob/master/source/Security/OAuth.rst#%E3%82%A8%E3%83%B3%E3%83%89%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA)

エンドポイントのカスタマイズに記載されているwarningで言及されている問題はすでに修正済みであると思われる。
`Spring Security OAuthのバージョン2.0.12以前を使用する場合、check-token-endpoint-urlは、authorization-endpoint-urlまたはtoken-endpoint-urlを指定していない場合は反映されないため注意が必要である。 これは以下のissueで取り上げられており、バージョン2.0.13で改修される予定である。`

改修が確認された場合、古いバージョンを使うことは無いように思えるので該当のwarningを削除する。

## Possible Solutions

Reflect verification result

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master)　※in #3173
- [x] 1.5.2_ja (m-t/1.5.x)　　

## Final Solution

Reflect verification result

## Change log(should be updated at the same time)
~~Not Required~~
- [ ] Required

## English Translation
- [ ] Required, handle created another issue

## Migrating Guide
Not Required

## Issue Links
- #XXX

**Comment by bthondamsb** [comment]
動作検証し、エラーが発生しないことが確認できたのでガイドライン修正作業を実施します。

証跡のログは以下

[Before_spring-functionaltest-oauth2-remote-application.log](https://github.com/terasolunaorg/guideline/files/1766512/Before_spring-functionaltest-oauth2-remote-application.log)
[After_spring-functionaltest-oauth2-remote-application.log](https://github.com/terasolunaorg/guideline/files/1766513/After_spring-functionaltest-oauth2-remote-application.log)

**Comment by bthondamsb** [comment]
動作検証し、エラーが発生しないことが確認できたのでガイドライン修正作業を実施します。

証跡のログは以下
[After.log](https://github.com/terasolunaorg/guideline/files/1766703/After.log)
[Before.log](https://github.com/terasolunaorg/guideline/files/1766704/Before.log)

**Comment by kazuki43zoo** [comment]
このIssueに記載されている内容だけ見ても何が問題なのか（＝何が修正対象なのか）わからない・・・。

**Comment by yoshikawaa** [comment]
www 

@bthondamsb 本文修正していただいたようですが、該当箇所へのリンクも付けておきましょう。

**Comment by bthondamsb** [comment]
該当箇所へのリンクを追加しました。

**Comment by kazuki43zoo** [comment]
👍

**Comment by yoshikawaa** [comment]
@sasakitsy @bthondamsb 更新履歴を書くよう、Issueを変更しました。
