### ISSUE TITLE
Unification of terms in Thymeleaf TBD-1st

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3268]
## Description
Unification of terms in Thymeleaf
(deal with pending problem in the first development)

## Possible Solutions

Correction of parts found by dictionary and overall confirmation

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 1.6.0_ja (m-t/master)
- [x] 1.6.0_ja (m-t/master 2nd)

**※第2次部分再チェック要**

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
[TODO] @bthondamsb PR集約後に第2次対応分を見直す。
