### ISSUE TITLE
Session Tutorial Application is not implemented for tiles

### ISSUE THREAD

**Issue by btkatagiriyu** [terasolunaorg/guideline#3270]
## Description
セッションチュートリアルのJSPが`<html>`タグから定義されており、
Tilesを適用することにより、`<body>`タグ内部に`<html>`タグが再定義される構成となってしまっている。

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 5.3.3_ja (5.3.x)
- [x] 5.2.2_ja (5.2.x)
- [x] 5.1.2_ja (5.1.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- [x] Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
