### ISSUE TITLE
Delete Input tag's Slash in Thymeleaf TBD-1st

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3274]
## Description
Delete Input tag's Slash 
It is not necessary if it is HTML5 compliant

## Possible Solutions

Before
`<input />`

after
`<input>`

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 1.6.0_ja (m-t/master)
- [x] 1.6.0_ja (m-t/master 2nd)

**※第2次部分再チェック要**

## Final Solution
`<input>`

## Change log(should be updated at the same time)
- [ ] Required

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
[TODO] @bthondamsb PR集約後に第2次対応分を見直す。
