### ISSUE TITLE
Different contents of spring-mvc.xml in TutorialSecurity.rst

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/guideline#3275]
## Description
[10.4.6.1.2. spring-mvc.xml](http://terasolunaorg.github.io/guideline/5.3.1.RELEASE/ja/Tutorial/TutorialSecurity.html#spring-mvc-xml) で `spring-mvc.xml` を掲載しているが、ガイドで紹介している以下のコマンドで生成された `spring-mvc.xml` と内容が異なる。

```
mvn archetype:generate -B^
 -DarchetypeGroupId=org.terasoluna.gfw.blank^
 -DarchetypeArtifactId=terasoluna-gfw-web-blank-mybatis3-archetype^
 -DarchetypeVersion=5.3.1.RELEASE^
 -DgroupId=com.example.security^
 -DartifactId=first-springsecurity^
 -Dversion=1.0.0-SNAPSHOT
```
## Possible Solutions
ガイドの`spring-mvc.xml`を以下のコマンドで生成された、`spring-mvc.xml` に合わせて修正する。

```
mvn archetype:generate -B^
 -DarchetypeGroupId=org.terasoluna.gfw.blank^
 -DarchetypeArtifactId=terasoluna-gfw-web-blank-mybatis3-archetype^
 -DarchetypeVersion=5.3.1.RELEASE^
 -DgroupId=com.example.security^
 -DartifactId=first-springsecurity^
 -Dversion=1.0.0-SNAPSHOT
```

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0_ja (master)
- [x] 5.4.2_ja (5.4.x)
- [x] 1.6.0_ja (m-j/master)
- [x] 1.5.2_ja (m-j/1.5.x)
- [x] 1.6.0_ja (m-t/master) in #3247
- [x] 1.5.2_ja (m-t/1.5.x)

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@btkomatsubaratka Please backport to m-t 1.5.x.

**Comment by yoshikawaa** [comment]
@hosoitk English translation remaining.
