### ISSUE TITLE
Modified Session Management that isEmpty is judged twice in Thymeleaf TBD-1st

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3277]
## Description
Modified Session Management that isEmpty is judged

## Possible Solutions

Include the second for the first

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 1.6.0_ja (m-t/master)

## Final Solution
Include the second for the first

## Change log(should be updated at the same time)
- [ ] Required

## Migrating Guide
- Not Required

## Issue Links
- #3027

**Comment by yoshikawaa** [comment]
@hosoitk m-t ver English translation not required.
