### ISSUE TITLE
Modified Description about ViewResolver Priority in Thymeleaf TBD-1st 

### ISSUE THREAD

**Issue by bthondamsb** [terasolunaorg/guideline#3284]
## Description
ViewResolverの優先順位に関する説明が存在していなかったため、
実装例を用いた説明を書き加える必要がある。

## Possible Solutions
優先順位の説明がしやすいように実装例を修正し、
それを用いた説明を書き加える。

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 1.6.0_ja (m-t/master)

## Final Solution

優先順位の説明がしやすいように実装例を修正し、
それを用いた説明を書き加える。

## Change log(should be updated at the same time)
- Not Required

## Migrating Guide
- Not Required

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@hosoitk m-t ver English translation not required.
