### ISSUE TITLE
Add a description about th: errorclass in Tymeleaf.

### ISSUE THREAD

**Issue by btkatagiriyu** [terasolunaorg/guideline#3292]
## Description
Add a description about th: errorclass in Tymeleaf.

## Possible Solutions
Thymeleaf版ガイドラインの「4.2.2.2.1. 基本的な単項目チェック」にて、
``<label>``タグの``th:errorclass``を使用する際、``name``属性を設定する旨の記載があるが、
もう少し説明を追加したほうが良い。

参考： org.thymeleaf.spring4.processor.SpringErrorClassTagProcessor#computeBindStatus
There are two scenarios for a th:errorclass to appear in: one is in an element for which a th:field has already been executed, in which case we already have a BindStatus to check for errors; and the other one is an element for which a th:field has not been executed, but which should have a "name" attribute (either directly or as the result of executing a th:name) -- in this case, we'll have to build the BuildStatus ourselves.

## Fix Version/s
(To be written later by project member)
- [x] 1.6.0_ja (m-t/master)
* ~~1.5.2_ja (m-t/1.5.x)~~

## Final Solution
(To be written later by project member)

## Change log(should be updated at the same time)
- Not Required

## English Translation
- [ ] Required, create a new issue for handling

## Migrating Guide
- Not Required

## Issue Links
- (パブリックなリンクではないため、削除しました)

**Comment by yoshikawaa** [comment]
@hosoitk アサインお願いします。

**Comment by yoshikawaa** [comment]
@hosoitk 
Removed target 1.5.x.
English translation remaining.

**Comment by yoshikawaa** [comment]
@btnakamuranom Thanks.
