### ISSUE TITLE
Reflect #189(Added the tip of about Internet Explorer 'friendly' error message) to English version

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#348]
Please reflect #189
related issue : #347

-
Required
- [x] master
- [x] 5.0.x
- [x] translation/5.0.0

-
Optional
- 1.0.x (Not apply)
- 1.0.2.RELEASE (Not apply)

-
Targeted PR

 - [x] #340

**Comment by kazuki43zoo** [comment]
@attarudes 

Please reflect(cherry-pick) into master & 5.0.x.

**Comment by attarudes** [comment]
Cherry-pick to master & 5.0.x has been done. 
Please review corresponding pull requests
  #966 -> 5.0.x
  #968 -> master

**Comment by btshimizukza** [comment]
@btamurutab @attarudes 

Thanks for translation !
