### ISSUE TITLE
5.3. データベースアクセス（Mybatis2編） - LOB型を扱う場合の設定 の説明が間違っている

### ISSUE THREAD

**Issue by NaozumiTaromaru** [terasolunaorg/guideline#402]
先日、
(グローバルFW使ってなかったと思うけど)
グローバルFWのドキュメントを参考にしてLob周りの設定をしたが、
Lob操作でエラーになった
と問い合わせを受けたのでフィードバック。

5.3. データベースアクセス（Mybatis2編）
5.3.2.2.4. LOB型を扱う場合の設定
http://terasolunaorg.github.io/guideline/1.0.1.RELEASE/ja/ArchitectureInDetail/DataAccessMybatis2.html#lob
項番(1)
```
org.springframework.jdbc.support.nativejdbc.NativeJdbcExtractorインタフェースの実装クラスを、bean定義する。

例では、org.springframework.jdbc.support.nativejdbc.SimpleNativeJdbcExtractorを指定しているが、

Tomcat以外のAPサーバでは、nativeデータソースを取得できない場合があるので、

Springが提供している他のNativeJdbcExtractorを指定するか、各APサーバ用に、新たにNativeJdbcExtractorを作成する必要がある。
```
の内容が間違っている。(古い現行FWのJavaDocがベースになっていると思われる。)
・TomcatならSimpleNativeJdbcExtractorでよさそうに見える記述だが、
  SimpleNativeJdbcExtractorは最近のTomcatでは通用しない。
・NativeJdbcExtractorの役割は、「nativeデータソースを取得」ではない、
  というか「nativeデータソース」って何？
等。

現行FWの2.0.5.0以前のJavaDocが元ネタだと思うが、2.0.5.1で、すでに修正しているので、
修正内容を取り込んだ方がよい。

修正前JavaDoc(多分これが元ネタ)
http://terasoluna.sourceforge.jp/javadoc/server-web_2.0.5.0/terasoluna-ibatis-2.0.5.0/?jp/terasoluna/fw/orm/ibatis/support/BlobInputStreamTypeHandler.html

修正後JavaDoc
http://terasoluna.sourceforge.jp/javadoc/server-web_2.0.5.1/terasoluna-ibatis-2.0.5.1/?jp/terasoluna/fw/orm/ibatis/support/BlobInputStreamTypeHandler.html

Fix Versions: 1.0.2, 5.0.0

**Comment by btshimizukza** [comment]
Need to backport to 1.0.x and translate.
