### ISSUE TITLE
Support validation for String object in collection

### ISSUE THREAD

**Issue by kinopie** [terasolunaorg/guideline#407]
## Description

複数選択可能な画面項目（チェックボックスや複数選択ドロップダウンとか）に対応したExistInCodeListアノテーションがあるとよいと思います。配列がnullか空か、もしくは配列中の全要素がCodeListに存在する場合はOK、そうでなければNG、的な。
## Possible Solution

http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Validation.html#validation-convine-existing-constraint
の次の節あたりに、
- [ ] コレクション型の `String` に対する入力チェックとして以下の方法を追記する。
  Springの型変換(Converter + ConversionService)を利用
  #1548 (comment)
- [ ] JDK8とHB5.2を用いた方法
  https://github.com/terasolunaorg/guideline/issues/407#issuecomment-150167706
- [ ] コードリスト章の方からもリンクを貼っておく。
  http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Codelist.html#codelist-validate
## Affect Versions
- 5.1.0
- 5.0.2
- 1.0.4
## Fix Versions
- [x] 5.3.0_ja
- [ ] 5.3.0_en

**Comment by making** [comment]
Hibernate Validatorを5.2にして、Java 8から導入された`java.lang.annotation.ElementType.TYPE_USE`を使えば、

``` java
List<@ExistInCodeList8(codeListId = "CL_XXX") String> listOfCode;
```

という書き方が可能に。

http://in.relation.to/2015/07/30/hibernate-validator-521-final/

Java 8以上必須にしたい・・

**Comment by kazuki43zoo** [comment]
@ikeyat @making @kinopie 

XxxCodeValueを作ると、↓のような実装＋工夫が必要になりそうな気がするのですが、そんなことないですかね？（私の知識不足なだけ？）

* https://github.com/terasolunaorg/guideline/issues/1548#issuecomment-171675906

やはり、Java 8にして、Hibernate 5.2+ & `java.lang.annotation.ElementType.TYPE_USE` で実現するようにしたいですね。

**Comment by kazuki43zoo** [comment]
@ikeyat @making @kinopie 

Springの型変換(`Converter` + `ConversionService`)を利用することで、いろいろ解決できそうです。
https://github.com/terasolunaorg/guideline/issues/1548#issuecomment-174261354

**Comment by ikeyat** [comment]
本件、比較的ニーズが多いことから、2016 Summerに設定。

**Comment by kazuki43zoo** [comment]
このIssueとは直接関係ないですが、Bean Validation 2.0 (Hibernate 6)で TYPE_USEがサポートされる模様？

* http://beanvalidation.org/news/2016/07/15/bean-validation-2-0-is-coming/
* https://hibernate.atlassian.net/projects/BVAL/issues/BVAL-508?filter=allopenissues

Bean Validation 2.0自体は2017 1QにFinal Release予定っぽい。Hibernate Validatorはその後か同時だろうから・・完全サポートは2018 Winter(5.4.0)かな？ 

Bean Validation 2.0で対応してほしいものがあれば、Issueあげましょう。（手遅れかもしれないが・・）

**Comment by btyoshikawaa** [comment]
@kazuki43zoo @btfurukawatkr 
（@kazuki43zoo とお話したことのログです）

#### Java Beanを使ったStringのラッパークラスによる実装 について
今回のシナリオは、画面のチェックボックスを`List<String>`にバインドしてチェックする場合を想定して書いているので`Formatter`を利用した実装で良いと思うのですが、メソッドバリデーションとか、画面（文字列）との変換に縛られずに、ピュアにコレクションの値をラップしてチェックする方法を考えた場合、`Formatter`より`Converter`実装のほうが適切なんじゃない？みたいな話もあるかと思います。

##### #2055 Add explanation about bean conversions in Spring MVC
本来は、こちらのIssueにあるとおりSpringが提供する型変換機能について包括的な説明があり、
その中から一例として`Formatter`を使った例を説明するよ！的な流れにすると良いのかなーと思います。

Ver 5.3.0 としては PR #1939 の対応で良いと思うので、今後の改善で！

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create translate issue, and close this.

**Comment by sasakitsy** [comment]
Translate in #2484 
And close this issue.

**Comment by making** [comment]
これ、わざわざ`Converter`作らなくても

* `String`を一つ引数に持つコンストラクタを作る
* `String`を一つ引数に持つstaticメソッド`valueOf`または`of`または`from`を作る

のどれかでいい気が。試してないけど。

**Comment by itouyun** [comment]
@making さん
コメントありがとうございます。試してみます。
`Converter`作らなくても実装できそうな場合、別issue立てて修正を検討します。
