### ISSUE TITLE
Support Lombok

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#408]
http://projectlombok.org/

やったほうが良さそう。

- [x] Lombokの代表的な使い方を説明するガイドラインの追加 #608 
* 各種チュートリアルでLombokを使用するように修正 -> 5.0.0としては対応しない
* 必要に応じて既存のガイドラインにLombokの話題を反映 -> 5.0.0としては対応しない
- [x] 英語化 #619

**Comment by kazuki43zoo** [comment]
@making 

Lombokの話題は、Appendixへの追加だけでいいですかね？でよければ、closeします。
