### ISSUE TITLE
Reflect #268(Inconsistency in currency - Codelist.rst (Japanese version)) to English version

### ISSUE THREAD

**Issue by tatsutanik** [terasolunaorg/guideline#425]
Please reflect #268
related issue : #205 

-
Require

- [x] master
- [x] 5.0.x
- [x] translation/5.0.0

-
Optional

- 1.0.x (Not apply)
- 1.0.2.RELEASE (Not apply)

-
Targeted PR

 - [x] #416

**Comment by kazuki43zoo** [comment]
@attarudes 

Please reflect(cherry-pick) into master & 5.0.x.

**Comment by attarudes** [comment]
Cherry-pick to master & 5.0.x has been done. 
Please review corresponding pull requests
  #967 -> 5.0.x
  #969 -> master

**Comment by btshimizukza** [comment]
@btamurutab @attarudes 

Thanks for translation !
