### ISSUE TITLE
JdbcCodeListにjdbcTemplateを設定する方法を推奨パターンにする

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#501]
## Description
現在、How to useには `dataSource` を設定(Inject)する方法が記載されているが、`jdbcTemplate` を指定する方法に変更し、推奨パターンとして紹介するように修正する。

## Possible Solutions
同上

## Affects Version/s
* 5.0.1.RELEASE
* 1.0.3.RELEASE

## Fix Version/s
- [x] 5.1.0.RELEASE
- [x] 5.0.2.RELEASE

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/39
* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/130
* #1494

**Comment by kazuki43zoo** [comment]
English translation will resolve via #1494.
