### ISSUE TITLE
[Spring4対応] @ControllerAdviceの変更内容をガイドラインに反映する

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/guideline#549]
Spring4対応(#482)に伴い、@ControllerAdviceの変更内容を確認しガイドラインに反映する。

- [x] https://github.com/terasolunaorg/guideline/issues/549#issuecomment-71297111 #758

**Comment by kazuki43zoo** [comment]
REST編の例外ハンドリングのセクションにて、 `@ControllerAdvice(annotations = RestController.class)` を付与するようにガイドしているが、属性を指定してしまうと、リクエストに対応するハンドラー(Controllerのメソッド)が見つからなかった時に発生する例外をハンドリングできない。(405 Method Not Allowが適切にハンドリングできない)

ガイドラインとしては、Webアプリを分ける/サーブレットを分けることを推奨しているので、Globalな例外ハンドラーについては属性は指定しない例に修正する。特定の範囲の例外ハンドラー(複数のコントローラに適用するような例外ハンドラー)を設ける場合は、属性を使用して対象を絞ることで実現できる旨をnote or tipとして記載するように修正する。
