### ISSUE TITLE
第3章チュートリアル(Todoアプリケーション)をMyBatis3に対応させる。

### ISSUE THREAD

**Issue by btmiyashitasts** [terasolunaorg/guideline#550]
第3章チュートリアル(Todoアプリケーション)をMyBatis3に対応させる。
- [x] プロジェクトの作成
- [x] プロジェクト構成
- [x] todo-infra.xmlの確認
- [x] todo-env.xmlの確認
- [x] spring-mvc.xmlの確認
- [x] Serviceの作成
- [x] MyBatis3を使用したインフラストラクチャ層の作成
- [x] 最終的にsnapshotsをreleasesに修正

**Comment by btshimizukza** [comment]
#451 (#728) で対応済み。
