### ISSUE TITLE
[Spring IO platform対応] JPA(Hibernate ORM)のバージョンアップ内容をガイドラインに反映する

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#556]
Spring4対応(#482)に伴い、JPAのバージョンを2.1(Hibernate ORM 4.3系)にする。

JPA 2.1の変更点、Hibernate ORM 4.3系の変更点を反映する。

5.0.0では、必要最低限の反映のみ行い、新機能の記載は5.0.1以降のバージョンで行う。

**Comment by kazuki43zoo** [comment]
Spring Data JPAがサポートしたJPA 2.1の新機能は以下の２つ。

* [Configuring Fetch- and LoadGraphs](http://docs.spring.io/spring-data/jpa/docs/1.7.1.RELEASE/reference/html/#jpa.entity-graph)
* [Stored procedures](http://docs.spring.io/spring-data/jpa/docs/1.7.1.RELEASE/reference/html/#jpa.stored-procedures)

上記の新機能については、5.0.1以降のバージョンでの反映を計画する。(5.0.0では反映しない)

**Comment by kazuki43zoo** [comment]
JPA 2.1の主な新機能(変更点)としては、

* `@EntityGraph` (ネストしたEntityのロード方法の柔軟な指定)
* ストアードプロシージャの呼び出し(抽象化)のサポート
* RDBMS固有(ユーザ定義)のSQL関数の呼び出し(抽象化)のサポート
* エンティティリスナのCDI連携
* `AttributeConverter` を使用した値の変換
* `SynchronizationType` を使用した永続化コンテキストとトランザクションとの同期化のコントロール
* `@ConstructorResult` を使用したNative SQLの実行結果からオブジェクトを生成(NEW)する仕組みの追加

などがあるが、5.0.0ではこれらに変更はガイドラインには反映しない。反映すべき内容を選定した上で、5.0.1以降のバージョンでの反映を計画する。

**Comment by btshimizukza** [comment]
新機能の反映については #853 へ移動。本issueはcloseする。
