### ISSUE TITLE
第7.1.章の チュートリアル(Todoアプリケーション REST編)にMyBatis3/SpringSecurity3.2に対応させる

### ISSUE THREAD

**Issue by btmiyashitasts** [terasolunaorg/guideline#565]
第7.1.章の チュートリアル(Todoアプリケーション REST編)にMyBatis3/SpringSecurity3.2に対応させる。
- MyBatis3対応
    - [x] プロジェクト作成
    - [x] ドメイン層のファイルをコピー
    - [x] spring-mvc-rest.xmlの作成
- SpringSecurity3.2対応
    - [x] REST API用のSpring Securityの定義追加
- 誤記修正
    - [x] web.xmlの修正
    - [x] POST Todosの実装

- [x] プロジェクト作成時の``archetypeCatalog``、``archetypeVersion``、``version``は最終的にはsnapshotsではく、releasesに修正すること

**Comment by btshimizukza** [comment]
#451 (#730) で対応済み。
