### ISSUE TITLE
Translate #560(about @RestController)

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/guideline#582]
Please reflect #560.
related issue : #241 

- [x] 5.0.0.RELEASE
- [x] master
- [x] 5.0.x

Targeted PR

 - [x] #552
 - [x] #581
 - [x] #622

**Comment by attarudes** [comment]
All targeted PRs are done.

**Comment by btamurutab** [comment]
Already committed under https://github.com/terasolunaorg/guideline/issues/580 and https://github.com/terasolunaorg/guideline/issues/885
