### ISSUE TITLE
Translate TagLibAndELFunctions.rst into English

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#618]
@attarudes 

Could you please translate?
https://github.com/terasolunaorg/guideline/blob/master/source/Appendix/TagLibAndELFunctions.rst

refs #497

- [x] master
- [x] 5.0.x
- [x] translation/5.0.0

---

- [x] 1.0.x
- [ ] 1.0.2.RELEASE

**Comment by attarudes** [comment]
Translation completed with backport therefore closing the issue.
