### ISSUE TITLE
English Translation ServletUriComponentsBuilder -> UriComponentsBuilder (#374)

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#626]
reflect #374 in English

related issue : #625 

- [x] master
- [x] 5.0.x
- [x] 5.0.0.RELEASE
- [ ] 1.0.x
- [ ] 1.0.2.RELEASE

Targeted PR

 - [x] #520

**Comment by attarudes** [comment]
Below rst has been translated under #580 including backport to master and 5.0.x
   source/ArchitectureInDetail/REST.rst
