### ISSUE TITLE
[Internationalization] SessionLocaleResolverのdefaultLocaleの説明について

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#686]
「Localeを画面操作等で動的に変更する場合」にて、
`defaultLocal` の説明が（微妙に？）正しくないと思われる。

Springの実装を見る限りでは、以下の動きになっている。

* セッションからロケールを取得する。
* セッションからロケールが取得できない場合（つまり、セッション開始後にリクエストパラメータで切り替えを１回も行っていない場合）は、`defaultLocale` をロケールとして使用。
* セッションからロケールが取得できた場合（つまり、セッション開始後にリクエストパラメータで切り替え済みの場合）は、セッションから取得したロケールを使用。
* `defaultLocale` を適用する際に、`defaultLocale` の指定がない場合は、`HttpServletRequest#getLocale` から取得したLocaleが適用される（つまり、ブラウザの設定で指定したロケールを使用）。

という動きになっている。

※ `CookieLocaleResolver` も同様。

#18 の (3)からの派生。

## Affect Versions
* 5.0.1
* 1.0.3

## Fix Versions 
- [x] 5.1.0_ja
- [x] 5.0.2_ja
-  5.1.0_en (will be fixed at #1576)
-  5.0.2_en (will be fixed at #1576)

**Comment by ikeyat** [comment]
@btkobayashitkzp 
#686の5.0.xへのバックポートお願いします。英語対応は不要です。

**Comment by ikeyat** [comment]
@btkigamim  
#686 の5.0.xへのバックポートお願いします。英語対応は不要です。
