### ISSUE TITLE
JavaBeanの循環参照注意の追加

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#691]
`@ToString(exclude=...)`だけでなく、`@EqualsAndHashCode`やJacksonの`@JsonIgnore`についても除外設定しないとStackOverflowに陥る

- [x] Lombok使用時の回避方法の追加 #745 
- [x] Jackson使用時の回避方法の追加 #746 

[English Translation]
Moved to #878 .

**Comment by btshimizukza** [comment]
英語版への反映issueを発行したので、close.
