### ISSUE TITLE
[PublicReview]6.1. Spring Security概要

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#7]
内容に対するコメント
----

（１）
6.1.1. Overviewにて、
「Spring Securityの概要図を、以下に示す。」とあるが、コンポーネント毎の説明がないため、この図で何が示したいのかよくわからない。

（２）
6.1.1. Overviewにて、
CSRFもSpring Securityから提供されている機能を使っているので、ここで登場させた方がいいのでは？

（３）
6.1.1.1. 認証にて、
「認証とは、正当性を確認する行為であり、・・」とあるが、何の正当性を確認する行為？

（４）
6.1.1.1. 認証にて、
「利用ユーザにその権利があるかどうかや・・・」とあるが、「その権限」って何？ネットやサーバへ接続する権限？の事？

（５）
6.1.1.1. 認証にて、
「その人」と「利用ユーザ」の関係がよくわからない。「その人」ってどの人？

（６）
6.1.2.2. Web.xmlの設定にて、
springSecurityFilterChainの定義する位置（順番）に対する注意点や補足があった方がよい気がします。

（７）
6.1.2.2. Web.xmlの設定にて、
(3)の説明で「各種機能を有効にするための・・」とあるが、各種機能ってなんですか？
＋
厳密にいうと「org.springframework.web.filter.DelegatingFilterProxy」はSpring SecurityのServlet Filterではないので、簡単（noteなど）にspring-security.xmlで"springSecurityFilterChain"という名前でSpring SecurityのServlet Filter（SecurityFilterChain）がBean定義され、そのServletFilterに委譲するためのServletFilterを定義していることを説明があった方がよい気がします。

（８）
6.1.2.3. spring-security.xmlの設定にて、
use-expressions=”true”に対する説明だけあるのが、ちょっと違和感を感じました。
<sec:http>が何者かについては、全く触れないの？
＋
「アクセス属性のSpring EL式を有効することができる。」とあるが、アクセス属性って何？このタイミングではどこにも触れられていない。

記述に対するコメント
----
（９）
6.1.1.2. パスワードハッシュにて、
「平文のパスワードから、ハッシュ関数を用いて計算されたハッシュ値を、元のパスワードと置き換えることである。」
↓
「パスワードハッシュとは、平文のパスワードをハッシュ関数などを使用してハッシュ値に置き換えてことである」＋なぜ置き換えるのか（第三者への漏洩の可能性などの考慮について）の簡単な説明があった方がよいかと思います。

（１０）
6.1.1.3. 認可にて、
「アクセス制御処理でその利用者がそのリソースの使用を許可されていることを調べることである。」の「アクセス制御処理で」って必要ですかね？「アクセス制御処理として、」ならわからなくもないが・・。

（１１）
6.1.2.2. Web.xmlの設定にて、
springSecurityFilterChainの前後にomittedのコメントがあった方がよい。

（１２）
6.1.2.3. spring-security.xmlの設定にて、
noteにて、
「use-expressions=”true” で有効になるSpring EL式は、」とあるが、表現が正確ではない気がする。
「use-expressions=”true” とすることで有効になるアクセス属性の指定方法については、」とかなのでは？

（１３）
6.1.2.2. Web.xmlの設定と6.1.2.3. spring-security.xmlの設定にて、
説明する順番は逆の方が自然な気がします。
spring-security.xmlを用意して、用意したspring-security.xmlをweb.xmlで指定するという流れ。

**Comment by btshimizukza** [comment]
5.1.0で全面的に記載内容を見直したので、本Issueはクローズします。
