### ISSUE TITLE
メソッドバリデーションをSpring Framework上で適用する方法をAppendixに追加する

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#708]
#555 からの移行。
PRは#624 。

**Comment by nakamuraruk** [comment]
Method validationの挿入箇所調査結果です

[入力チェックのextend](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/Validation.html#how-to-extend)にMethod validationを挿し込むといいという印象でした。

* 新しいページを作る場合，入力チェック節とMethod Validation節間で内容が重複しないよう大きく書き直す必要があるから。
* 入力チェックの本論はControllerを前提にした話になっているので，ここに挿入すると本節の書き直しの負担が大きいから。
* 入力チェックのAppendixはアノテーションやプロパティ属性の索引として使われているので，機能の紹介をいれるとAppendixの統一感が下がるから。
* Method validationは本論にあるControllerでの入力チェックほど利用されないと考えられるので，extendとして扱うと利用頻度からみた場合に適当な位置づけになるから。

**Comment by making** [comment]
OK.　How to extendに追加する方向で対応お願いします

**Comment by nakamuraruk** [comment]
@btshimizukza @making 
AppendixにあるMethod validationをhow to extendに移しました。
さしあたっての加筆修正の方向性をご確認願います。

主な加筆修正点
1 契約プログラミングの説明の削除
契約プログラミングは、Method Validationに限らず入力チェックの章全体の事前知識という位置づけにあります。そのため、契約プログラミングの説明をあえて挿入するならば章の頭に入れるべきであり、章の途中であるHow to extendに挿むべきではないからです。

2 契約プログラミングで使われる用語の言い換え
契約、事前・事後条件を制約や制約を意味する言葉で置き換えています。
* 契約プログラミングの説明を取り除いたために上記の単語が未定義になるから
* 契約違反時の例外名がConstraintViolationExceptionであるから

3 validation=妥当性確認、あるいは確認
* 章本体で使われている「検証」は主にverificationの訳に使われる単語であるから
* ソフトウェア工学上のvalidationとverificationは意味が違うので、訳も区別できるものであるべきだから
です

**Comment by nakamuraruk** [comment]
ご確認しやすいようにリベースしてまとめました
