### ISSUE TITLE
プロジェクトのビルド方法の追加

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#740]
ブランクプロジェクトから作成した開発用のMavenプロジェクト(マルチプロジェクト)を、Mavenコマンドを使ってビルドする方法をガイドラインに追加する。

* mvn package (generate war or jar file)
* mvn sql:execute (initialize database)
* profileの切り替え

など。

https://github.com/terasolunaorg/guideline/blob/master/source/ImplementationAtEachLayer/CreateWebApplicationProject.rst

のAppendixに追加する予定。

**Comment by making** [comment]
#1146 と重複
