### ISSUE TITLE
[Authentication] UsernameNotFoundExceptionの扱いについて説明を追加する

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#750]
`UserDetailsService`のコーディングポイントとして、ユーザが見つからない時に発生させる例外(`UsernameNotFoundException`)の扱いや例外に設定するメッセージに関する説明を追加する。
- デフォルトだと `BadCredentialsException` に置き換わる
- `BadCredentialsException`の例外メッセージには メッセージコード(`AbstractUserDetailsAuthenticationProvider.badCredentials`)のメッセージが使われるので、`UsernameNotFoundException` に設定するメッセージはハードコーディングでも問題ない
- `UsernameNotFoundException` に設定したメッセージを使用するように変更できるが、通常のアプリケーションでは推奨されない

などの点を追加する。

http://terasolunaorg.github.io/guideline/1.0.1.RELEASE/ja/Security/Authentication.html#authentication-failure-handler-ref

に `UsernameNotFoundException` についての注意点の記載はあるが、説明箇所として適切な箇所ではない。

**Comment by iwanagah** [comment]
@btshimizukza 取り込まれているか確認をお願いします

**Comment by btshimizukza** [comment]
@ikeyat @iwanagah 

↑のコメントが全て取り込まれているわけではありませんが、必須部分は #1325 で反映されているので、クローズ扱いでも問題ありません。

**Comment by btshimizukza** [comment]
5.0.x系の反映は別途検討が必要。 5.1.0だけでもよい気はします。

**Comment by kazuki43zoo** [comment]
@sasakitsy これは  #1325  で対応済みなのでクローズでよいと想います。
