### ISSUE TITLE
[Authentication] Translate #760(session management improvement)

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#767]
Reflect #760 to English version.

related issues : #754 , #253 

- [x] master
- [x] 5.0.x
- [x] 5.0.0.RELEASE
- [ ] 1.0.x
- [ ] 1.0.2.RELEASE

Targeted PR

 - [x] #760

**Comment by attarudes** [comment]
Translation completed with backport therefore closing the issue.
