### ISSUE TITLE
[Authentication] Improve remember-me authenticatoin

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#785]
## Description
#754 から移動。
## Possible Solution
- [x] keyの説明が不足している。（keyを指定しないとサーバを再起動した際にトークンが無効になる点を補足する） -> 元々対応済みだった。
- [x] parameter名とcookie名はデフォルトから変更することを推奨する旨と変更例を追加する。
    [SEC-2826](https://jira.spring.io/browse/SEC-2826)を起票し、[pull-request中](https://github.com/spring-projects/spring-security/pull/165)。 -> #1325 で対応済み。（Spring 4.0からパラメータ名が変更になったため、デフォルトのままで問題なし）
- [x] チェックボックスの有効値は`true`だけではなく、`on`, `yes`, `1` もOKなことを補足する。
## Affected Versions
- 5.2.0
- 5.1.0-5.1.1
## Fix Versions
- [x] 5.3.0_ja
- [ ] 5.3.0_en
- [x] 5.2.1_ja
- [ ] 5.2.1_en
## Change Log
- [x] required

**Comment by iwanagah** [comment]
@btshimizukza 取り込まれているか確認をお願いします

**Comment by btshimizukza** [comment]
@ikeyat @iwanagah 

パラメータ名とクッキー名のデフォルト値については#1325で対応済みです。
それ以外は取り込まれていませんが、改善系なので、5.1.0での対応は必須ではありません。
先送りでよいと思います。

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Please create translation issue, and close this.

**Comment by asaharas** [comment]
I have created translation issue #2708 
so you can close this issue.

**Comment by itouyun** [comment]
I have confirmed translation issue. I'll close this issue.
