### ISSUE TITLE
Translate #134(support spring security 3.2)

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#798]
Reflect  pull-requests of #134 to the English version.

---

- [x] 5.0.0.RELEASE
- [x] master
- [x] 5.0.x

Targeted PR

- [x] #424
- [x] #574
- [x] #793
- [x] #794
- [x] #795
- [x] #797

**Comment by attarudes** [comment]
Translation completed with backport therefore closing the issue.
