### ISSUE TITLE
[Validation] Translate #296(wrong description of @GroupSequence)

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#806]
Reflect #296 to the English version .

Issue : #241 

- [ ] master
- [ ] 5.0.x
- [ ] 5.0.0.RELEASE
- [ ] 1.0.x
- [ ] 1.0.2.RELEASE

Targeted PR

 - [x] #799

**Comment by attarudes** [comment]
Below rst has been translated under #885 including backport to master and 5.0.x
  source/ArchitectureInDetail/Validation.rst
