### ISSUE TITLE
[Authentication] ログインフォームの入力チェックをBean Validationで行うためのサンプルを追加する

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#810]
現在のガイドラインでは、Noteとして `UsernamePasswordAuthenticationFilter` を拡張する方法が記載されているが、ユーザとパスワードの入力チェックを行うだけであれば、ControllerでリクエストをハンドリングしてBean Validationを使ってチェックすることができる。
`UsernamePasswordAuthenticationFilter` を拡張するとspring-securityの設定が煩雑になりがちなので、その意味でもBean Validationでチェックする方式のサンプルを追加する方向で検討する。

**Comment by ikeyat** [comment]
@btsatoutkzy 
#1325 で本issueが取り組み済みが確認お願いします。

**Comment by ikeyat** [comment]
#1325で本Issueが取り込まれることを確認した。
#1325にIssueを統合するため、本Issueはクローズする。
