### ISSUE TITLE
[Authentication] DBエラー発生時に例外メッセージが出力されるケースがある

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#811]
認証処理にて、ユーザ情報(`UserDetails`)をDBから取得する際にエラー(システムエラー)が発生すると、認証エラーとしてハンドリングされ、ガイドラインで紹介している方法でエラーメッセージを表示すると、例外メッセージが表示されてしまう。

```jsp
<c:if test="${param.error}">
    <t:messagesPanel
        messagesAttributeName="SPRING_SECURITY_LAST_EXCEPTION"/><!-- (2) -->
</c:if>
```

例えば、以下の様な対策が考えられる。

* `ExceptionMappingAuthenticationFailureHandler` を使用して、 `org.springframework.security.authentication.AuthenticationServiceException` が発生した場合はシステムエラー画面に遷移(リダイレクト)させる。（ガイドラインで紹介している方法）

* `ExceptionMappingAuthenticationFailureHandler`で要件が満たせない場合は、独自の`AuthenticationFailureHandler`を作成して `AuthenticationServiceException`をハンドリングする。(`AuthenticationServiceException` が発生した場合は、`SystemException` を発生させるなどの対応を行う)

ガイドラインでは`ExceptionMappingAuthenticationFailureHandler` を使用する例が記載されており、`AuthenticationServiceException` がDBエラー時に発生する旨を記載されているが、`AuthenticationServiceException`のハンドリングが必須な旨が明記されていないため、同じようなことが発生する事が予想される。

ガイドラインを読む事で、この事象を回避できるような書き方に修正する。

**Comment by iwanagah** [comment]
https://github.com/terasolunaorg/guideline/issues/1325 にて対応済みの為、クローズ
