### ISSUE TITLE
Translate #555(about updating Bean Validation 1.1)

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#885]
Please reflect #555 to the English version.

- [x] 5.0.0.RELEASE
- [x] master
- [x] 5.0.x

Targeted PR
- [x] #594 
- [x] #598 
- [x] #599 
- [x] #600 
- [x] #601 
- [x] #603 
- [x] #604 
- [x] #640

**Comment by attarudes** [comment]
All Targeted PRs are done therefore closing the issue.
