### ISSUE TITLE
Translate #482(About updating Spring Framework 4.1)

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#886]
Please reflect #482 to the English version.

- [x] 5.0.0.RELEASE
- [x] master
- [x] 5.0.x

Targeted PR
- [x] #544 
- [x] #569 
- [x] #613 
- [x] #615 
- [x] #659 
- [x] #711 
- [x] #727 
- [x] #860

**Comment by attarudes** [comment]
Translation completed with backport therefore closing the issue.
