### ISSUE TITLE
Translate #349(support MyBatis3)

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#890]
Please reflect #349 to the English version.

- [x] 5.0.0.RELEASE
- [x] master
- [x] 5.0.x

Targeted PR
- [x] #447 
- [x] #473 
- [x] #474 
- [x] #475 
- [x] #476 
- [x] #477 
- [x] #478
- [x] #479 
- [x] #480 
- [x] #481

**Comment by attarudes** [comment]
Translation completed with backport therefore closing the issue.
