### ISSUE TITLE
Update change logs of English version for 1.0.2

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#894]
Please reflect #804 to the English version.

- [ ] 1.0.x
- [ ] 1.0.2.RELEASE

Targeted PR
- [x] #816 
- [x] #819 
- [x] #835 
- [x] #850 
- [x] #877

**Comment by btamurutab** [comment]
Already committed under https://github.com/terasolunaorg/guideline/issues/893
