### ISSUE TITLE
[PublicReview]6.4. パスワードハッシュ化

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#9]
内容に対するコメント
----
（１）
6.4.2. How to useにて、
「BCryptPasswordEncoderは対攻撃性を高めるために計算時間が多いため、・・・」とあるが、正確には「計算量」なのでは？
＋
BCryptPasswordEncoderとStandardPasswordEncoderの切り替え基準があると、うれしいかも。
たとえば、BCryptPasswordEncoderのソルトのハッシュ化のラウンド数をデフォの10より下にすると、強度及び計算量がどうなっていくのかの情報。
※自分で計算しろっていう話はあるが・・。

（２）
6.4.2.1.1. BCryptPasswordEncoderの設定例にて、
「指定しない場合、「10」が設定される。」とあるが、10がオススメと思ってよい？

（３）
6.4.2.1.1. BCryptPasswordEncoderの設定例にて、
Tipの最後の件「 そのため、従来のPasswordEncoder(authenticationパッケージ)から、新PasswordEncoderに移行する際も、ユーザのパスワード移行が完了後、 DaoAuthenticationProviderのpasswordEncoderを変更するだけで対応できる。」で伝えたい事がいまいちわからない・・。
BCrypt以外でハッシュ化していたものを、BCryptに移行するケースの事を言っている？

（４）
6.4.2.1.1. BCryptPasswordEncoderの設定例にて、
1つめのwarningに記載されている内容がなぜwarningなのかわからない・・。

（５）
6.4.2.2. StandardPasswordEncoderにて、
かなり細かくStandardPasswordEncoderのハッシュ化アルゴリズムの仕組みを説明しているが、いいのかな？
saltの部分が特に気になる。ふわっとどこかにある程度でよい気もするけど・・。

（６）
6.4.2.2.1. StandardPasswordEncoderの設定例にて、
秘密鍵に対して「指定することを推奨する。」とあるが、指定は必須では？

（７）
6.4.2.2.1. StandardPasswordEncoderの設定例にて、
「秘密鍵(secret)について」で「プロパティファイルや、環境変数などから取得する。」とあるが、いいのかな？
※設定値（秘密鍵自体）の暗号化は不要？
＋
「また本番環境ではプロパティファイルの格納場所にも注意する。」とあるが、どう注意すべき？
もうちょっとヒントがあった方がよい気がします。

（８）
6.4.3.1. ShaPasswordEncoderを使用した例にて、
「(3)ハッシュ化時のストレッチングの回数を指定する。省略した場合は、0回となる。」は正しい表現なのか？
正確には何回ハッシュ化するかを指定する属性だと思います。
例えば1000だと、ハッシュ化(1回)+ストレッチング(999回)のいうこと。

（９）
6.4.3.1. ShaPasswordEncoderを使用した例にて、
Javaクラスの実装例として「public String register(Customer customer, String rawPassword, String userSalt) {」というインタフェースに
なっているが、引数としてuserSaltを受け取るのではなく、Customerから取得する例にした方がよいのでは？
※matchesも同様。

記述に対するコメント
----
（１０）
6.4.1. Overviewにて、
「・・セキュアなアプリケーションを設計する上で考慮しなければならない点の一つである。」の「設計」は「構築」かな？

（１１）
6.4.1. Overviewにて、
システムに保存するパスワードを平文ではなく、ハッシュ化する理由を一応記載した方がよい気がします。
※一般常識ではあるが・・・
＋
その上で、ハッシュ化さらたパスワードから平文パスワードに戻される危険性を可能な限り低くするために、
強度の高いハッシュ化アルゴリズムが必要であるという流れの方がよいかと思います。
※これも、もはや一般常識ではあるが・・・

（１２）
6.4.1. Overviewにて、
「PasswordEncoderの仕組みとして、・・」の部分は、
↓
PasswordEncoderは以下の２つのメソッドを提供している。
・平文のパスワードをハッシュ化するためのencode(String rawPassword)メソッド
・平文のパスワードとハッシュ化されているパスワードを照合するためのmatches(String rawPassword, String encodedPassword)メソッド
といった感じの方がよい気がします。

（１３）
6.4.2.1. BCryptPasswordEncoderにて、
「BCryptPasswordEncoderとは、PasswordEncoderを実装した、パスワードのハッシュ化を提供しているクラスである。」って必要ですか？
大前提すぎて、この記述は不要だと思うのですが・・。

（１４）
6.4.2.1. BCryptPasswordEncoderにて、
noteの「汎用的なアルゴリズムより」の方に「(SHA、MD5など)」があった方がよい。「汎用的なアルゴリズム(SHA、MD5など)より・・」。

（１５）
6.4.2.1.1. BCryptPasswordEncoderの設定例にて、
「protected PasswordEncoder passwordEncoder; 」は「PasswordEncoder passwordEncoder; 」の方がよいかな～。

（１６）
6.4.2.1.1. BCryptPasswordEncoderの設定例にて、
なんとなく・・「public boolean matches(Customer customer, String rawPassword)」の引数の順番は逆にした方がよい気がします。

（１７）
6.4.4. Appendixにて、
noteではなく、見出しにしてほしい。
見出しにしないと目次に表示されない。

**Comment by btshimizukza** [comment]
5.1.0で全面的にセキュリティ編の記載内容を見直したので、本Issueはクローズします。
