### ISSUE TITLE
[TutorialREST] 例外ハンドリングの処理でNullPointerExceptionが発生する

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/guideline#918]
## 事象

以下の例外の例外ハンドリング処理にて、`NullPointerException` が発生する。

* `BusinessException`
* `ResourceNotFoundException`
* `Exception`

## 原因

`ResponseEntity` を作成する際に ビルダースタイルのメソッド（`BodyBuilder#headers(HttpHeaders)` メソッド）の引数に `null` を渡していたためであった。

## 解決方法

`BodyBuilder#headers(HttpHeaders)` の引数が `null` にならないように修正する。

`handleExceptionInternal` メソッドを呼び出す際に、`null` ではなく `new HttpHeaders()` を渡すように修正する。

## その他

* REST編のガイドラインに乗せているサンプルコードにも同様の問題がある。

* `ResponseEntity` のコンストラクタに ``null`` を渡した場合はエラーにならないため、同じ動きになるように、ビルダースタイルのメソッドでも `null` の場合は無視してもらうように修正依頼を行う(Spring JIRAを発行しPull-Requestを行う予定)。 -> [SPR-12792](https://jira.spring.io/browse/SPR-12792) を発行。 -> 4.1.6.RELEASEから `null` も許容されるようになる。

## Fix Version/s

- [x] 5.1.0
- [x] 5.0.1
- [x] 5.0.0.RELEASE (updating)
- [x] translation/5.0.0 (REST Tutorial) #889 
- [x] translation/5.0.0 (REST)

**Comment by btshimizukza** [comment]
ビルダーメソッドでの `null` の扱いについては、[SPR-12792](https://jira.spring.io/browse/SPR-12792) を発行してPR中。

**Comment by kazuki43zoo** [comment]
[SPR-12792](https://jira.spring.io/browse/SPR-12792) は対応された。Spring Framework 4.1.6.RELEASE から `null` も許容される。

**Comment by btshimizukza** [comment]
translation/5.0.0ブランチの英語版のREST.rst の修正が必要なので、reopenします。

**Comment by btshimizukza** [comment]
@attarudes 

アサインしました。対応よろしくお願いします。

**Comment by attarudes** [comment]
Updated and raised pull request of #974
