### ISSUE TITLE
[DatabaseAccess(JPA)] 5.3章 文章中の誤記について

### ISSUE THREAD

**Issue by btishidahrh** [terasolunaorg/guideline#941]
「5.3. データベースアクセス（JPA編）」内にて、以下の項目で計8件の誤記を確認。

##### 　◆項目「・<jpa:repositories>要素の属性について」
 - [x] 項番1.entity-manager-factory-refの説明文中に誤記あり。  
・「～使用するbeanの指定する必要がある。」  
　⇒「使用するbeanを指定する必要がある。」

##### 　◆項目「・spring-vmc.xml」
 - [x] 項目名誤り。    
・「spring-vmc.xml」  
　⇒「spring-mvc.xml」

- [x] 本文中に誤記あり。  
・「～Servlet Filter層までの伸ばす必要がある。」  
　⇒「Servlet Filter層まで伸ばす必要がある。」  

##### 　◆本文中
 - [x] 冒頭の文章中に誤記あり。  
・「～以下3つつの方法を提供している。」  
　⇒「以下3つの方法を提供している。」  

##### 　◆Note「mergeメソッドが呼び出されるデメリット」
 - [x] 文章中に誤記あり。  
・「～Entityの取得処理はは無駄な処理となる。」  
　⇒「Entityの取得処理は無駄な処理となる。」

##### 　◆Note「IDの採番方法について」
 - [x] 「AUTO」の説明文中に脱字あり。  
・「～適切な採番方法選択してIDを採番する。」  
　⇒「適切な採番方法を選択してIDを採番する。」  

##### 　◆「・Entityクラス」項番(3)
 - [x] 説明文中に誤記あり。  
・「～型を使用する場合は、をHibernateで扱えるようにするために～ 」  
　⇒「型を使用する場合は、Hibernateで扱えるようにするために～」

##### 　◆Note「想定される適用ケース」
 - [x] 文章中に誤字あり。  
・「～を行うようなアプリケーションで有効である。」  
　⇒「を行うようなアプリケーションが有効である。」

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.1

**Comment by kazuki43zoo** [comment]
Need to english version.
