### ISSUE TITLE
Logbackの設定例について

### ISSUE THREAD

**Issue by btarakists** [terasolunaorg/guideline#977]
#### 5.6.2.1. Logbackの設定

```
<logger name="org.terasoluna.gfw.common.exception.ExceptionLogger.Monitoring" additivity="false"><!-- (10) -->
        <level value="error" />
        <appender-ref ref="MONITORING_LOG_FILE" />
</logger>
```

additivityの説明があると親切なのではないかと思います。

# Fixed Versions
- [x] 5.1.0
- [x] 5.0.1

**Comment by making** [comment]
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/ExceptionHandling.html#exception-handling-how-to-use-application-configuration-common-label

には書かれていますね。5.6の方が適切だとは思いますが。

取り急ぎ。

**Comment by btarakists** [comment]
@making
ご回答ありがとうございます。

> http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/ExceptionHandling.html#exception-handling-how-to-use-application-configuration-common-label

> には書かれていますね。5.6の方が適切だとは思いますが。

こちらに記載があったのですね、失礼しました。
5.6 にも additivity属性の詳細な説明があるとわかりやすいのかと思います。

**Comment by btshimizukza** [comment]
@btarakists

Loggingの章にも `additivity`属性の説明を追加しました。`additivity`属性に対する詳細な説明というわけではありませんが、`true` (省略時のデフォルト)を指定した時の動作例を示すことで、挙動の違いがわかるように修正しました。
