### ISSUE TITLE
RESTチュートリアルのリソースクラスをシリアライズする

### ISSUE THREAD

**Issue by attarudes** [terasolunaorg/guideline#979]
RESTチュートリアル上に作成されているリソースクラス「TodoResource」をシリアライズしていないため、シリアライズすること。
REST APIのリソースクラスは「MemberResource」はすでにシリアライズしております。
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/REST.html#resource
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/TutorialREST/index.html#resource

# Fixed Versions
- [x] 5.1.0
- [x] 5.0.1

**Comment by making** [comment]
:+1:
