### ISSUE TITLE
[Validation] MessageSourceと連携したBean Validationのメッセージの読み込み方法

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#994]
## Description

Springの `MessageSource` の機能を使ってBean Validationのメッセージ(`ValidationMessage.properties`)を読む込むことができる。メッセージをNative to Asciiせずに直接日本語を扱いたい場合は、Springの `MessageSource` と連携すると簡単に実現できそう。
また、プロパティファイルの配置先もクラスパス直下に制限されない＋複数のプロパティファイルを指定することも可能。

## Possible Solutions

以下のように定義すると、`MessageSource` の機能で読み込まれたメッセージがHibernate Validatorの中で使用されるようになる。
Native to Asciiせずにメッセージを定義したいと思うケースはそこそこある気がするので、Bean Validation(Hibernate Validator)に同等の仕組みがあるかを調査した上で、実現案の一つとしてガイドラインに載せてもよいかな〜と思いました。

```xml
    <bean id="beanValidator" class="org.springframework.validation.beanvalidation.LocalValidatorFactoryBean">
        <property name="validationMessageSource">
            <bean class="org.springframework.context.support.ResourceBundleMessageSource">
                <property name="basenames">
                    <list>
                        <value>ValidationMessages</value>
                    </list>
                </property>
                <property name="defaultEncoding" value="UTF-8" />
            </bean>
        </property>
    </bean>
```
```xml
    <mvc:annotation-driven validator="beanValidator">
        <!-- ... -->
    </mvc:annotation-driven>
```

上記を入力チェックのAppendixに追加し、
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Validation.html#validation-message-def
の最後あたりにそこへのリンクを追加する（「～することも可能だ。詳細は～を参照すること。」）。

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0_ja
- [ ] 5.2.0_en
- [x] 5.1.1_ja
- [ ] 5.1.1_en

## Issue Links
Nothing

**Comment by ikeyat** [comment]
Bean Validation(Hibernate Validator)に同等の仕組みがあるかを調査した上、
なければPossible Solutionの内容で追記して欲しいです。

**Comment by btyoshikawaa** [comment]
@btyamadasun 
Please backport to 5.1.x_ja .

**Comment by btyamadasun** [comment]
@btyoshikawaa 
I have completed the backport and created the pull request. Please confirm.

**Comment by ikeyat** [comment]
Create a translation issue and close this. @sasakitsy

**Comment by sasakitsy** [comment]
I will close this issue, Because I've created issue for translate #1994
