### ISSUE TITLE
Excelダウンロードの実装方法修正

### ISSUE THREAD

**Issue by making** [terasolunaorg/guideline#996]
## Description

Spring 4.2から`AbstractExcelView`がDeprecatedになり、代わりに`AbstractXlsView`が追加される。また、`AbstractXlsxView`が追加されxlsx形式が(ようやく)サポートされる。

https://github.com/spring-projects/spring-framework/commit/76cf5beb59e52395602ff2d71afe5ca6c10c53c4

そのため、Spring 4.2対応以降は
http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/FileDownload.html#excel
の記述に影響が出る。

## Possible Solutions
xls形式はもう古いので、現状の`AbstractExcelView`の説明を`AbstractXlsxView`の説明に変えるのがよいと思われる。`AbstractXlsView`はあっても補足程度で良いのでは。

## Affects Version/s
Nothing

## Fix Version/s
- [x] 5.1.0

## Issue Links
* https://jira.spring.io/browse/SPR-6898
* #1305

**Comment by ikeyat** [comment]
- [ ]  ``pom.xml`` の定義例でpoiの ``<version>`` を指定しているが、Spring IO Platformが定義するバージョンを引き継ぐよう、 ``<version>`` を省略するように修正する。

http://terasolunaorg.github.io/guideline/5.0.0.RELEASE/ja/ArchitectureInDetail/FileDownload.html#id4
